# Generated by Django 5.2.9 on 2025-12-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="spo2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Oxygen saturation percentage (SpO2)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
