# Generated by Django 5.2.9 on 2025-12-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0002_add_spo2_vital"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="allergies",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Known allergies (medications, food, environmental)",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="chronic_conditions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Chronic conditions (e.g., Diabetes, Hypertension, Asthma)",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="current_medications",
            field=models.TextField(
                blank=True, default="", help_text="Current medications with dosage"
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="family_history",
            field=models.TextField(
                blank=True, default="", help_text="Relevant family medical history"
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="past_surgeries",
            field=models.TextField(
                blank=True, default="", help_text="Past surgical procedures with dates"
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="social_history",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Social history (smoking, alcohol, occupation, lifestyle)",
            ),
        ),
    ]
