# Generated by Django 5.2.9 on 2025-12-29 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0003_add_medical_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICD10Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ICD-10 code (e.g., A09, J18.9)",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ICD-10 code must be in format: Letter + 2 digits (e.g., A09) or Letter + 2 digits + decimal + 1-2 digits (e.g., J18.9)",
                                regex="^[A-Z]\\d{2}(\\.\\d{1,2})?$",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Full description of the diagnosis", max_length=500),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Disease category (e.g., Certain infectious and parasitic diseases)",
                        max_length=200,
                    ),
                ),
                ("chapter", models.IntegerField(help_text="ICD-10 chapter number (1-22)")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this code is currently active/valid"
                    ),
                ),
            ],
            options={
                "verbose_name": "ICD-10 Code",
                "verbose_name_plural": "ICD-10 Codes",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="encounters__code_d529a9_idx"),
                    models.Index(fields=["chapter"], name="encounters__chapter_d63db8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "diagnosis_type",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary Diagnosis"),
                            ("SECONDARY", "Secondary Diagnosis"),
                            ("DIFFERENTIAL", "Differential Diagnosis"),
                            ("WORKING", "Working Diagnosis"),
                        ],
                        help_text="Type of diagnosis",
                        max_length=20,
                    ),
                ),
                (
                    "free_text_diagnosis",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text diagnosis when ICD-10 code is unknown",
                        max_length=500,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional clinical notes about the diagnosis",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, help_text="Whether the diagnosis has been confirmed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        help_text="Encounter this diagnosis belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "icd10_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="ICD-10 code for this diagnosis",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnoses",
                        to="encounters.icd10code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis",
                "verbose_name_plural": "Diagnoses",
                "ordering": ["diagnosis_type", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["encounter", "diagnosis_type"],
                        name="encounters__encount_8b474f_idx",
                    )
                ],
            },
        ),
    ]
