# Generated by Django 5.2.9 on 2025-12-29 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0004_add_icd10_and_diagnosis_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosis",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Diagnosis",
                "verbose_name_plural": "Diagnoses",
            },
        ),
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True, default="", help_text="Clinical notes and assessment"
                    ),
                ),
                (
                    "follow_up_instructions",
                    models.TextField(
                        blank=True, default="", help_text="Follow-up instructions for patient"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(blank=True, help_text="Scheduled follow-up date", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        help_text="Status of the treatment plan",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.OneToOneField(
                        help_text="Encounter this treatment plan belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_plan",
                        to="encounters.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Treatment Plan",
                "verbose_name_plural": "Treatment Plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Medication name", max_length=200)),
                ("dosage", models.CharField(help_text="Dosage (e.g., 500mg)", max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Frequency (e.g., Three times daily, TDS, BD)",
                        max_length=100,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, default="", help_text="Duration (e.g., 7 days)", max_length=100
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("ORAL", "Oral"),
                            ("IV", "Intravenous"),
                            ("IM", "Intramuscular"),
                            ("SC", "Subcutaneous"),
                            ("TOPICAL", "Topical"),
                            ("INHALED", "Inhaled"),
                            ("RECTAL", "Rectal"),
                            ("OPHTHALMIC", "Ophthalmic"),
                            ("OTIC", "Otic"),
                            ("NASAL", "Nasal"),
                            ("OTHER", "Other"),
                        ],
                        default="ORAL",
                        help_text="Route of administration",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Quantity to dispense", null=True
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Special instructions (e.g., Take with food)",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Start date of medication", null=True),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="End date of medication", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "treatment_plan",
                    models.ForeignKey(
                        help_text="Treatment plan this medication belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="encounters.treatmentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medications",
                "ordering": ["name"],
            },
        ),
    ]
