# Generated by Django 5.2.9 on 2025-12-29 04:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0005_add_treatment_plan_and_medication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentPlanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Template description"),
                ),
                (
                    "default_medications",
                    models.TextField(
                        blank=True, default="", help_text="Default medications (JSON format)"
                    ),
                ),
                (
                    "default_procedures",
                    models.TextField(
                        blank=True, default="", help_text="Default procedures (JSON format)"
                    ),
                ),
                (
                    "default_instructions",
                    models.TextField(
                        blank=True, default="", help_text="Default patient instructions"
                    ),
                ),
                (
                    "follow_up_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Suggested follow-up in days", null=True
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Department this template is for",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Treatment Plan Template",
                "verbose_name_plural": "Treatment Plan Templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("provisional", "Provisional"),
                    ("ruled_out", "Ruled Out"),
                    ("suspected", "Suspected"),
                ],
                default="confirmed",
                help_text="Level of diagnostic certainty",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="diagnosed_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="When the diagnosis was made",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="diagnosed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Clinician who made the diagnosis",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnoses_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="icd10code",
            name="is_billable",
            field=models.BooleanField(
                default=True, help_text="Whether this is a billable/terminal code"
            ),
        ),
        migrations.AddField(
            model_name="icd10code",
            name="long_description",
            field=models.TextField(
                blank=True, default="", help_text="Detailed long description of the diagnosis"
            ),
        ),
        migrations.AddField(
            model_name="icd10code",
            name="short_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short description of the diagnosis",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="medications_json",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Prescribed medications (JSON format for template imports)",
            ),
        ),
        migrations.AddIndex(
            model_name="icd10code",
            index=models.Index(fields=["short_description"], name="encounters__short_d_2a9595_idx"),
        ),
        migrations.AddConstraint(
            model_name="diagnosis",
            constraint=models.UniqueConstraint(
                condition=models.Q(("diagnosis_type", "PRIMARY")),
                fields=("encounter",),
                name="unique_primary_diagnosis_per_encounter",
            ),
        ),
        migrations.AddField(
            model_name="treatmentplantemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_treatment_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treatmentplantemplate",
            name="diagnosis_codes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Suggested diagnoses for this template",
                related_name="treatment_templates",
                to="encounters.icd10code",
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used to create this plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatment_plans",
                to="encounters.treatmentplantemplate",
            ),
        ),
    ]
