# Generated by Django 5.2.9 on 2025-12-29 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0006_sprint_1_1_1_"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentplan",
            name="activity_restrictions",
            field=models.TextField(
                blank=True, default="", help_text="Activity restrictions and limitations"
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_treatment_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_treatment_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="diet_recommendations",
            field=models.TextField(
                blank=True, default="", help_text="Dietary recommendations for the patient"
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="procedures_json",
            field=models.TextField(
                blank=True, default="", help_text="Planned procedures (JSON format)"
            ),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="referral_needed",
            field=models.BooleanField(default=False, help_text="Whether a referral is needed"),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="referral_notes",
            field=models.TextField(blank=True, default="", help_text="Notes for the referral"),
        ),
        migrations.AddField(
            model_name="treatmentplan",
            name="referral_specialty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARDIOLOGY", "Cardiology"),
                    ("DERMATOLOGY", "Dermatology"),
                    ("ENT", "ENT (Ear, Nose, Throat)"),
                    ("GASTROENTEROLOGY", "Gastroenterology"),
                    ("GENERAL_SURGERY", "General Surgery"),
                    ("GYNECOLOGY", "Gynecology"),
                    ("NEPHROLOGY", "Nephrology"),
                    ("NEUROLOGY", "Neurology"),
                    ("ONCOLOGY", "Oncology"),
                    ("OPHTHALMOLOGY", "Ophthalmology"),
                    ("ORTHOPEDICS", "Orthopedics"),
                    ("PEDIATRICS", "Pediatrics"),
                    ("PSYCHIATRY", "Psychiatry"),
                    ("PULMONOLOGY", "Pulmonology"),
                    ("RADIOLOGY", "Radiology"),
                    ("UROLOGY", "Urology"),
                    ("OTHER", "Other"),
                ],
                default="",
                help_text="Specialty for referral",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="treatmentplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                help_text="Status of the treatment plan",
                max_length=20,
            ),
        ),
    ]
