# Generated by Django 5.2.9 on 2025-12-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0007_add_treatment_plan_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmentplan",
            name="referral_specialty",
            field=models.CharField(
                blank=True, default="", help_text="Specialty for referral", max_length=100
            ),
        ),
    ]
