# Generated by Django 5.2.9 on 2026-01-04 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0010_encounter_triage_consultation_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="chief_complaint_edit_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADDITIONAL_SYMPTOMS", "Additional symptoms identified"),
                    ("PATIENT_DETAILS", "Patient provided more details"),
                    ("INCORRECT_INITIAL", "Incorrect initial assessment"),
                    ("CLARIFICATION", "Clarification after examination"),
                    ("MISUNDERSTANDING", "Triage miscommunication"),
                    ("OTHER", "Other (specify)"),
                ],
                default="",
                help_text="Reason for editing chief complaint",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="chief_complaint_edit_reason_other",
            field=models.TextField(
                blank=True, default="", help_text="Details if 'Other' reason selected"
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="chief_complaint_edited",
            field=models.BooleanField(
                default=False, help_text="Whether the chief complaint was edited after triage"
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="chief_complaint_edited_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when chief complaint was edited", null=True
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="chief_complaint_edited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who edited the chief complaint",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chief_complaint_edits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="chief_complaint_original",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Original chief complaint from triage (preserved for audit)",
            ),
        ),
    ]
