# Generated by Django 5.2.9 on 2026-01-05 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_templates", "0001_initial"),
        ("encounters", "0012_add_vitals_source_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="clinical_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Clinical template used for this encounter",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encounters",
                to="clinical_templates.clinicaltemplate",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="clinical_template_data",
            field=models.JSONField(
                blank=True,
                help_text="Structured data collected using the clinical template (JSON)",
                null=True,
            ),
        ),
    ]
