# Generated by Django 5.2.9 on 2026-01-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0013_add_clinical_template_to_encounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="assessment",
            field=models.TextField(
                blank=True, default="", help_text="Clinical assessment/impression (SOAP 'A')"
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="history_of_present_illness",
            field=models.TextField(
                blank=True,
                default="",
                help_text="History of Present Illness (HPI) - detailed narrative of the patient's condition",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="physical_examination",
            field=models.TextField(
                blank=True, default="", help_text="Physical Examination findings"
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="plan",
            field=models.TextField(
                blank=True, default="", help_text="Treatment/management plan (SOAP 'P')"
            ),
        ),
    ]
