# Generated by Django 5.2.9 on 2026-01-06 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0014_add_soap_note_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encounter",
            name="plan",
        ),
    ]
