# Generated by Django 5.2.9 on 2026-01-23 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_templates", "0002_add_template_snapshot"),
        ("encounters", "0016_add_icd11_fields_to_diagnosis"),
        ("patients", "0010_add_unique_identification_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="assigned_clinician",
            field=models.ForeignKey(
                blank=True,
                help_text="Clinician currently attending this encounter",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_encounters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when clinician claimed this encounter", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["assigned_clinician", "status"], name="encounters__assigne_03a8ec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="encounter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("patient",),
                name="unique_active_encounter_per_patient",
            ),
        ),
    ]
