# Generated by Django 5.2.9 on 2026-01-24 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0003_alter_clinicvisit_encounter"),
        ("encounters", "0017_add_admission_integrity_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="clinic_visit",
            field=models.ForeignKey(
                blank=True,
                help_text="Clinic visit that initiated this encounter (if routed via clinic queue)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encounters",
                to="clinics.clinicvisit",
            ),
        ),
    ]
