# Generated by Django 5.2.9 on 2026-02-08 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0019_sprint2_state_machine_linking_visit_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this encounter",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_encounters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
