# Generated by Django 5.2.9 on 2026-02-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0021_fix_legacy_encounter_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="disposition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Set"),
                    ("ADVICE_ONLY", "Advice Only"),
                    ("TREATED_DISCHARGED", "Treated & Discharged"),
                    ("REFERRED", "Referred to Specialist"),
                    ("ADMITTED", "Admitted to Inpatient"),
                    ("FOLLOW_UP_SCHEDULED", "Follow-up Scheduled"),
                    ("LEFT_AMA", "Left Against Medical Advice"),
                ],
                default="",
                help_text="Encounter outcome/disposition",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="disposition_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required for ADVICE_ONLY and LEFT_AMA dispositions",
            ),
        ),
    ]
