# Generated by Django 5.2.9 on 2026-02-23 19:19

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_templates", "0002_add_template_snapshot"),
        ("clinics", "0009_add_unique_active_patient_per_session"),
        ("encounters", "0022_add_disposition_fields"),
        ("patients", "0013_add_birth_certificate_identification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDiagnosis",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "icd11_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ICD-11 code (e.g., 1A00, BA00.Z) from WHO ICD-11 API",
                        max_length=50,
                    ),
                ),
                (
                    "icd11_display",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ICD-11 display text/title from WHO ICD-11 API",
                        max_length=500,
                    ),
                ),
                (
                    "diagnosis_type",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary Diagnosis"),
                            ("SECONDARY", "Secondary Diagnosis"),
                            ("DIFFERENTIAL", "Differential Diagnosis"),
                            ("WORKING", "Working Diagnosis"),
                        ],
                        help_text="Type of diagnosis",
                        max_length=20,
                    ),
                ),
                (
                    "free_text_diagnosis",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text diagnosis when ICD-10 code is unknown",
                        max_length=500,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional clinical notes about the diagnosis",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, help_text="Whether the diagnosis has been confirmed"
                    ),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("provisional", "Provisional"),
                            ("ruled_out", "Ruled Out"),
                            ("suspected", "Suspected"),
                        ],
                        default="confirmed",
                        help_text="Level of diagnostic certainty",
                        max_length=20,
                    ),
                ),
                (
                    "diagnosed_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="When the diagnosis was made"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "diagnosed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Clinician who made the diagnosis",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Encounter this diagnosis belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "icd10_code",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="ICD-10 code for this diagnosis",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="encounters.icd10code",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Diagnosis",
                "verbose_name_plural": "historical Diagnoses",
                "db_table": "encounters_diagnosis_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEncounter",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("OPD", "Outpatient Department"),
                            ("IPD", "Inpatient Department"),
                            ("EMERGENCY", "Emergency"),
                            ("ANC", "Antenatal Clinic"),
                            ("PAEDIATRIC", "Paediatric Clinic"),
                            ("DIALYSIS", "Dialysis Unit"),
                            ("ONCOLOGY", "Oncology Clinic"),
                            ("SCHEDULED_OPD", "Scheduled Outpatient"),
                            ("FOLLOW_UP", "Follow-up Visit"),
                            ("CONSULTANT_REVIEW", "Consultant Review"),
                            ("CHRONIC_STABLE", "Stable Chronic Care"),
                            ("SPECIALIST_CLINIC", "Specialist Clinic"),
                            ("PROCEDURE", "Scheduled Procedure"),
                            ("DAY_CASE", "Day Case"),
                            ("WARD_ROUND", "Ward Round"),
                            ("DISCHARGE_REVIEW", "Discharge Review"),
                        ],
                        help_text="Type of encounter",
                        max_length=20,
                    ),
                ),
                (
                    "encounter_date",
                    models.DateField(
                        default=datetime.date.today, help_text="Date of the encounter"
                    ),
                ),
                ("chief_complaint", models.TextField(help_text="Patient's chief complaint")),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Body temperature in Celsius",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "pulse",
                    models.IntegerField(
                        blank=True, help_text="Pulse rate (beats per minute)", null=True
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Blood pressure (e.g., 120/80)",
                        max_length=20,
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True, help_text="Respiratory rate (breaths per minute)", null=True
                    ),
                ),
                (
                    "vitals_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRIAGE", "Triage"),
                            ("CONSULTATION", "Consultation"),
                            ("NURSING", "Nursing"),
                        ],
                        help_text="Where the vitals were recorded (e.g., triage)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "vitals_recorded_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when vitals were recorded", null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Patient weight in kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Patient height in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "spo2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Oxygen saturation percentage (SpO2)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Known allergies (medications, food, environmental)",
                    ),
                ),
                (
                    "chronic_conditions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Chronic conditions (e.g., Diabetes, Hypertension, Asthma)",
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(
                        blank=True, default="", help_text="Current medications with dosage"
                    ),
                ),
                (
                    "past_surgeries",
                    models.TextField(
                        blank=True, default="", help_text="Past surgical procedures with dates"
                    ),
                ),
                (
                    "family_history",
                    models.TextField(
                        blank=True, default="", help_text="Relevant family medical history"
                    ),
                ),
                (
                    "social_history",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Social history (smoking, alcohol, occupation, lifestyle)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Additional clinical notes"),
                ),
                (
                    "history_of_present_illness",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="History of Present Illness (HPI) - detailed narrative of the patient's condition",
                    ),
                ),
                (
                    "physical_examination",
                    models.TextField(
                        blank=True, default="", help_text="Physical Examination findings"
                    ),
                ),
                (
                    "assessment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Clinical assessment/impression (SOAP 'A')",
                    ),
                ),
                (
                    "clinical_template_data",
                    models.JSONField(
                        blank=True,
                        help_text="Structured data collected using the clinical template (JSON)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("CHECKED_IN", "Checked In"),
                            ("TRIAGED", "Triaged"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ON_HOLD", "On Hold"),
                            ("ORDERS_PLACED", "Orders Placed"),
                            ("RESULTS_PENDING", "Results Pending"),
                            ("READY_TO_CLOSE", "Ready to Close"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="CREATED",
                        help_text="Encounter status lifecycle",
                        max_length=20,
                    ),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the encounter was finalized/completed",
                        null=True,
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason for cancellation (if status is CANCELLED)",
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not Set"),
                            ("ADVICE_ONLY", "Advice Only"),
                            ("TREATED_DISCHARGED", "Treated & Discharged"),
                            ("REFERRED", "Referred to Specialist"),
                            ("ADMITTED", "Admitted to Inpatient"),
                            ("FOLLOW_UP_SCHEDULED", "Follow-up Scheduled"),
                            ("LEFT_AMA", "Left Against Medical Advice"),
                        ],
                        default="",
                        help_text="Encounter outcome/disposition",
                        max_length=30,
                    ),
                ),
                (
                    "disposition_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Required for ADVICE_ONLY and LEFT_AMA dispositions",
                    ),
                ),
                (
                    "triage_requirement",
                    models.CharField(
                        choices=[
                            ("MANDATORY", "Mandatory - Must complete triage"),
                            ("OPTIONAL", "Optional - Can bypass triage"),
                            ("NOT_REQUIRED", "Not Required - Skip triage"),
                        ],
                        default="MANDATORY",
                        help_text="Whether triage is mandatory, optional, or not required",
                        max_length=20,
                    ),
                ),
                (
                    "triage_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending - Awaiting triage"),
                            ("IN_PROGRESS", "In Progress - Being triaged"),
                            ("COMPLETED", "Completed - Triage done"),
                            ("BYPASSED", "Bypassed - Triage skipped"),
                            ("NOT_APPLICABLE", "Not Applicable - Triage not required"),
                        ],
                        default="PENDING",
                        help_text="Current triage status",
                        max_length=20,
                    ),
                ),
                (
                    "triage_bypass_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STABLE_FOLLOW_UP", "Stable follow-up patient"),
                            ("CONSULTANT_DECISION", "Consultant/senior decision"),
                            ("CHRONIC_CARE_REVIEW", "Chronic care review"),
                            ("STAFF_SHORTAGE", "Staff shortage"),
                            ("PATIENT_PREFERENCE", "Patient preference"),
                            ("OTHER", "Other reason"),
                        ],
                        default="",
                        help_text="Reason for bypassing triage (if applicable)",
                        max_length=30,
                    ),
                ),
                (
                    "triage_bypassed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when triage was bypassed", null=True
                    ),
                ),
                (
                    "consultation_status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting for consultation"),
                            ("CALLED", "Called - Patient summoned"),
                            ("IN_PROGRESS", "In Progress - Being seen"),
                            ("COMPLETED", "Completed - Consultation done"),
                        ],
                        default="WAITING",
                        help_text="Current consultation status",
                        max_length=20,
                    ),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when patient was called for consultation",
                        null=True,
                    ),
                ),
                (
                    "consultation_started_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when consultation started", null=True
                    ),
                ),
                (
                    "chief_complaint_original",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Original chief complaint from triage (preserved for audit)",
                    ),
                ),
                (
                    "chief_complaint_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the chief complaint was edited after triage",
                    ),
                ),
                (
                    "chief_complaint_edit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADDITIONAL_SYMPTOMS", "Additional symptoms identified"),
                            ("PATIENT_DETAILS", "Patient provided more details"),
                            ("INCORRECT_INITIAL", "Incorrect initial assessment"),
                            ("CLARIFICATION", "Clarification after examination"),
                            ("MISUNDERSTANDING", "Triage miscommunication"),
                            ("OTHER", "Other (specify)"),
                        ],
                        default="",
                        help_text="Reason for editing chief complaint",
                        max_length=30,
                    ),
                ),
                (
                    "chief_complaint_edit_reason_other",
                    models.TextField(
                        blank=True, default="", help_text="Details if 'Other' reason selected"
                    ),
                ),
                (
                    "chief_complaint_edited_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when chief complaint was edited", null=True
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when clinician claimed this encounter",
                        null=True,
                    ),
                ),
                (
                    "visit_reason",
                    models.CharField(
                        choices=[
                            ("NEW_COMPLAINT", "New Complaint"),
                            ("FOLLOW_UP", "Follow-up"),
                            ("CHRONIC_CARE", "Chronic Care Review"),
                            ("PROCEDURE_REVIEW", "Post-Procedure Review"),
                            ("REFILL_ONLY", "Medication Refill Only"),
                            ("LAB_REVIEW", "Lab Results Review"),
                            ("REFERRAL_VISIT", "Referral from Another Facility"),
                            ("OTHER", "Other"),
                        ],
                        default="NEW_COMPLAINT",
                        help_text="Reason for visit",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "assigned_clinician",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Clinician currently attending this encounter",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chief_complaint_edited_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who edited the chief complaint",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Clinic visit that initiated this encounter (if routed via clinic queue)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "clinical_template",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Clinical template used for this encounter",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clinical_templates.clinicaltemplate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who created this encounter",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who finalized/completed this encounter",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_encounter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Previous encounter this visit is following up on",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Patient associated with this encounter",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patients.patient",
                    ),
                ),
                (
                    "triage_bypassed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who bypassed the triage",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vitals_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who recorded the vitals",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Encounter",
                "verbose_name_plural": "historical Encounters",
                "db_table": "encounters_encounter_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
