# Generated by Django 5.2.11 on 2026-03-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0023_historicaldiagnosis_historicalencounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosis",
            name="snomed_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SNOMED CT concept ID (e.g., 38341003) for FHIR interoperability",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="snomed_display",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SNOMED CT concept display text (e.g., 'Hypertensive disorder')",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnosis",
            name="snomed_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SNOMED CT concept ID (e.g., 38341003) for FHIR interoperability",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnosis",
            name="snomed_display",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SNOMED CT concept display text (e.g., 'Hypertensive disorder')",
                max_length=500,
            ),
        ),
    ]
