# Generated by Django 5.2.11 on 2026-03-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_multitenancy_clinical_fks"),
        ("encounters", "0024_add_snomed_ct_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where this encounter took place.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encounters",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalencounter",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Facility where this encounter took place.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="historicalencounter",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.organization",
            ),
        ),
    ]
