# Generated by Django 5.2.13 on 2026-05-27 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0030_structured_history_models"),
        ("pharmacy", "0029_historicalprescription_bill_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentmedication",
            name="drug",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to drug catalog entry (for structured medication recording)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_medication_statements",
                to="pharmacy.drug",
            ),
        ),
    ]
