# Generated by Django 5.2.13 on 2026-07-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0032_chroniccondition_origin_hub_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="consultation_status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting for consultation"),
                    ("CALLED", "Called - Patient summoned"),
                    ("IN_PROGRESS", "In Progress - Being seen"),
                    ("COMPLETED", "Completed - Consultation done"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="WAITING",
                help_text="Current consultation status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalencounter",
            name="consultation_status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting for consultation"),
                    ("CALLED", "Called - Patient summoned"),
                    ("IN_PROGRESS", "In Progress - Being seen"),
                    ("COMPLETED", "Completed - Consultation done"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="WAITING",
                help_text="Current consultation status",
                max_length=20,
            ),
        ),
    ]
