# Generated by Django 5.2.13 on 2026-07-14 19:09

import uuid
from django.db import migrations, models


def backfill_encounter_public_ids(apps, schema_editor):
    Encounter = apps.get_model("encounters", "Encounter")
    HistoricalEncounter = apps.get_model("encounters", "HistoricalEncounter")

    for encounter in Encounter.objects.filter(public_id__isnull=True).iterator(chunk_size=1000):
        encounter.public_id = uuid.uuid4()
        encounter.save(update_fields=["public_id"])

    for snapshot in HistoricalEncounter.objects.filter(public_id__isnull=True).iterator(
        chunk_size=2000
    ):
        snapshot.public_id = uuid.uuid4()
        snapshot.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0033_add_cancelled_consultation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="public_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalencounter",
            name="public_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_encounter_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="encounter",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalencounter",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
            ),
        ),
    ]
