# Generated by Django 5.2.13 on 2026-08-15 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_rename_core_userce_organiz_4f466f_idx_core_userce_organiz_34425a_idx"),
        ("encounters", "0034_encounter_public_id_historicalencounter_public_id"),
        ("patients", "0027_alter_historicalpatient_identification_type_and_more"),
        ("triage", "0017_erbed_origin_hub_id_erbed_origin_local_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalFlagSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("TRIAGE", "Triage"),
                            ("ENCOUNTER", "Encounter"),
                            ("BACKGROUND_RULE", "Background Rule"),
                        ],
                        max_length=24,
                    ),
                ),
                ("flag_key", models.CharField(max_length=64)),
                ("clinical_domain", models.CharField(blank=True, default="", max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="WARNING",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("MAPPED", "Mapped"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                ("detected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("rule_id", models.CharField(blank=True, default="", max_length=80)),
                ("rule_version", models.CharField(blank=True, default="", max_length=40)),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("UNMAPPED", "Unmapped"),
                            ("AUTO_MAPPED", "Auto mapped"),
                            ("NEEDS_REVIEW", "Needs review"),
                            ("CONFIRMED", "Confirmed"),
                        ],
                        default="UNMAPPED",
                        max_length=24,
                    ),
                ),
                ("suggested_icd11_code", models.CharField(blank=True, default="", max_length=50)),
                ("suggested_icd11_title", models.CharField(blank=True, default="", max_length=500)),
                ("selected_icd11_code", models.CharField(blank=True, default="", max_length=50)),
                ("selected_icd11_title", models.CharField(blank=True, default="", max_length=500)),
                (
                    "resolution_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CREATE_DIAGNOSIS_PROVISIONAL", "Create provisional diagnosis"),
                            ("CREATE_DIAGNOSIS_CONFIRMED", "Create confirmed diagnosis"),
                            ("ADD_CHRONIC_CONDITION", "Add chronic condition"),
                            ("NOTE_ONLY", "Note only"),
                            ("NO_ACTION", "No action"),
                        ],
                        default="",
                        max_length=40,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True, default="")),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_flag_suggestions",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "linked_chronic_condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_vital_flag_suggestions",
                        to="encounters.chroniccondition",
                    ),
                ),
                (
                    "linked_diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_vital_flag_suggestions",
                        to="encounters.diagnosis",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_flag_suggestions",
                        to="patients.patient",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_vital_flag_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_icd10",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vital_flag_selected_by",
                        to="encounters.icd10code",
                    ),
                ),
                (
                    "suggested_icd10",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vital_flag_suggested_by",
                        to="encounters.icd10code",
                    ),
                ),
                (
                    "triage_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vital_flag_suggestions",
                        to="triage.triageassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VitalFlagSuggestionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("DETECTED", "Detected"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("MAPPING_UPDATED", "Mapping updated"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_status", models.CharField(blank=True, default="", max_length=16)),
                ("to_status", models.CharField(blank=True, default="", max_length=16)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vital_flag_suggestion_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="encounters.vitalflagsuggestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="vitalflagsuggestion",
            index=models.Index(fields=["patient", "status"], name="encounters__patient_fd43fe_idx"),
        ),
        migrations.AddIndex(
            model_name="vitalflagsuggestion",
            index=models.Index(
                fields=["encounter", "status"], name="encounters__encount_3b537a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vitalflagsuggestion",
            index=models.Index(
                fields=["flag_key", "status"], name="encounters__flag_ke_50591a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vitalflagsuggestion",
            index=models.Index(fields=["detected_at"], name="encounters__detecte_7b6aff_idx"),
        ),
        migrations.AddConstraint(
            model_name="vitalflagsuggestion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["NEW", "ACKNOWLEDGED", "MAPPED"])),
                fields=("patient", "encounter", "flag_key"),
                name="unique_open_vital_flag_per_patient_encounter",
            ),
        ),
        migrations.AddIndex(
            model_name="vitalflagsuggestionaction",
            index=models.Index(
                fields=["suggestion", "created_at"], name="encounters__suggest_a79e9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vitalflagsuggestionaction",
            index=models.Index(
                fields=["action_type", "created_at"], name="encounters__action__53b1ee_idx"
            ),
        ),
    ]
