# Copyright (c) 2026 Nexora Consulting Ltd. All rights reserved.
# Generated by Django 5.2.9 on 2026-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0035_vitalflagsuggestion_vitalflagsuggestionaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="disposition_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Set"),
                    ("MANUAL", "Manual"),
                    ("AUTO_REFERRAL", "Auto: Referral"),
                    ("AUTO_ADMISSION", "Auto: Admission"),
                    ("AUTO_DISCHARGE", "Auto: Discharge"),
                ],
                default="",
                help_text="Whether disposition was set manually or auto-derived from workflow events",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="historicalencounter",
            name="disposition_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Set"),
                    ("MANUAL", "Manual"),
                    ("AUTO_REFERRAL", "Auto: Referral"),
                    ("AUTO_ADMISSION", "Auto: Admission"),
                    ("AUTO_DISCHARGE", "Auto: Discharge"),
                ],
                default="",
                help_text="Whether disposition was set manually or auto-derived from workflow events",
                max_length=30,
            ),
        ),
    ]
