# Generated by Django 5.2.11 on 2026-03-02 02:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0010_alter_clinic_clinic_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique measure code (e.g., 'KE-CQM-001', 'KHIS-ANC-01')",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable measure name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Full description of what this measure assesses"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("CLINICAL", "Clinical Quality"),
                            ("PATIENT_SAFETY", "Patient Safety"),
                            ("EFFICIENCY", "Efficiency"),
                            ("PATIENT_EXPERIENCE", "Patient Experience"),
                            ("PUBLIC_HEALTH", "Public Health"),
                            ("CARE_COORDINATION", "Care Coordination"),
                        ],
                        default="CLINICAL",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DRAFT", "Draft"), ("RETIRED", "Retired")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "numerator_logic",
                    models.TextField(
                        help_text="JSON or text description of the numerator criteria. E.g., 'patients with HbA1c < 7% in the reporting period'"
                    ),
                ),
                (
                    "denominator_logic",
                    models.TextField(
                        help_text="JSON or text description of the denominator criteria. E.g., 'all diabetic patients enrolled in the reporting period'"
                    ),
                ),
                (
                    "exclusion_logic",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Criteria for excluding patients from the denominator",
                    ),
                ),
                (
                    "target_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target performance percentage (e.g., 90.00 for 90%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "low_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Below this percentage is considered poor performance",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "reporting_period",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        default="QUARTERLY",
                        max_length=20,
                    ),
                ),
                (
                    "dhis2_indicator_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DHIS2 indicator ID for mapping",
                        max_length=50,
                    ),
                ),
                (
                    "reference_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to measure specification or evidence base",
                    ),
                ),
                (
                    "applicable_clinic_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of clinic type codes this measure applies to. Empty list means all clinic types.",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="QuarterlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                (
                    "quarter",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Q1 (Jan–Mar)"),
                            (2, "Q2 (Apr–Jun)"),
                            (3, "Q3 (Jul–Sep)"),
                            (4, "Q4 (Oct–Dec)"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("total_visits", models.PositiveIntegerField(default=0)),
                ("new_visits", models.PositiveIntegerField(default=0)),
                ("revisits", models.PositiveIntegerField(default=0)),
                ("priority_red", models.PositiveIntegerField(default=0)),
                ("priority_orange", models.PositiveIntegerField(default=0)),
                ("priority_yellow", models.PositiveIntegerField(default=0)),
                ("priority_green", models.PositiveIntegerField(default=0)),
                ("priority_blue", models.PositiveIntegerField(default=0)),
                ("male_visits", models.PositiveIntegerField(default=0)),
                ("female_visits", models.PositiveIntegerField(default=0)),
                ("under_5_visits", models.PositiveIntegerField(default=0)),
                ("under_18_visits", models.PositiveIntegerField(default=0)),
                ("adult_visits", models.PositiveIntegerField(default=0)),
                ("over_60_visits", models.PositiveIntegerField(default=0)),
                ("new_enrollments", models.PositiveIntegerField(default=0)),
                ("active_enrollments", models.PositiveIntegerField(default=0)),
                ("defaulters", models.PositiveIntegerField(default=0)),
                ("anc_first_visits", models.PositiveIntegerField(default=0)),
                ("anc_revisits", models.PositiveIntegerField(default=0)),
                ("deliveries", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "sha_claims_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "cash_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("dhis2_submitted", models.BooleanField(default=False)),
                ("dhis2_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("dhis2_response", models.JSONField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarterly_reports",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monthly_reports",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The monthly reports aggregated into this quarterly report.",
                        related_name="quarterly_report_refs",
                        to="clinics.monthlyclinicreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-quarter", "clinic__name"],
                "unique_together": {("clinic", "year", "quarter")},
            },
        ),
        migrations.CreateModel(
            name="QualityMeasureResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                (
                    "period",
                    models.PositiveIntegerField(
                        help_text="Month (1-12), quarter (1-4), or 0 for annual",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("numerator", models.PositiveIntegerField(default=0)),
                ("denominator", models.PositiveIntegerField(default=0)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculated percentage (numerator / denominator * 100)",
                        max_digits=5,
                    ),
                ),
                (
                    "meets_target",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the result meets the measure's target_percentage",
                    ),
                ),
                (
                    "calculation_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes about the calculation (e.g., data quality issues)",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_results",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="quality.qualitymeasure",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-period", "measure__code"],
                "unique_together": {("measure", "clinic", "year", "period", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="AnnualReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("total_visits", models.PositiveIntegerField(default=0)),
                ("new_visits", models.PositiveIntegerField(default=0)),
                ("revisits", models.PositiveIntegerField(default=0)),
                ("priority_red", models.PositiveIntegerField(default=0)),
                ("priority_orange", models.PositiveIntegerField(default=0)),
                ("priority_yellow", models.PositiveIntegerField(default=0)),
                ("priority_green", models.PositiveIntegerField(default=0)),
                ("priority_blue", models.PositiveIntegerField(default=0)),
                ("male_visits", models.PositiveIntegerField(default=0)),
                ("female_visits", models.PositiveIntegerField(default=0)),
                ("under_5_visits", models.PositiveIntegerField(default=0)),
                ("under_18_visits", models.PositiveIntegerField(default=0)),
                ("adult_visits", models.PositiveIntegerField(default=0)),
                ("over_60_visits", models.PositiveIntegerField(default=0)),
                ("new_enrollments", models.PositiveIntegerField(default=0)),
                ("active_enrollments", models.PositiveIntegerField(default=0)),
                ("defaulters", models.PositiveIntegerField(default=0)),
                ("anc_first_visits", models.PositiveIntegerField(default=0)),
                ("anc_revisits", models.PositiveIntegerField(default=0)),
                ("deliveries", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "sha_claims_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "cash_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("dhis2_submitted", models.BooleanField(default=False)),
                ("dhis2_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("dhis2_response", models.JSONField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_reports",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quarterly_reports",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The quarterly reports aggregated into this annual report.",
                        related_name="annual_report_refs",
                        to="quality.quarterlyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "clinic__name"],
                "unique_together": {("clinic", "year")},
            },
        ),
    ]
