# Generated by Django 5.2.13 on 2026-05-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annualreport",
            options={
                "ordering": ["-year", "clinic__name"],
                "permissions": [
                    ("regenerate", "Can regenerate annual report"),
                    ("export_sdmx", "Can export annual report as SDMX"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="qualitymeasure",
            options={
                "ordering": ["code"],
                "permissions": [
                    ("import_csv", "Can import quality measures from CSV"),
                    ("export_csv", "Can export quality measures to CSV"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="quarterlyreport",
            options={
                "ordering": ["-year", "-quarter", "clinic__name"],
                "permissions": [
                    ("regenerate", "Can regenerate quarterly report"),
                    ("export_sdmx", "Can export quarterly report as SDMX"),
                ],
            },
        ),
    ]
