# Generated by Django 5.2.11 on 2026-04-10 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0037_add_facility_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MOH705Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField(help_text="First day of the reporting month")),
                ("period_end", models.DateField(help_text="Last day of the reporting month")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("SUBMITTED", "Submitted to DHIS2"),
                            ("FAILED", "Submission Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("dhis2_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("dhis2_response", models.JSONField(blank=True, default=dict)),
                ("dhis2_import_summary", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("total_visits", models.IntegerField(default=0)),
                ("total_under_5", models.IntegerField(default=0)),
                ("total_5_and_above", models.IntegerField(default=0)),
                ("revisits", models.IntegerField(default=0)),
                ("new_cases", models.IntegerField(default=0)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "MOH 705 Report",
                "verbose_name_plural": "MOH 705 Reports",
                "ordering": ["-period_start"],
                "unique_together": {("facility", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="MOHDataElementMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("MOH705", "MOH 705"),
                            ("MOH711", "MOH 711"),
                            ("MOH717", "MOH 717"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "indicator_code",
                    models.CharField(
                        help_text="Internal indicator code, e.g. 'malaria_under_5', 'opd_total'",
                        max_length=60,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local Development"),
                            ("staging", "Staging / UAT"),
                            ("production", "Production (KHIS)"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                (
                    "data_element_uid",
                    models.CharField(help_text="DHIS2 dataElement UID", max_length=11),
                ),
                ("short_name", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "MOH DHIS2 Mapping",
                "verbose_name_plural": "MOH DHIS2 Mappings",
                "ordering": ["report_type", "indicator_code"],
                "unique_together": {("report_type", "indicator_code", "environment")},
            },
        ),
        migrations.CreateModel(
            name="MOH705DiseaseRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("icd10_chapter", models.IntegerField(help_text="ICD-10 chapter (1-22)")),
                (
                    "category_name",
                    models.CharField(help_text="Disease category name", max_length=200),
                ),
                ("cases_under_5", models.IntegerField(default=0)),
                ("cases_5_and_above", models.IntegerField(default=0)),
                ("total_cases", models.IntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_rows",
                        to="moh_reporting.moh705report",
                    ),
                ),
            ],
            options={
                "verbose_name": "MOH 705 Disease Row",
                "verbose_name_plural": "MOH 705 Disease Rows",
                "ordering": ["icd10_chapter"],
                "unique_together": {("report", "icd10_chapter")},
            },
        ),
        migrations.CreateModel(
            name="MOH711Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField(help_text="First day of the reporting month")),
                ("period_end", models.DateField(help_text="Last day of the reporting month")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("SUBMITTED", "Submitted to DHIS2"),
                            ("FAILED", "Submission Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("dhis2_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("dhis2_response", models.JSONField(blank=True, default=dict)),
                ("dhis2_import_summary", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("anc_visits", models.IntegerField(default=0)),
                ("deliveries_normal", models.IntegerField(default=0)),
                ("deliveries_caesarean", models.IntegerField(default=0)),
                ("deliveries_total", models.IntegerField(default=0)),
                ("live_births", models.IntegerField(default=0)),
                ("still_births", models.IntegerField(default=0)),
                ("malaria_cases_under_5", models.IntegerField(default=0)),
                ("malaria_cases_5_and_above", models.IntegerField(default=0)),
                ("malaria_in_pregnancy", models.IntegerField(default=0)),
                ("children_underweight", models.IntegerField(default=0)),
                ("children_stunted", models.IntegerField(default=0)),
                ("children_wasted", models.IntegerField(default=0)),
                ("bcg_given", models.IntegerField(default=0)),
                ("opv_given", models.IntegerField(default=0)),
                ("penta_given", models.IntegerField(default=0)),
                ("measles_given", models.IntegerField(default=0)),
                ("fully_immunised", models.IntegerField(default=0)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "MOH 711 Report",
                "verbose_name_plural": "MOH 711 Reports",
                "ordering": ["-period_start"],
                "unique_together": {("facility", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="MOH717Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField(help_text="First day of the reporting month")),
                ("period_end", models.DateField(help_text="Last day of the reporting month")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("SUBMITTED", "Submitted to DHIS2"),
                            ("FAILED", "Submission Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("dhis2_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("dhis2_response", models.JSONField(blank=True, default=dict)),
                ("dhis2_import_summary", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("opd_new_visits", models.IntegerField(default=0)),
                ("opd_revisits", models.IntegerField(default=0)),
                ("opd_total", models.IntegerField(default=0)),
                ("admissions_total", models.IntegerField(default=0)),
                ("discharges_total", models.IntegerField(default=0)),
                ("inpatient_days", models.IntegerField(default=0)),
                ("deaths_total", models.IntegerField(default=0)),
                ("deliveries_total", models.IntegerField(default=0)),
                ("deliveries_caesarean", models.IntegerField(default=0)),
                ("surgeries_major", models.IntegerField(default=0)),
                ("surgeries_minor", models.IntegerField(default=0)),
                ("referrals_in", models.IntegerField(default=0)),
                ("referrals_out", models.IntegerField(default=0)),
                ("lab_tests_total", models.IntegerField(default=0)),
                ("emergency_visits", models.IntegerField(default=0)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "MOH 717 Report",
                "verbose_name_plural": "MOH 717 Reports",
                "ordering": ["-period_start"],
                "unique_together": {("facility", "period_start")},
            },
        ),
    ]
