# Generated by Django 5.2.9 on 2025-12-28 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True, help_text="Type of action performed", max_length=50
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Type of resource accessed (e.g., Patient, Encounter)",
                        max_length=100,
                    ),
                ),
                (
                    "resource_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the resource accessed",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, default="", help_text="User agent string from the request"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (changes, purpose, legal basis, etc.)",
                    ),
                ),
                (
                    "patient_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Patient ID for sensitive access tracking (denormalized for query performance)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"], name="core_auditl_user_id_7b678c_idx"
                    ),
                    models.Index(
                        fields=["action", "timestamp"], name="core_auditl_action_096de0_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="core_auditl_resourc_a674ad_idx",
                    ),
                    models.Index(
                        fields=["patient_id", "timestamp"], name="core_auditl_patient_df3a3d_idx"
                    ),
                ],
            },
        ),
    ]
