# Generated by Django 5.2.9 on 2025-12-28 03:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(
                        default=True, help_text="Whether the system is currently online"
                    ),
                ),
                (
                    "last_check",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the status was last checked",
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Network latency in milliseconds", null=True
                    ),
                ),
                (
                    "server_url",
                    models.URLField(
                        blank=True, default="", help_text="Server URL that was checked"
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Status",
                "verbose_name_plural": "Network Status Entries",
                "ordering": ["-last_check"],
            },
        ),
        migrations.CreateModel(
            name="SyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("CREATE", "Create"), ("UPDATE", "Update"), ("DELETE", "Delete")],
                        db_index=True,
                        help_text="Type of operation to sync",
                        max_length=10,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True, help_text="Name of the model being synced", max_length=100
                    ),
                ),
                (
                    "record_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the record (null for new records)",
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(default=dict, help_text="Serialized data for the operation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SYNCING", "Syncing"),
                            ("SYNCED", "Synced"),
                            ("FAILED", "Failed"),
                            ("CONFLICT", "Conflict"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current sync status",
                        max_length=10,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, help_text="Number of sync attempts"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Error message if sync failed"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When the entry was queued"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, help_text="When the entry was successfully synced", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Queue Entry",
                "verbose_name_plural": "Sync Queue Entries",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="core_syncqu_status_78ab07_idx"
                    ),
                    models.Index(
                        fields=["model_name", "record_id"], name="core_syncqu_model_n_3bce90_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True, help_text="Name of the model with conflict", max_length=100
                    ),
                ),
                (
                    "record_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the record with conflict",
                        null=True,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Specific field with conflict (if field-level)",
                        max_length=100,
                    ),
                ),
                (
                    "local_data",
                    models.JSONField(default=dict, help_text="Local version of the data"),
                ),
                (
                    "remote_data",
                    models.JSONField(default=dict, help_text="Remote version of the data"),
                ),
                (
                    "resolved_data",
                    models.JSONField(blank=True, default=dict, help_text="Final resolved data"),
                ),
                (
                    "resolution_strategy",
                    models.CharField(
                        choices=[
                            ("LAST_WRITE_WINS", "Last Write Wins"),
                            ("LOCAL_WINS", "Local Wins"),
                            ("REMOTE_WINS", "Remote Wins"),
                            ("MANUAL", "Manual Resolution"),
                            ("MERGED", "Merged"),
                        ],
                        default="LAST_WRITE_WINS",
                        help_text="Strategy used to resolve the conflict",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Resolution"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current resolution status",
                        max_length=10,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="When the conflict was detected"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the conflict was resolved", null=True
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who resolved the conflict (if manual)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Conflict",
                "verbose_name_plural": "Sync Conflicts",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "detected_at"], name="core_syncco_status_4802e2_idx"
                    ),
                    models.Index(
                        fields=["model_name", "record_id"], name="core_syncco_model_n_33dad1_idx"
                    ),
                ],
            },
        ),
    ]
