# Generated by Django 5.2.9 on 2025-12-31 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0004_add_kenya_location_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique department code (e.g., OPD, IPD, LAB)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Department name", max_length=100)),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("CLINICAL", "Clinical"),
                            ("ADMINISTRATIVE", "Administrative"),
                            ("SUPPORT", "Support"),
                            ("LABORATORY", "Laboratory"),
                            ("PHARMACY", "Pharmacy"),
                            ("RADIOLOGY", "Radiology"),
                            ("RECORDS", "Medical Records"),
                        ],
                        help_text="Type of department",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this department is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent department for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique role code (e.g., DOCTOR, NURSE)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Role name", max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CLINICAL", "Clinical Staff"),
                            ("ADMINISTRATIVE", "Administrative Staff"),
                            ("TECHNICAL", "Technical Staff"),
                            ("MANAGEMENT", "Management"),
                        ],
                        help_text="Role category",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Role description")),
                (
                    "permissions_matrix",
                    models.JSONField(
                        default=dict, help_text="Permission matrix with resources and actions"
                    ),
                ),
                (
                    "hierarchy_level",
                    models.PositiveIntegerField(default=0, help_text="Hierarchy level (0=highest)"),
                ),
                (
                    "requires_license",
                    models.BooleanField(
                        default=False, help_text="Whether this role requires a medical license"
                    ),
                ),
                (
                    "license_body",
                    models.CharField(
                        blank=True, help_text="Licensing body (e.g., KMPDB, NCK)", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this role is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "django_group",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked Django Group for standard permissions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "parent_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent role for permission inheritance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["hierarchy_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique employee ID (e.g., VH-2026-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Title (e.g., Dr., Nurse)", max_length=20
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, help_text="Professional license number", max_length=50
                    ),
                ),
                (
                    "license_expiry",
                    models.DateField(blank=True, help_text="License expiry date", null=True),
                ),
                (
                    "license_verified",
                    models.BooleanField(
                        default=False, help_text="Whether license has been verified by admin"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, help_text="Medical specialization", max_length=100
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, help_text="Contact phone number", max_length=20),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, help_text="Emergency contact name", max_length=100
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, help_text="Emergency contact phone", max_length=20
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="ACTIVE",
                        help_text="Current employment status",
                        max_length=20,
                    ),
                ),
                ("date_joined", models.DateField(help_text="Date joined the organization")),
                (
                    "date_left",
                    models.DateField(blank=True, help_text="Date left the organization", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_department",
                    models.ForeignKey(
                        help_text="Primary department",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_staff",
                        to="core.department",
                    ),
                ),
                (
                    "primary_role",
                    models.ForeignKey(
                        help_text="Primary role",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_staff",
                        to="core.role",
                    ),
                ),
                (
                    "secondary_departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional departments",
                        related_name="secondary_staff",
                        to="core.department",
                    ),
                ),
                (
                    "secondary_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional roles",
                        related_name="secondary_staff",
                        to="core.role",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct supervisor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisees",
                        to="core.staffprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Linked user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Profile",
                "verbose_name_plural": "Staff Profiles",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                help_text="Department head",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="core.staffprofile",
            ),
        ),
    ]
