# Generated by Django 5.2.9 on 2026-01-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_department_role_staffprofile_department_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("PERMANENT", "Permanent"),
                    ("CONTRACT", "Contract"),
                    ("LOCUM", "Locum (Part-time)"),
                ],
                default="PERMANENT",
                help_text="Type of employment (Permanent, Contract, or Locum/Part-time)",
                max_length=20,
            ),
        ),
    ]
