# Generated by Django 5.2.9 on 2026-01-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_employment_type_to_staffprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="category",
            field=models.CharField(
                choices=[
                    ("CLINICAL", "Clinical Staff"),
                    ("ADMINISTRATIVE", "Administrative Staff"),
                    ("TECHNICAL", "Technical Staff"),
                    ("MANAGEMENT", "Management"),
                    ("COMMUNITY", "Community Health"),
                ],
                help_text="Role category",
                max_length=20,
            ),
        ),
    ]
