# Generated by Django 5.2.9 on 2026-01-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0009_rename_core_notifi_user_id_3f3d8f_idx_core_notifi_user_id_f286cd_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="hwr_id",
            field=models.CharField(
                blank=True, help_text="Health Worker Registry ID (e.g., PUID-059839)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="licensing_body",
            field=models.CharField(
                blank=True,
                help_text="Regulatory body (e.g., Clinical Officers Council, NCK)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="middle_name",
            field=models.CharField(blank=True, help_text="Middle name (optional)", max_length=100),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Professional license number from licensing body (e.g., COC-Clinical Officer-2026-620095)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="license_verified",
            field=models.BooleanField(
                default=False, help_text="Whether license has been verified via DHA registry lookup"
            ),
        ),
    ]
