# Generated by Django 5.2.9 on 2026-01-18 01:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_add_staff_hwr_middle_name_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("encounter", "Encounter"),
                            ("laboratory", "Laboratory"),
                            ("pharmacy", "Pharmacy"),
                            ("billing", "Billing"),
                            ("triage", "Triage"),
                            ("inpatient", "Inpatient"),
                            ("prescription", "Prescription"),
                            ("appointment", "Appointment"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        help_text="Type of activity (module)",
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Action performed (e.g., registered, completed, dispensed)",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Human-readable title for the activity", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Additional description or context"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the activity occurred",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Type of resource (e.g., Patient, LabOrder)", max_length=50
                    ),
                ),
                ("resource_id", models.PositiveIntegerField(help_text="ID of the resource")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured data (e.g., MRN, patient name)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_feed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Feed",
                "verbose_name_plural": "Activity Feed Entries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["activity_type", "-timestamp"],
                        name="core_activi_activit_9c8c53_idx",
                    ),
                    models.Index(fields=["-timestamp"], name="core_activi_timesta_681121_idx"),
                ],
            },
        ),
    ]
