# Generated by Django 5.2.9 on 2026-01-23 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_frontend_event_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique idempotency key from client (usually UUID)", max_length=64
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Type of resource created (e.g., Patient, Encounter)",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.BigIntegerField(
                        blank=True, help_text="ID of the created resource", null=True
                    ),
                ),
                (
                    "response_status",
                    models.IntegerField(help_text="HTTP status code of the original response"),
                ),
                (
                    "response_data",
                    models.JSONField(
                        default=dict, help_text="Response data to replay on duplicate requests"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this key was created"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Idempotency Key",
                "verbose_name_plural": "Idempotency Keys",
                "indexes": [
                    models.Index(fields=["key", "user"], name="core_idempo_key_91aaf0_idx"),
                    models.Index(fields=["created_at"], name="core_idempo_created_bb3e28_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "user"), name="unique_idempotency_key_per_user"
                    )
                ],
            },
        ),
    ]
