# Generated by Django 5.2.9 on 2026-02-14 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0013_add_idempotency_key_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCodeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_system",
                    models.CharField(
                        db_index=True,
                        help_text="External system ID, e.g., 'LIS_ACME', 'SHA_TARIFF', 'NHIF_2025', 'LOINC'",
                        max_length=100,
                    ),
                ),
                (
                    "external_code",
                    models.CharField(
                        db_index=True, help_text="Code in the external system", max_length=100
                    ),
                ),
                (
                    "external_display",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Display name in external system (for reference)",
                        max_length=255,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(help_text="ID of the internal Vitora entity"),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("EQUIVALENT", "Equivalent"),
                            ("BROADER", "Broader"),
                            ("NARROWER", "Narrower"),
                            ("RELATED", "Related"),
                        ],
                        default="EQUIVALENT",
                        help_text="How the external code relates to the internal entity",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this mapping is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes about this mapping"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this mapping was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this mapping was last updated"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of internal Vitora entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Code Mapping",
                "verbose_name_plural": "External Code Mappings",
                "indexes": [
                    models.Index(
                        fields=["code_system", "external_code"],
                        name="core_extern_code_sy_22db16_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"], name="core_extern_content_82ba8f_idx"
                    ),
                ],
                "unique_together": {("code_system", "external_code")},
            },
        ),
    ]
