# Generated by Django 5.2.9 on 2026-02-15 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_external_code_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'vitora-lab', 'icd-10', 'loinc')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the code system", max_length=100
                    ),
                ),
                (
                    "uri",
                    models.URLField(
                        help_text="FHIR CodeSystem URI (e.g., 'http://hl7.org/fhir/sid/icd-10')",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Code system version (e.g., '2025', 'R4')",
                        max_length=50,
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Organization responsible for the code system",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Detailed description of the code system"
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, help_text="Whether this is a Vitora-managed vocabulary"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this code system is currently in use",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this code system was registered"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this code system was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Code System",
                "verbose_name_plural": "Code Systems",
                "ordering": ["slug"],
            },
        ),
        migrations.AddField(
            model_name="externalcodemapping",
            name="code_system_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to CodeSystem registry for FHIR compliance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mappings",
                to="core.codesystem",
            ),
        ),
    ]
