# Generated by Django 5.2.9 on 2026-02-15 00:37

from django.db import migrations


def populate_code_systems(apps, schema_editor):
    """Pre-populate CodeSystem registry with standard code systems."""
    CodeSystem = apps.get_model("core", "CodeSystem")

    code_systems = [
        {
            "slug": "vitora-lab",
            "name": "Vitora Laboratory Codes",
            "uri": "https://vitora.health/fhir/CodeSystem/laboratory",
            "version": "1.0",
            "publisher": "Nexora Africa Ltd",
            "description": "Internal laboratory test codes used in Vitora HMIS. "
            "Maps to LOINC where applicable.",
            "is_internal": True,
        },
        {
            "slug": "icd-10",
            "name": "ICD-10",
            "uri": "http://hl7.org/fhir/sid/icd-10",
            "version": "2019",
            "publisher": "World Health Organization",
            "description": "International Classification of Diseases, "
            "10th Revision. Used for diagnosis coding.",
            "is_internal": False,
        },
        {
            "slug": "loinc",
            "name": "LOINC",
            "uri": "http://loinc.org",
            "version": "2.77",
            "publisher": "Regenstrief Institute",
            "description": "Logical Observation Identifiers Names and Codes. "
            "Universal standard for laboratory and clinical observations.",
            "is_internal": False,
        },
        {
            "slug": "sha-tariff-2025",
            "name": "SHA Tariff 2025",
            "uri": "https://sha.go.ke/tariff/2025",
            "version": "2025",
            "publisher": "Social Health Authority Kenya",
            "description": "Kenya Social Health Authority tariff codes for "
            "healthcare services and procedures.",
            "is_internal": False,
        },
        {
            "slug": "snomed-ct",
            "name": "SNOMED CT",
            "uri": "http://snomed.info/sct",
            "version": "2024-01",
            "publisher": "SNOMED International",
            "description": "Systematized Nomenclature of Medicine Clinical Terms. "
            "Comprehensive clinical terminology.",
            "is_internal": False,
        },
        {
            "slug": "khis",
            "name": "KHIS/DHIS2 Codes",
            "uri": "https://hiskenya.org/khis",
            "version": "2024",
            "publisher": "Ministry of Health Kenya",
            "description": "Kenya Health Information System (DHIS2) indicator and "
            "data element codes for national health reporting.",
            "is_internal": False,
        },
        {
            "slug": "ndc",
            "name": "National Drug Code",
            "uri": "http://hl7.org/fhir/sid/ndc",
            "version": "2024",
            "publisher": "U.S. Food and Drug Administration",
            "description": "National Drug Code for pharmaceutical product identification.",
            "is_internal": False,
        },
    ]

    for cs_data in code_systems:
        CodeSystem.objects.get_or_create(slug=cs_data["slug"], defaults=cs_data)


def remove_code_systems(apps, schema_editor):
    """Remove pre-populated code systems (reverse migration)."""
    CodeSystem = apps.get_model("core", "CodeSystem")
    slugs = [
        "vitora-lab",
        "icd-10",
        "loinc",
        "sha-tariff-2025",
        "snomed-ct",
        "khis",
        "ndc",
    ]
    CodeSystem.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_add_code_system"),
    ]

    operations = [
        migrations.RunPython(populate_code_systems, remove_code_systems),
    ]
