# Generated by Django 5.2.9 on 2026-02-22 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_populate_code_systems"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(help_text="SHA-256 hash of the backup code", max_length=64),
                ),
                (
                    "used",
                    models.BooleanField(default=False, help_text="Whether this code has been used"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When code was created"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, help_text="When code was used", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Code",
                "verbose_name_plural": "Backup Codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MFAToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="The temporary MFA token", max_length=128, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When token was created"),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False, help_text="Whether this token has been used"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the login request", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this token belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA Token",
                "verbose_name_plural": "MFA Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserTOTPDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Device name (e.g., 'Phone', 'Tablet')", max_length=100
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(help_text="Base32-encoded secret key", max_length=64),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False, help_text="Whether device has been verified"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When device was created"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When device was last used for verification",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TOTP Device",
                "verbose_name_plural": "TOTP Devices",
                "ordering": ["-created_at"],
            },
        ),
    ]
