# Generated by Django 5.2.9 on 2026-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_mfa_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertotpdevice",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, help_text="When device was confirmed (MFA enabled)", null=True
            ),
        ),
    ]
