# Generated by Django 5.2.9 on 2026-02-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_emergency_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="mfatoken",
            name="failed_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of failed verification attempts"
            ),
        ),
    ]
