# Generated by Django 5.2.11 on 2026-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_mfa_token_failed_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique feature name (e.g., smart_autopopulate)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, help_text="Whether the feature is currently enabled"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of what this flag controls",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["name"],
            },
        ),
    ]
