# Generated by Django 5.2.11 on 2026-03-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_department_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mfl_code",
                    models.CharField(
                        help_text="Kenya Master Facility List (MFL) code – the unique identifier assigned to every registered health facility by the MoH.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official facility name as registered on the MFL.", max_length=200
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("1", "Level 1 – Community Unit"),
                            ("2", "Level 2 – Dispensary"),
                            ("3", "Level 3 – Health Centre"),
                            ("4", "Level 4 – Sub-County Hospital"),
                            ("5", "Level 5 – County Referral Hospital"),
                            ("6", "Level 6 – National Referral Hospital"),
                        ],
                        help_text="KEPH level (1–6) determining the scope of services offered.",
                        max_length=1,
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[
                            ("GOK", "Government of Kenya"),
                            ("FBO", "Faith-Based Organization"),
                            ("NGO", "Non-Governmental Organization"),
                            ("PRIVATE", "Private Practice"),
                        ],
                        help_text="Ownership category (GOK, FBO, NGO, or Private).",
                        max_length=20,
                    ),
                ),
                (
                    "sha_contracted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the facility is contracted by the Social Health Authority (SHA) for claims processing.",
                    ),
                ),
                (
                    "sha_contract_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Date when the current SHA contract expires.",
                        null=True,
                    ),
                ),
                (
                    "sha_facility_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-specific facility code used in claims submission.",
                        max_length=50,
                    ),
                ),
                (
                    "has_outpatient",
                    models.BooleanField(
                        default=True, help_text="Outpatient Department (OPD) services."
                    ),
                ),
                (
                    "has_inpatient",
                    models.BooleanField(
                        default=False, help_text="Inpatient (ward admission) services."
                    ),
                ),
                (
                    "has_emergency",
                    models.BooleanField(
                        default=False, help_text="Emergency / Casualty department."
                    ),
                ),
                (
                    "has_pharmacy",
                    models.BooleanField(default=True, help_text="Pharmacy / dispensing services."),
                ),
                (
                    "has_laboratory",
                    models.BooleanField(
                        default=False, help_text="Laboratory / diagnostics services."
                    ),
                ),
                (
                    "has_imaging",
                    models.BooleanField(default=False, help_text="Radiology / imaging services."),
                ),
                (
                    "has_theatre",
                    models.BooleanField(
                        default=False, help_text="Surgical theatre / operating room."
                    ),
                ),
                (
                    "has_dialysis",
                    models.BooleanField(default=False, help_text="Renal dialysis unit."),
                ),
                (
                    "has_icu",
                    models.BooleanField(default=False, help_text="Intensive Care Unit (ICU)."),
                ),
                (
                    "has_maternity",
                    models.BooleanField(
                        default=False, help_text="Maternity / obstetrics services."
                    ),
                ),
                (
                    "has_mortuary",
                    models.BooleanField(default=False, help_text="Mortuary / funeral services."),
                ),
                (
                    "has_blood_bank",
                    models.BooleanField(
                        default=False, help_text="Blood bank / transfusion services."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the facility is currently operational."
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        help_text="County where the facility is located.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facilities",
                        to="core.county",
                    ),
                ),
                (
                    "sub_county",
                    models.ForeignKey(
                        help_text="Sub-county where the facility is located.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facilities",
                        to="core.subcounty",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ward where the facility is located (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facilities",
                        to="core.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "ordering": ["name"],
            },
        ),
    ]
