# Generated by Django 5.2.11 on 2026-03-13 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_add_snomed_ct_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="entry_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA-256 hex digest of this audit entry",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 hash of the previous entry in the chain",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="sequence_number",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Monotonic sequence number for hash chain ordering",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["sequence_number"], name="core_auditl_sequenc_928bf7_idx"),
        ),
    ]
