# Generated by Django 5.2.11 on 2026-03-13 23:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_add_audit_hash_chaining"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="CA display name (e.g., 'Vitora HMIS Root CA')", max_length=200
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Certificate serial number (hex)", max_length=64, unique=True
                    ),
                ),
                (
                    "subject_dn",
                    models.CharField(
                        help_text="Distinguished Name (e.g., 'CN=Vitora HMIS Root CA, O=Nexora Africa Ltd, C=KE')",
                        max_length=500,
                    ),
                ),
                ("public_key_pem", models.TextField(help_text="PEM-encoded public key")),
                (
                    "private_key_pem_encrypted",
                    models.TextField(help_text="PEM private key encrypted with KMS"),
                ),
                ("certificate_pem", models.TextField(help_text="X.509 certificate in PEM format")),
                ("valid_from", models.DateTimeField(help_text="Certificate validity start")),
                ("valid_to", models.DateTimeField(help_text="Certificate validity end")),
                (
                    "is_root",
                    models.BooleanField(
                        default=True, help_text="Whether this is a root CA (self-signed)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this CA is currently active for issuing certificates",
                    ),
                ),
                ("key_size", models.IntegerField(default=2048, help_text="RSA key size in bits")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_ca",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent CA for intermediate CAs",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subordinate_cas",
                        to="core.certificateauthority",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Authority",
                "verbose_name_plural": "Certificate Authorities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Certificate serial number (hex)", max_length=64, unique=True
                    ),
                ),
                (
                    "subject_dn",
                    models.CharField(help_text="Certificate subject DN", max_length=500),
                ),
                ("public_key_pem", models.TextField(help_text="PEM-encoded public key")),
                (
                    "private_key_pem_encrypted",
                    models.TextField(help_text="PEM private key encrypted with KMS"),
                ),
                ("certificate_pem", models.TextField(help_text="X.509 certificate in PEM format")),
                ("valid_from", models.DateTimeField(help_text="Certificate validity start")),
                ("valid_to", models.DateTimeField(help_text="Certificate validity end")),
                (
                    "is_revoked",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this certificate has been revoked",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, help_text="When the certificate was revoked", null=True
                    ),
                ),
                (
                    "revocation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("KEY_COMPROMISE", "Key Compromise"),
                            ("AFFILIATION_CHANGED", "Affiliation Changed"),
                            ("SUPERSEDED", "Superseded"),
                            ("CESSATION", "Cessation of Operation"),
                            ("PRIVILEGE_WITHDRAWN", "Privilege Withdrawn"),
                        ],
                        default="",
                        help_text="Reason for revocation",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate_authority",
                    models.ForeignKey(
                        help_text="CA that issued this certificate",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_certificates",
                        to="core.certificateauthority",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Certificate",
                "verbose_name_plural": "User Certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        db_index=True,
                        help_text="Model name of the signed document (e.g., 'LabResult', 'Prescription')",
                        max_length=50,
                    ),
                ),
                (
                    "document_id",
                    models.BigIntegerField(
                        db_index=True, help_text="Primary key of the signed document"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SHA-256 hex digest of the document content at signing time",
                        max_length=64,
                    ),
                ),
                ("signature", models.TextField(help_text="Base64-encoded RSA signature")),
                (
                    "hash_algorithm",
                    models.CharField(
                        default="SHA-256", help_text="Hash algorithm used", max_length=20
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When the document was signed"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True, help_text="Cached validity (updated on verification)"
                    ),
                ),
                (
                    "verification_note",
                    models.TextField(
                        blank=True, default="", help_text="Notes from the last verification"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signer",
                    models.ForeignKey(
                        help_text="User who signed the document",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        help_text="Certificate used to create the signature",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to="core.usercertificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Signature",
                "verbose_name_plural": "Document Signatures",
                "ordering": ["-signed_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateRevocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the certificate was revoked",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("KEY_COMPROMISE", "Key Compromise"),
                            ("AFFILIATION_CHANGED", "Affiliation Changed"),
                            ("SUPERSEDED", "Superseded"),
                            ("CESSATION", "Cessation of Operation"),
                            ("PRIVILEGE_WITHDRAWN", "Privilege Withdrawn"),
                        ],
                        help_text="Reason for revocation",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revoked_by",
                    models.ForeignKey(
                        help_text="User who revoked the certificate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_revocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        help_text="The revoked certificate",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revocations",
                        to="core.usercertificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Revocation",
                "verbose_name_plural": "Certificate Revocations",
                "ordering": ["-revoked_at"],
            },
        ),
        migrations.AddIndex(
            model_name="usercertificate",
            index=models.Index(
                fields=["user", "is_revoked"], name="core_userce_user_id_85f683_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsignature",
            index=models.Index(
                fields=["document_type", "document_id"], name="core_docume_documen_854d0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsignature",
            index=models.Index(
                fields=["signer", "signed_at"], name="core_docume_signer__d7de05_idx"
            ),
        ),
    ]
