# Generated by Django 5.2.11 on 2026-03-25 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0029_multitenancy_clinical_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility this role is scoped to (only when scope=FACILITY).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this role belongs to (null = system-wide default).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="scope",
            field=models.CharField(
                choices=[("ORG", "Organization-wide"), ("FACILITY", "Facility-specific")],
                default="ORG",
                help_text="Whether this role applies org-wide or to a specific facility.",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("facility__isnull", True), ("scope", "FACILITY"), _negated=True
                ),
                name="role_facility_required_when_facility_scoped",
            ),
        ),
    ]
