# Generated by Django 5.2.11 on 2026-03-31 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_staffprofile_must_change_password_passwordresettoken_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the admin email has been verified (self-service signup).",
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        editable=False, help_text="Unique verification token.", unique=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this token expires (default: 24 hours)."),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False, help_text="Whether this token has been used."
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification Token",
                "verbose_name_plural": "Email Verification Tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="core_emailv_token_aabf9a_idx"),
                    models.Index(fields=["user", "used"], name="core_emailv_user_id_915379_idx"),
                ],
            },
        ),
    ]
