# Generated by Django 5.2.11 on 2026-04-01 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_add_org_verification_and_email_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="secondary_organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional organizations (for locum, part-time, or consultant physicians)",
                related_name="secondary_staff_profiles",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary organization (cached from primary_facility for query performance)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_profiles",
                to="core.organization",
            ),
        ),
    ]
