# Generated by Django 5.2.11 on 2026-04-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_unique_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="mfa_grace_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline by which MFA must be configured for roles that require it. Set on first login; after this deadline, API access is blocked until MFA is set up. Default grace period: 72 hours.",
                null=True,
            ),
        ),
    ]
