# Generated by Django 5.2.11 on 2026-04-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_add_webauthn_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Facility logo for branding. Falls back to organization logo if not set.",
                null=True,
                upload_to="facilities/logos/",
            ),
        ),
    ]
