# Generated by Django 5.2.11 on 2026-04-11 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_add_facility_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="UUID v4 identifier for this event instance.",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Dotted event type name (e.g. 'prescription.created').",
                        max_length=200,
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        db_index=True,
                        help_text="Model/entity that produced the event (e.g. 'Prescription').",
                        max_length=100,
                    ),
                ),
                (
                    "aggregate_id",
                    models.CharField(
                        help_text="Primary key of the aggregate instance.", max_length=100
                    ),
                ),
                ("payload", models.JSONField(default=dict, help_text="Event-specific data.")),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the event occurred.",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, help_text="User ID who triggered the event.", null=True
                    ),
                ),
                (
                    "facility_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Facility where the event originated.",
                        null=True,
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Organization scope for the event.",
                        null=True,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        db_index=True,
                        help_text="UUID linking related events in a workflow.",
                        max_length=36,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Event",
                "verbose_name_plural": "Domain Events",
                "ordering": ["timestamp", "id"],
                "indexes": [
                    models.Index(
                        fields=["aggregate_type", "aggregate_id", "timestamp"],
                        name="idx_event_aggregate_ts",
                    ),
                    models.Index(fields=["event_type", "timestamp"], name="idx_event_type_ts"),
                ],
            },
        ),
    ]
