# Generated by Django 5.2.11 on 2026-04-11 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_domain_event_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicQueueStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("facility_id", models.IntegerField(db_index=True)),
                ("clinic_id", models.IntegerField(db_index=True)),
                ("waiting_count", models.PositiveIntegerField(default=0)),
                ("in_consultation_count", models.PositiveIntegerField(default=0)),
                ("completed_today", models.PositiveIntegerField(default=0)),
                ("no_show_today", models.PositiveIntegerField(default=0)),
                (
                    "avg_wait_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Average wait time in seconds (registered → called)"
                    ),
                ),
                (
                    "longest_wait_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Longest current wait in seconds"
                    ),
                ),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Clinic Queue Stats",
                "verbose_name_plural": "Clinic Queue Stats",
                "indexes": [models.Index(fields=["facility_id"], name="idx_cqs_facility")],
                "unique_together": {("facility_id", "clinic_id")},
            },
        ),
        migrations.CreateModel(
            name="PharmacyQueueStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("facility_id", models.IntegerField(db_index=True, unique=True)),
                ("pending_prescriptions", models.PositiveIntegerField(default=0)),
                ("dispensed_today", models.PositiveIntegerField(default=0)),
                (
                    "critical_stock_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of drugs at zero stock"
                    ),
                ),
                (
                    "low_stock_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of drugs below reorder level"
                    ),
                ),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Pharmacy Queue Stats",
                "verbose_name_plural": "Pharmacy Queue Stats",
                "indexes": [models.Index(fields=["facility_id"], name="idx_pqs_facility")],
            },
        ),
        migrations.CreateModel(
            name="WardOccupancyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("facility_id", models.IntegerField(db_index=True)),
                ("ward_id", models.IntegerField(db_index=True)),
                ("total_beds", models.PositiveIntegerField(default=0)),
                ("occupied_beds", models.PositiveIntegerField(default=0)),
                ("available_beds", models.PositiveIntegerField(default=0)),
                (
                    "occupancy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Occupancy percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                ("admissions_today", models.PositiveIntegerField(default=0)),
                ("discharges_today", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Ward Occupancy Stats",
                "verbose_name_plural": "Ward Occupancy Stats",
                "indexes": [models.Index(fields=["facility_id"], name="idx_wos_facility")],
                "unique_together": {("facility_id", "ward_id")},
            },
        ),
    ]
