# Generated by Django 5.2.13 on 2026-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_projection_read_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="has_inventory",
            field=models.BooleanField(
                default=False, help_text="Inventory / supply chain management module."
            ),
        ),
    ]
