# Generated by Django 5.2.13 on 2026-04-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_add_has_inventory_to_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="onboarding_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When initial onboarding was completed. NULL means the org admin has not finished setting up the organization (facility modules, first clinic, inviting staff, etc.).",
                null=True,
            ),
        ),
    ]
