# Generated by Django 5.2.13 on 2026-04-18 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_add_onboarding_completed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the staff member's primary (home) organization.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="ACTIVE",
                        help_text="Current membership status.",
                        max_length=20,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the member joined this organization."
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department within this organization (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="org_memberships",
                        to="core.department",
                    ),
                ),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Facilities the member can access within this organization.",
                        related_name="org_memberships",
                        to="core.facility",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who invited this member (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization the staff member belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Role within this organization.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="org_memberships",
                        to="core.role",
                    ),
                ),
                (
                    "staff_profile",
                    models.ForeignKey(
                        help_text="Staff member this membership belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
                "ordering": ["-is_primary", "-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["staff_profile", "status"], name="core_orgmem_staff_p_5e925c_idx"
                    ),
                    models.Index(
                        fields=["organization", "status"], name="core_orgmem_organiz_fc0ba1_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff_profile", "organization"), name="unique_staff_org_membership"
                    )
                ],
            },
        ),
    ]
