# Generated by Django 5.2.13 on 2026-04-18 18:28

from django.db import migrations


def backfill_org_memberships(apps, schema_editor):
    """Create OrgMembership records from existing StaffProfile data.

    For each StaffProfile with an organization:
      - Create a primary OrgMembership from organization + primary_role + primary_department
      - Add primary_facility to the membership's facilities M2M
      - Add secondary_facilities to the membership's facilities M2M

    For each entry in secondary_organizations M2M:
      - Create a non-primary OrgMembership using the profile's primary_role as fallback
      - Add any secondary_facilities belonging to that org
    """
    StaffProfile = apps.get_model("core", "StaffProfile")
    OrgMembership = apps.get_model("core", "OrgMembership")

    for profile in StaffProfile.objects.select_related(
        "organization", "primary_role", "primary_department", "primary_facility"
    ).all():
        if not profile.organization_id:
            continue

        # --- Primary membership ---
        membership, _created = OrgMembership.objects.get_or_create(
            staff_profile=profile,
            organization=profile.organization,
            defaults={
                "role_id": profile.primary_role_id,
                "department_id": profile.primary_department_id,
                "is_primary": True,
                "status": "ACTIVE",
            },
        )
        # Add primary facility
        if profile.primary_facility_id:
            membership.facilities.add(profile.primary_facility_id)
        # Add secondary facilities that belong to the primary org
        for fac in profile.secondary_facilities.filter(
            organization=profile.organization
        ):
            membership.facilities.add(fac)

        # --- Secondary org memberships ---
        for sec_org in profile.secondary_organizations.all():
            sec_membership, _created = OrgMembership.objects.get_or_create(
                staff_profile=profile,
                organization=sec_org,
                defaults={
                    "role_id": profile.primary_role_id,  # Fallback
                    "department_id": profile.primary_department_id,
                    "is_primary": False,
                    "status": "ACTIVE",
                },
            )
            # Add secondary facilities belonging to this org
            for fac in profile.secondary_facilities.filter(organization=sec_org):
                sec_membership.facilities.add(fac)


def reverse_backfill(apps, schema_editor):
    """Remove all OrgMembership records (reverse of backfill)."""
    OrgMembership = apps.get_model("core", "OrgMembership")
    OrgMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_org_membership"),
    ]

    operations = [
        migrations.RunPython(backfill_org_memberships, reverse_backfill),
    ]
