# Generated by Django 5.2.13 on 2026-04-18 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_backfill_org_memberships"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staffinvitation",
            name="existing_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to existing user being invited cross-org.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cross_org_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffinvitation",
            name="is_cross_org",
            field=models.BooleanField(
                default=False, help_text="True when inviting an existing user to a different org."
            ),
        ),
        migrations.AlterField(
            model_name="staffinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("EXPIRED", "Expired"),
                    ("REVOKED", "Revoked"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OrgJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.TextField(
                        blank=True, default="", help_text="Reason the user wants to join."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, default="", help_text="Admin notes on approval/rejection."
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization the user wants to join.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="core.organization",
                    ),
                ),
                (
                    "requested_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role the user is requesting (optional suggestion).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="join_requests",
                        to="core.role",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved or rejected.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting to join.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Join Request",
                "verbose_name_plural": "Organization Join Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="core_orgjoi_user_id_f8fc6c_idx"),
                    models.Index(
                        fields=["organization", "status"], name="core_orgjoi_organiz_f1f22c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("user", "organization"),
                        name="unique_pending_join_request",
                    )
                ],
            },
        ),
    ]
