# Generated by Django 5.2.13 on 2026-04-21 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_cross_org_join_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomUtilizationStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_id", models.IntegerField(db_index=True)),
                ("room_id", models.IntegerField(db_index=True)),
                ("clinic_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("stat_date", models.DateField(db_index=True)),
                ("staffed_minutes", models.PositiveIntegerField(default=0)),
                ("consultation_minutes", models.PositiveIntegerField(default=0)),
                (
                    "utilization_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Consultation time / staffed time * 100",
                        max_digits=5,
                    ),
                ),
                ("visits_completed", models.PositiveIntegerField(default=0)),
                ("no_show_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_wait_to_room_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average minutes from registration to consultation start",
                        max_digits=8,
                    ),
                ),
                (
                    "avg_consultation_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average minutes spent in consultation",
                        max_digits=8,
                    ),
                ),
                ("active_clinicians_count", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Room Utilization Stats",
                "verbose_name_plural": "Room Utilization Stats",
                "indexes": [
                    models.Index(fields=["facility_id", "stat_date"], name="idx_rus_facility_date"),
                    models.Index(fields=["facility_id", "clinic_id"], name="idx_rus_facility_clinic"),
                ],
                "unique_together": {("facility_id", "room_id", "stat_date")},
            },
        ),
    ]
