# Generated by Django 5.2.13 on 2026-04-21 16:34

import hmis.apps.core.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_room_utilization_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='logo',
            field=models.ImageField(blank=True, help_text='Facility logo for branding. Falls back to organization logo if not set.', null=True, upload_to='facilities/logos/', validators=[hmis.apps.core.upload_validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo for branding.', null=True, upload_to='organizations/logos/', validators=[hmis.apps.core.upload_validators.validate_image_upload]),
        ),
    ]
