# Generated by Django 5.2.13 on 2026-04-23 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_backfill_department_facility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "endpoint",
                    models.URLField(help_text="Push service endpoint URL", max_length=500),
                ),
                (
                    "p256dh",
                    models.CharField(help_text="Client public key (base64url)", max_length=200),
                ),
                ("auth", models.CharField(help_text="Auth secret (base64url)", max_length=200)),
                ("user_agent", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Subscription",
                "verbose_name_plural": "Push Subscriptions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "endpoint"), name="unique_push_subscription"
                    )
                ],
            },
        ),
    ]
