# Generated by Django 5.2.13 on 2026-04-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_push_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pushsubscription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Push Subscription",
                "verbose_name_plural": "Push Subscriptions",
            },
        ),
    ]
