# Generated by Django 5.2.13 on 2026-04-29 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_alter_pushsubscription_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DHAOutboundCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("method", models.CharField(max_length=10)),
                (
                    "path",
                    models.CharField(
                        help_text="Path on the ILM middleware (no host).", max_length=500
                    ),
                ),
                ("base_url", models.CharField(blank=True, default="", max_length=255)),
                ("auth_mode", models.CharField(blank=True, default="", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("CLIENT_ERROR", "Client Error (4xx)"),
                            ("SERVER_ERROR", "Server Error (5xx)"),
                            ("TRANSPORT", "Transport Error"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("consent_token", models.CharField(blank=True, default="", max_length=255)),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=64)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "request_payload",
                    models.JSONField(blank=True, help_text="PII-redacted body.", null=True),
                ),
                (
                    "response_excerpt",
                    models.JSONField(blank=True, help_text="First 4KB of response.", null=True),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dha_outbound_calls",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dha_outbound_calls",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the call (if request-scoped).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dha_outbound_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DHA Outbound Call",
                "verbose_name_plural": "DHA Outbound Calls",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["facility", "-created_at"], name="core_dhaout_facilit_be30e1_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="core_dhaout_status_1bd44e_idx"
                    ),
                    models.Index(fields=["consent_token"], name="core_dhaout_consent_45bc0f_idx"),
                    models.Index(fields=["correlation_id"], name="core_dhaout_correla_b92644_idx"),
                    models.Index(fields=["path"], name="core_dhaout_path_aea5b1_idx"),
                ],
            },
        ),
    ]
