# Generated by Django 5.2.13 on 2026-05-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_facility_biometrics_agent_national_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="has_lis_standalone",
            field=models.BooleanField(
                default=False,
                help_text="LIS standalone mode: lab operates independently without full HMIS.",
            ),
        ),
    ]
