# Generated by Django 5.2.13 on 2026-05-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_lis_standalone_facility_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="dhis2_org_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DHIS2 Organisation Unit UID for this facility. Each facility has a unique 11-character UID in KHIS.",
                max_length=11,
            ),
        ),
        migrations.CreateModel(
            name="DHIS2Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label, e.g. 'Mombasa Sub-County KHIS'.",
                        max_length=100,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="DHIS2 instance base URL, e.g. 'https://hiskenya.org'.",
                        max_length=255,
                    ),
                ),
                ("username", models.CharField(help_text="DHIS2 API username.", max_length=150)),
                (
                    "_password",
                    models.TextField(
                        db_column="password",
                        help_text="Encrypted DHIS2 API password. Use set_password()/get_password().",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("local", "Local (dev/test)"),
                            ("staging", "Staging"),
                            ("production", "Production (KHIS)"),
                        ],
                        default="production",
                        help_text="Target DHIS2 environment (controls data-element UID resolution).",
                        max_length=12,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this configuration is currently active."
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "DHIS2 Configuration",
                "verbose_name_plural": "DHIS2 Configurations",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("organization",),
                        name="unique_active_dhis2_config_per_org",
                    )
                ],
            },
        ),
    ]
