# Generated by Django 5.2.13 on 2026-05-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_dhis2_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("BASIC", "Basic"),
                            ("PROFESSIONAL", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        help_text="Unique tier code (matches Organization.subscription_tier).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name shown to customers (e.g. 'Professional Plan').",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Marketing description of this plan."
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly price in KES.",
                        max_digits=10,
                    ),
                ),
                (
                    "annual_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual price in KES (typically discounted).",
                        max_digits=10,
                    ),
                ),
                (
                    "max_facilities",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of facilities (null = unlimited).",
                        null=True,
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of staff users (null = unlimited).",
                        null=True,
                    ),
                ),
                (
                    "max_patients",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of patient records (null = unlimited).",
                        null=True,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Feature flags for this plan. Example: {"pharmacy": true, "laboratory": true, "ai_assistant": false}',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is currently available for selection.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower = first)."
                    ),
                ),
                (
                    "trial_period_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Trial period in days (0 = no trial)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["sort_order", "monthly_price"],
            },
        ),
    ]
