# Generated by Django 5.2.13 on 2026-05-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_add_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="max_patients",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of patient records (synced from plan, null = unlimited).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked subscription plan (source of truth for limits/features).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="core.subscriptionplan",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="max_facilities",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of facilities allowed (synced from plan, null = unlimited).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="max_users",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of staff users allowed (synced from plan, null = unlimited).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("BASIC", "Basic"),
                    ("PROFESSIONAL", "Professional"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="BASIC",
                help_text="Current subscription tier (synced from subscription_plan.code).",
                max_length=20,
            ),
        ),
    ]
