# Generated by Django 5.2.13 on 2026-05-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_link_org_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="ai_tokens_reset_at",
            field=models.DateTimeField(
                blank=True, help_text="When the AI token counter was last reset.", null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_tokens_used",
            field=models.PositiveIntegerField(
                default=0, help_text="AI tokens consumed in the current billing cycle."
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="monthly_ai_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Monthly AI token quota (synced from plan, null = unlimited).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("TRIAL", "Trial"),
                    ("EXPIRED", "Expired"),
                    ("SUSPENDED", "Suspended"),
                ],
                default="ACTIVE",
                help_text="Current subscription lifecycle state.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current subscription period expires (null = no expiry).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="monthly_ai_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Monthly AI token quota (null = unlimited). Resets on billing cycle.",
                null=True,
            ),
        ),
    ]
