# Generated by Django 5.2.13 on 2026-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_subscription_expiry_ai_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("BASIC", "Basic"),
                    ("PROFESSIONAL", "Professional"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="FREE",
                editable=False,
                help_text="Derived from subscription_plan.code — do not set directly.",
                max_length=20,
            ),
        ),
    ]
