# Generated by Django 5.2.13 on 2026-05-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_subscription_tier_derived_readonly"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="has_allied_health",
            field=models.BooleanField(
                default=False,
                help_text="Allied health services (physiotherapy, nutrition, social work, etc.).",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="has_billing",
            field=models.BooleanField(
                default=True, help_text="Billing, invoicing, and financial management."
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="has_immunizations",
            field=models.BooleanField(
                default=False, help_text="Immunization / vaccination programme."
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="has_quality",
            field=models.BooleanField(
                default=False, help_text="Quality improvement and clinical audit."
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="has_scheduling",
            field=models.BooleanField(
                default=True, help_text="Appointment scheduling and roster management."
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="has_surveillance",
            field=models.BooleanField(
                default=False, help_text="Disease surveillance and outbreak reporting."
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="has_triage",
            field=models.BooleanField(
                default=True, help_text="Triage / patient acuity assessment."
            ),
        ),
    ]
