# Generated by Django 5.2.13 on 2026-05-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_add_has_private_insurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="has_imaging_standalone",
            field=models.BooleanField(
                default=False,
                help_text="Imaging standalone mode: imaging operates independently (e.g., diagnostic centre) without full HMIS.",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="has_pharmacy_standalone",
            field=models.BooleanField(
                default=False,
                help_text="Pharmacy standalone mode: pharmacy operates as a retail/walk-in dispensary without full HMIS.",
            ),
        ),
    ]
