# Generated by Django 5.2.13 on 2026-05-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_facility_has_imaging_standalone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="operating_mode",
            field=models.CharField(
                choices=[
                    ("FULL_HMIS", "Full HMIS"),
                    ("STANDALONE_LAB", "Standalone Lab"),
                    ("STANDALONE_PHARMACY", "Standalone Pharmacy"),
                    ("STANDALONE_IMAGING", "Standalone Imaging"),
                    ("STANDALONE_DIAGNOSTIC", "Standalone Diagnostic Centre"),
                ],
                default="FULL_HMIS",
                help_text="Top-level facility mode. Choosing a standalone mode disables clinical workflow modules (inpatient, ER, triage, etc.) and enables the relevant standalone module + billing + inventory.",
                max_length=30,
            ),
        ),
    ]
