# Generated by Django 5.2.13 on 2026-05-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_facility_operating_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="has_moh_reporting",
            field=models.BooleanField(
                default=True, help_text="MOH 705/711/717 aggregate reporting and DHIS2 submission."
            ),
        ),
    ]
