# Generated by Django 5.2.13 on 2026-05-26 18:58

from django.db import migrations


def disable_moh_for_standalone(apps, schema_editor):
    """Disable has_moh_reporting for all standalone facilities."""
    Facility = apps.get_model("core", "Facility")
    standalone_modes = [
        "STANDALONE_LAB",
        "STANDALONE_PHARMACY",
        "STANDALONE_IMAGING",
        "STANDALONE_DIAGNOSTIC",
    ]
    updated = Facility.objects.filter(operating_mode__in=standalone_modes).update(
        has_moh_reporting=False
    )
    if updated:
        print(f"  Disabled has_moh_reporting for {updated} standalone facility(ies)")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_add_has_moh_reporting"),
    ]

    operations = [
        migrations.RunPython(disable_moh_for_standalone, noop),
    ]
