# Generated by Django 5.2.13 on 2026-07-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_staffprofile_employee_id_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="biometrics_enforced",
            field=models.BooleanField(
                default=False,
                help_text="When True, DHA requires biometric (fingerprint) consent for this facility — OTP-only consent is not allowed. Set by DHA compliance.",
            ),
        ),
    ]
