# Generated by Django 5.2.13 on 2026-07-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_add_biometrics_enforced_to_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="workstation_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hardware Server workstation identifier for DHA biometric consent.",
                max_length=100,
            ),
        ),
    ]
