# Generated by Django 5.2.13 on 2026-07-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_staffprofile_mfa_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="discipline_name",
            field=models.CharField(
                blank=True, help_text="Discipline name from DHA registry", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="educational_qualifications",
            field=models.CharField(
                blank=True, help_text="Educational qualifications from DHA registry", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="hwr_salutation",
            field=models.CharField(
                blank=True,
                help_text="Salutation from DHA registry (e.g., Dr., Prof., Mr.)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="hwr_status",
            field=models.CharField(
                blank=True, help_text="HWR practitioner status (e.g., Licensed)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="identification_type",
            field=models.CharField(
                blank=True,
                help_text="Identification document type from DHA registry (e.g., National ID)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="postal_address",
            field=models.CharField(
                blank=True, help_text="Postal address from DHA registry", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="practice_type",
            field=models.CharField(
                blank=True,
                help_text="Practice type from DHA registry (e.g., Clinical Officer)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="subspecialty",
            field=models.CharField(
                blank=True, help_text="Sub-specialty from DHA registry", max_length=200
            ),
        ),
    ]
