# Generated by Django 5.2.13 on 2026-07-20 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_add_hwr_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "sku_type",
                    models.CharField(
                        choices=[
                            ("BASE", "Base"),
                            ("MODULE", "Module"),
                            ("PLATFORM", "Platform"),
                            ("STANDALONE", "Standalone"),
                        ],
                        default="MODULE",
                        max_length=20,
                    ),
                ),
                ("enabled_feature_keys", models.JSONField(blank=True, default=list)),
                ("monthly_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("annual_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("included_ai_tokens", models.PositiveIntegerField(default=0)),
                ("included_sms_messages", models.PositiveIntegerField(default=0)),
                ("included_api_calls", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "price_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="core.pricebook",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="SKUDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("FEATURE_ALL", "Feature All"), ("FEATURE_ANY", "Feature Any")],
                        default="FEATURE_ALL",
                        max_length=20,
                    ),
                ),
                ("required_feature_keys", models.JSONField(blank=True, default=list)),
                ("error_message", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="core.sku",
                    ),
                ),
            ],
            options={
                "ordering": ["sku__code", "id"],
            },
        ),
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True, default="")),
                ("included_sku_codes", models.JSONField(blank=True, default=list)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENT", "Percent"),
                            ("FIXED", "Fixed"),
                            ("NEGOTIATED", "Negotiated"),
                        ],
                        default="PERCENT",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "price_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="core.pricebook",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("price_book", "code"), name="uniq_pricebook_bundle_code"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sku",
            constraint=models.UniqueConstraint(
                fields=("price_book", "code"), name="uniq_pricebook_sku_code"
            ),
        ),
    ]
