# Generated by Django 5.2.11 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_smsdeliverycallback"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="has_hdu",
            field=models.BooleanField(default=False, help_text="High Dependency Unit (HDU)."),
        ),
        migrations.AddField(
            model_name="facility",
            name="has_nbu",
            field=models.BooleanField(default=False, help_text="Newborn Unit (NBU)."),
        ),
    ]
