# Generated by Django 5.2.13 on 2026-08-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_scope_pki_to_organization"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usercertificate",
            new_name="core_userce_organiz_34425a_idx",
            old_name="core_userce_organiz_4f466f_idx",
        ),
    ]
