# Copyright (c) 2026 Nexora Consulting Ltd. All rights reserved.
# Generated by Django 5.2.13 on 2026-09-04 17:40

import django.db.models.deletion
import hmis.apps.core.models_reference_geo_staff
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_facility_lis_onboarding_completed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 code (e.g., KE, UG, TZ).",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display country name.", max_length=120, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="country_code",
            field=models.CharField(
                default="KE",
                help_text="ISO 3166-1 alpha-2 code for the facility country.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="district",
            field=models.CharField(
                blank=True,
                default="",
                help_text="District/county equivalent for non-Kenya locations.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_registry_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Generic national registry code for non-Kenya facilities.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="locality",
            field=models.CharField(
                blank=True,
                default="",
                help_text="City/town/locality for non-Kenya locations.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="region_state",
            field=models.CharField(
                blank=True,
                default="",
                help_text="State/province/region for non-Kenya locations.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="county",
            name="code",
            field=models.PositiveSmallIntegerField(help_text="County code (1-47 for Kenya)"),
        ),
        migrations.AlterField(
            model_name="county",
            name="name",
            field=models.CharField(help_text="County name", max_length=100),
        ),
        migrations.AlterField(
            model_name="facility",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="County where the facility is located.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facilities",
                to="core.county",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="sub_county",
            field=models.ForeignKey(
                blank=True,
                help_text="Sub-county where the facility is located.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facilities",
                to="core.subcounty",
            ),
        ),
        migrations.AddField(
            model_name="county",
            name="country",
            field=models.ForeignKey(
                default=hmis.apps.core.models_reference_geo_staff.get_default_country_pk,
                help_text="Parent country (Kenya for the existing county hierarchy).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="counties",
                to="core.country",
            ),
        ),
        migrations.AddConstraint(
            model_name="county",
            constraint=models.UniqueConstraint(
                fields=("country", "code"), name="uniq_county_country_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="county",
            constraint=models.UniqueConstraint(
                fields=("country", "name"), name="uniq_county_country_name"
            ),
        ),
    ]
