# Generated by Django 5.2.11 on 2026-04-05 01:32

import django.db.models.deletion
import hmis.apps.core.history
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immunizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ColdChainEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Equipment name/label (e.g., Main Fridge 1)", max_length=200
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("FRIDGE", "Refrigerator"),
                            ("FREEZER", "Freezer"),
                            ("COLD_BOX", "Cold Box"),
                            ("VACCINE_CARRIER", "Vaccine Carrier"),
                            ("COLD_ROOM", "Cold Room"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_number", models.CharField(blank=True, default="", max_length=100)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=100, unique=True),
                ),
                ("manufacturer", models.CharField(blank=True, default="", max_length=200)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Physical location in facility",
                        max_length=200,
                    ),
                ),
                (
                    "capacity_litres",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Storage capacity in litres",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "min_temp",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.0,
                        help_text="Minimum acceptable temperature (°C)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_temp",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Maximum acceptable temperature (°C)",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("FAULTY", "Faulty"),
                            ("DECOMMISSIONED", "Decommissioned"),
                            ("UNDER_REPAIR", "Under Repair"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                (
                    "power_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Power source (e.g., Mains, Solar, Gas)",
                        max_length=100,
                    ),
                ),
                (
                    "has_backup_power",
                    models.BooleanField(
                        default=False, help_text="Equipment has backup power source"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Cold Chain Equipment",
                "verbose_name_plural": "Cold Chain Equipment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalVaccineIncident",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "title",
                    models.CharField(help_text="Brief description of the incident", max_length=200),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("POWER_OUTAGE", "Power Outage"),
                            ("COLD_CHAIN_BREAK", "Cold Chain Break"),
                            ("EQUIPMENT_FAILURE", "Equipment Failure"),
                            ("STOCK_DAMAGE", "Stock Damage"),
                            ("THEFT", "Theft / Loss"),
                            ("EXPIRED_STOCK", "Expired Stock"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Detailed description of the incident")),
                ("occurred_at", models.DateTimeField(help_text="When the incident occurred")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the incident was resolved", null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration of the incident in minutes", null=True
                    ),
                ),
                (
                    "doses_affected",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated number of vaccine doses affected"
                    ),
                ),
                (
                    "doses_lost",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of vaccine doses lost/wasted due to incident"
                    ),
                ),
                (
                    "corrective_actions",
                    models.TextField(
                        blank=True, default="", help_text="Actions taken to resolve the incident"
                    ),
                ),
                (
                    "preventive_actions",
                    models.TextField(
                        blank=True, default="", help_text="Actions taken to prevent recurrence"
                    ),
                ),
                (
                    "reported_to_county",
                    models.BooleanField(
                        default=False, help_text="Reported to county health office"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investigated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Vaccine Incident",
                "verbose_name_plural": "historical Vaccine Incidents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TemperatureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2, help_text="Temperature reading in °C", max_digits=5
                    ),
                ),
                ("recorded_at", models.DateTimeField(help_text="When the reading was taken")),
                (
                    "is_excursion",
                    models.BooleanField(
                        default=False, help_text="Temperature outside acceptable range"
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True, default="", help_text="Action taken if excursion detected"
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_logs",
                        to="immunizations.coldchainequipment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temperature_logs_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Temperature Log",
                "verbose_name_plural": "Temperature Logs",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="VaccineStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_number",
                    models.CharField(help_text="Manufacturer batch/lot number", max_length=50),
                ),
                (
                    "quantity_received",
                    models.PositiveIntegerField(help_text="Original quantity received (doses)"),
                ),
                (
                    "quantity_on_hand",
                    models.PositiveIntegerField(help_text="Current quantity available (doses)"),
                ),
                ("expiry_date", models.DateField(help_text="Batch expiry date")),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, default="", help_text="Manufacturer name", max_length=200
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Supplier / source (e.g., KEMSA, WHO, direct)",
                        max_length=200,
                    ),
                ),
                (
                    "received_date",
                    models.DateField(help_text="Date batch was received at facility"),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Storage location (e.g., Main Fridge, Cold Room A)",
                        max_length=100,
                    ),
                ),
                (
                    "vvm_status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vaccine Vial Monitor status at receipt (Stage 1-4)",
                        max_length=20,
                    ),
                ),
                (
                    "min_stock_level",
                    models.PositiveIntegerField(
                        default=10, help_text="Minimum stock level before alert"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccine_stock_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        help_text="Vaccine this batch belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_batches",
                        to="immunizations.vaccinedefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaccine Stock Batch",
                "verbose_name_plural": "Vaccine Stock Batches",
                "ordering": ["expiry_date"],
                "unique_together": {("vaccine", "batch_number")},
            },
        ),
        migrations.CreateModel(
            name="VaccineIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(help_text="Brief description of the incident", max_length=200),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("POWER_OUTAGE", "Power Outage"),
                            ("COLD_CHAIN_BREAK", "Cold Chain Break"),
                            ("EQUIPMENT_FAILURE", "Equipment Failure"),
                            ("STOCK_DAMAGE", "Stock Damage"),
                            ("THEFT", "Theft / Loss"),
                            ("EXPIRED_STOCK", "Expired Stock"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Detailed description of the incident")),
                ("occurred_at", models.DateTimeField(help_text="When the incident occurred")),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the incident was resolved", null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration of the incident in minutes", null=True
                    ),
                ),
                (
                    "doses_affected",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated number of vaccine doses affected"
                    ),
                ),
                (
                    "doses_lost",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of vaccine doses lost/wasted due to incident"
                    ),
                ),
                (
                    "corrective_actions",
                    models.TextField(
                        blank=True, default="", help_text="Actions taken to resolve the incident"
                    ),
                ),
                (
                    "preventive_actions",
                    models.TextField(
                        blank=True, default="", help_text="Actions taken to prevent recurrence"
                    ),
                ),
                (
                    "reported_to_county",
                    models.BooleanField(
                        default=False, help_text="Reported to county health office"
                    ),
                ),
                (
                    "affected_equipment",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Cold chain equipment affected",
                        related_name="incidents",
                        to="immunizations.coldchainequipment",
                    ),
                ),
                (
                    "investigated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccine_incidents_investigated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccine_incidents_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "affected_batches",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Vaccine batches affected",
                        related_name="incidents",
                        to="immunizations.vaccinestock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaccine Incident",
                "verbose_name_plural": "Vaccine Incidents",
                "ordering": ["-occurred_at"],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "Received"),
                            ("ISSUE", "Issued / Administered"),
                            ("WASTAGE", "Wastage"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("TRANSFER_IN", "Transfer In"),
                            ("TRANSFER_OUT", "Transfer Out"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive for additions, negative for reductions"
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(help_text="Stock balance after this transaction"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference (e.g., immunization record ID, transfer doc number)",
                        max_length=200,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for wastage/adjustment"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "immunization_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked immunization record (for ISSUE transactions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to="immunizations.immunizationrecord",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="immunizations.vaccinestock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transaction",
                "verbose_name_plural": "Stock Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
