# Generated by Django 5.2.11 on 2026-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immunizations", "0002_add_stock_coldchain_incidents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coldchainequipment",
            name="serial_number",
            field=models.CharField(
                help_text="Unique manufacturer serial number or asset tag",
                max_length=100,
                unique=True,
            ),
        ),
    ]
