# Generated by Django 5.2.11 on 2026-04-05 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0026_add_vaccination_itemtype_and_immunization_fk"),
        ("immunizations", "0005_aefi_moh_form_expansion"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccinedefinition",
            name="base_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Base vaccine fee (KES). Used as fallback when billing_service is not set.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vaccinedefinition",
            name="billing_service",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked billing service for invoice generation. When set, the service unit_price and SHA code are used for billing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vaccine_definitions",
                to="billing.service",
            ),
        ),
        migrations.AddField(
            model_name="vaccinedefinition",
            name="sha_tariff_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA intervention tariff code for vaccine billing",
                max_length=50,
            ),
        ),
    ]
