# Generated by Django 5.2.13 on 2026-04-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immunizations", "0006_add_billing_fields_to_vaccine_definition"),
        ("scheduling", "0018_shift_swap_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="coldchainequipment",
            name="scheduling_resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked scheduling resource for this equipment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cold_chain_equipment",
                to="scheduling.resource",
            ),
        ),
    ]
