# Generated by Django 5.2.13 on 2026-06-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immunizations", "0008_add_custom_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="aefi",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aefi",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coldchainequipment",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coldchainequipment",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalaefi",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalaefi",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalimmunizationrecord",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalimmunizationrecord",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalvaccineincident",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalvaccineincident",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="immunizationrecord",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="immunizationrecord",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vaccinecampaign",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vaccinecampaign",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vaccineincident",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vaccineincident",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vaccinestock",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vaccinestock",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
    ]
