# Copyright (c) 2026 Nexora Consulting Ltd. All rights reserved.
# Generated by Django 5.2.13 on 2026-09-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0076_facility_scoped_service_categories"),
        ("core", "0093_facility_dha_contract_types_and_more"),
        ("immunizations", "0009_aefi_origin_hub_id_aefi_origin_local_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityVaccineConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                ("is_offered", models.BooleanField(blank=True, null=True)),
                (
                    "base_fee",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("sha_tariff_code", models.CharField(blank=True, default="", max_length=50)),
                (
                    "billing_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facility_vaccine_configs",
                        to="billing.service",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_configs",
                        to="immunizations.vaccinedefinition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("facility", "vaccine"), name="unique_facility_vaccine_config"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationVaccineConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "base_fee",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("sha_tariff_code", models.CharField(blank=True, default="", max_length=50)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_configs",
                        to="immunizations.vaccinedefinition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "vaccine"),
                        name="unique_organization_vaccine_config",
                    )
                ],
            },
        ),
    ]
