# Copyright (c) 2026 Nexora Consulting Ltd. All rights reserved.
# Generated by Django 5.2.13 on 2026-09-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("immunizations", "0011_facility_custom_vaccines"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitycustomvaccine",
            name="sha_tariff_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
