# Generated by Django 5.2.9 on 2026-02-25 19:57

import django.core.validators
import django.db.models.deletion
import hmis.apps.core.history
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0021_change_imaging_order_on_delete"),
        ("clinics", "0009_add_unique_active_patient_per_session"),
        ("encounters", "0023_historicaldiagnosis_historicalencounter"),
        ("patients", "0014_historicalpatient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OTTreatmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique treatment type code (e.g., OT-ADL-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Full treatment type name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description of treatment"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ADL_TRAINING", "Activities of Daily Living Training"),
                            ("COGNITIVE_REHAB", "Cognitive Rehabilitation"),
                            ("SENSORY_INTEGRATION", "Sensory Integration"),
                            ("HAND_THERAPY", "Hand Therapy"),
                            ("PEDIATRIC", "Pediatric OT"),
                            ("WORKPLACE_REHAB", "Workplace Rehabilitation"),
                            ("MENTAL_HEALTH", "Mental Health OT"),
                            ("NEUROLOGICAL", "Neurological Rehabilitation"),
                            ("GERIATRIC", "Geriatric OT"),
                            ("ASSISTIVE_TECH", "Assistive Technology Assessment"),
                            ("HOME_MODIFICATION", "Home Modification Assessment"),
                            ("SPLINTING", "Splinting/Orthotics"),
                            ("OTHER", "Other"),
                        ],
                        default="ADL_TRAINING",
                        max_length=30,
                    ),
                ),
                (
                    "typical_duration_minutes",
                    models.PositiveIntegerField(
                        default=45,
                        help_text="Typical session duration in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(240),
                        ],
                    ),
                ),
                (
                    "recommended_sessions",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Recommended number of sessions",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "recommended_frequency",
                    models.CharField(
                        default="2x per week",
                        help_text="Recommended session frequency (e.g., '2x per week', 'weekly')",
                        max_length=50,
                    ),
                ),
                (
                    "cost_per_session",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost per session in KES",
                        max_digits=10,
                    ),
                ),
                (
                    "sha_claimable",
                    models.BooleanField(default=True, help_text="Covered by Kenya SHA"),
                ),
                (
                    "sha_intervention_code",
                    models.CharField(
                        blank=True, help_text="SHA intervention code for claims", max_length=50
                    ),
                ),
                ("requires_equipment", models.BooleanField(default=False)),
                (
                    "equipment_needed",
                    models.TextField(blank=True, help_text="Equipment required for treatment"),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, help_text="Treatment contraindications"),
                ),
                ("precautions", models.TextField(blank=True, help_text="Treatment precautions")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OT Treatment Type",
                "verbose_name_plural": "OT Treatment Types",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="occupationa_code_b22a58_idx"),
                    models.Index(fields=["category"], name="occupationa_categor_32f2b6_idx"),
                    models.Index(fields=["is_active"], name="occupationa_is_acti_54172f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OccupationalTherapyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial Assessment"),
                            ("FOLLOW_UP", "Follow-up Assessment"),
                            ("FUNCTIONAL", "Functional Capacity Evaluation"),
                            ("COGNITIVE", "Cognitive Assessment"),
                            ("SENSORY", "Sensory Processing Assessment"),
                            ("ADL", "ADL Assessment"),
                            ("HOME", "Home Assessment"),
                            ("WORK", "Workplace Assessment"),
                            ("PEDIATRIC", "Pediatric Developmental Assessment"),
                            ("HAND", "Hand Function Assessment"),
                            ("OTHER", "Other"),
                        ],
                        default="INITIAL",
                        help_text="Type of OT assessment to perform",
                        max_length=30,
                    ),
                ),
                (
                    "referral_reason",
                    models.CharField(
                        choices=[
                            ("POST_INJURY", "Post-Injury Rehabilitation"),
                            ("POST_SURGERY", "Post-Surgical Rehabilitation"),
                            ("STROKE_REHAB", "Stroke Rehabilitation"),
                            ("DEVELOPMENTAL", "Developmental Delay"),
                            ("COGNITIVE_DECLINE", "Cognitive Decline"),
                            ("ADL_SUPPORT", "ADL Support/Training"),
                            ("WORKPLACE_INJURY", "Workplace Injury"),
                            ("HAND_INJURY", "Hand/Upper Limb Injury"),
                            ("MENTAL_HEALTH", "Mental Health Support"),
                            ("SENSORY_ISSUES", "Sensory Processing Issues"),
                            ("ASSISTIVE_DEVICE", "Assistive Device Assessment"),
                            ("HOME_MODIFICATION", "Home Modification Assessment"),
                            ("PEDIATRIC", "Pediatric Development"),
                            ("GERIATRIC", "Geriatric Care"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "clinical_indication",
                    models.TextField(help_text="Clinical reason for OT referral"),
                ),
                (
                    "relevant_history",
                    models.TextField(
                        blank=True, help_text="Relevant medical/surgical/developmental history"
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, help_text="Working diagnosis")),
                (
                    "precautions",
                    models.TextField(blank=True, help_text="Patient-specific precautions"),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, help_text="Patient-specific contraindications"),
                ),
                (
                    "treatment_goals",
                    models.TextField(help_text="Specific, measurable treatment goals"),
                ),
                (
                    "short_term_goals",
                    models.TextField(blank=True, help_text="Goals to achieve within 2-4 weeks"),
                ),
                (
                    "long_term_goals",
                    models.TextField(blank=True, help_text="Goals to achieve by end of treatment"),
                ),
                (
                    "functional_limitations",
                    models.TextField(
                        blank=True, help_text="Current functional limitations to address"
                    ),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Total number of sessions prescribed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "sessions_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of sessions completed"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        default="2x per week",
                        help_text="Treatment frequency (e.g., '2x per week', 'weekly')",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Treatment start date", null=True),
                ),
                (
                    "expected_end_date",
                    models.DateField(
                        blank=True, help_text="Expected treatment end date", null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_therapist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Occupational therapist assigned to this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ot_orders_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked clinic visit for queue management",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ot_orders",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ot_orders",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked billing invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ot_orders",
                        to="billing.invoice",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ot_orders_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ot_orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ot_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treatment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="occupational_therapy.ottreatmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupational Therapy Order",
                "verbose_name_plural": "Occupational Therapy Orders",
                "ordering": ["-ordered_at"],
                "permissions": [
                    ("approve_ot_order", "Can approve occupational therapy orders"),
                    ("assign_ot_therapist", "Can assign occupational therapist to orders"),
                ],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOccupationalTherapyOrder",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("order_number", models.CharField(db_index=True, editable=False, max_length=30)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial Assessment"),
                            ("FOLLOW_UP", "Follow-up Assessment"),
                            ("FUNCTIONAL", "Functional Capacity Evaluation"),
                            ("COGNITIVE", "Cognitive Assessment"),
                            ("SENSORY", "Sensory Processing Assessment"),
                            ("ADL", "ADL Assessment"),
                            ("HOME", "Home Assessment"),
                            ("WORK", "Workplace Assessment"),
                            ("PEDIATRIC", "Pediatric Developmental Assessment"),
                            ("HAND", "Hand Function Assessment"),
                            ("OTHER", "Other"),
                        ],
                        default="INITIAL",
                        help_text="Type of OT assessment to perform",
                        max_length=30,
                    ),
                ),
                (
                    "referral_reason",
                    models.CharField(
                        choices=[
                            ("POST_INJURY", "Post-Injury Rehabilitation"),
                            ("POST_SURGERY", "Post-Surgical Rehabilitation"),
                            ("STROKE_REHAB", "Stroke Rehabilitation"),
                            ("DEVELOPMENTAL", "Developmental Delay"),
                            ("COGNITIVE_DECLINE", "Cognitive Decline"),
                            ("ADL_SUPPORT", "ADL Support/Training"),
                            ("WORKPLACE_INJURY", "Workplace Injury"),
                            ("HAND_INJURY", "Hand/Upper Limb Injury"),
                            ("MENTAL_HEALTH", "Mental Health Support"),
                            ("SENSORY_ISSUES", "Sensory Processing Issues"),
                            ("ASSISTIVE_DEVICE", "Assistive Device Assessment"),
                            ("HOME_MODIFICATION", "Home Modification Assessment"),
                            ("PEDIATRIC", "Pediatric Development"),
                            ("GERIATRIC", "Geriatric Care"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "clinical_indication",
                    models.TextField(help_text="Clinical reason for OT referral"),
                ),
                (
                    "relevant_history",
                    models.TextField(
                        blank=True, help_text="Relevant medical/surgical/developmental history"
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, help_text="Working diagnosis")),
                (
                    "precautions",
                    models.TextField(blank=True, help_text="Patient-specific precautions"),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, help_text="Patient-specific contraindications"),
                ),
                (
                    "treatment_goals",
                    models.TextField(help_text="Specific, measurable treatment goals"),
                ),
                (
                    "short_term_goals",
                    models.TextField(blank=True, help_text="Goals to achieve within 2-4 weeks"),
                ),
                (
                    "long_term_goals",
                    models.TextField(blank=True, help_text="Goals to achieve by end of treatment"),
                ),
                (
                    "functional_limitations",
                    models.TextField(
                        blank=True, help_text="Current functional limitations to address"
                    ),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Total number of sessions prescribed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "sessions_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of sessions completed"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        default="2x per week",
                        help_text="Treatment frequency (e.g., '2x per week', 'weekly')",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Treatment start date", null=True),
                ),
                (
                    "expected_end_date",
                    models.DateField(
                        blank=True, help_text="Expected treatment end date", null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("ordered_at", models.DateTimeField(blank=True, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "assigned_therapist",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Occupational therapist assigned to this order",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked clinic visit for queue management",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked billing invoice",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="billing.invoice",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patients.patient",
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treatment_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="occupational_therapy.ottreatmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Occupational Therapy Order",
                "verbose_name_plural": "historical Occupational Therapy Orders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OTSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_number",
                    models.PositiveIntegerField(help_text="Session number in treatment course"),
                ),
                ("scheduled_date", models.DateField(help_text="Scheduled date for session")),
                (
                    "scheduled_time",
                    models.TimeField(blank=True, help_text="Scheduled time", null=True),
                ),
                (
                    "actual_date",
                    models.DateField(blank=True, help_text="Actual session date", null=True),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Actual session duration in minutes",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(240),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "pre_functional_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TOTAL_ASSIST", "Total Assistance (0-24%)"),
                            ("MAX_ASSIST", "Maximum Assistance (25-49%)"),
                            ("MOD_ASSIST", "Moderate Assistance (50-74%)"),
                            ("MIN_ASSIST", "Minimum Assistance (75-99%)"),
                            ("SUPERVISION", "Supervision/Setup"),
                            ("MODIFIED_IND", "Modified Independence"),
                            ("INDEPENDENT", "Independent"),
                        ],
                        help_text="Independence level before session",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "pre_assessment_notes",
                    models.TextField(blank=True, help_text="Pre-session assessment notes"),
                ),
                (
                    "patient_reported_changes",
                    models.TextField(
                        blank=True, help_text="Changes reported by patient since last session"
                    ),
                ),
                (
                    "patient_goals_for_session",
                    models.TextField(
                        blank=True, help_text="What patient wants to achieve this session"
                    ),
                ),
                (
                    "activities_performed",
                    models.TextField(
                        blank=True, help_text="Therapeutic activities performed during session"
                    ),
                ),
                (
                    "adl_activities",
                    models.TextField(
                        blank=True,
                        help_text="ADL training activities (dressing, grooming, feeding, etc.)",
                    ),
                ),
                (
                    "cognitive_exercises",
                    models.TextField(blank=True, help_text="Cognitive rehabilitation exercises"),
                ),
                (
                    "sensory_activities",
                    models.TextField(blank=True, help_text="Sensory integration activities"),
                ),
                (
                    "fine_motor_exercises",
                    models.TextField(blank=True, help_text="Fine motor and hand therapy exercises"),
                ),
                (
                    "gross_motor_activities",
                    models.TextField(blank=True, help_text="Gross motor coordination activities"),
                ),
                (
                    "adaptive_equipment_training",
                    models.TextField(
                        blank=True, help_text="Assistive device/adaptive equipment training"
                    ),
                ),
                (
                    "splint_orthotics",
                    models.TextField(
                        blank=True, help_text="Splint/orthotic fabrication or adjustment"
                    ),
                ),
                (
                    "patient_response",
                    models.TextField(
                        blank=True, help_text="Patient's response to treatment activities"
                    ),
                ),
                (
                    "patient_engagement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("UNCOOPERATIVE", "Uncooperative"),
                        ],
                        help_text="Level of patient engagement/participation",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "post_functional_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TOTAL_ASSIST", "Total Assistance (0-24%)"),
                            ("MAX_ASSIST", "Maximum Assistance (25-49%)"),
                            ("MOD_ASSIST", "Moderate Assistance (50-74%)"),
                            ("MIN_ASSIST", "Minimum Assistance (75-99%)"),
                            ("SUPERVISION", "Supervision/Setup"),
                            ("MODIFIED_IND", "Modified Independence"),
                            ("INDEPENDENT", "Independent"),
                        ],
                        help_text="Independence level after session",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IMPROVED", "Improved"),
                            ("UNCHANGED", "Unchanged"),
                            ("WORSENED", "Worsened"),
                            ("GOALS_MET", "Goals Met"),
                            ("PARTIAL_IMPROVEMENT", "Partial Improvement"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(blank=True, help_text="Session progress notes"),
                ),
                (
                    "goals_addressed",
                    models.TextField(blank=True, help_text="Which treatment goals were addressed"),
                ),
                (
                    "goals_progress",
                    models.TextField(blank=True, help_text="Progress toward treatment goals"),
                ),
                (
                    "home_activities",
                    models.TextField(blank=True, help_text="Home activities/exercises prescribed"),
                ),
                (
                    "home_activity_instructions",
                    models.TextField(blank=True, help_text="Instructions for home activities"),
                ),
                (
                    "caregiver_education",
                    models.TextField(
                        blank=True, help_text="Education provided to family/caregivers"
                    ),
                ),
                (
                    "environmental_recommendations",
                    models.TextField(
                        blank=True, help_text="Home/environment modification recommendations"
                    ),
                ),
                (
                    "precautions_advised",
                    models.TextField(blank=True, help_text="Precautions advised to patient"),
                ),
                (
                    "follow_up_recommendations",
                    models.TextField(blank=True, help_text="Follow-up recommendations"),
                ),
                (
                    "next_session_goals",
                    models.TextField(blank=True, help_text="Goals for next session"),
                ),
                (
                    "equipment_recommendations",
                    models.TextField(blank=True, help_text="Adaptive equipment recommendations"),
                ),
                ("is_billed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked clinic visit for queue management",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ot_sessions",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ot_sessions",
                        to="billing.invoiceitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="occupational_therapy.occupationaltherapyorder",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ot_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OT Session",
                "verbose_name_plural": "OT Sessions",
                "ordering": ["order", "session_number"],
                "indexes": [
                    models.Index(fields=["order"], name="occupationa_order_i_e073ce_idx"),
                    models.Index(fields=["therapist"], name="occupationa_therapi_fedd7c_idx"),
                    models.Index(fields=["scheduled_date"], name="occupationa_schedul_6be64b_idx"),
                    models.Index(fields=["status"], name="occupationa_status_c3c466_idx"),
                ],
                "unique_together": {("order", "session_number")},
            },
        ),
        migrations.AddIndex(
            model_name="occupationaltherapyorder",
            index=models.Index(fields=["order_number"], name="occupationa_order_n_e2f9d7_idx"),
        ),
        migrations.AddIndex(
            model_name="occupationaltherapyorder",
            index=models.Index(fields=["patient"], name="occupationa_patient_414f9d_idx"),
        ),
        migrations.AddIndex(
            model_name="occupationaltherapyorder",
            index=models.Index(fields=["status"], name="occupationa_status_422feb_idx"),
        ),
        migrations.AddIndex(
            model_name="occupationaltherapyorder",
            index=models.Index(fields=["ordered_at"], name="occupationa_ordered_6416f4_idx"),
        ),
        migrations.AddIndex(
            model_name="occupationaltherapyorder",
            index=models.Index(fields=["priority"], name="occupationa_priorit_c588ca_idx"),
        ),
        migrations.AddIndex(
            model_name="occupationaltherapyorder",
            index=models.Index(
                fields=["assigned_therapist"], name="occupationa_assigne_ae57ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="occupationaltherapyorder",
            index=models.Index(fields=["assessment_type"], name="occupationa_assessm_bab60b_idx"),
        ),
    ]
