# Generated by Django 5.2.9 on 2026-01-03 00:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Unique ward name (e.g., 'Medical Ward 1')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique ward code (e.g., 'MED-01')", max_length=20, unique=True
                    ),
                ),
                (
                    "ward_type",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Medical Ward"),
                            ("SURGICAL", "Surgical Ward"),
                            ("PEDIATRIC", "Pediatric Ward"),
                            ("MATERNITY", "Maternity Ward"),
                            ("ICU", "Intensive Care Unit"),
                            ("ISOLATION", "Isolation Ward"),
                        ],
                        help_text="Type of ward",
                        max_length=20,
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, default="", help_text="Floor location", max_length=50
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Total bed count (must be positive)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Ward description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether ward is currently active"),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bed charge per day (must be positive)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
            ],
            options={
                "verbose_name": "Ward",
                "verbose_name_plural": "Wards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bed_number",
                    models.CharField(help_text="Bed identifier (e.g., 'B-101')", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("RESERVED", "Reserved"),
                        ],
                        default="AVAILABLE",
                        help_text="Current bed status",
                        max_length=20,
                    ),
                ),
                (
                    "bed_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of bed (e.g., 'Standard', 'ICU')",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes (maintenance reason, etc.)",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(auto_now=True, help_text="When status last changed"),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who changed status",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bed_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        help_text="Parent ward",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="inpatient.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bed",
                "verbose_name_plural": "Beds",
                "ordering": ["ward", "bed_number"],
                "unique_together": {("ward", "bed_number")},
            },
        ),
    ]
