# Generated by Django 5.2.9 on 2026-01-03 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0009_add_encounter_status_workflow"),
        ("inpatient", "0002_admissionrecommendation"),
        ("patients", "0007_add_location_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission_number",
                    models.CharField(
                        editable=False,
                        help_text="Unique admission number (ADM-YYYYMMDD-XXXX)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("admission_date", models.DateTimeField(help_text="Date and time of admission")),
                (
                    "admitting_diagnosis",
                    models.CharField(
                        help_text="ICD-10 code for admitting diagnosis", max_length=10
                    ),
                ),
                (
                    "admitting_diagnosis_text",
                    models.CharField(help_text="Text description of diagnosis", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISCHARGED", "Discharged"),
                            ("TRANSFERRED_OUT", "Transferred Out"),
                            ("DECEASED", "Deceased"),
                            ("ABSCONDED", "Absconded"),
                        ],
                        default="ACTIVE",
                        help_text="Current admission status",
                        max_length=20,
                    ),
                ),
                (
                    "payer_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("SHA", "SHA Insurance"),
                            ("CORPORATE", "Corporate"),
                        ],
                        help_text="Type of payer",
                        max_length=20,
                    ),
                ),
                (
                    "insurance_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Insurance information (for SHA/Corporate)",
                    ),
                ),
                (
                    "discharge_date",
                    models.DateTimeField(
                        blank=True, help_text="Date and time of discharge", null=True
                    ),
                ),
                (
                    "admitting_officer",
                    models.ForeignKey(
                        help_text="User who processed the admission",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attending_doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Doctor attending the patient",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients_attending",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        help_text="Specific bed assigned",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="inpatient.bed",
                    ),
                ),
                (
                    "ipd_encounter",
                    models.OneToOneField(
                        help_text="IPD encounter for this admission",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "opd_encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="OPD encounter that led to admission (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_from_opd",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient being admitted",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="patients.patient",
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        blank=True,
                        help_text="Admission recommendation (if from OPD)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission",
                        to="inpatient.admissionrecommendation",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        help_text="Ward where patient is admitted",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="inpatient.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission",
                "verbose_name_plural": "Admissions",
                "ordering": ["-admission_date"],
            },
        ),
    ]
