# Generated by Django 5.2.9 on 2026-01-03 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0003_admission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discharge_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal Discharge"),
                            ("AGAINST_ADVICE", "Discharge Against Medical Advice"),
                            ("TRANSFERRED", "Transferred to Another Facility"),
                            ("DECEASED", "Deceased"),
                            ("ABSCONDED", "Absconded"),
                        ],
                        help_text="Type of discharge",
                        max_length=20,
                    ),
                ),
                ("discharge_date", models.DateTimeField(help_text="Date and time of discharge")),
                (
                    "admission_diagnosis",
                    models.CharField(help_text="ICD-10 code from admission", max_length=10),
                ),
                (
                    "final_diagnosis",
                    models.CharField(help_text="ICD-10 code at discharge", max_length=10),
                ),
                (
                    "final_diagnosis_text",
                    models.CharField(
                        help_text="Text description of final diagnosis", max_length=255
                    ),
                ),
                (
                    "procedures_performed",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Summary of procedures performed during stay",
                    ),
                ),
                ("treatment_summary", models.TextField(help_text="Overall treatment summary")),
                (
                    "discharge_medications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of discharge medications with dosage and instructions",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, help_text="Date for follow-up appointment", null=True
                    ),
                ),
                (
                    "follow_up_instructions",
                    models.TextField(
                        blank=True, default="", help_text="Instructions for follow-up care"
                    ),
                ),
                (
                    "referral_facility",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Facility name if transferred",
                        max_length=255,
                    ),
                ),
                (
                    "referral_reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for referral/transfer"
                    ),
                ),
                (
                    "patient_instructions",
                    models.TextField(help_text="Discharge instructions for patient"),
                ),
                (
                    "pharmacy_cleared",
                    models.BooleanField(default=False, help_text="Pharmacy clearance obtained"),
                ),
                (
                    "billing_cleared",
                    models.BooleanField(default=False, help_text="Billing clearance obtained"),
                ),
                (
                    "lab_results_acknowledged",
                    models.BooleanField(
                        default=False, help_text="Lab results reviewed and acknowledged"
                    ),
                ),
                (
                    "admission",
                    models.OneToOneField(
                        help_text="Admission being discharged",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "discharged_by",
                    models.ForeignKey(
                        help_text="User who processed the discharge",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discharges_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discharge",
                "verbose_name_plural": "Discharges",
                "ordering": ["-discharge_date"],
            },
        ),
    ]
