# Generated by Django 5.2.9 on 2026-01-03 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0005_transfer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WardRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("round_date", models.DateField()),
                ("round_time", models.TimeField()),
                ("subjective", models.TextField(help_text="Patient complaints, symptoms")),
                (
                    "objective",
                    models.TextField(help_text="Examination findings, vitals, observations"),
                ),
                (
                    "assessment",
                    models.TextField(help_text="Clinical assessment, diagnosis updates"),
                ),
                ("plan", models.TextField(help_text="Treatment plan, orders, next steps")),
                (
                    "condition_status",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable"),
                            ("IMPROVING", "Improving"),
                            ("DETERIORATING", "Deteriorating"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requires_consultant_review", models.BooleanField(default=False)),
                ("consultant_specialty", models.CharField(blank=True, max_length=100)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ward_rounds",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "conducted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Ward Round",
                "verbose_name_plural": "Ward Rounds",
                "ordering": ["-round_date", "-round_time"],
                "unique_together": {("admission", "round_date", "conducted_by")},
            },
        ),
    ]
