# Generated by Django 5.2.9 on 2026-01-03 04:04

import hmis.apps.inpatient.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inpatient",
            "0009_rename_inpatient_k_kardex__a5f2e1_idx_inpatient_k_kardex__153565_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="admission",
            old_name="status",
            new_name="admission_status",
        ),
        migrations.AlterField(
            model_name="admissionrecommendation",
            name="expires_at",
            field=models.DateTimeField(
                default=hmis.apps.inpatient.models.default_recommendation_expiry,
                help_text="Expiration time (default 24 hours from creation)",
            ),
        ),
    ]
