# Generated by Django 5.2.10 on 2026-01-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0010_align_admission_status_and_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="nursingkardex",
            name="allergies",
            field=models.TextField(blank=True, help_text="Known allergies"),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="dietary_requirements",
            field=models.CharField(
                blank=True,
                help_text="Dietary requirements (e.g., Regular, Diabetic, NPO)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="fall_risk_level",
            field=models.CharField(
                blank=True,
                choices=[("LOW", "Low"), ("MODERATE", "Moderate"), ("HIGH", "High")],
                help_text="Fall risk level if at risk",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="isolation_required",
            field=models.BooleanField(
                default=False, help_text="Whether patient requires isolation"
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="isolation_type",
            field=models.CharField(
                blank=True,
                help_text="Type of isolation (e.g., Contact, Droplet, Airborne)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="iv_access",
            field=models.CharField(
                blank=True,
                help_text="IV access details (e.g., Right arm IV cannula)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="mobility_status",
            field=models.CharField(
                blank=True,
                help_text="Patient mobility status (e.g., Ambulatory, Wheelchair, Bedridden)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="pressure_sore_risk_level",
            field=models.CharField(
                blank=True,
                choices=[("LOW", "Low"), ("MODERATE", "Moderate"), ("HIGH", "High")],
                help_text="Pressure sore risk level if at risk",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nursingkardex",
            name="fall_risk",
            field=models.BooleanField(
                default=False, help_text="Whether patient is at risk of falls"
            ),
        ),
        migrations.AlterField(
            model_name="nursingkardex",
            name="pressure_sore_risk",
            field=models.BooleanField(
                default=False, help_text="Whether patient is at risk of pressure sores"
            ),
        ),
    ]
