# Generated by Django 5.2.10 on 2026-01-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0011_add_kardex_care_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nursingkardex",
            name="fall_risk_level",
        ),
        migrations.RemoveField(
            model_name="nursingkardex",
            name="pressure_sore_risk_level",
        ),
        migrations.AlterField(
            model_name="nursingkardex",
            name="fall_risk",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MODERATE", "Moderate"), ("HIGH", "High")],
                default="LOW",
                help_text="Patient fall risk level",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nursingkardex",
            name="pressure_sore_risk",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MODERATE", "Moderate"), ("HIGH", "High")],
                default="LOW",
                help_text="Patient pressure sore risk level",
                max_length=20,
            ),
        ),
    ]
