# Generated by Django 5.2.9 on 2026-01-23 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0017_add_admission_integrity_constraints"),
        ("inpatient", "0012_fix_kardex_risk_fields"),
        ("patients", "0010_add_unique_identification_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="admission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("admission_status", "ACTIVE")),
                fields=("patient",),
                name="unique_active_admission_per_patient",
            ),
        ),
        migrations.AddConstraint(
            model_name="admission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("admission_status", "ACTIVE")),
                fields=("bed",),
                name="unique_active_admission_per_bed",
            ),
        ),
    ]
