# Generated by Django 5.2.9 on 2026-02-20 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0016_add_supervisor_alert_acknowledgment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wardround",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="wardround",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("WARD_ROUND", "Scheduled Ward Round"),
                    ("URGENT_REVIEW", "Urgent Review"),
                    ("CONSULTANT_REVIEW", "Consultant Review"),
                    ("TRANSFER_REVIEW", "Transfer Assessment"),
                    ("PRE_DISCHARGE", "Pre-Discharge Assessment"),
                ],
                default="WARD_ROUND",
                help_text="Type of review being conducted",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReviewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("URGENT_REVIEW", "Urgent Review"),
                            ("CONSULTANT_REVIEW", "Consultant Review"),
                            ("TRANSFER_REVIEW", "Transfer Assessment"),
                            ("PRE_DISCHARGE", "Pre-Discharge Assessment"),
                        ],
                        help_text="Type of review requested",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        help_text="Urgency level of the review",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Clinical reason for review request")),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the review was requested"
                    ),
                ),
                (
                    "consultant_specialty",
                    models.CharField(
                        blank=True,
                        help_text="Specialty required (for consultant reviews)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the review request",
                        max_length=20,
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, help_text="When the request was acknowledged", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the review was completed", null=True
                    ),
                ),
                (
                    "clinical_context",
                    models.TextField(
                        blank=True,
                        help_text="Additional clinical context (e.g., latest vitals, observations)",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, help_text="Reason for cancellation (if cancelled)"
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who acknowledged the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_requests_acknowledged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        help_text="Admission requiring review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clinician assigned to handle this review",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_requests_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="User who requested the review",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Request",
                "verbose_name_plural": "Review Requests",
                "ordering": ["-requested_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="wardround",
            name="review_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Review request this ward round fulfills (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ward_rounds",
                to="inpatient.reviewrequest",
            ),
        ),
    ]
