# Generated by Django 5.2.11 on 2026-03-04 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0017_add_review_type_and_review_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="nursingkardex",
            name="care_task_frequency",
            field=models.TextField(
                blank=True, help_text="DEPRECATED: Use care_plan_entries. Frequency of care tasks"
            ),
        ),
        migrations.AlterField(
            model_name="nursingkardex",
            name="interventions",
            field=models.TextField(
                blank=True,
                help_text="DEPRECATED: Use care_plan_entries. Nursing interventions and care activities",
            ),
        ),
        migrations.AlterField(
            model_name="nursingkardex",
            name="monitoring_requirements",
            field=models.TextField(
                blank=True,
                help_text="DEPRECATED: Use care_plan_entries. What to monitor and how often",
            ),
        ),
        migrations.AlterField(
            model_name="nursingkardex",
            name="nursing_problems",
            field=models.TextField(
                blank=True,
                help_text="DEPRECATED: Use care_plan_entries. Identified nursing problems/diagnoses",
            ),
        ),
        migrations.CreateModel(
            name="NursingCarePlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(help_text="Date and time the entry was recorded"),
                ),
                (
                    "assessment",
                    models.TextField(help_text="Assessment findings / cluster of cues observed"),
                ),
                (
                    "nursing_diagnosis",
                    models.TextField(help_text="Nursing diagnosis derived from assessment"),
                ),
                (
                    "goal_and_outcome_criteria",
                    models.TextField(help_text="Expected goals and measurable outcome criteria"),
                ),
                (
                    "plan_of_action",
                    models.TextField(help_text="Nursing plan of action / planned interventions"),
                ),
                (
                    "scientific_rationale",
                    models.TextField(
                        help_text="Scientific rationale for the planned interventions"
                    ),
                ),
                (
                    "implementation",
                    models.TextField(
                        blank=True, help_text="What was actually implemented / carried out"
                    ),
                ),
                (
                    "evaluation",
                    models.TextField(
                        blank=True, help_text="Evaluation of whether goals and outcomes were met"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESOLVED", "Resolved"),
                            ("ONGOING", "Ongoing"),
                        ],
                        default="ACTIVE",
                        help_text="Current status of this care plan entry",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kardex",
                    models.ForeignKey(
                        help_text="Parent Kardex for this care plan entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_plan_entries",
                        to="inpatient.nursingkardex",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="Nurse who recorded this entry",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nursing_care_plan_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nursing Care Plan Entry",
                "verbose_name_plural": "Nursing Care Plan Entries",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["kardex", "-recorded_at"], name="inpatient_n_kardex__bbdd5b_idx"
                    ),
                    models.Index(fields=["status"], name="inpatient_n_status_c43c4d_idx"),
                ],
            },
        ),
    ]
