# Generated by Django 5.2.11 on 2026-03-04 23:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0018_nursing_care_plan_entry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodTransfusionObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blood_product",
                    models.CharField(
                        choices=[
                            ("WHOLE", "Whole Blood"),
                            ("PACKED_RED_CELLS", "Packed Red Cells"),
                            ("FFP", "Fresh Frozen Plasma"),
                            ("PLATELETS", "Platelets"),
                            ("CRYOPRECIPITATE", "Cryoprecipitate"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of blood product transfused",
                        max_length=30,
                    ),
                ),
                (
                    "blood_product_other",
                    models.CharField(
                        blank=True, help_text="Specify if blood product is 'Other'", max_length=100
                    ),
                ),
                (
                    "blood_unit_number",
                    models.CharField(help_text="Blood unit/bag number", max_length=50),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        help_text="Blood group of the product (e.g., A+, O-)",
                        max_length=10,
                    ),
                ),
                (
                    "amount_ml",
                    models.PositiveIntegerField(help_text="Amount to be transfused in mL"),
                ),
                ("transfusion_date", models.DateField(help_text="Date of transfusion")),
                (
                    "time_started",
                    models.TimeField(blank=True, help_text="Time transfusion started", null=True),
                ),
                (
                    "time_ended",
                    models.TimeField(blank=True, help_text="Time transfusion ended", null=True),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, help_text="Diagnosis/indication for transfusion"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("STOPPED", "Stopped - Reaction"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="IN_PROGRESS",
                        help_text="Current status of the transfusion",
                        max_length=20,
                    ),
                ),
                (
                    "reaction_occurred",
                    models.BooleanField(
                        default=False, help_text="Whether a transfusion reaction occurred"
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        blank=True, help_text="Type of reaction (if any)", max_length=200
                    ),
                ),
                (
                    "reaction_action_taken",
                    models.TextField(
                        blank=True, help_text="Action taken in response to the reaction"
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        help_text="Admission this transfusion belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_transfusions",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "counter_checked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who counter-checked the blood product",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusions_counter_checked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        help_text="Staff who started the transfusion",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusions_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blood Transfusion",
                "verbose_name_plural": "Blood Transfusions",
                "ordering": ["-transfusion_date", "-time_started"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BPMonitoringReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_at", models.DateTimeField(help_text="When the reading was taken")),
                (
                    "systolic",
                    models.IntegerField(
                        help_text="Systolic blood pressure (mmHg)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "diastolic",
                    models.IntegerField(
                        help_text="Diastolic blood pressure (mmHg)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pulse",
                    models.IntegerField(
                        blank=True,
                        help_text="Pulse rate in BPM",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("SITTING", "Sitting"),
                            ("STANDING", "Standing"),
                            ("LYING", "Lying/Supine"),
                            ("LEFT_LATERAL", "Left Lateral"),
                        ],
                        default="SITTING",
                        help_text="Patient position when reading was taken",
                        max_length=20,
                    ),
                ),
                (
                    "arm",
                    models.CharField(
                        blank=True,
                        help_text="Which arm was used (e.g., Left, Right)",
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes (e.g., medication taken, symptoms)"
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        help_text="Admission this reading belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bp_readings",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="Nurse/clinician who recorded the reading",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bp_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "BP Monitoring Reading",
                "verbose_name_plural": "BP Monitoring Readings",
                "ordering": ["-recorded_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemperatureReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_at", models.DateTimeField(help_text="When the reading was taken")),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Temperature in °C (e.g., 36.5)",
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(Decimal("30.0"))],
                    ),
                ),
                (
                    "pulse",
                    models.IntegerField(
                        blank=True,
                        help_text="Pulse rate in BPM",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True,
                        help_text="Respiratory rate in breaths/min",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bowels",
                    models.CharField(
                        blank=True,
                        help_text="Bowel movement status (e.g., Normal, Constipated, Diarrhoea)",
                        max_length=100,
                    ),
                ),
                (
                    "urine_output",
                    models.CharField(
                        blank=True,
                        help_text="Urine output (e.g., Normal, Reduced, Nil)",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional observations or notes"),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        help_text="Admission this reading belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_readings",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="Nurse/clinician who recorded the reading",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="temperature_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Temperature Reading",
                "verbose_name_plural": "Temperature Readings",
                "ordering": ["-recorded_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransfusionObservationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "observation_interval",
                    models.CharField(
                        choices=[
                            ("BEFORE", "Before Transfusion"),
                            ("00_MIN", "00 Minutes"),
                            ("15_MIN", "15 Minutes"),
                            ("45_MIN", "45 Minutes"),
                            ("1HR_15MIN", "1hr 15 Minutes"),
                            ("1HR_45MIN", "1hr 45 Minutes"),
                            ("2HR_15MIN", "2hr 15 Minutes"),
                            ("2HR_45MIN", "2hr 45 Minutes"),
                            ("3HR_15MIN", "3hr 15 Minutes"),
                            ("3HR_45MIN", "3hr 45 Minutes"),
                            ("4HR_15MIN", "4hr 15 Minutes"),
                            ("4HR_AFTER", "4hr After Transfusion"),
                        ],
                        help_text="Observation timing interval",
                        max_length=20,
                    ),
                ),
                ("exact_time", models.TimeField(help_text="Exact time the observation was taken")),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True, help_text="Blood pressure (e.g., '120/80')", max_length=20
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Temperature in °C",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "pulse",
                    models.IntegerField(blank=True, help_text="Pulse rate in BPM", null=True),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True, help_text="Respiratory rate in breaths/min", null=True
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks or observations"),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="Staff who recorded this observation",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusion_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfusion",
                    models.ForeignKey(
                        help_text="Parent transfusion record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="inpatient.bloodtransfusionobservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfusion Observation Entry",
                "verbose_name_plural": "Transfusion Observation Entries",
                "ordering": ["exact_time"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="bloodtransfusionobservation",
            index=models.Index(
                fields=["admission", "-transfusion_date"], name="inpatient_b_admissi_c689d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bpmonitoringreading",
            index=models.Index(
                fields=["admission", "-recorded_at"], name="inpatient_b_admissi_4f6cf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="temperaturereading",
            index=models.Index(
                fields=["admission", "-recorded_at"], name="inpatient_t_admissi_cdc461_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfusionobservationentry",
            index=models.Index(
                fields=["transfusion", "observation_interval"],
                name="inpatient_t_transfu_b1099e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transfusionobservationentry",
            unique_together={("transfusion", "observation_interval")},
        ),
    ]
