# Generated by Django 5.2.11 on 2026-03-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0019_observation_charts"),
    ]

    operations = [
        migrations.AddField(
            model_name="temperaturereading",
            name="fluid_intake_ml",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Measured fluid intake in mL for this charting interval",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="temperaturereading",
            name="urine_output_ml",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Measured urine output in mL for this charting interval",
                null=True,
            ),
        ),
    ]
