# Generated by Django 5.2.11 on 2026-03-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0011_clinicvisit_source_module_and_more"),
        ("inpatient", "0021_admission_mch_registration"),
        ("scheduling", "0003_add_assignment_engine_phase2"),
    ]

    operations = [
        migrations.AddField(
            model_name="discharge",
            name="maternity_continuity_action",
            field=models.CharField(
                choices=[
                    ("NONE", "No Continuity Action"),
                    ("CONTINUE_POSTPARTUM_OBSERVATION", "Continue Postpartum Observation"),
                    ("SCHEDULE_EARLY_PNC", "Schedule Early PNC"),
                    ("ROUTE_TO_PNC_QUEUE", "Route To PNC Queue"),
                ],
                default="NONE",
                help_text="Structured postpartum continuity action for maternity discharges",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="discharge",
            name="maternity_continuity_status",
            field=models.CharField(
                choices=[
                    ("NOT_APPLICABLE", "Not Applicable"),
                    ("SCHEDULED", "Scheduled"),
                    ("QUEUED", "Queued"),
                ],
                default="NOT_APPLICABLE",
                help_text="Outcome of the postpartum continuity action",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="discharge",
            name="pnc_appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Scheduled PNC follow-up appointment created from maternity discharge",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discharge_continuity_appointments",
                to="scheduling.appointment",
            ),
        ),
        migrations.AddField(
            model_name="discharge",
            name="pnc_clinic_visit",
            field=models.ForeignKey(
                blank=True,
                help_text="PNC clinic visit created directly from maternity discharge",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discharge_continuity_routes",
                to="clinics.clinicvisit",
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="maternity_continuity_action",
            field=models.CharField(
                choices=[
                    ("NONE", "No Continuity Action"),
                    ("CONTINUE_POSTPARTUM_OBSERVATION", "Continue Postpartum Observation"),
                    ("SCHEDULE_EARLY_PNC", "Schedule Early PNC"),
                    ("ROUTE_TO_PNC_QUEUE", "Route To PNC Queue"),
                ],
                default="NONE",
                help_text="Current postpartum continuity action the nursing team is working toward",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="maternity_continuity_notes",
            field=models.TextField(
                blank=True,
                help_text="Operational postpartum continuity notes for nursing handoff and discharge workflow",
            ),
        ),
        migrations.AddField(
            model_name="wardround",
            name="maternity_continuity_action",
            field=models.CharField(
                choices=[
                    ("NONE", "No Continuity Action"),
                    ("CONTINUE_POSTPARTUM_OBSERVATION", "Continue Postpartum Observation"),
                    ("SCHEDULE_EARLY_PNC", "Schedule Early PNC"),
                    ("ROUTE_TO_PNC_QUEUE", "Route To PNC Queue"),
                ],
                default="NONE",
                help_text="Planned postpartum continuity step captured during ward review",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="wardround",
            name="maternity_continuity_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Postpartum continuity notes for the next nursing or discharge workflow step",
            ),
        ),
    ]
