# Generated by Django 5.2.11 on 2026-03-08 19:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_temperature_fluid_data(apps, schema_editor):
    TemperatureReading = apps.get_model("inpatient", "TemperatureReading")
    FluidBalanceSheet = apps.get_model("inpatient", "FluidBalanceSheet")
    FluidBalanceEntry = apps.get_model("inpatient", "FluidBalanceEntry")

    db_alias = schema_editor.connection.alias
    sheet_cache = {}

    readings = TemperatureReading.objects.using(db_alias).exclude(
        fluid_intake_ml__isnull=True,
        urine_output_ml__isnull=True,
        bowels="",
        urine_output="",
    )

    for reading in readings.iterator():
        has_fluid_data = any(
            [
                reading.fluid_intake_ml is not None,
                reading.urine_output_ml is not None,
                bool(reading.bowels),
                bool(reading.urine_output),
            ]
        )
        if not has_fluid_data:
            continue

        cache_key = (reading.admission_id, reading.recorded_at.date(), reading.recorded_by_id)
        sheet = sheet_cache.get(cache_key)
        if sheet is None:
            sheet, _created = FluidBalanceSheet.objects.using(db_alias).get_or_create(
                admission_id=reading.admission_id,
                chart_date=reading.recorded_at.date(),
                defaults={"recorded_by_id": reading.recorded_by_id},
            )
            sheet_cache[cache_key] = sheet

        if reading.fluid_intake_ml is not None:
            FluidBalanceEntry.objects.using(db_alias).create(
                fluid_balance_sheet_id=sheet.id,
                recorded_at=reading.recorded_at,
                recorded_by_id=reading.recorded_by_id,
                entry_type="OTHER_INTAKE",
                amount_ml=reading.fluid_intake_ml,
                notes="Migrated from legacy temperature reading fluid intake",
            )

        if reading.urine_output_ml is not None or reading.urine_output:
            FluidBalanceEntry.objects.using(db_alias).create(
                fluid_balance_sheet_id=sheet.id,
                recorded_at=reading.recorded_at,
                recorded_by_id=reading.recorded_by_id,
                entry_type="URINE",
                amount_ml=reading.urine_output_ml,
                notes=reading.urine_output or "Migrated from legacy temperature reading urine output",
            )

        if reading.bowels:
            FluidBalanceEntry.objects.using(db_alias).create(
                fluid_balance_sheet_id=sheet.id,
                recorded_at=reading.recorded_at,
                recorded_by_id=reading.recorded_by_id,
                entry_type="STOOL",
                notes=reading.bowels,
            )


def reverse_migrate_temperature_fluid_data(apps, schema_editor):
    # Irreversible in practice because multiple fluid entries may originate from one reading.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0022_discharge_maternity_continuity_action_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FluidBalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chart_date",
                    models.DateField(help_text="Date for the 24-hour fluid balance sheet"),
                ),
                (
                    "patient_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Patient weight in kilograms for this sheet",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                    ),
                ),
                (
                    "intravenous_infusion_notes",
                    models.TextField(
                        blank=True, help_text="Intravenous infusion details noted on the chart"
                    ),
                ),
                (
                    "other_instructions",
                    models.TextField(
                        blank=True, help_text="Other instructions recorded on the chart"
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        help_text="Admission this fluid balance sheet belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fluid_balance_sheets",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="User who created the sheet",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fluid_balance_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fluid Balance Sheet",
                "verbose_name_plural": "Fluid Balance Sheets",
                "ordering": ["-chart_date", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FluidBalanceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_at",
                    models.DateTimeField(help_text="When the fluid entry was recorded"),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("INTRAVENOUS", "Intravenous"),
                            ("ALIMENTARY", "Alimentary"),
                            ("OTHER_INTAKE", "Other Intake"),
                            ("VOMIT", "Vomit"),
                            ("STOOL", "Stool"),
                            ("NASOGASTRIC", "Naso Gastric"),
                            ("OTHER_OUTPUT", "Other Output"),
                            ("URINE", "Urine"),
                        ],
                        help_text="Category of fluid balance entry",
                        max_length=20,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        blank=True,
                        help_text="Type/name of fluid, feed, or output item",
                        max_length=100,
                    ),
                ),
                (
                    "bottle_number",
                    models.CharField(
                        blank=True,
                        help_text="Bottle number for IV intake where applicable",
                        max_length=50,
                    ),
                ),
                (
                    "amount_ml",
                    models.PositiveIntegerField(
                        blank=True, help_text="Measured amount in mL", null=True
                    ),
                ),
                (
                    "specific_gravity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Urine specific gravity where applicable",
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.000"))],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes for this fluid balance entry"
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        help_text="Nurse/clinician who recorded the entry",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fluid_balance_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fluid_balance_sheet",
                    models.ForeignKey(
                        help_text="Fluid balance sheet this entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="inpatient.fluidbalancesheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fluid Balance Entry",
                "verbose_name_plural": "Fluid Balance Entries",
                "ordering": ["-recorded_at", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="fluidbalancesheet",
            index=models.Index(
                fields=["admission", "-chart_date"], name="inpatient_f_admissi_5e3a3d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fluidbalancesheet",
            constraint=models.UniqueConstraint(
                fields=("admission", "chart_date"),
                name="unique_fluid_balance_sheet_per_admission_day",
            ),
        ),
        migrations.AddIndex(
            model_name="fluidbalanceentry",
            index=models.Index(
                fields=["fluid_balance_sheet", "-recorded_at"],
                name="inpatient_f_fluid_b_a17878_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fluidbalanceentry",
            index=models.Index(
                fields=["fluid_balance_sheet", "entry_type"], name="inpatient_f_fluid_b_af282f_idx"
            ),
        ),
        migrations.RunPython(
            migrate_temperature_fluid_data,
            reverse_migrate_temperature_fluid_data,
        ),
        migrations.RemoveField(
            model_name="temperaturereading",
            name="bowels",
        ),
        migrations.RemoveField(
            model_name="temperaturereading",
            name="fluid_intake_ml",
        ),
        migrations.RemoveField(
            model_name="temperaturereading",
            name="urine_output",
        ),
        migrations.RemoveField(
            model_name="temperaturereading",
            name="urine_output_ml",
        ),
    ]
