# Generated by Django 5.2.11 on 2026-03-09 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0024_inpatientconsumableusage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="inpatientconsumableusage",
            new_name="inpatient_i_admissi_5f28db_idx",
            old_name="inpatient_c_admissi_5a7b3b_idx",
        ),
        migrations.RenameIndex(
            model_name="inpatientconsumableusage",
            new_name="inpatient_i_drug_id_5e39c4_idx",
            old_name="inpatient_c_drug_id_d80a76_idx",
        ),
        migrations.RenameIndex(
            model_name="inpatientconsumableusage",
            new_name="inpatient_i_is_reve_9a402d_idx",
            old_name="inpatient_c_is_reve_4c48e3_idx",
        ),
    ]
