# Generated by Django 5.2.11 on 2026-03-11 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inpatient",
            "0025_rename_inpatient_c_admissi_5a7b3b_idx_inpatient_i_admissi_5f28db_idx_and_more",
        ),
        ("pharmacy", "0016_historicalprescription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationAdministration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheduled_time",
                    models.DateTimeField(help_text="When this dose is/was scheduled"),
                ),
                (
                    "actual_time",
                    models.DateTimeField(
                        blank=True, help_text="When the dose was actually administered", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("GIVEN", "Given"),
                            ("SKIPPED", "Skipped"),
                            ("REFUSED", "Refused"),
                            ("HELD", "Held"),
                            ("VOMITED", "Vomited"),
                        ],
                        default="SCHEDULED",
                        help_text="Administration status",
                        max_length=20,
                    ),
                ),
                (
                    "dose_given",
                    models.CharField(
                        blank=True,
                        help_text="Actual dose administered (e.g., '500mg')",
                        max_length=100,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="Route of administration (e.g., oral, IV, IM)",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes (reason for skipping, patient response)",
                    ),
                ),
                (
                    "is_prn",
                    models.BooleanField(
                        default=False, help_text="Whether this is a PRN (as-needed) administration"
                    ),
                ),
                (
                    "administered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nurse who administered/recorded",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medication_administrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        help_text="Admission this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_administrations",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "prescription_item",
                    models.ForeignKey(
                        help_text="The prescription item being administered",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrations",
                        to="pharmacy.prescriptionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication Administration",
                "verbose_name_plural": "Medication Administrations",
                "ordering": ["-scheduled_time"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["admission", "-scheduled_time"],
                        name="inpatient_m_admissi_2b07f2_idx",
                    ),
                    models.Index(
                        fields=["prescription_item", "-scheduled_time"],
                        name="inpatient_m_prescri_2ca46c_idx",
                    ),
                ],
            },
        ),
    ]
