# Generated by Django 5.2.11 on 2026-03-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0026_add_medication_administration"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="expected_discharge_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Clinician-set expected discharge date for bed planning",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="emergency_buffer_percent",
            field=models.PositiveIntegerField(
                default=0, help_text="Percentage of beds reserved for emergency admissions (0-100)"
            ),
        ),
    ]
