# Generated by Django 5.2.11 on 2026-03-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0027_smart_allocation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bed",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("OCCUPIED", "Occupied"),
                    ("CLEANING", "Cleaning In Progress"),
                    ("MAINTENANCE", "Under Maintenance"),
                    ("RESERVED", "Reserved"),
                ],
                default="AVAILABLE",
                help_text="Current bed status",
                max_length=20,
            ),
        ),
    ]
