# Generated by Django 5.2.11 on 2026-03-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0028_alter_bed_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ward",
            name="maternity_designated",
            field=models.BooleanField(
                default=False,
                help_text="Whether ward is designated for maternity patients (enforces female-only admission)",
            ),
        ),
    ]
