# Generated by Django 5.2.11 on 2026-03-16 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0030_backfill_ward_type_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="DischargeDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary Diagnosis"),
                            ("SECONDARY", "Secondary Diagnosis"),
                            ("COMPLICATION", "Complication"),
                        ],
                        help_text="Role of this diagnosis (PRIMARY, SECONDARY, COMPLICATION)",
                        max_length=15,
                    ),
                ),
                ("code", models.CharField(help_text="ICD-10 or ICD-11 code", max_length=20)),
                (
                    "description",
                    models.CharField(help_text="Diagnosis description text", max_length=500),
                ),
                (
                    "discharge",
                    models.ForeignKey(
                        help_text="Discharge this diagnosis belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="inpatient.discharge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discharge Diagnosis",
                "verbose_name_plural": "Discharge Diagnoses",
                "ordering": ["role", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("role", "PRIMARY")),
                        fields=("discharge", "role"),
                        name="unique_primary_diagnosis_per_discharge",
                    )
                ],
            },
        ),
    ]
