# Generated by Django 5.2.11 on 2026-03-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0032_migrate_final_diagnosis_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nursingcareplanentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ONGOING", "Ongoing"),
                    ("RESOLVED", "Resolved"),
                    ("DISCONTINUED", "Discontinued"),
                ],
                default="ACTIVE",
                help_text="Current status of this care plan entry",
                max_length=20,
            ),
        ),
    ]
