# Generated by Django 5.2.11 on 2026-04-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0035_add_atr_and_expiry_date"),
        ("laboratory", "0018_multitenancy_clinical_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="adversetransfusionreaction",
            name="lab_order",
            field=models.OneToOneField(
                blank=True,
                help_text="Lab order created for post-transfusion investigation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atr_report",
                to="laboratory.laborder",
            ),
        ),
    ]
