# Generated by Django 5.2.11 on 2026-04-07 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_add_webauthn_credential"),
        ("inpatient", "0036_add_lab_order_to_atr"),
    ]

    operations = [
        migrations.CreateModel(
            name="DischargeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable template name, e.g. 'Maternity Discharge'",
                        max_length=120,
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard (narrative layout)"),
                            ("STRUCTURED", "Structured (labelled fields in grid)"),
                            ("MINIMAL", "Minimal (compact single-page)"),
                        ],
                        default="STANDARD",
                        help_text="Print layout variant (standard narrative, structured grid, minimal).",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default template for the facility.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive templates are hidden from the print selector.",
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of section configs. Each entry: {key, label, enabled}. The key maps to a content source (AI section id or model field).",
                    ),
                ),
                (
                    "header_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Override document title (default: 'Discharge Summary').",
                        max_length=200,
                    ),
                ),
                (
                    "header_subtitle",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subtitle line printed below the facility name.",
                        max_length=200,
                    ),
                ),
                (
                    "show_signature_lines",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include signature lines on the printed document.",
                    ),
                ),
                (
                    "show_qr_code",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include a QR code for document verification.",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discharge Template",
                "verbose_name_plural": "Discharge Templates",
                "ordering": ["-is_default", "name"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("facility", "name"), name="unique_discharge_template_per_facility"
                    )
                ],
            },
        ),
    ]
