# Generated by Django 5.2.13 on 2026-04-23 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inpatient", "0039_facility_scoped_model_fix"),
        ("scheduling", "0018_shift_swap_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="discharge",
            name="follow_up_appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Scheduled follow-up appointment created from discharge",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discharge_follow_ups",
                to="scheduling.appointment",
            ),
        ),
    ]
