# Generated by Django 5.2.13 on 2026-05-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inpatient", "0040_discharge_follow_up_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adversetransfusionreaction",
            name="initial_reporter_email",
        ),
        migrations.RemoveField(
            model_name="adversetransfusionreaction",
            name="initial_reporter_mobile",
        ),
        migrations.RemoveField(
            model_name="adversetransfusionreaction",
            name="ppb_submitter_email",
        ),
        migrations.RemoveField(
            model_name="adversetransfusionreaction",
            name="ppb_submitter_mobile",
        ),
        migrations.AddField(
            model_name="adversetransfusionreaction",
            name="initial_reporter_email_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="adversetransfusionreaction",
            name="initial_reporter_mobile_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="adversetransfusionreaction",
            name="ppb_submitter_email_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="adversetransfusionreaction",
            name="ppb_submitter_mobile_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
