# Generated by Django 5.2.13 on 2026-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_staffprofile_employee_id_unique"),
        ("inpatient", "0042_admission_origin_hub_id_admission_origin_local_id_and_more"),
        ("scheduling", "0021_appointment_origin_hub_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ward",
            name="code",
            field=models.CharField(
                help_text="Ward code (e.g., 'MED-01'), unique per facility", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="ward",
            name="name",
            field=models.CharField(
                help_text="Ward name (e.g., 'Medical Ward 1'), unique per facility", max_length=100
            ),
        ),
        migrations.AddConstraint(
            model_name="ward",
            constraint=models.UniqueConstraint(
                fields=("code", "facility"), name="unique_ward_code_per_facility"
            ),
        ),
        migrations.AddConstraint(
            model_name="ward",
            constraint=models.UniqueConstraint(
                fields=("name", "facility"), name="unique_ward_name_per_facility"
            ),
        ),
    ]
