# Generated by Django 5.2.13 on 2026-07-14 19:09

import uuid
from django.db import migrations, models


def backfill_admission_public_ids(apps, schema_editor):
    Admission = apps.get_model("inpatient", "Admission")
    for admission_id in Admission.objects.filter(public_id__isnull=True).values_list("id", flat=True).iterator(
        chunk_size=1000
    ):
        Admission.objects.filter(id=admission_id, public_id__isnull=True).update(public_id=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ("inpatient", "0044_alter_admission_admission_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="public_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_admission_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="admission",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                unique=True,
            ),
        ),
    ]
