"""Create Kardex field change history table.

This migration adds `KardexFieldChange` for tracking NursingKardex field edits over time.
Run with: `python manage.py migrate`.
Inputs: standard Django migration execution (no custom args/env vars).
"""

# Generated by Django 5.2.13 on 2026-08-19 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inpatient", "0054_atr_volume_and_link_transfusion_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KardexFieldChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(help_text="Field that was changed", max_length=100),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, help_text="Previous value before update"),
                ),
                ("new_value", models.TextField(blank=True, help_text="New value after update")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kardex_field_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kardex",
                    models.ForeignKey(
                        help_text="Kardex this field change belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_change_history",
                        to="inpatient.nursingkardex",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["kardex", "-changed_at"], name="inpatient_k_kardex__70ae0c_idx"
                    ),
                    models.Index(
                        fields=["field_name", "-changed_at"], name="inpatient_k_field_n_bdfad1_idx"
                    ),
                ],
            },
        ),
    ]
