"""Add structured Kardex clinical fields and schedule items.

This migration adds code-status/clinical snapshot fields to NursingKardex and
creates KardexScheduleItem for timed treatments/tests/vitals/medications.
Run with: `python manage.py migrate`.
Inputs: standard Django migration execution (no custom args/env vars).
"""

# Generated by Django 5.2.13 on 2026-08-19 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inpatient", "0055_kardexfieldchange"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nursingkardex",
            name="code_status",
            field=models.CharField(
                choices=[
                    ("FULL_CODE", "Full Code"),
                    ("DNR", "Do Not Resuscitate (DNR)"),
                    ("DNI", "Do Not Intubate (DNI)"),
                    ("LIMITED", "Limited Intervention"),
                    ("UNKNOWN", "Unknown / Not Documented"),
                ],
                default="UNKNOWN",
                help_text="Resuscitation/code status (e.g., Full Code, DNR)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="code_status_notes",
            field=models.TextField(
                blank=True, help_text="Optional context for code status decisions"
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="current_medications",
            field=models.TextField(
                blank=True, help_text="Current medications snapshot for nursing handoff"
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="hygiene_precautions",
            field=models.TextField(
                blank=True, help_text="Personal hygiene needs or safety precautions"
            ),
        ),
        migrations.AddField(
            model_name="nursingkardex",
            name="iv_fluids",
            field=models.TextField(blank=True, help_text="Current IV fluids and rates"),
        ),
        migrations.CreateModel(
            name="KardexScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("TREATMENT", "Treatment"),
                            ("DIAGNOSTIC_TEST", "Diagnostic Test"),
                            ("VITALS_CHECK", "Vitals Check"),
                            ("MEDICATION", "Medication"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "scheduled_for",
                    models.DateTimeField(help_text="Scheduled date and time for this task"),
                ),
                ("frequency", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kardex_schedule_items_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kardex",
                    models.ForeignKey(
                        help_text="Kardex this schedule item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="inpatient.nursingkardex",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for", "id"],
                "indexes": [
                    models.Index(
                        fields=["kardex", "scheduled_for"], name="inpatient_k_kardex__f83d34_idx"
                    ),
                    models.Index(
                        fields=["status", "scheduled_for"], name="inpatient_k_status_b969db_idx"
                    ),
                ],
            },
        ),
    ]
