# Copyright (c) 2026 Nexora Consulting Ltd. All rights reserved.
"""Create the facility-scoped inpatient bed assignment request workflow.

Run with: python manage.py migrate inpatient.
Inputs: standard Django migration command arguments only.
"""

# Generated by Django 5.2.13 on 2026-09-06 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_add_laboratory_license_fields"),
        ("inpatient", "0057_nursingcareplanentry_last_reviewed_at_and_more"),
        ("patients", "0027_alter_historicalpatient_identification_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BedAssignmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="ROUTINE",
                        help_text="Clinical priority for bed allocation.",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Clinical or operational reason for the request."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ASSIGNED", "Assigned"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current bed assignment request status.",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, help_text="When the bed was assigned.", null=True
                    ),
                ),
                (
                    "assigned_bed",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bed reserved for this request.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bed_assignment_requests",
                        to="inpatient.bed",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who assigned the bed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bed_assignment_requests_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient requiring a bed assignment.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bed_assignment_requests",
                        to="patients.patient",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional admission recommendation supporting this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bed_assignment_requests",
                        to="inpatient.admissionrecommendation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="User who requested the bed assignment.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bed_assignment_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_ward",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preferred ward, when known.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bed_assignment_requests",
                        to="inpatient.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bed Assignment Request",
                "verbose_name_plural": "Bed Assignment Requests",
                "ordering": ["priority", "created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["facility", "status", "priority"],
                        name="inpatient_b_facilit_e429cd_idx",
                    ),
                    models.Index(
                        fields=["patient", "status"], name="inpatient_b_patient_fc7823_idx"
                    ),
                ],
            },
        ),
    ]
