# Generated by Django 5.2.11 on 2026-03-02 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("encounters", "0023_historicaldiagnosis_historicalencounter"),
        ("patients", "0014_historicalpatient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CDSRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique rule code (e.g., DRUG-ALLERGY-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable rule name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of what this rule checks",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DRUG_ALLERGY", "Drug-Allergy Interaction"),
                            ("DRUG_DRUG", "Drug-Drug Interaction"),
                            ("CRITICAL_LAB", "Critical Lab Value"),
                            ("VITAL_SIGN", "Vital Sign Alert"),
                            ("GUIDELINE", "Clinical Guideline"),
                            ("PREVENTIVE", "Preventive Care"),
                            ("DOSAGE", "Dosage Check"),
                        ],
                        help_text="Category of clinical decision support rule",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("INFO", "Informational"),
                        ],
                        default="MEDIUM",
                        help_text="Priority/severity when triggered",
                        max_length=10,
                    ),
                ),
                (
                    "evidence_level",
                    models.CharField(
                        choices=[
                            ("A", "Level A — Strong evidence"),
                            ("B", "Level B — Moderate evidence"),
                            ("C", "Level C — Limited evidence"),
                            ("D", "Level D — Expert consensus"),
                        ],
                        default="D",
                        help_text="Evidence level supporting this rule",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        help_text="Lifecycle status",
                        max_length=10,
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        help_text="JSON logic condition. Keys: 'type' (vital_range|drug_allergy|drug_drug|lab_range|custom), plus type-specific fields."
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ALERT", "Show Alert"),
                            ("CONTRAINDICATE", "Contraindicate"),
                            ("WARN", "Warn"),
                            ("SUGGEST", "Suggest"),
                            ("REQUIRE", "Require Action"),
                            ("INFORM", "Inform"),
                        ],
                        default="ALERT",
                        help_text="Type of action when rule triggers",
                        max_length=20,
                    ),
                ),
                (
                    "action_message",
                    models.TextField(
                        help_text="Message template shown when rule triggers. Supports {variable} placeholders."
                    ),
                ),
                (
                    "suggestion",
                    models.TextField(
                        blank=True, default="", help_text="Recommended clinical action"
                    ),
                ),
                (
                    "references",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of clinical references/guidelines supporting this rule",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional rule configuration (thresholds, parameters)",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the rule was approved/activated", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved/activated this rule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cds_rules_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this rule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cds_rules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CDS Rule",
                "verbose_name_plural": "CDS Rules",
                "ordering": ["-priority", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="CDSAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("INFO", "Informational"),
                        ],
                        help_text="Priority (copied from rule at trigger time)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("ACCEPTED", "Accepted"),
                            ("OVERRIDDEN", "Overridden"),
                            ("DISMISSED", "Dismissed"),
                            ("AUTO_RESOLVED", "Auto-Resolved"),
                        ],
                        default="PENDING",
                        help_text="Current alert status",
                        max_length=15,
                    ),
                ),
                ("message", models.TextField(help_text="Rendered alert message")),
                (
                    "suggestion",
                    models.TextField(
                        blank=True, default="", help_text="Recommended action (copied from rule)"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Evaluation context — values that triggered the alert",
                    ),
                ),
                (
                    "override_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason provided when overriding the alert",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the alert was resolved", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Encounter context (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cds_alerts",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient this alert is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cds_alerts",
                        to="patients.patient",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who resolved this alert",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cds_alerts_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User whose action triggered this alert",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cds_alerts_triggered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="CDS rule that generated this alert",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="cds.cdsrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "CDS Alert",
                "verbose_name_plural": "CDS Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cdsrule",
            index=models.Index(
                fields=["category", "status"], name="cds_cdsrule_categor_d7f29c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cdsrule",
            index=models.Index(fields=["status", "priority"], name="cds_cdsrule_status_435c87_idx"),
        ),
        migrations.AddIndex(
            model_name="cdsrule",
            index=models.Index(fields=["code"], name="cds_cdsrule_code_57e05e_idx"),
        ),
        migrations.AddIndex(
            model_name="cdsalert",
            index=models.Index(fields=["patient", "status"], name="cds_cdsaler_patient_c15c32_idx"),
        ),
        migrations.AddIndex(
            model_name="cdsalert",
            index=models.Index(
                fields=["encounter", "status"], name="cds_cdsaler_encount_2aa915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cdsalert",
            index=models.Index(fields=["status", "priority"], name="cds_cdsaler_status_8aedf5_idx"),
        ),
        migrations.AddIndex(
            model_name="cdsalert",
            index=models.Index(fields=["rule", "status"], name="cds_cdsaler_rule_id_006f25_idx"),
        ),
        migrations.AddIndex(
            model_name="cdsalert",
            index=models.Index(fields=["-created_at"], name="cds_cdsaler_created_3b245c_idx"),
        ),
    ]
