# Generated by Django 5.2.11 on 2026-03-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cds", "0001_initial"),
        ("core", "0030_role_multitenancy_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="cdsalert",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where alert was generated.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cds_alerts",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="cdsalert",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cds_alerts",
                to="core.organization",
            ),
        ),
    ]
