# Generated by Django 5.2.9 on 2026-02-06 21:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0013_add_idempotency_key_model"),
        ("patients", "0010_add_unique_identification_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_time",
                    models.DateTimeField(
                        db_index=True, help_text="Start datetime (timezone-aware)"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(db_index=True, help_text="End datetime (timezone-aware)"),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Nairobi",
                        help_text="IANA timezone name (e.g., Africa/Nairobi)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "ordering": ["start_time"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Display name of the resource", max_length=200),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("PERSON", "Person"), ("PLACE", "Place"), ("ASSET", "Asset")],
                        db_index=True,
                        help_text="Type of resource (PERSON, PLACE, ASSET)",
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique resource code (e.g., DOC-001, ROOM-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether resource is available for scheduling",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=1, help_text="Capacity (for places/assets, e.g., room capacity)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional resource-specific data"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Description of the resource"
                    ),
                ),
                (
                    "staff_profile",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to StaffProfile for person resources",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduling_resource",
                        to="core.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduling Resource",
                "verbose_name_plural": "Scheduling Resources",
                "ordering": ["resource_type", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("RECURRING", "Recurring Weekly"),
                            ("ONE_TIME", "One-Time"),
                            ("BLOCK", "Blocked Time"),
                        ],
                        db_index=True,
                        default="RECURRING",
                        help_text="Type of schedule",
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        db_index=True,
                        help_text="Day of week for recurring schedules (0=Monday)",
                        null=True,
                    ),
                ),
                (
                    "specific_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Specific date for one-time schedules",
                        null=True,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Daily start time")),
                ("end_time", models.TimeField(help_text="Daily end time")),
                (
                    "slot_duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Duration of each bookable slot in minutes"
                    ),
                ),
                (
                    "buffer_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Buffer time between appointments in minutes"
                    ),
                ),
                (
                    "max_appointments",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum appointments per day (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        db_index=True,
                        default=datetime.date.today,
                        help_text="When this schedule becomes effective",
                    ),
                ),
                (
                    "effective_until",
                    models.DateField(
                        blank=True,
                        help_text="When this schedule ends (null = indefinite)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this schedule is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes about this schedule"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        help_text="Resource this schedule applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="scheduling.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "ordering": ["resource", "day_of_week", "start_time"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduleBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.TimeField(help_text="Break start time")),
                ("end_time", models.TimeField(help_text="Break end time")),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reason for break (e.g., Lunch)",
                        max_length=100,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        help_text="Parent schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="scheduling.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Break",
                "verbose_name_plural": "Schedule Breaks",
                "ordering": ["schedule", "start_time"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment_number",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated appointment number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consultation"),
                            ("FOLLOW_UP", "Follow-up"),
                            ("PROCEDURE", "Procedure"),
                            ("LAB_TEST", "Laboratory Test"),
                            ("IMAGING", "Imaging/Radiology"),
                            ("VACCINATION", "Vaccination"),
                            ("THERAPY", "Therapy Session"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="CONSULTATION",
                        help_text="Type of appointment",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(db_index=True, help_text="Scheduled start datetime"),
                ),
                (
                    "scheduled_end",
                    models.DateTimeField(db_index=True, help_text="Scheduled end datetime"),
                ),
                (
                    "actual_start",
                    models.DateTimeField(blank=True, help_text="Actual start datetime", null=True),
                ),
                (
                    "actual_end",
                    models.DateTimeField(blank=True, help_text="Actual end datetime", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("CONFIRMED", "Confirmed"),
                            ("CHECKED_IN", "Checked In"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        db_index=True,
                        default="CREATED",
                        help_text="Current appointment status",
                        max_length=20,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="When appointment was confirmed", null=True
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, help_text="When patient checked in", null=True
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="When appointment was cancelled", null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, default="", help_text="Reason for cancellation"),
                ),
                ("reason", models.TextField(help_text="Reason for appointment")),
                ("notes", models.TextField(blank=True, default="", help_text="Additional notes")),
                (
                    "completion_notes",
                    models.TextField(blank=True, default="", help_text="Notes upon completion"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        db_index=True,
                        default="ROUTINE",
                        help_text="Appointment priority",
                        max_length=20,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who cancelled the appointment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who checked in the patient",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkedin_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who confirmed the appointment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the appointment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient for this appointment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduling_appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        help_text="Scheduled resource",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="scheduling.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-scheduled_start"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["scheduled_start", "status"], name="scheduling__schedul_4ea709_idx"
                    ),
                    models.Index(
                        fields=["resource", "scheduled_start"],
                        name="scheduling__resourc_2475ac_idx",
                    ),
                    models.Index(
                        fields=["patient", "scheduled_start"], name="scheduling__patient_b950e7_idx"
                    ),
                ],
            },
        ),
    ]
