# Generated by Django 5.2.11 on 2026-04-05 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_add_mfa_grace_deadline"),
        ("scheduling", "0003_add_assignment_engine_phase2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="assignmentrule",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="assignmentrule",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentrule",
            name="rule_code",
            field=models.CharField(
                db_index=True,
                help_text="Unique rule identifier (e.g., assign_doctor_to_opd)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Unique resource code (e.g., DOC-001, ROOM-001)",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="assignmentrule",
            constraint=models.UniqueConstraint(
                fields=("facility", "rule_code"), name="scheduling_rule_unique_code_per_facility"
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                fields=("facility", "code"), name="scheduling_resource_unique_code_per_facility"
            ),
        ),
    ]
