# Generated by Django 5.2.11 on 2026-04-11 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_projection_read_models"),
        ("scheduling", "0004_add_facility_tenant_scoping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shift_date", models.DateField(db_index=True, help_text="Date of the shift")),
                ("start_time", models.TimeField(help_text="Shift start time")),
                ("end_time", models.TimeField(help_text="Shift end time")),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("DAY", "Day Shift"),
                            ("NIGHT", "Night Shift"),
                            ("MORNING", "Morning Shift"),
                            ("AFTERNOON", "Afternoon Shift"),
                            ("ON_CALL", "On-Call"),
                            ("OVERTIME", "Overtime"),
                        ],
                        db_index=True,
                        default="DAY",
                        help_text="Type of shift",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        help_text="Current shift status",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Department for this shift (e.g., OPD, Emergency, Ward A)",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes about this shift"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Actual shift start timestamp", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Actual shift end timestamp", null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, default="", help_text="Reason for cancellation"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who cancelled the shift",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the shift",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "staff_resource",
                    models.ForeignKey(
                        help_text="Staff member assigned to this shift",
                        limit_choices_to={"resource_type": "PERSON"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="scheduling.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["shift_date", "start_time"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["shift_date", "status"], name="scheduling__shift_d_d29484_idx"
                    ),
                    models.Index(
                        fields=["staff_resource", "shift_date"],
                        name="scheduling__staff_r_ba0772_idx",
                    ),
                ],
            },
        ),
    ]
