# Generated by Django 5.2.11 on 2026-04-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_projection_read_models"),
        ("scheduling", "0007_add_max_day_night_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="staff_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to StaffProfile for person resources (one per facility)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduling_resources",
                to="core.staffprofile",
            ),
        ),
    ]
