# Generated by Django 5.2.11 on 2026-04-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0008_staff_profile_fk_multi_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulingsettings",
            name="active_shift_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Working shift types this facility uses for auto-fill coverage, e.g. ['MORNING','AFTERNOON','NIGHT']. When set, auto-fill distributes staff across ALL listed types each day.",
            ),
        ),
    ]
