# Generated by Django 5.2.11 on 2026-04-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0009_add_active_shift_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulingsettings",
            name="enforce_punctuality",
            field=models.BooleanField(
                default=False,
                help_text="When True, clock-in is blocked if staff is more than late_cutoff_minutes late",
            ),
        ),
        migrations.AddField(
            model_name="schedulingsettings",
            name="late_cutoff_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Minutes after shift start after which clock-in is blocked (0 = no limit)",
            ),
        ),
    ]
