# Generated by Django 5.2.11 on 2026-04-12 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0011_add_on_break_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shift",
            options={
                "ordering": ["shift_date", "start_time"],
                "permissions": [("manage_schedules", "Can manage schedules")],
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
            },
        ),
    ]
