# Generated by Django 5.2.11 on 2026-04-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0014_clinicvisit_room_clinicroom"),
        ("scheduling", "0012_add_manage_schedules_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                help_text="Clinic associated with this shift (set at clock-in)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="clinics.clinic",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Room/location where this shift is being served",
                limit_choices_to={"resource_type": "PLACE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_shifts",
                to="scheduling.resource",
            ),
        ),
    ]
