# Generated by Django 5.2.11 on 2026-04-13 17:34

import django.db.models.deletion
from django.db import migrations, models


def copy_department_to_legacy_and_remove(apps, schema_editor):
    """Copy old department CharField values to department_legacy, then remove the old column."""
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            "UPDATE scheduling_shift SET department_legacy = department WHERE department IS NOT NULL AND department != ''"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_projection_read_models"),
        ("scheduling", "0014_attendance_phase2_3"),
    ]

    operations = [
        # 1. Add Resource.department FK
        migrations.AddField(
            model_name="resource",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department this resource belongs to (e.g., Laboratory, Pharmacy, Outpatient)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduling_resources",
                to="core.department",
            ),
        ),
        # 2. Add Shift.department_legacy CharField
        migrations.AddField(
            model_name="shift",
            name="department_legacy",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Legacy text department (migrating to FK). Do not use for new code.",
                max_length=200,
            ),
        ),
        # 3. Copy old department text to department_legacy
        migrations.RunPython(
            copy_department_to_legacy_and_remove,
            migrations.RunPython.noop,
        ),
        # 4. Remove old CharField column
        migrations.RemoveField(
            model_name="shift",
            name="department",
        ),
        # 5. Add new FK column
        migrations.AddField(
            model_name="shift",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text="Department for this shift",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="core.department",
            ),
        ),
    ]
