# Generated by Django 5.2.11 on 2026-04-13 17:34

from django.db import migrations


def backfill_resource_department(apps, schema_editor):
    """
    Backfill Resource.department from:
    1. PERSON resources: copy from staff_profile.primary_department
    2. PLACE resources linked to clinics: copy from clinic.department (if set)
    """
    Resource = apps.get_model("scheduling", "Resource")

    # PERSON resources → staff_profile.primary_department
    for resource in Resource.objects.filter(
        resource_type="PERSON",
        staff_profile__isnull=False,
        staff_profile__primary_department__isnull=False,
        department__isnull=True,
    ).select_related("staff_profile__primary_department"):
        resource.department = resource.staff_profile.primary_department
        resource.save(update_fields=["department"])


def backfill_shift_department(apps, schema_editor):
    """
    Backfill Shift.department FK from department_legacy text.
    Tries to match by Department.name (case-insensitive), then Department.code.
    Also copies old CharField value into department_legacy.
    """
    Shift = apps.get_model("scheduling", "Shift")
    Department = apps.get_model("core", "Department")

    dept_by_name = {}
    dept_by_code = {}
    for dept in Department.objects.all():
        dept_by_name[dept.name.lower()] = dept
        dept_by_code[dept.code.lower()] = dept

    for shift in Shift.objects.filter(department__isnull=True).exclude(
        department_legacy=""
    ):
        legacy = shift.department_legacy.strip()
        match = dept_by_name.get(legacy.lower()) or dept_by_code.get(legacy.lower())
        if match:
            shift.department = match
            shift.save(update_fields=["department"])


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0015_add_department_fk"),
    ]

    operations = [
        migrations.RunPython(
            backfill_resource_department,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_shift_department,
            migrations.RunPython.noop,
        ),
    ]
