# Generated by Django 5.2.13 on 2026-04-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0016_backfill_department_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="emergency_reason",
            field=models.TextField(
                blank=True, default="", help_text="Reason provided for emergency clock-in"
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="is_emergency",
            field=models.BooleanField(
                default=False,
                help_text="True if this shift was created via emergency clock-in (ad-hoc)",
            ),
        ),
    ]
