# Generated by Django 5.2.13 on 2026-05-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0019_resource_equipment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shiftswaprequest",
            options={
                "ordering": ["-created_at"],
                "permissions": [("approve_swap", "Can approve shift swap requests")],
                "verbose_name": "Shift Swap Request",
                "verbose_name_plural": "Shift Swap Requests",
            },
        ),
    ]
