# Generated by Django 5.2.13 on 2026-06-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0020_add_custom_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignmentrule",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignmentrule",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="schedulingsettings",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="schedulingsettings",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shiftswaprequest",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shiftswaprequest",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staffconstraint",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staffconstraint",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
    ]
