# Generated by Django 5.2.13 on 2026-07-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_staffprofile_employee_id_unique"),
        ("scheduling", "0021_appointment_origin_hub_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftTypeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("DAY", "Day Shift"),
                            ("NIGHT", "Night Shift"),
                            ("MORNING", "Morning Shift"),
                            ("AFTERNOON", "Afternoon Shift"),
                            ("ON_CALL", "On-Call"),
                            ("OVERTIME", "Overtime"),
                            ("DAY_OFF", "Day Off"),
                            ("NIGHT_OFF", "Night Off"),
                            ("OFF", "Off (Full Day)"),
                            ("AFTERNOON_OFF", "Afternoon Off"),
                            ("LEAVE", "Leave"),
                            ("SICK_LEAVE", "Sick Leave"),
                            ("REST", "Rest Day"),
                        ],
                        help_text="The shift type this configuration applies to",
                        max_length=30,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional custom display label (e.g. 'Early Morning' instead of 'Morning Shift')",
                        max_length=100,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Default start time for this shift type at this facility"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="Default end time for this shift type at this facility"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional hex color code for roster display (e.g. '#4CAF50')",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this shift type is currently in use at this facility",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Type Configuration",
                "verbose_name_plural": "Shift Type Configurations",
                "ordering": ["shift_type"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("facility", "shift_type"), name="unique_shift_type_per_facility"
                    )
                ],
            },
        ),
    ]
