# Generated by Django 5.2.13 on 2026-08-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0024_scheduling_settings_autofill_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulingsettings",
            name="autofill_group_minimums",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Group-specific minimum staffing rules for autofill, e.g. [{"scope": "DEPARTMENT", "value": "Nursing", "min_staff": 2, "shift_types": ["DAY", "NIGHT"]}].',
            ),
        ),
        migrations.AlterField(
            model_name="schedulingsettings",
            name="autofill_weights",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-facility scoring weights for weekly roster autofill, e.g. {"weekly_load": 30, "history_hours": 4, "night_penalty": 16}. Missing keys fall back to system defaults.',
            ),
        ),
    ]
