# Generated by Django 5.2.13 on 2026-08-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0025_schedulingsettings_autofill_group_minimums_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulingsettings",
            name="autofill_group_maximums",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Group-specific maximum staffing rules for autofill, e.g. [{"scope": "ROLE", "value": "Nurse", "max_staff": 3, "shift_types": ["NIGHT"]}].',
            ),
        ),
        migrations.AlterField(
            model_name="staffconstraint",
            name="constraint_type",
            field=models.CharField(
                choices=[
                    ("NO_NIGHTS", "Cannot work night shifts"),
                    ("NO_WEEKENDS", "Cannot work weekends"),
                    ("MAX_HOURS", "Custom max hours per week"),
                    ("MAX_CONSECUTIVE", "Custom max consecutive days"),
                    ("PREFERRED_SHIFTS", "Preferred shift types only"),
                    ("NO_OVERTIME", "No overtime shifts"),
                    ("LIGHT_DUTY", "Light duty — day shifts only"),
                    ("NO_SHARED_SHIFT_WITH", "Cannot share shift with specific staff"),
                ],
                help_text="Type of scheduling constraint",
                max_length=30,
            ),
        ),
    ]
