# Generated by Django 5.2.9 on 2026-01-03 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="triagequeue",
            options={
                "ordering": ["triage_assessment__arrival_time"],
                "verbose_name": "Triage Queue Entry",
                "verbose_name_plural": "Triage Queue Entries",
            },
        ),
    ]
