# Generated by Django 5.2.9 on 2026-01-04 01:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0009_add_encounter_status_workflow"),
        ("patients", "0007_add_location_fields"),
        ("triage", "0002_alter_triagequeue_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When patient checked in/registered",
                    ),
                ),
                (
                    "reason_for_visit",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Initial reason for visit (chief complaint)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING_TRIAGE", "Waiting for Triage"),
                            ("IN_TRIAGE", "Being Triaged"),
                            ("TRIAGED", "Triaged - Moved to Priority Queue"),
                            ("CANCELLED", "Cancelled/Left"),
                        ],
                        default="WAITING_TRIAGE",
                        max_length=20,
                    ),
                ),
                (
                    "priority_hint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Initial priority hint (e.g., 'EMERGENCY' for walk-in emergencies)",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who checked in the patient",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_check_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated encounter (created when patient checks in)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiting_queue_entries",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient waiting to be seen",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiting_queue_entries",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waiting Queue Entry",
                "verbose_name_plural": "Waiting Queue Entries",
                "ordering": ["check_in_time"],
            },
        ),
    ]
