# Generated by Django 5.2.9 on 2026-01-05

from django.db import migrations, models
from django.core.validators import MaxValueValidator, MinValueValidator


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0003_add_waiting_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="triageassessment",
            name="spo2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Oxygen saturation percentage (SpO2)",
                max_digits=5,
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="triageassessment",
            name="heart_rate",
            field=models.IntegerField(
                blank=True,
                help_text="Heart rate (beats per minute)",
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(300)],
            ),
        ),
        migrations.AddField(
            model_name="triageassessment",
            name="systolic_bp",
            field=models.IntegerField(
                blank=True,
                help_text="Systolic blood pressure (mmHg)",
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(300)],
            ),
        ),
        migrations.AddField(
            model_name="triageassessment",
            name="diastolic_bp",
            field=models.IntegerField(
                blank=True,
                help_text="Diastolic blood pressure (mmHg)",
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(200)],
            ),
        ),
        migrations.AddField(
            model_name="triageassessment",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Body temperature in Celsius (°C)",
                max_digits=4,
                null=True,
                validators=[MinValueValidator(30), MaxValueValidator(45)],
            ),
        ),
        migrations.AddField(
            model_name="triageassessment",
            name="respiratory_rate",
            field=models.IntegerField(
                blank=True,
                help_text="Respiratory rate (breaths per minute)",
                null=True,
                validators=[MinValueValidator(0), MaxValueValidator(60)],
            ),
        ),
    ]
