# Generated by Django 5.2.9 on 2026-01-05 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0004_add_vitals_fields_to_triageassessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="triageassessment",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Body weight in kilograms (kg)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
    ]
