# Generated by Django 5.2.9 on 2026-02-19 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0006_add_assigned_clinic_to_triageassessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="triageassessment",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Body height in centimeters (cm)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
    ]
