# Generated by Django 5.2.9 on 2026-02-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0007_add_height_to_triageassessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="triageassessment",
            name="referring_facility_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of referring facility (required when arrival_mode is REFERRAL)",
                max_length=255,
            ),
        ),
    ]
