# Generated by Django 5.2.11 on 2026-03-04 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0014_historicalpatient"),
        ("triage", "0008_add_referring_facility_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ERBed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("ER_RESUS", "ER - Resuscitation"),
                            ("ER_ACUTE", "ER - Acute Care"),
                            ("ER_FAST_TRACK", "ER - Fast Track"),
                            ("OBSERVATION", "Observation Unit"),
                            ("TRAUMA", "Trauma Bay"),
                            ("PEDIATRIC_ER", "Pediatric ER"),
                            ("MATERNITY", "Maternity/Labor"),
                        ],
                        help_text="ER zone this bed belongs to",
                        max_length=20,
                    ),
                ),
                (
                    "bed_number",
                    models.CharField(
                        help_text="Bed/bay identifier within zone (e.g., 'R-01', 'A-05')",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("CLEANING", "Cleaning"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="AVAILABLE",
                        help_text="Current bed status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes (cleaning reason, out-of-service reason, etc.)",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the bed status last changed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Patient currently occupying this bed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="er_beds",
                        to="patients.patient",
                    ),
                ),
                (
                    "current_triage_assessment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Triage assessment for current occupant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="er_bed_assignment",
                        to="triage.triageassessment",
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last changed the bed status",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="er_bed_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ER Bed",
                "verbose_name_plural": "ER Beds",
                "ordering": ["zone", "bed_number"],
                "unique_together": {("zone", "bed_number")},
            },
        ),
    ]
