# Generated by Django 5.2.11 on 2026-03-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0014_historicalpatient"),
        ("triage", "0009_add_er_bed_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "escalation_type",
                    models.CharField(
                        choices=[
                            ("CHARGE_NURSE", "Escalate to Charge Nurse"),
                            ("ADDITIONAL_STAFF", "Request Additional Staff"),
                            ("SUPERVISOR", "Escalate to Supervisor"),
                        ],
                        help_text="Type of escalation",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for escalation")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending – Escalation raised"),
                            ("IN_PROGRESS", "In Progress – Being handled"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "wait_time_at_escalation",
                    models.IntegerField(
                        blank=True,
                        help_text="Patient's wait time in minutes when escalation was raised",
                        null=True,
                    ),
                ),
                (
                    "triage_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Triage category at escalation time",
                        max_length=10,
                    ),
                ),
                (
                    "assigned_area",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ER zone at time of escalation",
                        max_length=30,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "escalated_by",
                    models.ForeignKey(
                        help_text="Staff member who raised the escalation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient being escalated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="patients.patient",
                    ),
                ),
                (
                    "queue_entry",
                    models.ForeignKey(
                        help_text="Queue entry being escalated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="triage.triagequeue",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triage_assessment",
                    models.ForeignKey(
                        help_text="Associated triage assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="triage.triageassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation",
                "verbose_name_plural": "Escalations",
                "ordering": ["-created_at"],
                "permissions": [("escalate_patient", "Can escalate patient in triage queue")],
            },
        ),
        migrations.CreateModel(
            name="WaitTimeBreach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "triage_category",
                    models.CharField(help_text="Triage category at breach time", max_length=10),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical – RED category breach (> 0 min)"),
                            ("URGENT", "Urgent – ORANGE category breach (> 10 min)"),
                            ("WARNING", "Warning – YELLOW category breach (> 60 min)"),
                            ("INFO", "Informational – GREEN/BLUE category breach"),
                        ],
                        help_text="Severity derived from triage category",
                        max_length=10,
                    ),
                ),
                (
                    "target_wait_minutes",
                    models.IntegerField(
                        help_text="KETA target wait time in minutes for this category"
                    ),
                ),
                (
                    "actual_wait_minutes",
                    models.IntegerField(
                        help_text="Actual wait time in minutes when breach was detected"
                    ),
                ),
                (
                    "assigned_area",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ER zone where patient is waiting",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active – Unacknowledged"),
                            ("ACKNOWLEDGED", "Acknowledged by staff"),
                            ("ESCALATED", "Escalated to charge nurse/supervisor"),
                            ("RESOLVED", "Resolved – Patient seen or left"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_breaches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient whose wait time was breached",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wait_time_breaches",
                        to="patients.patient",
                    ),
                ),
                (
                    "queue_entry",
                    models.ForeignKey(
                        help_text="Queue entry whose wait time was breached",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wait_time_breaches",
                        to="triage.triagequeue",
                    ),
                ),
                (
                    "triage_assessment",
                    models.ForeignKey(
                        help_text="Associated triage assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wait_time_breaches",
                        to="triage.triageassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wait Time Breach",
                "verbose_name_plural": "Wait Time Breaches",
                "ordering": ["-created_at"],
            },
        ),
    ]
