# Generated by Django 5.2.11 on 2026-03-06 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0010_phase4_escalation_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="triageassessment",
            name="gcs_eye",
            field=models.IntegerField(
                blank=True,
                help_text="Eye response: 1=None, 2=To pain, 3=To voice, 4=Spontaneous",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AddField(
            model_name="triageassessment",
            name="gcs_motor",
            field=models.IntegerField(
                blank=True,
                help_text="Motor response: 1=None, 2=Extension, 3=Flexion, 4=Withdrawal, 5=Localizes, 6=Obeys",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AddField(
            model_name="triageassessment",
            name="gcs_verbal",
            field=models.IntegerField(
                blank=True,
                help_text="Verbal response: 1=None, 2=Sounds, 3=Words, 4=Confused, 5=Oriented",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
