# Generated by Django 5.2.11 on 2026-03-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_multitenancy_clinical_fks"),
        ("triage", "0011_add_gcs_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="triageassessment",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where triage was performed.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triage_assessments",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="triageassessment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triage_assessments",
                to="core.organization",
            ),
        ),
    ]
