# Generated by Django 5.2.13 on 2026-04-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_add_has_inventory_to_facility"),
        ("triage", "0014_add_triage_room_and_settings"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="erbed",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="erbed",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="erbed",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="erbed",
            unique_together={("facility", "zone", "bed_number")},
        ),
    ]
