# Generated by Django 5.2.9 on 2025-12-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_patient_options_patient_consent_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="national_id",
            field=models.CharField(
                blank=True, help_text="Patient's national ID number", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Patient's phone number", max_length=20, null=True
            ),
        ),
    ]
