# Generated by Django 5.2.9 on 2025-12-28 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_allow_null_phone_national_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(help_text="Contact's full name", max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("friend", "Friend"),
                            ("other", "Other"),
                        ],
                        help_text="Relationship to patient",
                        max_length=50,
                    ),
                ),
                ("phone_number", models.CharField(help_text="Primary phone number", max_length=20)),
                (
                    "alternative_phone",
                    models.CharField(
                        blank=True, default="", help_text="Alternative phone number", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="The patient this emergency contact belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "ordering": ["-created_at"],
            },
        ),
    ]
