# Generated by Django 5.2.9 on 2025-12-28 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_add_emergency_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="registered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who registered this patient",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
