# Generated by Django 5.2.9 on 2026-01-10 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0009_rename_core_notifi_user_id_3f3d8f_idx_core_notifi_user_id_f286cd_idx_and_more",
        ),
        ("patients", "0007_add_location_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="citizenship",
            field=models.CharField(
                default="Kenyan", help_text="Patient's citizenship", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="consent_deferred",
            field=models.BooleanField(
                default=False,
                help_text="Consent was deferred and must be obtained before discharge",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="cr_number",
            field=models.CharField(
                blank=True,
                help_text="Client Registry number from Kenya HIE (CR-XXXXXXXXXX-X format)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="identification_number",
            field=models.CharField(
                blank=True, help_text="Identification document number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="identification_type",
            field=models.CharField(
                choices=[
                    ("national_id", "National ID"),
                    ("cr_number", "HIE Patient ID"),
                    ("mandate_number", "Mandate Number"),
                    ("alien_id", "Alien ID"),
                    ("kra_pin", "KRA PIN"),
                    ("temporary_id", "Temporary ID"),
                    ("passport", "Passport Number"),
                ],
                default="national_id",
                help_text="Type of identification document",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_person_with_disability",
            field=models.BooleanField(
                default=False, help_text="Whether the patient has a disability (1=Yes, 0=No)"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="place_of_birth",
            field=models.CharField(
                blank=True, default="", help_text="Patient's place of birth", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mr", "Mr"),
                    ("Mrs", "Mrs"),
                    ("Miss", "Miss"),
                    ("Ms", "Ms"),
                    ("Dr", "Dr"),
                    ("Prof", "Prof"),
                    ("Hon", "Hon"),
                    ("Rev", "Rev"),
                    ("", "None"),
                ],
                default="",
                help_text="Patient's title (Mr, Mrs, Miss, etc.)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="national_id",
            field=models.CharField(
                blank=True,
                help_text="Patient's national ID number (legacy)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["cr_number"], name="patients_pa_cr_numb_cb5244_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["identification_type", "identification_number"],
                name="patients_pa_identif_b1f10a_idx",
            ),
        ),
    ]
