# Generated by Django 5.2.9 on 2026-01-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0008_add_cr_and_identification_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="sha_number",
            field=models.CharField(
                blank=True,
                help_text="SHA member number for Social Health Authority coverage",
                max_length=50,
                null=True,
            ),
        ),
    ]
