# Generated by Django 5.2.9 on 2026-02-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0012_migrate_encounter_allergies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="identification_type",
            field=models.CharField(
                choices=[
                    ("national_id", "National ID"),
                    ("cr_number", "HIE Patient ID"),
                    ("mandate_number", "Mandate Number"),
                    ("alien_id", "Alien ID"),
                    ("kra_pin", "KRA PIN"),
                    ("temporary_id", "Temporary ID"),
                    ("passport", "Passport Number"),
                    ("birth_certificate", "Birth Certificate"),
                ],
                default="national_id",
                help_text="Type of identification document",
                max_length=20,
            ),
        ),
    ]
