# Generated by Django 5.2.11 on 2026-03-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0014_historicalpatient"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatient",
            name="cr_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When patient was last synced with the Client Registry",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="cr_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When patient was last synced with the Client Registry",
                null=True,
            ),
        ),
    ]
