# Generated by Django 5.2.11 on 2026-03-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_multitenancy_clinical_fks"),
        ("patients", "0015_add_cr_synced_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergy",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization. Allergies are shared across org facilities.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allergies",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Owning organization (tenant). Patient is visible across all org facilities.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="registered_at_facility",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Facility where the patient was first registered.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant). Patient is visible across all org facilities.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="registered_at_facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where the patient was first registered.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_patients",
                to="core.facility",
            ),
        ),
    ]
