# Generated by Django 5.2.13 on 2026-05-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0020_add_principal_national_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencycontact",
            name="alternative_phone_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted alternative_phone"
            ),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="phone_number_encrypted",
            field=models.TextField(blank=True, default="", help_text="KMS-encrypted phone_number"),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="address_encrypted",
            field=models.TextField(blank=True, default="", help_text="KMS-encrypted address"),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="email_encrypted",
            field=models.TextField(blank=True, default="", help_text="KMS-encrypted email"),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="identification_number_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted identification_number"
            ),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="identification_number_hmac",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="HMAC blind index for identification_number lookup",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="national_id_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted national_id (legacy)"
            ),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="phone_number_encrypted",
            field=models.TextField(blank=True, default="", help_text="KMS-encrypted phone_number"),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="phone_number_hmac",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="HMAC blind index for phone_number lookup",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="principal_national_id_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted principal_national_id"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="address_encrypted",
            field=models.TextField(blank=True, default="", help_text="KMS-encrypted address"),
        ),
        migrations.AddField(
            model_name="patient",
            name="email_encrypted",
            field=models.TextField(blank=True, default="", help_text="KMS-encrypted email"),
        ),
        migrations.AddField(
            model_name="patient",
            name="identification_number_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted identification_number"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="identification_number_hmac",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="HMAC blind index for identification_number lookup",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="national_id_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted national_id (legacy)"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_number_encrypted",
            field=models.TextField(blank=True, default="", help_text="KMS-encrypted phone_number"),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_number_hmac",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="HMAC blind index for phone_number lookup",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="principal_national_id_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted principal_national_id"
            ),
        ),
    ]
