# Generated by Django 5.2.13 on 2026-05-13 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_add_hwr_national_id_and_last_verified"),
        ("patients", "0022_add_national_id_hmac"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="patient",
            name="unique_patient_identification",
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identification_number_hmac", ""), _negated=True),
                fields=("identification_type", "identification_number_hmac"),
                name="unique_patient_identification",
            ),
        ),
    ]
