# Generated by Django 5.2.13 on 2026-07-14 19:09

import uuid
from django.db import migrations, models


def backfill_patient_public_ids(apps, schema_editor):
    Patient = apps.get_model("patients", "Patient")
    HistoricalPatient = apps.get_model("patients", "HistoricalPatient")

    for patient_id in Patient.objects.filter(public_id__isnull=True).values_list("id", flat=True).iterator(
        chunk_size=1000
    ):
        Patient.objects.filter(id=patient_id, public_id__isnull=True).update(public_id=uuid.uuid4())

    for snapshot_id in HistoricalPatient.objects.filter(public_id__isnull=True).values_list(
        "id", flat=True
    ).iterator(chunk_size=2000):
        HistoricalPatient.objects.filter(id=snapshot_id, public_id__isnull=True).update(
            public_id=uuid.uuid4()
        )


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0024_phase_d_drop_pii_plaintext"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpatient",
            name="public_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="public_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_patient_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="historicalpatient",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                unique=True,
            ),
        ),
    ]
