# Generated by Django 5.2.13 on 2026-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0025_historicalpatient_public_id_patient_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpatient",
            name="identification_type",
            field=models.CharField(
                choices=[
                    ("national_id", "National ID"),
                    ("cr_number", "CR ID"),
                    ("mandate_number", "Mandate Number"),
                    ("alien_id", "Alien ID"),
                    ("kra_pin", "KRA PIN"),
                    ("temporary_id", "Temporary ID"),
                    ("passport", "Passport Number"),
                    ("birth_certificate", "Birth Certificate Number"),
                ],
                default="national_id",
                help_text="Type of identification document",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="identification_type",
            field=models.CharField(
                choices=[
                    ("national_id", "National ID"),
                    ("cr_number", "CR ID"),
                    ("mandate_number", "Mandate Number"),
                    ("alien_id", "Alien ID"),
                    ("kra_pin", "KRA PIN"),
                    ("temporary_id", "Temporary ID"),
                    ("passport", "Passport Number"),
                    ("birth_certificate", "Birth Certificate Number"),
                ],
                default="national_id",
                help_text="Type of identification document",
                max_length=20,
            ),
        ),
    ]
