# Generated by Django 5.2.9 on 2026-02-25 19:27

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import hmis.apps.core.history
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0021_change_imaging_order_on_delete"),
        ("clinics", "0009_add_unique_active_patient_per_session"),
        ("encounters", "0023_historicaldiagnosis_historicalencounter"),
        ("patients", "0014_historicalpatient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalNutritionConsultation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "consultation_number",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated consultation number",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Review"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "referral_reason",
                    models.CharField(
                        choices=[
                            ("WEIGHT_MANAGEMENT", "Weight Management"),
                            ("DIABETES", "Diabetes Management"),
                            ("CARDIOVASCULAR", "Cardiovascular Disease"),
                            ("RENAL", "Renal Disease/CKD"),
                            ("GI_DISORDERS", "GI Disorders"),
                            ("EATING_DISORDER", "Eating Disorder"),
                            ("MALNUTRITION", "Malnutrition (SAM/MAM)"),
                            ("PREGNANCY", "Pregnancy/Prenatal"),
                            ("PEDIATRIC", "Pediatric Nutrition"),
                            ("ONCOLOGY", "Oncology Support"),
                            ("FOOD_ALLERGY", "Food Allergy Management"),
                            ("TUBE_FEEDING", "Tube Feeding/Enteral Nutrition"),
                            ("TPN", "Total Parenteral Nutrition"),
                            ("SPORTS", "Sports Nutrition"),
                            ("GENERAL", "General Nutrition Counseling"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                (
                    "referral_notes",
                    models.TextField(blank=True, help_text="Additional referral details"),
                ),
                ("diagnosis", models.TextField(blank=True, help_text="Relevant diagnoses")),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("500")),
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in cm",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("20")),
                            django.core.validators.MaxValueValidator(Decimal("300")),
                        ],
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        editable=False,
                        help_text="Calculated BMI (kg/m²)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "bmi_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNDERWEIGHT_SEVERE", "Severe Underweight (<16.0)"),
                            ("UNDERWEIGHT_MODERATE", "Moderate Underweight (16.0-16.9)"),
                            ("UNDERWEIGHT_MILD", "Mild Underweight (17.0-18.4)"),
                            ("NORMAL", "Normal Weight (18.5-24.9)"),
                            ("OVERWEIGHT", "Overweight (25.0-29.9)"),
                            ("OBESE_CLASS_I", "Obese Class I (30.0-34.9)"),
                            ("OBESE_CLASS_II", "Obese Class II (35.0-39.9)"),
                            ("OBESE_CLASS_III", "Obese Class III (≥40.0)"),
                        ],
                        editable=False,
                        max_length=30,
                    ),
                ),
                (
                    "waist_circumference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Waist circumference in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "hip_circumference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hip circumference in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "waist_hip_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated waist-to-hip ratio",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "mid_upper_arm_circumference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="MUAC in cm (important for malnutrition screening)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("5")),
                            django.core.validators.MaxValueValidator(Decimal("60")),
                        ],
                    ),
                ),
                (
                    "triceps_skinfold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Triceps skinfold thickness in mm",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "ideal_body_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated ideal body weight in kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "percent_ideal_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        editable=False,
                        help_text="Percentage of ideal body weight",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "nutritional_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WELL_NOURISHED", "Well Nourished"),
                            ("MILD_MALNUTRITION", "Mild Malnutrition"),
                            ("MODERATE_MALNUTRITION", "Moderate Malnutrition"),
                            ("SEVERE_MALNUTRITION", "Severe Malnutrition"),
                            ("OVERNUTRITION", "Over-nutrition"),
                            ("AT_RISK", "At Nutritional Risk"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("SEDENTARY", "Sedentary (little/no exercise)"),
                            ("LIGHT", "Light (1-3 days/week)"),
                            ("MODERATE", "Moderate (3-5 days/week)"),
                            ("ACTIVE", "Active (6-7 days/week)"),
                            ("VERY_ACTIVE", "Very Active (intense exercise daily)"),
                        ],
                        default="SEDENTARY",
                        max_length=20,
                    ),
                ),
                (
                    "dietary_history",
                    models.TextField(blank=True, help_text="Current dietary patterns and habits"),
                ),
                (
                    "food_preferences",
                    models.TextField(
                        blank=True, help_text="Food preferences and cultural considerations"
                    ),
                ),
                (
                    "food_allergies",
                    models.TextField(blank=True, help_text="Known food allergies and intolerances"),
                ),
                (
                    "food_intolerances",
                    models.TextField(
                        blank=True, help_text="Food intolerances (lactose, gluten, etc.)"
                    ),
                ),
                (
                    "current_diet",
                    models.TextField(blank=True, help_text="Description of current diet"),
                ),
                (
                    "meals_per_day",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of meals per day",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "snacks_per_day",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of snacks per day",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "fluid_intake",
                    models.CharField(
                        blank=True, help_text="Estimated daily fluid intake", max_length=100
                    ),
                ),
                (
                    "alcohol_consumption",
                    models.CharField(
                        blank=True, help_text="Alcohol consumption patterns", max_length=100
                    ),
                ),
                (
                    "supplement_use",
                    models.TextField(blank=True, help_text="Current supplements being taken"),
                ),
                (
                    "basal_metabolic_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated BMR in kcal/day",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "total_daily_energy_expenditure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated TDEE in kcal/day",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "recommended_calories",
                    models.PositiveIntegerField(
                        blank=True, help_text="Recommended daily caloric intake", null=True
                    ),
                ),
                (
                    "recommended_protein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Recommended daily protein in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recommended_carbs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Recommended daily carbohydrates in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recommended_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Recommended daily fat in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "clinical_signs",
                    models.TextField(
                        blank=True, help_text="Clinical signs of nutritional deficiencies"
                    ),
                ),
                (
                    "lab_results_summary",
                    models.TextField(
                        blank=True,
                        help_text="Relevant laboratory results (albumin, prealbumin, etc.)",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(blank=True, help_text="Relevant medical history"),
                ),
                (
                    "medications",
                    models.TextField(
                        blank=True, help_text="Current medications that may affect nutrition"
                    ),
                ),
                (
                    "gi_symptoms",
                    models.TextField(
                        blank=True,
                        help_text="GI symptoms (nausea, vomiting, diarrhea, constipation)",
                    ),
                ),
                (
                    "appetite_assessment",
                    models.CharField(
                        blank=True, help_text="Good, Fair, Poor, Very Poor", max_length=50
                    ),
                ),
                (
                    "chewing_swallowing",
                    models.TextField(
                        blank=True, help_text="Assessment of chewing/swallowing ability"
                    ),
                ),
                (
                    "nutrition_goals",
                    models.TextField(blank=True, help_text="Nutrition intervention goals"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, help_text="Detailed nutrition recommendations"),
                ),
                (
                    "education_provided",
                    models.TextField(blank=True, help_text="Education topics covered"),
                ),
                (
                    "follow_up_plan",
                    models.TextField(blank=True, help_text="Follow-up recommendations"),
                ),
                (
                    "follow_up_date",
                    models.DateField(blank=True, help_text="Recommended follow-up date", null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("consultation_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sha_claimable", models.BooleanField(default=True)),
                (
                    "sha_intervention_code",
                    models.CharField(
                        blank=True, help_text="SHA intervention code for claims", max_length=50
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "dietitian",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Assigned dietitian/nutritionist",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="billing.invoice",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patients.patient",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Nutrition Consultation",
                "verbose_name_plural": "historical Nutrition Consultations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="NutritionConsultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "consultation_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated consultation number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Review"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "referral_reason",
                    models.CharField(
                        choices=[
                            ("WEIGHT_MANAGEMENT", "Weight Management"),
                            ("DIABETES", "Diabetes Management"),
                            ("CARDIOVASCULAR", "Cardiovascular Disease"),
                            ("RENAL", "Renal Disease/CKD"),
                            ("GI_DISORDERS", "GI Disorders"),
                            ("EATING_DISORDER", "Eating Disorder"),
                            ("MALNUTRITION", "Malnutrition (SAM/MAM)"),
                            ("PREGNANCY", "Pregnancy/Prenatal"),
                            ("PEDIATRIC", "Pediatric Nutrition"),
                            ("ONCOLOGY", "Oncology Support"),
                            ("FOOD_ALLERGY", "Food Allergy Management"),
                            ("TUBE_FEEDING", "Tube Feeding/Enteral Nutrition"),
                            ("TPN", "Total Parenteral Nutrition"),
                            ("SPORTS", "Sports Nutrition"),
                            ("GENERAL", "General Nutrition Counseling"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                (
                    "referral_notes",
                    models.TextField(blank=True, help_text="Additional referral details"),
                ),
                ("diagnosis", models.TextField(blank=True, help_text="Relevant diagnoses")),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("500")),
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in cm",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("20")),
                            django.core.validators.MaxValueValidator(Decimal("300")),
                        ],
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        editable=False,
                        help_text="Calculated BMI (kg/m²)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "bmi_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNDERWEIGHT_SEVERE", "Severe Underweight (<16.0)"),
                            ("UNDERWEIGHT_MODERATE", "Moderate Underweight (16.0-16.9)"),
                            ("UNDERWEIGHT_MILD", "Mild Underweight (17.0-18.4)"),
                            ("NORMAL", "Normal Weight (18.5-24.9)"),
                            ("OVERWEIGHT", "Overweight (25.0-29.9)"),
                            ("OBESE_CLASS_I", "Obese Class I (30.0-34.9)"),
                            ("OBESE_CLASS_II", "Obese Class II (35.0-39.9)"),
                            ("OBESE_CLASS_III", "Obese Class III (≥40.0)"),
                        ],
                        editable=False,
                        max_length=30,
                    ),
                ),
                (
                    "waist_circumference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Waist circumference in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "hip_circumference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hip circumference in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "waist_hip_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated waist-to-hip ratio",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "mid_upper_arm_circumference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="MUAC in cm (important for malnutrition screening)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("5")),
                            django.core.validators.MaxValueValidator(Decimal("60")),
                        ],
                    ),
                ),
                (
                    "triceps_skinfold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Triceps skinfold thickness in mm",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "ideal_body_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated ideal body weight in kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "percent_ideal_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        editable=False,
                        help_text="Percentage of ideal body weight",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "nutritional_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WELL_NOURISHED", "Well Nourished"),
                            ("MILD_MALNUTRITION", "Mild Malnutrition"),
                            ("MODERATE_MALNUTRITION", "Moderate Malnutrition"),
                            ("SEVERE_MALNUTRITION", "Severe Malnutrition"),
                            ("OVERNUTRITION", "Over-nutrition"),
                            ("AT_RISK", "At Nutritional Risk"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("SEDENTARY", "Sedentary (little/no exercise)"),
                            ("LIGHT", "Light (1-3 days/week)"),
                            ("MODERATE", "Moderate (3-5 days/week)"),
                            ("ACTIVE", "Active (6-7 days/week)"),
                            ("VERY_ACTIVE", "Very Active (intense exercise daily)"),
                        ],
                        default="SEDENTARY",
                        max_length=20,
                    ),
                ),
                (
                    "dietary_history",
                    models.TextField(blank=True, help_text="Current dietary patterns and habits"),
                ),
                (
                    "food_preferences",
                    models.TextField(
                        blank=True, help_text="Food preferences and cultural considerations"
                    ),
                ),
                (
                    "food_allergies",
                    models.TextField(blank=True, help_text="Known food allergies and intolerances"),
                ),
                (
                    "food_intolerances",
                    models.TextField(
                        blank=True, help_text="Food intolerances (lactose, gluten, etc.)"
                    ),
                ),
                (
                    "current_diet",
                    models.TextField(blank=True, help_text="Description of current diet"),
                ),
                (
                    "meals_per_day",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of meals per day",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "snacks_per_day",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of snacks per day",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "fluid_intake",
                    models.CharField(
                        blank=True, help_text="Estimated daily fluid intake", max_length=100
                    ),
                ),
                (
                    "alcohol_consumption",
                    models.CharField(
                        blank=True, help_text="Alcohol consumption patterns", max_length=100
                    ),
                ),
                (
                    "supplement_use",
                    models.TextField(blank=True, help_text="Current supplements being taken"),
                ),
                (
                    "basal_metabolic_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated BMR in kcal/day",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "total_daily_energy_expenditure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculated TDEE in kcal/day",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "recommended_calories",
                    models.PositiveIntegerField(
                        blank=True, help_text="Recommended daily caloric intake", null=True
                    ),
                ),
                (
                    "recommended_protein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Recommended daily protein in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recommended_carbs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Recommended daily carbohydrates in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recommended_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Recommended daily fat in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "clinical_signs",
                    models.TextField(
                        blank=True, help_text="Clinical signs of nutritional deficiencies"
                    ),
                ),
                (
                    "lab_results_summary",
                    models.TextField(
                        blank=True,
                        help_text="Relevant laboratory results (albumin, prealbumin, etc.)",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(blank=True, help_text="Relevant medical history"),
                ),
                (
                    "medications",
                    models.TextField(
                        blank=True, help_text="Current medications that may affect nutrition"
                    ),
                ),
                (
                    "gi_symptoms",
                    models.TextField(
                        blank=True,
                        help_text="GI symptoms (nausea, vomiting, diarrhea, constipation)",
                    ),
                ),
                (
                    "appetite_assessment",
                    models.CharField(
                        blank=True, help_text="Good, Fair, Poor, Very Poor", max_length=50
                    ),
                ),
                (
                    "chewing_swallowing",
                    models.TextField(
                        blank=True, help_text="Assessment of chewing/swallowing ability"
                    ),
                ),
                (
                    "nutrition_goals",
                    models.TextField(blank=True, help_text="Nutrition intervention goals"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, help_text="Detailed nutrition recommendations"),
                ),
                (
                    "education_provided",
                    models.TextField(blank=True, help_text="Education topics covered"),
                ),
                (
                    "follow_up_plan",
                    models.TextField(blank=True, help_text="Follow-up recommendations"),
                ),
                (
                    "follow_up_date",
                    models.DateField(blank=True, help_text="Recommended follow-up date", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("consultation_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sha_claimable", models.BooleanField(default=True)),
                (
                    "sha_intervention_code",
                    models.CharField(
                        blank=True, help_text="SHA intervention code for claims", max_length=50
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nutrition_consultations",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "dietitian",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned dietitian/nutritionist",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nutrition_consultations_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nutrition_consultations",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nutrition_consultations",
                        to="billing.invoice",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nutrition_consultations",
                        to="patients.patient",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nutrition_referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutrition Consultation",
                "verbose_name_plural": "Nutrition Consultations",
                "ordering": ["-consultation_date"],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDietPlan",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "plan_number",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated diet plan number",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(help_text="Name/title of the diet plan", max_length=200)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("THERAPEUTIC", "Therapeutic Diet"),
                            ("WEIGHT_LOSS", "Weight Loss"),
                            ("WEIGHT_GAIN", "Weight Gain"),
                            ("DIABETIC", "Diabetic Diet"),
                            ("RENAL", "Renal Diet"),
                            ("CARDIAC", "Cardiac/Heart Healthy"),
                            ("LOW_SODIUM", "Low Sodium"),
                            ("LOW_FAT", "Low Fat"),
                            ("HIGH_PROTEIN", "High Protein"),
                            ("HIGH_FIBER", "High Fiber"),
                            ("GLUTEN_FREE", "Gluten-Free"),
                            ("LACTOSE_FREE", "Lactose-Free"),
                            ("ENTERAL", "Enteral Nutrition"),
                            ("PARENTERAL", "Parenteral Nutrition"),
                            ("PREGNANCY", "Pregnancy/Prenatal"),
                            ("PEDIATRIC", "Pediatric"),
                            ("GERIATRIC", "Geriatric"),
                            ("VEGETARIAN", "Vegetarian"),
                            ("VEGAN", "Vegan"),
                            ("GENERAL_HEALTHY", "General Healthy Eating"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL_HEALTHY",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("DISCONTINUED", "Discontinued"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Overview of the diet plan"),
                ),
                ("goals", models.TextField(blank=True, help_text="Goals of this diet plan")),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "duration_value",
                    models.PositiveIntegerField(blank=True, help_text="Duration number", null=True),
                ),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[
                            ("DAYS", "Days"),
                            ("WEEKS", "Weeks"),
                            ("MONTHS", "Months"),
                            ("INDEFINITE", "Indefinite"),
                        ],
                        default="WEEKS",
                        max_length=20,
                    ),
                ),
                (
                    "meal_plan",
                    models.TextField(blank=True, help_text="Detailed meal plan description"),
                ),
                (
                    "breakfast_guidelines",
                    models.TextField(blank=True, help_text="Breakfast recommendations"),
                ),
                (
                    "lunch_guidelines",
                    models.TextField(blank=True, help_text="Lunch recommendations"),
                ),
                (
                    "dinner_guidelines",
                    models.TextField(blank=True, help_text="Dinner recommendations"),
                ),
                (
                    "snack_guidelines",
                    models.TextField(blank=True, help_text="Snack recommendations"),
                ),
                ("sample_menu", models.TextField(blank=True, help_text="Sample daily menu")),
                (
                    "portion_guidelines",
                    models.TextField(blank=True, help_text="Portion size guidelines"),
                ),
                (
                    "target_calories",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily caloric target", null=True
                    ),
                ),
                (
                    "target_protein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Daily protein target in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_carbs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Daily carbohydrate target in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Daily fat target in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_fiber",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Daily fiber target in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_sodium",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily sodium limit in mg", null=True
                    ),
                ),
                (
                    "target_fluid",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily fluid target in ml", null=True
                    ),
                ),
                (
                    "restrictions",
                    models.TextField(blank=True, help_text="General dietary restrictions"),
                ),
                (
                    "foods_to_avoid",
                    models.TextField(blank=True, help_text="Specific foods to avoid"),
                ),
                (
                    "foods_to_limit",
                    models.TextField(blank=True, help_text="Foods to limit/moderate"),
                ),
                (
                    "foods_to_include",
                    models.TextField(blank=True, help_text="Foods to include/encourage"),
                ),
                (
                    "allergen_restrictions",
                    models.TextField(blank=True, help_text="Allergen-specific restrictions"),
                ),
                (
                    "texture_modifications",
                    models.CharField(
                        blank=True,
                        help_text="Texture modifications (pureed, soft, etc.)",
                        max_length=100,
                    ),
                ),
                ("supplements", models.TextField(blank=True, help_text="Recommended supplements")),
                (
                    "oral_nutrition_supplements",
                    models.TextField(
                        blank=True, help_text="ONS recommendations (e.g., Ensure, Glucerna)"
                    ),
                ),
                (
                    "vitamin_supplements",
                    models.TextField(blank=True, help_text="Vitamin supplementation"),
                ),
                (
                    "mineral_supplements",
                    models.TextField(blank=True, help_text="Mineral supplementation"),
                ),
                (
                    "special_instructions",
                    models.TextField(blank=True, help_text="Additional special instructions"),
                ),
                (
                    "food_preparation_notes",
                    models.TextField(blank=True, help_text="Notes on food preparation"),
                ),
                (
                    "timing_instructions",
                    models.TextField(blank=True, help_text="Meal timing instructions"),
                ),
                (
                    "hydration_instructions",
                    models.TextField(blank=True, help_text="Hydration guidance"),
                ),
                (
                    "monitoring_parameters",
                    models.TextField(
                        blank=True, help_text="Parameters to monitor (weight, labs, etc.)"
                    ),
                ),
                (
                    "target_outcomes",
                    models.TextField(blank=True, help_text="Expected outcomes/targets"),
                ),
                (
                    "review_date",
                    models.DateField(blank=True, help_text="Next review date", null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("discontinued_at", models.DateTimeField(blank=True, null=True)),
                ("discontinuation_reason", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="nutrition.nutritionconsultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Diet Plan",
                "verbose_name_plural": "historical Diet Plans",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "plan_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated diet plan number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Name/title of the diet plan", max_length=200)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("THERAPEUTIC", "Therapeutic Diet"),
                            ("WEIGHT_LOSS", "Weight Loss"),
                            ("WEIGHT_GAIN", "Weight Gain"),
                            ("DIABETIC", "Diabetic Diet"),
                            ("RENAL", "Renal Diet"),
                            ("CARDIAC", "Cardiac/Heart Healthy"),
                            ("LOW_SODIUM", "Low Sodium"),
                            ("LOW_FAT", "Low Fat"),
                            ("HIGH_PROTEIN", "High Protein"),
                            ("HIGH_FIBER", "High Fiber"),
                            ("GLUTEN_FREE", "Gluten-Free"),
                            ("LACTOSE_FREE", "Lactose-Free"),
                            ("ENTERAL", "Enteral Nutrition"),
                            ("PARENTERAL", "Parenteral Nutrition"),
                            ("PREGNANCY", "Pregnancy/Prenatal"),
                            ("PEDIATRIC", "Pediatric"),
                            ("GERIATRIC", "Geriatric"),
                            ("VEGETARIAN", "Vegetarian"),
                            ("VEGAN", "Vegan"),
                            ("GENERAL_HEALTHY", "General Healthy Eating"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL_HEALTHY",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("DISCONTINUED", "Discontinued"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Overview of the diet plan"),
                ),
                ("goals", models.TextField(blank=True, help_text="Goals of this diet plan")),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "duration_value",
                    models.PositiveIntegerField(blank=True, help_text="Duration number", null=True),
                ),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[
                            ("DAYS", "Days"),
                            ("WEEKS", "Weeks"),
                            ("MONTHS", "Months"),
                            ("INDEFINITE", "Indefinite"),
                        ],
                        default="WEEKS",
                        max_length=20,
                    ),
                ),
                (
                    "meal_plan",
                    models.TextField(blank=True, help_text="Detailed meal plan description"),
                ),
                (
                    "breakfast_guidelines",
                    models.TextField(blank=True, help_text="Breakfast recommendations"),
                ),
                (
                    "lunch_guidelines",
                    models.TextField(blank=True, help_text="Lunch recommendations"),
                ),
                (
                    "dinner_guidelines",
                    models.TextField(blank=True, help_text="Dinner recommendations"),
                ),
                (
                    "snack_guidelines",
                    models.TextField(blank=True, help_text="Snack recommendations"),
                ),
                ("sample_menu", models.TextField(blank=True, help_text="Sample daily menu")),
                (
                    "portion_guidelines",
                    models.TextField(blank=True, help_text="Portion size guidelines"),
                ),
                (
                    "target_calories",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily caloric target", null=True
                    ),
                ),
                (
                    "target_protein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Daily protein target in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_carbs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Daily carbohydrate target in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Daily fat target in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_fiber",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Daily fiber target in grams",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_sodium",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily sodium limit in mg", null=True
                    ),
                ),
                (
                    "target_fluid",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily fluid target in ml", null=True
                    ),
                ),
                (
                    "restrictions",
                    models.TextField(blank=True, help_text="General dietary restrictions"),
                ),
                (
                    "foods_to_avoid",
                    models.TextField(blank=True, help_text="Specific foods to avoid"),
                ),
                (
                    "foods_to_limit",
                    models.TextField(blank=True, help_text="Foods to limit/moderate"),
                ),
                (
                    "foods_to_include",
                    models.TextField(blank=True, help_text="Foods to include/encourage"),
                ),
                (
                    "allergen_restrictions",
                    models.TextField(blank=True, help_text="Allergen-specific restrictions"),
                ),
                (
                    "texture_modifications",
                    models.CharField(
                        blank=True,
                        help_text="Texture modifications (pureed, soft, etc.)",
                        max_length=100,
                    ),
                ),
                ("supplements", models.TextField(blank=True, help_text="Recommended supplements")),
                (
                    "oral_nutrition_supplements",
                    models.TextField(
                        blank=True, help_text="ONS recommendations (e.g., Ensure, Glucerna)"
                    ),
                ),
                (
                    "vitamin_supplements",
                    models.TextField(blank=True, help_text="Vitamin supplementation"),
                ),
                (
                    "mineral_supplements",
                    models.TextField(blank=True, help_text="Mineral supplementation"),
                ),
                (
                    "special_instructions",
                    models.TextField(blank=True, help_text="Additional special instructions"),
                ),
                (
                    "food_preparation_notes",
                    models.TextField(blank=True, help_text="Notes on food preparation"),
                ),
                (
                    "timing_instructions",
                    models.TextField(blank=True, help_text="Meal timing instructions"),
                ),
                (
                    "hydration_instructions",
                    models.TextField(blank=True, help_text="Hydration guidance"),
                ),
                (
                    "monitoring_parameters",
                    models.TextField(
                        blank=True, help_text="Parameters to monitor (weight, labs, etc.)"
                    ),
                ),
                (
                    "target_outcomes",
                    models.TextField(blank=True, help_text="Expected outcomes/targets"),
                ),
                (
                    "review_date",
                    models.DateField(blank=True, help_text="Next review date", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("discontinued_at", models.DateTimeField(blank=True, null=True)),
                ("discontinuation_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diet_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diet_plans",
                        to="patients.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diet_plans_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diet_plans",
                        to="nutrition.nutritionconsultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diet Plan",
                "verbose_name_plural": "Diet Plans",
                "ordering": ["-created_at"],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="nutritionconsultation",
            index=models.Index(
                fields=["consultation_number"], name="nutrition_n_consult_65ebc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nutritionconsultation",
            index=models.Index(fields=["patient", "status"], name="nutrition_n_patient_2904f9_idx"),
        ),
        migrations.AddIndex(
            model_name="nutritionconsultation",
            index=models.Index(
                fields=["dietitian", "status"], name="nutrition_n_dietiti_163579_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nutritionconsultation",
            index=models.Index(fields=["consultation_date"], name="nutrition_n_consult_ca1440_idx"),
        ),
        migrations.AddIndex(
            model_name="dietplan",
            index=models.Index(fields=["plan_number"], name="nutrition_d_plan_nu_c8825b_idx"),
        ),
        migrations.AddIndex(
            model_name="dietplan",
            index=models.Index(fields=["patient", "status"], name="nutrition_d_patient_eb039c_idx"),
        ),
        migrations.AddIndex(
            model_name="dietplan",
            index=models.Index(
                fields=["start_date", "end_date"], name="nutrition_d_start_d_11b1dc_idx"
            ),
        ),
    ]
