# Generated by Django 5.2.13 on 2026-07-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0005_remove_nutritionconsultation_sha_claimable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalnutritionconsultation",
            name="sha_claimable",
        ),
    ]
