# Generated by Django 5.2.13 on 2026-04-20 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0044_cross_org_join_request"),
        ("encounters", "0027_facility_scoped_model_fix"),
        ("inpatient", "0039_facility_scoped_model_fix"),
        ("patients", "0017_death_record"),
        ("pharmacy", "0023_facility_scoped_model_fix"),
        ("procedures", "0006_procedurecatalog_anesthesia_fee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnesthesiaRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pre_op_assessment_at", models.DateTimeField(blank=True, null=True)),
                ("mallampati_class", models.CharField(blank=True, default="", max_length=5)),
                ("mouth_opening", models.CharField(blank=True, default="", max_length=50)),
                ("neck_mobility", models.CharField(blank=True, default="", max_length=50)),
                ("dentition_notes", models.TextField(blank=True, default="")),
                ("last_solid_food", models.DateTimeField(blank=True, null=True)),
                ("last_clear_fluids", models.DateTimeField(blank=True, null=True)),
                ("npo_confirmed", models.BooleanField(default=False)),
                ("premedication_given", models.TextField(blank=True, default="")),
                ("anesthesia_consent_obtained", models.BooleanField(default=False)),
                ("risks_explained", models.BooleanField(default=False)),
                ("induction_time", models.DateTimeField(blank=True, null=True)),
                ("intubation_time", models.DateTimeField(blank=True, null=True)),
                ("extubation_time", models.DateTimeField(blank=True, null=True)),
                ("airway_device", models.CharField(blank=True, default="", max_length=100)),
                ("tube_size", models.CharField(blank=True, default="", max_length=20)),
                ("intubation_attempts", models.IntegerField(default=1)),
                ("intubation_difficulty", models.TextField(blank=True, default="")),
                ("anesthesia_technique", models.TextField(blank=True, default="")),
                ("induction_agents", models.TextField(blank=True, default="")),
                ("maintenance_agents", models.TextField(blank=True, default="")),
                ("muscle_relaxants", models.TextField(blank=True, default="")),
                ("reversal_agents", models.TextField(blank=True, default="")),
                ("crystalloid_volume", models.IntegerField(default=0, help_text="mL")),
                ("colloid_volume", models.IntegerField(default=0, help_text="mL")),
                ("blood_products", models.TextField(blank=True, default="")),
                ("estimated_blood_loss", models.IntegerField(default=0, help_text="mL")),
                ("urine_output", models.IntegerField(default=0, help_text="mL")),
                ("intraop_complications", models.TextField(blank=True, default="")),
                ("pacu_handover_at", models.DateTimeField(blank=True, null=True)),
                ("pacu_handover_notes", models.TextField(blank=True, default="")),
                ("pain_management_plan", models.TextField(blank=True, default="")),
                ("post_op_nausea_plan", models.TextField(blank=True, default="")),
                ("other_post_op_orders", models.TextField(blank=True, default="")),
                (
                    "anesthesiologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anesthesia_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anesthesia Record",
                "verbose_name_plural": "Anesthesia Records",
            },
        ),
        migrations.CreateModel(
            name="IntraOpVitalReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_at", models.DateTimeField()),
                ("systolic_bp", models.IntegerField(blank=True, null=True)),
                ("diastolic_bp", models.IntegerField(blank=True, null=True)),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("respiratory_rate", models.IntegerField(blank=True, null=True)),
                (
                    "spo2",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("etco2", models.IntegerField(blank=True, help_text="End-tidal CO2", null=True)),
                (
                    "fio2",
                    models.IntegerField(
                        blank=True, help_text="Fraction of inspired O2 (%)", null=True
                    ),
                ),
                ("tidal_volume", models.IntegerField(blank=True, help_text="mL", null=True)),
                ("peak_pressure", models.IntegerField(blank=True, help_text="cmH2O", null=True)),
                (
                    "temperature",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "anesthesia_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_readings",
                        to="theatre.anesthesiarecord",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intraop_vital_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intra-Op Vital Reading",
                "verbose_name_plural": "Intra-Op Vital Readings",
                "ordering": ["recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="OperatingTheatre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(help_text='e.g. "OT-01"', max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "theatre_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Surgery"),
                            ("ORTHO", "Orthopedic"),
                            ("CARDIAC", "Cardiac Surgery"),
                            ("NEURO", "Neurosurgery"),
                            ("EYE", "Ophthalmology"),
                            ("ENT", "ENT Surgery"),
                            ("OBSTETRIC", "Obstetric/Gynecology"),
                            ("PEDIATRIC", "Pediatric Surgery"),
                            ("EMERGENCY", "Emergency/Trauma"),
                            ("MINOR", "Minor Procedures"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                ("has_laminar_flow", models.BooleanField(default=False)),
                ("has_cath_lab", models.BooleanField(default=False)),
                ("has_image_intensifier", models.BooleanField(default=False)),
                ("equipment_notes", models.TextField(blank=True, default="")),
                ("operating_hours_start", models.TimeField(default="08:00")),
                ("operating_hours_end", models.TimeField(default="18:00")),
                ("slot_duration_minutes", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("maintenance_notes", models.TextField(blank=True, default="")),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operating Theatre",
                "verbose_name_plural": "Operating Theatres",
                "ordering": ["code"],
                "unique_together": {("facility", "code")},
            },
        ),
        migrations.CreateModel(
            name="PACURecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("arrival_time", models.DateTimeField()),
                ("initial_aldrete_score", models.IntegerField(help_text="0-10 Aldrete score")),
                (
                    "initial_pain_score",
                    models.IntegerField(blank=True, help_text="0-10 NRS pain score", null=True),
                ),
                ("discharge_time", models.DateTimeField(blank=True, null=True)),
                ("discharge_aldrete_score", models.IntegerField(blank=True, null=True)),
                (
                    "discharge_destination",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WARD", "Ward"),
                            ("ICU", "ICU"),
                            ("DAY_CASE_DISCHARGE", "Day Case Discharge"),
                            ("EXTENDED_OBSERVATION", "Extended Observation"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("nausea_vomiting", models.BooleanField(default=False)),
                ("shivering", models.BooleanField(default=False)),
                ("respiratory_issues", models.BooleanField(default=False)),
                ("cardiovascular_issues", models.BooleanField(default=False)),
                ("complications_notes", models.TextField(blank=True, default="")),
                ("medications_given", models.TextField(blank=True, default="")),
                ("discharge_notes", models.TextField(blank=True, default="")),
                (
                    "arriving_nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pacu_arrivals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discharged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pacu_discharges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PACU Record",
                "verbose_name_plural": "PACU Records",
            },
        ),
        migrations.CreateModel(
            name="PACUVitalReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_at", models.DateTimeField()),
                ("systolic_bp", models.IntegerField(blank=True, null=True)),
                ("diastolic_bp", models.IntegerField(blank=True, null=True)),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("respiratory_rate", models.IntegerField(blank=True, null=True)),
                (
                    "spo2",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "temperature",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                ("aldrete_score", models.IntegerField(blank=True, null=True)),
                ("pain_score", models.IntegerField(blank=True, null=True)),
                ("sedation_level", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "pacu_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_readings",
                        to="theatre.pacurecord",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pacu_vital_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PACU Vital Reading",
                "verbose_name_plural": "PACU Vital Readings",
                "ordering": ["recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="SurgeryCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case_number", models.CharField(editable=False, max_length=30, unique=True)),
                ("procedure_notes", models.TextField(blank=True, default="")),
                ("scheduled_date", models.DateField()),
                ("scheduled_start_time", models.TimeField()),
                ("estimated_duration_minutes", models.IntegerField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ELECTIVE", "Elective"),
                            ("URGENT", "Urgent"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="ELECTIVE",
                        max_length=20,
                    ),
                ),
                ("diagnosis", models.TextField()),
                (
                    "laterality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEFT", "Left"),
                            ("RIGHT", "Right"),
                            ("BILATERAL", "Bilateral"),
                            ("NA", "Not Applicable"),
                        ],
                        default="NA",
                        max_length=20,
                    ),
                ),
                (
                    "asa_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "ASA I – Healthy"),
                            ("II", "ASA II – Mild systemic disease"),
                            ("III", "ASA III – Severe systemic disease"),
                            ("IV", "ASA IV – Life-threatening disease"),
                            ("V", "ASA V – Moribund"),
                            ("VI", "ASA VI – Brain dead donor"),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
                (
                    "anesthesia_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GENERAL", "General Anesthesia"),
                            ("SPINAL", "Spinal Anesthesia"),
                            ("EPIDURAL", "Epidural Anesthesia"),
                            ("REGIONAL", "Regional Block"),
                            ("LOCAL", "Local Anesthesia"),
                            ("SEDATION", "Sedation"),
                            ("COMBINED", "Combined"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("SCHEDULED", "Scheduled"),
                            ("PRE_OP", "Pre-Operative"),
                            ("IN_THEATRE", "In Theatre"),
                            ("IN_SURGERY", "Surgery In Progress"),
                            ("IN_PACU", "In Recovery (PACU)"),
                            ("DISCHARGED", "Discharged"),
                            ("POSTPONED", "Postponed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("postponed_to_date", models.DateField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("total_charges", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("is_billable", models.BooleanField(default=True)),
                (
                    "additional_procedures",
                    models.ManyToManyField(
                        blank=True,
                        related_name="secondary_surgery_cases",
                        to="procedures.procedurecatalog",
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgery_cases",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgery_cases",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgery_cases",
                        to="patients.patient",
                    ),
                ),
                (
                    "primary_procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_surgery_cases",
                        to="procedures.procedurecatalog",
                    ),
                ),
                (
                    "requesting_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgery_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgery_case_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theatre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgery_cases",
                        to="theatre.operatingtheatre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surgery Case",
                "verbose_name_plural": "Surgery Cases",
                "ordering": ["-scheduled_date", "-scheduled_start_time"],
                "permissions": [
                    ("manage_theatre", "Can manage theatre schedules and cases"),
                    ("document_surgery", "Can document operative notes"),
                ],
            },
        ),
        migrations.AddField(
            model_name="pacurecord",
            name="surgery_case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pacu_record",
                to="theatre.surgerycase",
            ),
        ),
        migrations.CreateModel(
            name="OperativeNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("incision_time", models.DateTimeField(blank=True, null=True)),
                ("closure_time", models.DateTimeField(blank=True, null=True)),
                ("pre_operative_diagnosis", models.TextField()),
                ("post_operative_diagnosis", models.TextField()),
                ("procedure_performed", models.TextField()),
                ("findings", models.TextField()),
                ("technique_description", models.TextField()),
                ("implants_used", models.TextField(blank=True, default="")),
                ("drains_placed", models.TextField(blank=True, default="")),
                ("sutures_used", models.TextField(blank=True, default="")),
                ("estimated_blood_loss", models.IntegerField(default=0)),
                ("specimens_sent", models.TextField(blank=True, default="")),
                ("frozen_section", models.BooleanField(default=False)),
                ("frozen_section_result", models.TextField(blank=True, default="")),
                ("intraoperative_complications", models.TextField(blank=True, default="")),
                ("post_operative_plan", models.TextField(blank=True, default="")),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dictated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dictated_operative_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_operative_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surgery_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operative_note",
                        to="theatre.surgerycase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operative Note",
                "verbose_name_plural": "Operative Notes",
            },
        ),
        migrations.AddField(
            model_name="anesthesiarecord",
            name="surgery_case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anesthesia_record",
                to="theatre.surgerycase",
            ),
        ),
        migrations.CreateModel(
            name="SurgicalTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEAD_SURGEON", "Lead Surgeon"),
                            ("ASSISTANT_SURGEON", "Assistant Surgeon"),
                            ("ANESTHESIOLOGIST", "Anesthesiologist"),
                            ("ANESTHESIA_TECH", "Anesthesia Technician"),
                            ("CIRCULATING_NURSE", "Circulating Nurse"),
                            ("SCRUB_NURSE", "Scrub Nurse"),
                            ("SCRUB_TECH", "Scrub Technician"),
                            ("RECOVERY_NURSE", "Recovery Nurse"),
                            ("OBSERVER", "Observer/Trainee"),
                        ],
                        max_length=30,
                    ),
                ),
                ("scrub_in_time", models.DateTimeField(blank=True, null=True)),
                ("scrub_out_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgical_team_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surgery_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="theatre.surgerycase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surgical Team Member",
                "verbose_name_plural": "Surgical Team Members",
                "ordering": ["role"],
            },
        ),
        migrations.CreateModel(
            name="TheatreConsumable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lot_number", models.CharField(blank=True, default="", max_length=50)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("quantity_used", models.IntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("is_implant", models.BooleanField(default=False)),
                ("implant_serial_number", models.CharField(blank=True, default="", max_length=100)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theatre_consumables_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theatre_consumables",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "surgery_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumables",
                        to="theatre.surgerycase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theatre Consumable",
                "verbose_name_plural": "Theatre Consumables",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="WHOSafetyChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sign_in_completed_at", models.DateTimeField(blank=True, null=True)),
                ("patient_identity_confirmed", models.BooleanField(default=False)),
                ("procedure_site_marked", models.BooleanField(default=False)),
                ("consent_signed", models.BooleanField(default=False)),
                ("anesthesia_machine_checked", models.BooleanField(default=False)),
                ("pulse_oximeter_attached", models.BooleanField(default=False)),
                ("allergies_reviewed", models.BooleanField(default=False)),
                ("allergy_notes", models.TextField(blank=True, default="")),
                ("difficult_airway_risk", models.BooleanField(default=False)),
                ("aspiration_risk", models.BooleanField(default=False)),
                ("airway_equipment_available", models.BooleanField(default=False)),
                ("blood_loss_risk", models.CharField(blank=True, default="", max_length=20)),
                ("iv_access_adequate", models.BooleanField(default=False)),
                ("blood_products_available", models.BooleanField(default=False)),
                ("time_out_completed_at", models.DateTimeField(blank=True, null=True)),
                ("team_members_introduced", models.BooleanField(default=False)),
                ("patient_name_confirmed", models.BooleanField(default=False)),
                ("procedure_confirmed", models.BooleanField(default=False)),
                ("site_confirmed", models.BooleanField(default=False)),
                ("surgeon_critical_steps_discussed", models.BooleanField(default=False)),
                ("anesthesia_concerns_discussed", models.BooleanField(default=False)),
                ("nursing_concerns_discussed", models.BooleanField(default=False)),
                ("prophylactic_antibiotics_given", models.BooleanField(default=False)),
                ("antibiotics_timing_within_60_min", models.BooleanField(default=False)),
                ("antibiotics_not_applicable", models.BooleanField(default=False)),
                ("essential_imaging_displayed", models.BooleanField(default=False)),
                ("imaging_not_applicable", models.BooleanField(default=False)),
                ("sign_out_completed_at", models.DateTimeField(blank=True, null=True)),
                ("procedure_name_recorded", models.BooleanField(default=False)),
                ("instrument_count_correct", models.BooleanField(default=False)),
                ("sponge_count_correct", models.BooleanField(default=False)),
                ("needle_count_correct", models.BooleanField(default=False)),
                ("specimens_labeled", models.BooleanField(default=False)),
                ("specimen_count", models.IntegerField(default=0)),
                ("equipment_problems_noted", models.BooleanField(default=False)),
                ("equipment_problems_description", models.TextField(blank=True, default="")),
                ("key_recovery_concerns", models.TextField(blank=True, default="")),
                (
                    "sign_in_completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="who_sign_ins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sign_out_completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="who_sign_outs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surgery_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="who_checklist",
                        to="theatre.surgerycase",
                    ),
                ),
                (
                    "time_out_completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="who_time_outs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WHO Safety Checklist",
                "verbose_name_plural": "WHO Safety Checklists",
            },
        ),
        migrations.AddIndex(
            model_name="surgerycase",
            index=models.Index(fields=["case_number"], name="theatre_sur_case_nu_84e057_idx"),
        ),
        migrations.AddIndex(
            model_name="surgerycase",
            index=models.Index(fields=["status"], name="theatre_sur_status_04312e_idx"),
        ),
        migrations.AddIndex(
            model_name="surgerycase",
            index=models.Index(fields=["scheduled_date"], name="theatre_sur_schedul_49d2d3_idx"),
        ),
        migrations.AddIndex(
            model_name="surgerycase",
            index=models.Index(
                fields=["facility", "status"], name="theatre_sur_facilit_909833_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surgerycase",
            index=models.Index(
                fields=["facility", "scheduled_date"], name="theatre_sur_facilit_4d39ee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surgicalteammember",
            unique_together={("surgery_case", "staff_member", "role")},
        ),
    ]
