# Generated by Django 5.2.13 on 2026-04-20 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatingtheatre",
            name="operating_hours_end",
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name="operatingtheatre",
            name="operating_hours_start",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
