# Generated by Django 5.2.13 on 2026-05-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_bank", "0002_add_rbac_permissions"),
        ("theatre", "0008_intraop_vital_extended_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="anesthesiarecord",
            name="blood_issues",
            field=models.ManyToManyField(
                blank=True,
                help_text="Blood products issued during surgery",
                related_name="anesthesia_records",
                to="blood_bank.bloodissue",
            ),
        ),
        migrations.AddField(
            model_name="whosafetychecklist",
            name="cross_match",
            field=models.ForeignKey(
                blank=True,
                help_text="Completed cross-match (required when blood_loss_risk is HIGH)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="who_checklists",
                to="blood_bank.crossmatch",
            ),
        ),
        migrations.AlterField(
            model_name="anesthesiarecord",
            name="blood_products",
            field=models.TextField(
                blank=True, default="", help_text="Legacy free-text field (prefer blood_issues M2M)"
            ),
        ),
    ]
