# Generated by Django 5.2.13 on 2026-05-15 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_facility_dha_registry_cache_and_encrypted_pii"),
        ("scheduling", "0018_shift_swap_request"),
        ("theatre", "0009_blood_bank_theatre_integration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TheatreEquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(help_text='e.g. "EQ-CARM-01"', max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IMAGING", "Imaging"),
                            ("MONITORING", "Monitoring"),
                            ("SURGICAL_INSTRUMENT", "Surgical Instrument"),
                            ("LIFE_SUPPORT", "Life Support"),
                            ("STERILIZATION", "Sterilization"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_portable", models.BooleanField(default=False)),
                (
                    "setup_time_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Minutes to set up before surgery"
                    ),
                ),
                (
                    "cleanup_time_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Minutes to clean/sterilize after surgery"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theatre Equipment Type",
                "verbose_name_plural": "Theatre Equipment Types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="CaseEquipmentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_required", models.PositiveIntegerField(default=1)),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="True when a specific unit has been allocated and confirmed",
                    ),
                ),
                (
                    "reserved_from",
                    models.TimeField(help_text="Start of equipment reservation window"),
                ),
                (
                    "reserved_until",
                    models.TimeField(help_text="End of equipment reservation window"),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_requirements_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific equipment unit (null for type-level requests)",
                        limit_choices_to={"resource_type": "ASSET"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_equipment_requirements",
                        to="scheduling.resource",
                    ),
                ),
                (
                    "surgery_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_requirements",
                        to="theatre.surgerycase",
                    ),
                ),
                (
                    "equipment_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Equipment type catalog entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_requirements",
                        to="theatre.theatreequipmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Equipment Requirement",
                "verbose_name_plural": "Case Equipment Requirements",
                "ordering": ["reserved_from"],
            },
        ),
        migrations.AddConstraint(
            model_name="theatreequipmenttype",
            constraint=models.UniqueConstraint(
                fields=("facility", "code"), name="theatre_equipment_type_unique_code_per_facility"
            ),
        ),
        migrations.AddConstraint(
            model_name="caseequipmentrequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resource__isnull", False)),
                fields=("surgery_case", "resource"),
                name="unique_case_equipment_resource",
            ),
        ),
    ]
