# Generated by Django 5.2.13 on 2026-05-15 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0010_theatreequipmenttype_caseequipmentrequirement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theatreequipmenttype",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent equipment type for sub-type hierarchy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="theatre.theatreequipmenttype",
            ),
        ),
    ]
