# Generated by Django 5.2.13 on 2026-07-09 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_staffprofile_mfa_disabled"),
        ("encounters", "0033_add_cancelled_consultation_status"),
        ("inpatient", "0044_alter_admission_admission_number_and_more"),
        ("patients", "0024_phase_d_drop_pii_plaintext"),
        ("procedures", "0008_procedurecatalog_origin_hub_id_and_more"),
        ("theatre", "0012_operatingtheatre_origin_hub_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="surgerycase",
            name="case_number",
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AddConstraint(
            model_name="surgerycase",
            constraint=models.UniqueConstraint(
                fields=("facility", "case_number"), name="unique_case_number_per_facility"
            ),
        ),
    ]
