# Generated by Django 5.2.13 on 2026-05-04 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0052_facility_biometrics_agent_national_id"),
        ("encounters", "0030_structured_history_models"),
        ("patients", "0020_add_principal_national_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodDonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("donor_number", models.CharField(editable=False, max_length=30, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(choices=[("M", "Male"), ("F", "Female")], max_length=1),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A Positive"),
                            ("A-", "A Negative"),
                            ("B+", "B Positive"),
                            ("B-", "B Negative"),
                            ("AB+", "AB Positive"),
                            ("AB-", "AB Negative"),
                            ("O+", "O Positive"),
                            ("O-", "O Negative"),
                        ],
                        max_length=3,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("national_id", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                ("total_donations", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to patient record if donor is also a patient.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_donations",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A Positive"),
                            ("A-", "A Negative"),
                            ("B+", "B Positive"),
                            ("B-", "B Negative"),
                            ("AB+", "AB Positive"),
                            ("AB-", "AB Negative"),
                            ("O+", "O Positive"),
                            ("O-", "O Negative"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("WHOLE_BLOOD", "Whole Blood"),
                            ("PACKED_RBC", "Packed Red Blood Cells"),
                            ("PLATELETS", "Platelets"),
                            ("FFP", "Fresh Frozen Plasma"),
                            ("CRYOPRECIPITATE", "Cryoprecipitate"),
                        ],
                        default="WHOLE_BLOOD",
                        max_length=20,
                    ),
                ),
                ("units_requested", models.PositiveIntegerField(default=1)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="ROUTINE",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CROSSMATCH_PENDING", "Crossmatch Pending"),
                            ("READY", "Ready for Issue"),
                            ("ISSUED", "Issued"),
                            ("TRANSFUSED", "Transfused"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED", "Returned"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("clinical_indication", models.TextField(help_text="Reason for transfusion")),
                (
                    "patient_hemoglobin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Pre-transfusion Hb (g/dL)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_requests",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blood_requests",
                        to="patients.patient",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blood_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unit_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A Positive"),
                            ("A-", "A Negative"),
                            ("B+", "B Positive"),
                            ("B-", "B Negative"),
                            ("AB+", "AB Positive"),
                            ("AB-", "AB Negative"),
                            ("O+", "O Positive"),
                            ("O-", "O Negative"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("WHOLE_BLOOD", "Whole Blood"),
                            ("PACKED_RBC", "Packed Red Blood Cells"),
                            ("PLATELETS", "Platelets"),
                            ("FFP", "Fresh Frozen Plasma"),
                            ("CRYOPRECIPITATE", "Cryoprecipitate"),
                        ],
                        default="WHOLE_BLOOD",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COLLECTED", "Collected"),
                            ("TESTING", "Testing"),
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("ISSUED", "Issued"),
                            ("EXPIRED", "Expired"),
                            ("DISCARDED", "Discarded"),
                            ("QUARANTINED", "Quarantined"),
                        ],
                        default="COLLECTED",
                        max_length=20,
                    ),
                ),
                ("collection_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateTimeField()),
                ("volume_ml", models.PositiveIntegerField(default=450)),
                ("hiv_screened", models.BooleanField(default=False)),
                ("hbv_screened", models.BooleanField(default=False)),
                ("hcv_screened", models.BooleanField(default=False)),
                ("syphilis_screened", models.BooleanField(default=False)),
                ("malaria_screened", models.BooleanField(default=False)),
                ("all_screens_negative", models.BooleanField(default=False)),
                ("storage_location", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="blood_bank.blooddonor",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-collection_date"],
            },
        ),
        migrations.CreateModel(
            name="CrossMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("COMPATIBLE", "Compatible"),
                            ("INCOMPATIBLE", "Incompatible"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("performed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("method", models.CharField(default="Gel card", max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "blood_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crossmatches",
                        to="blood_bank.bloodrequest",
                    ),
                ),
                (
                    "blood_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crossmatches",
                        to="blood_bank.bloodunit",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crossmatches_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
                "unique_together": {("blood_request", "blood_unit")},
            },
        ),
        migrations.CreateModel(
            name="BloodIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("transfusion_started_at", models.DateTimeField(blank=True, null=True)),
                ("transfusion_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transfusion_reaction",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("FEBRILE", "Febrile Non-Hemolytic"),
                            ("ALLERGIC", "Allergic"),
                            ("HEMOLYTIC_ACUTE", "Acute Hemolytic"),
                            ("HEMOLYTIC_DELAYED", "Delayed Hemolytic"),
                            ("ANAPHYLACTIC", "Anaphylactic"),
                            ("TACO", "Transfusion-Associated Circulatory Overload"),
                            ("TRALI", "Transfusion-Related Acute Lung Injury"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("reaction_details", models.TextField(blank=True)),
                ("vital_signs_pre", models.JSONField(blank=True, default=dict)),
                ("vital_signs_post", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blood_issues_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "blood_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="blood_bank.bloodrequest",
                    ),
                ),
                (
                    "blood_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue",
                        to="blood_bank.bloodunit",
                    ),
                ),
                (
                    "crossmatch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue",
                        to="blood_bank.crossmatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
    ]
