# Generated by Django 5.2.13 on 2026-05-15 15:15

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0049_encrypt_sha_member_national_id"),
        ("core", "0062_facility_dha_registry_cache_and_encrypted_pii"),
        ("encounters", "0030_structured_history_models"),
        ("patients", "0024_phase_d_drop_pii_plaintext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("claim_number", models.CharField(editable=False, max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_preauth", "Pending Pre-auth"),
                            ("preauth_approved", "Pre-auth Approved"),
                            ("preauth_denied", "Pre-auth Denied"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("under_review", "Under Review"),
                            ("query", "Query"),
                            ("approved", "Approved"),
                            ("partially_approved", "Partially Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("appealed", "Appealed"),
                            ("written_off", "Written Off"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=25,
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("outpatient", "Outpatient"),
                            ("inpatient", "Inpatient"),
                            ("dental", "Dental"),
                            ("optical", "Optical"),
                            ("maternity", "Maternity"),
                            ("emergency", "Emergency"),
                        ],
                        default="outpatient",
                        max_length=20,
                    ),
                ),
                (
                    "diagnosis_codes",
                    models.JSONField(blank=True, default=list, help_text="ICD-10 codes"),
                ),
                ("service_date", models.DateField(default=datetime.date.today)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("discharge_date", models.DateField(blank=True, null=True)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "approved_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "copay_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "external_claim_id",
                    models.CharField(
                        blank=True, help_text="Insurer's reference number", max_length=100
                    ),
                ),
                (
                    "external_preauth_id",
                    models.CharField(
                        blank=True, help_text="Linked preauth at insurer", max_length=100
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "query_details",
                    models.TextField(
                        blank=True, help_text="Insurer queries / requests for information"
                    ),
                ),
                ("query_response", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_claims",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_claims",
                        to="billing.invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_claims",
                        to="patients.patient",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_claims_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_claims_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceClaimItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("service_description", models.CharField(max_length=300)),
                (
                    "service_code",
                    models.CharField(
                        blank=True, help_text="Payer-specific service code", max_length=30
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("claimed_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "approved_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=300)),
                ("tariff_code", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("partially_approved", "Partially Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="insurance.insuranceclaim",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_claim_items",
                        to="billing.invoiceitem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="InsurancePreauth",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("preauth_number", models.CharField(editable=False, max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "preauth_type",
                    models.CharField(
                        choices=[
                            ("admission", "Admission"),
                            ("surgery", "Surgery"),
                            ("procedure", "Procedure"),
                            ("investigation", "Investigation"),
                            ("medication", "Medication"),
                            ("other", "Other"),
                        ],
                        default="admission",
                        max_length=20,
                    ),
                ),
                ("diagnosis_codes", models.JSONField(blank=True, default=list)),
                (
                    "requested_services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {description, code, quantity, estimated_cost}",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "approved_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "validity_period_days",
                    models.IntegerField(
                        blank=True, help_text="How long approval is valid (days)", null=True
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_preauth_id",
                    models.CharField(
                        blank=True, help_text="Insurer's preauth reference", max_length=100
                    ),
                ),
                ("clinical_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_preauths",
                        to="patients.patient",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_preauths_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_preauths_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="insuranceclaim",
            name="preauth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="insurance.insurancepreauth",
            ),
        ),
        migrations.CreateModel(
            name="InsuranceProvider",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(help_text="Short code, e.g. JUBILEE, AAR, CIC", max_length=30),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("corporate", "Corporate"),
                            ("community", "Community-Based"),
                            ("micro", "Micro-Insurance"),
                            ("other", "Other"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "api_integration_enabled",
                    models.BooleanField(
                        default=False, help_text="Whether this provider supports API integration"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="insurancepreauth",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preauths",
                to="insurance.insuranceprovider",
            ),
        ),
        migrations.CreateModel(
            name="InsurancePlan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=30)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("family", "Family"),
                            ("group", "Group"),
                            ("corporate", "Corporate"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[
                            ("inpatient", "Inpatient Only"),
                            ("outpatient", "Outpatient Only"),
                            ("comprehensive", "Comprehensive"),
                            ("dental", "Dental"),
                            ("optical", "Optical"),
                            ("maternity", "Maternity"),
                        ],
                        default="comprehensive",
                        max_length=20,
                    ),
                ),
                (
                    "default_copay_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Patient co-pay percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "annual_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual benefit cap in KES",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "per_visit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per-visit benefit cap in KES",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "preauth_required",
                    models.BooleanField(
                        default=False, help_text="Does this plan require pre-authorization?"
                    ),
                ),
                (
                    "preauth_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount above which preauth is mandatory (KES)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "waiting_period_days",
                    models.IntegerField(
                        default=0, help_text="Waiting period for new members (days)"
                    ),
                ),
                (
                    "exclusions",
                    models.JSONField(
                        blank=True, default=list, help_text="List of excluded services/conditions"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("discontinued", "Discontinued")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="insurance.insuranceprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "name"],
            },
        ),
        migrations.AddField(
            model_name="insuranceclaim",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="insurance.insuranceprovider",
            ),
        ),
        migrations.CreateModel(
            name="InsuranceProviderConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("contract_number", models.CharField(blank=True, max_length=50)),
                ("contract_start", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
                (
                    "accreditation_status",
                    models.CharField(
                        choices=[
                            ("accredited", "Accredited"),
                            ("pending", "Pending"),
                            ("expired", "Expired"),
                            ("not_accredited", "Not Accredited"),
                        ],
                        default="not_accredited",
                        max_length=20,
                    ),
                ),
                ("accreditation_number", models.CharField(blank=True, max_length=50)),
                ("api_base_url", models.URLField(blank=True)),
                (
                    "api_auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("basic", "Basic Auth"),
                            ("bearer", "Bearer Token"),
                            ("oauth2", "OAuth 2.0"),
                            ("api_key", "API Key"),
                            ("custom", "Custom"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "api_credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Encrypted credentials blob (keys vary by auth type)",
                    ),
                ),
                ("api_enabled", models.BooleanField(default=False)),
                (
                    "max_claim_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum single-claim amount for this facility (KES)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "submission_format",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("pdf", "PDF"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_configs",
                        to="insurance.insuranceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance Provider Config",
                "verbose_name_plural": "Insurance Provider Configs",
            },
        ),
        migrations.CreateModel(
            name="InsuranceRemittance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("remittance_number", models.CharField(max_length=50)),
                ("remittance_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reconciled_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("reconciled", "Reconciled"),
                            ("partial", "Partially Reconciled"),
                            ("disputed", "Disputed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("bank_reference", models.CharField(blank=True, max_length=100)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remittances",
                        to="insurance.insuranceprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-remittance_date"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceRemittanceLine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "claim_number",
                    models.CharField(
                        help_text="Claim number as reported by insurer", max_length=50
                    ),
                ),
                ("member_number", models.CharField(blank=True, max_length=50)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remittance_lines",
                        to="insurance.insuranceclaim",
                    ),
                ),
                (
                    "remittance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="insurance.insuranceremittance",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PatientInsurance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("member_number", models.CharField(max_length=50)),
                ("policy_number", models.CharField(blank=True, max_length=50)),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("principal", "Principal"),
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("dependent", "Dependent"),
                            ("other", "Other"),
                        ],
                        default="principal",
                        max_length=20,
                    ),
                ),
                (
                    "principal_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of principal member (if external)",
                        max_length=200,
                    ),
                ),
                ("employer", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("pending_verification", "Pending Verification"),
                        ],
                        default="active",
                        max_length=25,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                (
                    "copay_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Patient-specific co-pay if different from plan default",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "annual_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Remaining annual benefit",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=True, help_text="Primary vs secondary insurance"),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_enrollments",
                        to="patients.patient",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="insurance.insuranceplan",
                    ),
                ),
                (
                    "principal_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="If dependent, link to the principal member",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependents",
                        to="insurance.patientinsurance",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Denormalized from plan for fast filtering",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_enrollments",
                        to="insurance.insuranceprovider",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-valid_to"],
            },
        ),
        migrations.AddField(
            model_name="insurancepreauth",
            name="patient_insurance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preauths",
                to="insurance.patientinsurance",
            ),
        ),
        migrations.AddField(
            model_name="insuranceclaim",
            name="patient_insurance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="insurance.patientinsurance",
            ),
        ),
        migrations.CreateModel(
            name="PayerTariff",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "service_code",
                    models.CharField(help_text="Facility's service code", max_length=30),
                ),
                (
                    "payer_code",
                    models.CharField(help_text="Insurer's code for this service", max_length=30),
                ),
                ("payer_description", models.CharField(blank=True, max_length=300)),
                (
                    "tariff_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Insurer's approved rate (KES)", max_digits=12
                    ),
                ),
                (
                    "facility_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="What facility normally charges (KES)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("requires_preauth", models.BooleanField(default=False)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, applies to all plans for this provider",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tariffs",
                        to="insurance.insuranceplan",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="insurance.insuranceprovider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payer_tariffs",
                        to="billing.service",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "service_code"],
            },
        ),
        migrations.AddIndex(
            model_name="insuranceprovider",
            index=models.Index(
                fields=["organization", "status"], name="insurance_i_organiz_9e10a3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="insuranceprovider",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="unique_provider_code_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="insuranceplan",
            constraint=models.UniqueConstraint(
                fields=("provider", "code"), name="unique_plan_code_per_provider"
            ),
        ),
        migrations.AddConstraint(
            model_name="insuranceproviderconfig",
            constraint=models.UniqueConstraint(
                fields=("facility", "provider"), name="unique_provider_config_per_facility"
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceremittance",
            index=models.Index(
                fields=["provider", "status"], name="insurance_i_provide_1388e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientinsurance",
            index=models.Index(fields=["patient", "status"], name="insurance_p_patient_1feeb5_idx"),
        ),
        migrations.AddIndex(
            model_name="patientinsurance",
            index=models.Index(
                fields=["provider", "member_number"], name="insurance_p_provide_b0bd05_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="patientinsurance",
            constraint=models.UniqueConstraint(
                fields=("patient", "plan", "member_number"), name="unique_patient_plan_member"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepreauth",
            index=models.Index(
                fields=["provider", "status"], name="insurance_i_provide_c4f751_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancepreauth",
            index=models.Index(fields=["patient", "status"], name="insurance_i_patient_c6b4d5_idx"),
        ),
        migrations.AddIndex(
            model_name="insuranceclaim",
            index=models.Index(
                fields=["provider", "status"], name="insurance_i_provide_6b639f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceclaim",
            index=models.Index(fields=["patient", "status"], name="insurance_i_patient_9cb328_idx"),
        ),
        migrations.AddIndex(
            model_name="insuranceclaim",
            index=models.Index(fields=["claim_number"], name="insurance_i_claim_n_de6fe8_idx"),
        ),
        migrations.AddIndex(
            model_name="insuranceclaim",
            index=models.Index(
                fields=["status", "submission_date"], name="insurance_i_status_d23a63_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payertariff",
            constraint=models.UniqueConstraint(
                fields=("provider", "service_code", "plan", "effective_from"),
                name="unique_tariff_mapping",
            ),
        ),
    ]
