# Generated by Django 5.2.13 on 2026-05-15 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_facility_dha_registry_cache_and_encrypted_pii"),
        ("insurance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceOutboundCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(help_text="Path on the insurer API.", max_length=500)),
                ("base_url", models.CharField(blank=True, default="", max_length=500)),
                ("auth_mode", models.CharField(blank=True, default="", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("CLIENT_ERROR", "Client Error (4xx)"),
                            ("SERVER_ERROR", "Server Error (5xx)"),
                            ("TRANSPORT", "Transport Error"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=64)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "request_payload",
                    models.JSONField(blank=True, help_text="PII-redacted request body.", null=True),
                ),
                (
                    "response_excerpt",
                    models.JSONField(blank=True, help_text="First 4 KB of response.", null=True),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_calls",
                        to="insurance.insuranceprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the call (if request-scoped).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_outbound_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance Outbound Call",
                "verbose_name_plural": "Insurance Outbound Calls",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["facility", "-created_at"], name="insurance_i_facilit_f1050b_idx"
                    ),
                    models.Index(
                        fields=["provider", "-created_at"], name="insurance_i_provide_f8958a_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="insurance_i_status_a17659_idx"
                    ),
                    models.Index(fields=["correlation_id"], name="insurance_i_correla_c19495_idx"),
                ],
            },
        ),
    ]
