# Generated by Django 5.2.13 on 2026-08-05 15:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_facility_hdu_nbu_flags"),
        ("encounters", "0034_encounter_public_id_historicalencounter_public_id"),
        ("insurance", "0004_insuranceclaim_origin_hub_id_and_more"),
        ("patients", "0027_alter_historicalpatient_identification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="auth_base_url",
            field=models.URLField(
                blank=True,
                help_text="OAuth2 authorization host (e.g. accounts.multitenant.slade360.co.ke)",
            ),
        ),
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="healthcloud_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable HealthCloud by Slade360 workflow for this facility/provider config",
            ),
        ),
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="payer_slade_code",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Payer identifier on HealthCloud (e.g. 457 for Jubilee in sandbox docs)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="provider_edi_base_url",
            field=models.URLField(
                blank=True,
                help_text="Provider EDI host for eligibility/reservations/remittance APIs",
            ),
        ),
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="provider_is_base_url",
            field=models.URLField(
                blank=True, help_text="Provider IS host for claim/invoice/visit APIs"
            ),
        ),
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="require_balance_reservation",
            field=models.BooleanField(
                default=True, help_text="Require balance reservation before invoice submission"
            ),
        ),
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="require_visit_authorization",
            field=models.BooleanField(
                default=True, help_text="Require start-visit authorization before claim submission"
            ),
        ),
        migrations.CreateModel(
            name="InsuranceVisitAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                ("member_number", models.CharField(max_length=50)),
                ("payer_slade_code", models.PositiveIntegerField(blank=True, null=True)),
                ("benefit_type", models.CharField(blank=True, max_length=40)),
                ("benefit_code", models.CharField(blank=True, max_length=60)),
                ("policy_number", models.CharField(blank=True, max_length=80)),
                ("policy_effective_date", models.DateTimeField(blank=True, null=True)),
                ("beneficiary_id", models.BigIntegerField(blank=True, null=True)),
                ("beneficiary_contact_id", models.BigIntegerField(blank=True, null=True)),
                ("beneficiary_contact_value", models.CharField(blank=True, max_length=30)),
                ("factors", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("otp_requested", "OTP Requested"),
                            ("authorized", "Authorized"),
                            ("validated", "Validated"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("auth_token", models.CharField(blank=True, max_length=100)),
                ("authorization_guid", models.CharField(blank=True, max_length=100)),
                ("authorization_date", models.DateTimeField(blank=True, null=True)),
                ("auth_expiry", models.DateTimeField(blank=True, null=True)),
                ("auth_status", models.CharField(blank=True, max_length=50)),
                ("last_error", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insurance_visit_authorizations",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_authorizations",
                        to="insurance.patientinsurance",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_visit_authorizations",
                        to="patients.patient",
                    ),
                ),
                (
                    "provider_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_authorizations",
                        to="insurance.insuranceproviderconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceExternalSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                ("operation", models.CharField(max_length=60)),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Outbound"), ("inbound", "Inbound")],
                        default="outbound",
                        max_length=10,
                    ),
                ),
                ("request_hash", models.CharField(blank=True, db_index=True, max_length=128)),
                ("external_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("external_ref", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retry", "Retry"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("correlation_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_sync_logs",
                        to="insurance.insuranceclaim",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "preauth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_sync_logs",
                        to="insurance.insurancepreauth",
                    ),
                ),
                (
                    "authorization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_sync_logs",
                        to="insurance.insurancevisitauthorization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceBalanceReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                ("reservation_guid", models.CharField(blank=True, db_index=True, max_length=100)),
                ("invoice_number", models.CharField(blank=True, max_length=80)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_released",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("release_notes", models.TextField(blank=True)),
                ("payer_invoice_reference", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("partially_released", "Partially Released"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="reserved",
                        max_length=30,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="balance_reservations",
                        to="insurance.insuranceclaim",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "authorization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="insurance.insurancevisitauthorization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="insurancevisitauthorization",
            index=models.Index(
                fields=["facility", "status"], name="insurance_i_facilit_5a22c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancevisitauthorization",
            index=models.Index(
                fields=["authorization_guid"], name="insurance_i_authori_c00151_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancevisitauthorization",
            index=models.Index(
                fields=["member_number", "payer_slade_code"], name="insurance_i_member__9e05f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceexternalsync",
            index=models.Index(
                fields=["facility", "operation", "status"], name="insurance_i_facilit_0259c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceexternalsync",
            index=models.Index(
                fields=["request_hash", "operation"], name="insurance_i_request_a256e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancebalancereservation",
            index=models.Index(
                fields=["facility", "status"], name="insurance_i_facilit_bf3cab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insurancebalancereservation",
            index=models.Index(fields=["invoice_number"], name="insurance_i_invoice_6890c1_idx"),
        ),
    ]
