"""Add encrypted Slade credential columns for provider config.

Usage: Applied automatically via Django migrations.
Inputs: No CLI args; runs through ``python manage.py migrate``.
"""

# Generated by Django 5.2.13 on 2026-08-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0007_insuranceproviderconfig_health_crm_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="slade_client_id_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted Slade OAuth client ID"
            ),
        ),
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="slade_client_secret_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted Slade OAuth client secret"
            ),
        ),
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="slade_password_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted Slade OAuth password"
            ),
        ),
        migrations.AddField(
            model_name="insuranceproviderconfig",
            name="slade_username_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="KMS-encrypted Slade OAuth username"
            ),
        ),
    ]
