# Generated by Django 5.2.13 on 2026-08-13 21:36

import hmis.apps.core.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0009_facilitysladecredential"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insurancevisitauthorization",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "HealthCloud Session",
                "verbose_name_plural": "HealthCloud Sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="patientinsurance",
            options={
                "ordering": ["-is_primary", "-valid_to"],
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
            },
        ),
        migrations.AlterField(
            model_name="patientinsurance",
            name="card_image_back",
            field=models.ImageField(
                blank=True,
                help_text="Back image of insurance card",
                null=True,
                upload_to="insurance/cards/",
                validators=[hmis.apps.core.upload_validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="patientinsurance",
            name="card_image_front",
            field=models.ImageField(
                blank=True,
                help_text="Front image of insurance card",
                null=True,
                upload_to="insurance/cards/",
                validators=[hmis.apps.core.upload_validators.validate_image_upload],
            ),
        ),
    ]
