# Generated by Django 5.2.9 on 2026-02-27 15:35

import django.db.models.deletion
import hmis.apps.core.history
import hmis.apps.referrals.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0010_alter_clinic_clinic_type"),
        ("encounters", "0023_historicaldiagnosis_historicalencounter"),
        ("patients", "0014_historicalpatient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalClinicalReferral",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "referral_number",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated referral number (REF-YYYYMMDD-XXXX)",
                        max_length=30,
                    ),
                ),
                (
                    "referral_type",
                    models.CharField(
                        choices=[
                            ("ALLIED_HEALTH", "Allied Health Service"),
                            ("SPECIALTY_CLINIC", "Specialty Clinic"),
                            ("ADMISSION", "Inpatient Admission"),
                            ("EXTERNAL", "External Facility"),
                        ],
                        help_text="Auto-derived from target_service. ALLIED_HEALTH, SPECIALTY_CLINIC, ADMISSION, or EXTERNAL.",
                        max_length=20,
                    ),
                ),
                (
                    "target_service",
                    models.CharField(
                        choices=[
                            ("PHYSIOTHERAPY", "Physiotherapy"),
                            ("NUTRITION", "Nutrition / Dietetics"),
                            ("OCCUPATIONAL_THERAPY", "Occupational Therapy"),
                            ("COUNSELLING", "Counselling"),
                            ("SOCIAL_WORK", "Social Work"),
                            ("DENTAL", "Dental"),
                            ("EYE", "Eye / Ophthalmology"),
                            ("ENT", "ENT"),
                            ("SURGICAL", "Surgical"),
                            ("ORTHO", "Orthopedic"),
                            ("DERM", "Dermatology"),
                            ("CARDIOLOGY", "Cardiology"),
                            ("ONCOLOGY", "Oncology"),
                            ("MENTAL_HEALTH", "Mental Health / Psychiatry"),
                            ("DIALYSIS", "Dialysis"),
                            ("ANC", "Antenatal Care"),
                            ("PNC", "Postnatal Care"),
                            ("FP", "Family Planning"),
                            ("CWC", "Child Welfare"),
                            ("CCC", "Comprehensive Care (HIV)"),
                            ("TB", "TB Clinic"),
                            ("DIABETIC", "Diabetic Clinic"),
                            ("HYPERTENSION", "Hypertension Clinic"),
                            ("GENERAL_WARD", "General Ward"),
                            ("MEDICAL_WARD", "Medical Ward"),
                            ("SURGICAL_WARD", "Surgical Ward"),
                            ("MATERNITY_WARD", "Maternity Ward"),
                            ("PEDIATRIC_WARD", "Pediatric Ward"),
                            ("ICU", "Intensive Care Unit"),
                            ("HDU", "High Dependency Unit"),
                            ("PROCEDURE_ROOM", "Procedure Room"),
                            ("OTHER", "Other"),
                        ],
                        help_text="The specific service/clinic/ward being referred to",
                        max_length=30,
                    ),
                ),
                ("reason", models.TextField(help_text="Clinical reason for referral")),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional clinical context for the receiving service",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="ROUTINE",
                        help_text="Urgency of the referral",
                        max_length=20,
                    ),
                ),
                (
                    "relevant_diagnoses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Snapshot of encounter diagnoses at referral time",
                    ),
                ),
                (
                    "relevant_vitals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of encounter vitals at referral time",
                    ),
                ),
                (
                    "provisional_diagnosis",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ICD-10 code for provisional diagnosis (admission referrals)",
                        max_length=10,
                    ),
                ),
                (
                    "provisional_diagnosis_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Text description of provisional diagnosis",
                        max_length=255,
                    ),
                ),
                (
                    "preferred_ward_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Preferred ward type for admission",
                        max_length=30,
                    ),
                ),
                (
                    "external_facility_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of external facility",
                        max_length=255,
                    ),
                ),
                (
                    "external_facility_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MFL code of external facility (Kenya Master Facility List)",
                        max_length=50,
                    ),
                ),
                (
                    "referral_letter",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Referral letter content for external facility",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Review"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        help_text="Current referral status",
                        max_length=20,
                    ),
                ),
                (
                    "decline_reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason if referral was declined"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="When the referral was accepted", null=True
                    ),
                ),
                (
                    "declined_at",
                    models.DateTimeField(
                        blank=True, help_text="When the referral was declined", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the referral was completed", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=hmis.apps.referrals.models.default_referral_expiry,
                        help_text="When the referral expires if not acted upon (default 48h)",
                    ),
                ),
                (
                    "linked_module",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Module name of linked specialist record (e.g., 'physiotherapy')",
                        max_length=50,
                    ),
                ),
                (
                    "linked_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model name of linked specialist record (e.g., 'PhysiotherapyOrder')",
                        max_length=100,
                    ),
                ),
                (
                    "linked_object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="PK of the linked specialist record", null=True
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this referral involves sensitive data (HIV, GBV, etc.)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Person who accepted the referral",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Clinic visit created for queue routing",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "declined_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Person who declined the referral",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Encounter that generated this referral",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Patient being referred",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patients.patient",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Clinician who created the referral",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Clinical Referral",
                "verbose_name_plural": "historical Clinical Referrals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ClinicalReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referral_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated referral number (REF-YYYYMMDD-XXXX)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "referral_type",
                    models.CharField(
                        choices=[
                            ("ALLIED_HEALTH", "Allied Health Service"),
                            ("SPECIALTY_CLINIC", "Specialty Clinic"),
                            ("ADMISSION", "Inpatient Admission"),
                            ("EXTERNAL", "External Facility"),
                        ],
                        help_text="Auto-derived from target_service. ALLIED_HEALTH, SPECIALTY_CLINIC, ADMISSION, or EXTERNAL.",
                        max_length=20,
                    ),
                ),
                (
                    "target_service",
                    models.CharField(
                        choices=[
                            ("PHYSIOTHERAPY", "Physiotherapy"),
                            ("NUTRITION", "Nutrition / Dietetics"),
                            ("OCCUPATIONAL_THERAPY", "Occupational Therapy"),
                            ("COUNSELLING", "Counselling"),
                            ("SOCIAL_WORK", "Social Work"),
                            ("DENTAL", "Dental"),
                            ("EYE", "Eye / Ophthalmology"),
                            ("ENT", "ENT"),
                            ("SURGICAL", "Surgical"),
                            ("ORTHO", "Orthopedic"),
                            ("DERM", "Dermatology"),
                            ("CARDIOLOGY", "Cardiology"),
                            ("ONCOLOGY", "Oncology"),
                            ("MENTAL_HEALTH", "Mental Health / Psychiatry"),
                            ("DIALYSIS", "Dialysis"),
                            ("ANC", "Antenatal Care"),
                            ("PNC", "Postnatal Care"),
                            ("FP", "Family Planning"),
                            ("CWC", "Child Welfare"),
                            ("CCC", "Comprehensive Care (HIV)"),
                            ("TB", "TB Clinic"),
                            ("DIABETIC", "Diabetic Clinic"),
                            ("HYPERTENSION", "Hypertension Clinic"),
                            ("GENERAL_WARD", "General Ward"),
                            ("MEDICAL_WARD", "Medical Ward"),
                            ("SURGICAL_WARD", "Surgical Ward"),
                            ("MATERNITY_WARD", "Maternity Ward"),
                            ("PEDIATRIC_WARD", "Pediatric Ward"),
                            ("ICU", "Intensive Care Unit"),
                            ("HDU", "High Dependency Unit"),
                            ("PROCEDURE_ROOM", "Procedure Room"),
                            ("OTHER", "Other"),
                        ],
                        help_text="The specific service/clinic/ward being referred to",
                        max_length=30,
                    ),
                ),
                ("reason", models.TextField(help_text="Clinical reason for referral")),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional clinical context for the receiving service",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="ROUTINE",
                        help_text="Urgency of the referral",
                        max_length=20,
                    ),
                ),
                (
                    "relevant_diagnoses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Snapshot of encounter diagnoses at referral time",
                    ),
                ),
                (
                    "relevant_vitals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of encounter vitals at referral time",
                    ),
                ),
                (
                    "provisional_diagnosis",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ICD-10 code for provisional diagnosis (admission referrals)",
                        max_length=10,
                    ),
                ),
                (
                    "provisional_diagnosis_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Text description of provisional diagnosis",
                        max_length=255,
                    ),
                ),
                (
                    "preferred_ward_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Preferred ward type for admission",
                        max_length=30,
                    ),
                ),
                (
                    "external_facility_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of external facility",
                        max_length=255,
                    ),
                ),
                (
                    "external_facility_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MFL code of external facility (Kenya Master Facility List)",
                        max_length=50,
                    ),
                ),
                (
                    "referral_letter",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Referral letter content for external facility",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Review"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        help_text="Current referral status",
                        max_length=20,
                    ),
                ),
                (
                    "decline_reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason if referral was declined"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="When the referral was accepted", null=True
                    ),
                ),
                (
                    "declined_at",
                    models.DateTimeField(
                        blank=True, help_text="When the referral was declined", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the referral was completed", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=hmis.apps.referrals.models.default_referral_expiry,
                        help_text="When the referral expires if not acted upon (default 48h)",
                    ),
                ),
                (
                    "linked_module",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Module name of linked specialist record (e.g., 'physiotherapy')",
                        max_length=50,
                    ),
                ),
                (
                    "linked_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model name of linked specialist record (e.g., 'PhysiotherapyOrder')",
                        max_length=100,
                    ),
                ),
                (
                    "linked_object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="PK of the linked specialist record", null=True
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this referral involves sensitive data (HIV, GBV, etc.)",
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who accepted the referral",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clinic visit created for queue routing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "declined_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who declined the referral",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_declined",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        help_text="Encounter that generated this referral",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient being referred",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="patients.patient",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        help_text="Clinician who created the referral",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Referral",
                "verbose_name_plural": "Clinical Referrals",
                "ordering": ["-created_at"],
                "permissions": [
                    ("accept_referral", "Can accept referrals"),
                    ("decline_referral", "Can decline referrals"),
                    ("view_sensitive_referral", "Can view sensitive referrals"),
                ],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="ref_status_created_idx"),
                    models.Index(fields=["patient", "-created_at"], name="ref_patient_created_idx"),
                    models.Index(fields=["encounter"], name="ref_encounter_idx"),
                    models.Index(fields=["referral_type"], name="ref_type_idx"),
                    models.Index(fields=["target_service"], name="ref_service_idx"),
                    models.Index(fields=["referred_by"], name="ref_referred_by_idx"),
                    models.Index(fields=["referral_number"], name="ref_number_idx"),
                ],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
    ]
