# Generated by Django 5.2.13 on 2026-04-23 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0016_facility_scoped_model_fix"),
        ("referrals", "0002_clinicalreferral_destination_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalclinicalreferral",
            name="destination_clinic",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Explicit clinic destination for clinic-routed referrals.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinic",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreferral",
            name="destination_clinic",
            field=models.ForeignKey(
                blank=True,
                help_text="Explicit clinic destination for clinic-routed referrals.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_clinical_referrals",
                to="clinics.clinic",
            ),
        ),
    ]
