# Generated by Django 5.2.13 on 2026-05-08 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_tenant_from_encounter(apps, schema_editor):
    """Populate facility/organization on existing referrals from their encounter."""
    ClinicalReferral = apps.get_model("referrals", "ClinicalReferral")
    qs = ClinicalReferral.objects.filter(
        models.Q(facility__isnull=True) | models.Q(organization__isnull=True)
    ).select_related("encounter")
    updated = 0
    for ref in qs.iterator():
        enc = ref.encounter
        changed = False
        if not ref.facility_id and getattr(enc, "facility_id", None):
            ref.facility_id = enc.facility_id
            changed = True
        if not ref.organization_id and getattr(enc, "organization_id", None):
            ref.organization_id = enc.organization_id
            changed = True
        if changed:
            ref.save(update_fields=["facility", "organization"])
            updated += 1


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_dhis2_config"),
        ("referrals", "0003_fix_destination_clinic_related_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalreferral",
            name="cancel_reason",
            field=models.TextField(
                blank=True, default="", help_text="Reason if referral was cancelled"
            ),
        ),
        migrations.AddField(
            model_name="clinicalreferral",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When the referral was cancelled", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicalreferral",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Person who cancelled the referral",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals_cancelled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicalreferral",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="clinicalreferral",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicalreferral",
            name="cancel_reason",
            field=models.TextField(
                blank=True, default="", help_text="Reason if referral was cancelled"
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicalreferral",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, help_text="When the referral was cancelled", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicalreferral",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Person who cancelled the referral",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicalreferral",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicalreferral",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.organization",
            ),
        ),
        migrations.RunPython(backfill_tenant_from_encounter, reverse_noop),
    ]
