"""
Triage models for Vitora HMIS.

This module implements the Kenya Emergency Triage Assessment (KETA) system
for patient prioritization and queue management.

Sprint 1.5-1.6 Track E: Triage Module MVP
Phase 4: Auto-Escalation & Alerts
"""

from decimal import Decimal
from typing import TYPE_CHECKING

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone

if TYPE_CHECKING:
    from hmis.apps.clinics.models import ClinicVisit


# =============================================================================
# Phase 4: Wait Time Breach Alert Model
# =============================================================================


class WaitTimeBreach(models.Model):
    """
    Recorded when a patient's wait time exceeds the KETA target for their
    triage category. Generated by Celery periodic task.

    Each breach is created once per queue entry; no duplicates are generated
    for the same queue entry unless it is acknowledged and later breaches again
    (which shouldn't happen in practice).

    Phase 4: Auto-Escalation & Alerts
    """

    SEVERITY_CHOICES = [
        ("CRITICAL", "Critical – RED category breach (> 0 min)"),
        ("URGENT", "Urgent – ORANGE category breach (> 10 min)"),
        ("WARNING", "Warning – YELLOW category breach (> 60 min)"),
        ("INFO", "Informational – GREEN/BLUE category breach"),
    ]

    STATUS_CHOICES = [
        ("ACTIVE", "Active – Unacknowledged"),
        ("ACKNOWLEDGED", "Acknowledged by staff"),
        ("ESCALATED", "Escalated to charge nurse/supervisor"),
        ("RESOLVED", "Resolved – Patient seen or left"),
    ]

    # Maps triage category → breach severity
    CATEGORY_SEVERITY_MAP = {
        "RED": "CRITICAL",
        "ORANGE": "URGENT",
        "YELLOW": "WARNING",
        "GREEN": "INFO",
        "BLUE": "INFO",
    }

    queue_entry = models.ForeignKey(
        "triage.TriageQueue",
        on_delete=models.CASCADE,
        related_name="wait_time_breaches",
        help_text="Queue entry whose wait time was breached",
    )
    triage_assessment = models.ForeignKey(
        "triage.TriageAssessment",
        on_delete=models.CASCADE,
        related_name="wait_time_breaches",
        help_text="Associated triage assessment",
    )
    patient = models.ForeignKey(
        "patients.Patient",
        on_delete=models.CASCADE,
        related_name="wait_time_breaches",
        help_text="Patient whose wait time was breached",
    )

    triage_category = models.CharField(
        max_length=10,
        help_text="Triage category at breach time",
    )
    severity = models.CharField(
        max_length=10,
        choices=SEVERITY_CHOICES,
        help_text="Severity derived from triage category",
    )
    target_wait_minutes = models.IntegerField(
        help_text="KETA target wait time in minutes for this category",
    )
    actual_wait_minutes = models.IntegerField(
        help_text="Actual wait time in minutes when breach was detected",
    )
    assigned_area = models.CharField(
        max_length=30,
        blank=True,
        default="",
        help_text="ER zone where patient is waiting",
    )
    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default="ACTIVE",
    )
    acknowledged_by = models.ForeignKey(
        "auth.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="acknowledged_breaches",
    )
    acknowledged_at = models.DateTimeField(null=True, blank=True)
    notes = models.TextField(blank=True, default="")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Wait Time Breach"
        verbose_name_plural = "Wait Time Breaches"

    def __str__(self) -> str:
        return (
            f"Breach: {self.triage_category} ({self.actual_wait_minutes}m / "
            f"target {self.target_wait_minutes}m) - {self.status}"
        )

    def acknowledge(self, user, notes: str = ""):
        """Acknowledge the breach alert."""
        self.status = "ACKNOWLEDGED"
        self.acknowledged_by = user
        self.acknowledged_at = timezone.now()
        if notes:
            self.notes = notes
        self.save(
            update_fields=["status", "acknowledged_by", "acknowledged_at", "notes", "updated_at"]
        )

    def escalate(self, user=None, notes: str = ""):
        """Escalate the breach to charge nurse/supervisor."""
        self.status = "ESCALATED"
        if notes:
            self.notes = notes
        self.save(update_fields=["status", "notes", "updated_at"])

    def resolve(self):
        """Mark breach as resolved (patient seen or left)."""
        self.status = "RESOLVED"
        self.save(update_fields=["status", "updated_at"])


# =============================================================================
# Phase 4: Escalation Event Model
# =============================================================================


class Escalation(models.Model):
    """
    Records an escalation action taken by staff for a patient in the ER queue.

    Escalation types:
    - CHARGE_NURSE: Escalate to charge nurse for priority re-assessment
    - ADDITIONAL_STAFF: Request additional staff to reduce queue load
    - SUPERVISOR: Escalate to on-duty supervisor

    Phase 4: Auto-Escalation & Alerts
    """

    ESCALATION_TYPE_CHOICES = [
        ("CHARGE_NURSE", "Escalate to Charge Nurse"),
        ("ADDITIONAL_STAFF", "Request Additional Staff"),
        ("SUPERVISOR", "Escalate to Supervisor"),
    ]

    STATUS_CHOICES = [
        ("PENDING", "Pending – Escalation raised"),
        ("IN_PROGRESS", "In Progress – Being handled"),
        ("RESOLVED", "Resolved"),
        ("DISMISSED", "Dismissed"),
    ]

    queue_entry = models.ForeignKey(
        "triage.TriageQueue",
        on_delete=models.CASCADE,
        related_name="escalations",
        help_text="Queue entry being escalated",
    )
    triage_assessment = models.ForeignKey(
        "triage.TriageAssessment",
        on_delete=models.CASCADE,
        related_name="escalations",
        help_text="Associated triage assessment",
    )
    patient = models.ForeignKey(
        "patients.Patient",
        on_delete=models.CASCADE,
        related_name="escalations",
        help_text="Patient being escalated",
    )
    escalation_type = models.CharField(
        max_length=20,
        choices=ESCALATION_TYPE_CHOICES,
        help_text="Type of escalation",
    )
    reason = models.TextField(
        help_text="Reason for escalation",
    )
    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default="PENDING",
    )
    wait_time_at_escalation = models.IntegerField(
        null=True,
        blank=True,
        help_text="Patient's wait time in minutes when escalation was raised",
    )
    triage_category = models.CharField(
        max_length=10,
        blank=True,
        default="",
        help_text="Triage category at escalation time",
    )
    assigned_area = models.CharField(
        max_length=30,
        blank=True,
        default="",
        help_text="ER zone at time of escalation",
    )

    escalated_by = models.ForeignKey(
        "auth.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="escalations_raised",
        help_text="Staff member who raised the escalation",
    )
    resolved_by = models.ForeignKey(
        "auth.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="escalations_resolved",
    )
    resolved_at = models.DateTimeField(null=True, blank=True)
    resolution_notes = models.TextField(blank=True, default="")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Escalation"
        verbose_name_plural = "Escalations"
        permissions = [
            ("escalate_patient", "Can escalate patient in triage queue"),
        ]

    def __str__(self) -> str:
        return f"{self.get_escalation_type_display()} - {self.patient} - {self.status}"

    def mark_in_progress(self, user=None):
        """Mark escalation as being handled."""
        self.status = "IN_PROGRESS"
        self.save(update_fields=["status", "updated_at"])

    def resolve(self, user, notes: str = ""):
        """Resolve the escalation."""
        self.status = "RESOLVED"
        self.resolved_by = user
        self.resolved_at = timezone.now()
        if notes:
            self.resolution_notes = notes
        self.save(
            update_fields=["status", "resolved_by", "resolved_at", "resolution_notes", "updated_at"]
        )

    def dismiss(self, user, notes: str = ""):
        """Dismiss the escalation."""
        self.status = "DISMISSED"
        self.resolved_by = user
        self.resolved_at = timezone.now()
        if notes:
            self.resolution_notes = notes
        self.save(
            update_fields=["status", "resolved_by", "resolved_at", "resolution_notes", "updated_at"]
        )


class WaitingQueue(models.Model):
    """
    Queue for patients who have checked in but not yet been triaged.

    This represents the initial waiting state before triage assessment.
    Once triaged, patients move to TriageQueue with their priority category.
    """

    STATUS_CHOICES = [
        ("WAITING_TRIAGE", "Waiting for Triage"),
        ("IN_TRIAGE", "Being Triaged"),
        ("TRIAGED", "Triaged - Moved to Priority Queue"),
        ("CANCELLED", "Cancelled/Left"),
    ]

    patient = models.ForeignKey(
        "patients.Patient",
        on_delete=models.CASCADE,
        related_name="waiting_queue_entries",
        help_text="Patient waiting to be seen",
    )
    encounter = models.ForeignKey(
        "encounters.Encounter",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="waiting_queue_entries",
        help_text="Associated encounter (created when patient checks in)",
    )
    check_in_time = models.DateTimeField(
        default=timezone.now,
        help_text="When patient checked in/registered",
    )
    reason_for_visit = models.TextField(
        blank=True,
        default="",
        help_text="Initial reason for visit (chief complaint)",
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="WAITING_TRIAGE",
    )
    priority_hint = models.CharField(
        max_length=20,
        blank=True,
        default="",
        help_text="Initial priority hint (e.g., 'EMERGENCY' for walk-in emergencies)",
    )
    checked_in_by = models.ForeignKey(
        "auth.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="patient_check_ins",
        help_text="Staff who checked in the patient",
    )
    triage_room = models.ForeignKey(
        "scheduling.Resource",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="triage_queue_entries",
        limit_choices_to={"resource_type": "PLACE"},
        help_text="Triage room assigned to this patient (auto or manual).",
    )
    notes = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["check_in_time"]  # FIFO for waiting patients
        verbose_name = "Waiting Queue Entry"
        verbose_name_plural = "Waiting Queue Entries"

    def __str__(self) -> str:
        return f"Waiting: {self.patient} - {self.status} ({self.check_in_time.strftime('%H:%M')})"

    @classmethod
    def get_waiting_patients(cls):
        """Get patients waiting for triage."""
        return (
            cls.objects.filter(status__in=["WAITING_TRIAGE", "IN_TRIAGE"])
            .select_related("patient", "encounter")
            .order_by("check_in_time")
        )

    def start_triage(self):
        """Mark patient as being triaged."""
        self.status = "IN_TRIAGE"
        self.save(update_fields=["status", "updated_at"])

    def complete_triage(self):
        """Mark as triaged (moves to priority queue)."""
        self.status = "TRIAGED"
        self.save(update_fields=["status", "updated_at"])

    def cancel(self, reason: str = ""):
        """Cancel/remove from waiting queue."""
        self.status = "CANCELLED"
        if reason:
            self.notes = f"{self.notes}\nCancelled: {reason}".strip()
        self.save(update_fields=["status", "notes", "updated_at"])


class TriageVitalThreshold(models.Model):
    """
    Configurable thresholds for vital sign alerts.
    Can be customized per facility or use system defaults.
    """

    VITAL_TYPE_CHOICES = [
        ("SPO2", "Oxygen Saturation (%)"),
        ("SYSTOLIC_BP", "Systolic Blood Pressure (mmHg)"),
        ("DIASTOLIC_BP", "Diastolic Blood Pressure (mmHg)"),
        ("HEART_RATE", "Heart Rate (bpm)"),
        ("TEMPERATURE", "Temperature (°C)"),
        ("RESPIRATORY_RATE", "Respiratory Rate (breaths/min)"),
    ]

    vital_type = models.CharField(
        max_length=30,
        choices=VITAL_TYPE_CHOICES,
        unique=True,
        help_text="Type of vital sign",
    )
    critical_low = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Value below this triggers critical alert",
    )
    warning_low = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Value below this triggers warning",
    )
    warning_high = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Value above this triggers warning",
    )
    critical_high = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Value above this triggers critical alert",
    )
    is_active = models.BooleanField(default=True, help_text="Whether this threshold is active")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Triage Vital Threshold"
        verbose_name_plural = "Triage Vital Thresholds"
        ordering = ["vital_type"]

    def __str__(self) -> str:
        display = getattr(self, "get_vital_type_display", lambda: self.vital_type)
        return f"{display()} Threshold"

    @classmethod
    def get_defaults(cls) -> dict:
        """Return default threshold values for all vital types."""
        return {
            "SPO2": {"critical_low": 90, "warning_low": 95},
            "SYSTOLIC_BP": {
                "critical_high": 180,
                "critical_low": 90,
                "warning_high": 140,
                "warning_low": 100,
            },
            "DIASTOLIC_BP": {"critical_high": 120, "warning_high": 90},
            "HEART_RATE": {
                "critical_high": 150,
                "critical_low": 40,
                "warning_high": 100,
                "warning_low": 50,
            },
            "TEMPERATURE": {
                "critical_high": 40.0,
                "critical_low": 32.0,
                "warning_high": 37.5,
                "warning_low": 36.0,
            },
            "RESPIRATORY_RATE": {
                "critical_high": 30,
                "critical_low": 8,
                "warning_high": 24,
                "warning_low": 10,
            },
        }

    def check_value(self, value: Decimal) -> str:
        """
        Check a vital value against thresholds.

        Args:
            value: The vital value to check

        Returns:
            str: 'critical', 'warning', or 'normal'
        """
        if value is None:
            return "normal"

        # Check critical thresholds first
        if self.critical_low is not None and value < self.critical_low:
            return "critical"
        if self.critical_high is not None and value > self.critical_high:
            return "critical"

        # Check warning thresholds
        if self.warning_low is not None and value < self.warning_low:
            return "warning"
        if self.warning_high is not None and value > self.warning_high:
            return "warning"

        return "normal"


class TriageAssessment(models.Model):
    """
    Triage assessment linked to an encounter.
    Captures initial patient assessment and KETA priority categorization.
    """

    # Chief Complaint Categories
    CHIEF_COMPLAINT_CHOICES = [
        ("CHEST_PAIN", "Chest Pain"),
        ("DIFFICULTY_BREATHING", "Difficulty Breathing"),
        ("TRAUMA", "Trauma/Injury"),
        ("FEVER", "Fever"),
        ("ABDOMINAL_PAIN", "Abdominal Pain"),
        ("HEADACHE", "Headache"),
        ("ALTERED_CONSCIOUSNESS", "Altered Consciousness"),
        ("BLEEDING", "Bleeding"),
        ("POISONING", "Poisoning/Overdose"),
        ("OBSTETRIC", "Obstetric Emergency"),
        ("PEDIATRIC", "Pediatric Emergency"),
        # Neonatal-specific (<1 month)
        ("NEONATAL_SEPSIS", "Neonatal Sepsis"),
        ("NEONATAL_JAUNDICE", "Neonatal Jaundice"),
        ("NEONATAL_RESPIRATORY_DISTRESS", "Neonatal Respiratory Distress"),
        ("BIRTH_ASPHYXIA", "Birth Asphyxia"),
        # Pediatric-specific (1-12y)
        ("FEBRILE_CONVULSION", "Febrile Convulsion"),
        ("CROUP", "Croup"),
        ("BRONCHIOLITIS", "Bronchiolitis"),
        ("SEVERE_MALARIA", "Severe Malaria"),
        ("OTHER", "Other"),
    ]

    # AVPU Mental Status Scale
    MENTAL_STATUS_CHOICES = [
        ("A", "Alert"),
        ("V", "Responds to Voice"),
        ("P", "Responds to Pain"),
        ("U", "Unresponsive"),
    ]

    # Mobility Status
    MOBILITY_CHOICES = [
        ("AMBULATORY", "Ambulatory"),
        ("WHEELCHAIR", "Wheelchair"),
        ("STRETCHER", "Stretcher"),
        ("IMMOBILE", "Immobile/Carried"),
    ]

    # Arrival Mode
    ARRIVAL_MODE_CHOICES = [
        ("WALK_IN", "Walk-in"),
        ("AMBULANCE", "Ambulance"),
        ("POLICE", "Police"),
        ("REFERRAL", "Referral from another facility"),
        ("OTHER", "Other"),
    ]

    # KETA Triage Categories (Kenya Emergency Triage Assessment)
    TRIAGE_CATEGORY_CHOICES = [
        ("RED", "Emergency - Immediate"),
        ("ORANGE", "Very Urgent - <10 min"),
        ("YELLOW", "Urgent - <60 min"),
        ("GREEN", "Standard - <240 min"),
        ("BLUE", "Non-Urgent/Referral"),
    ]

    # Care Area Assignment
    ASSIGNED_AREA_CHOICES = [
        ("ER_RESUS", "ER - Resuscitation"),
        ("ER_ACUTE", "ER - Acute Care"),
        ("ER_FAST_TRACK", "ER - Fast Track"),
        ("OBSERVATION", "Observation Unit"),
        ("OPD", "Outpatient Department"),
        ("TRAUMA", "Trauma Bay"),
        ("PEDIATRIC_ER", "Pediatric ER"),
        ("MATERNITY", "Maternity/Labor"),
        ("SPECIALTY", "Specialty Clinic"),
    ]

    # Target wait times by category (in minutes)
    TARGET_WAIT_TIMES = {
        "RED": 0,  # Immediate
        "ORANGE": 10,  # Very Urgent
        "YELLOW": 60,  # Urgent
        "GREEN": 240,  # Standard
        "BLUE": 480,  # Non-Urgent
    }

    # Category priority for sorting (lower number = higher priority)
    CATEGORY_PRIORITY = {
        "RED": 1,
        "ORANGE": 2,
        "YELLOW": 3,
        "GREEN": 4,
        "BLUE": 5,
    }

    # Core Relationship
    organization = models.ForeignKey(
        "core.Organization",
        on_delete=models.CASCADE,
        related_name="triage_assessments",
        null=True,
        blank=True,
        help_text="Owning organization (auto-set from facility).",
    )
    facility = models.ForeignKey(
        "core.Facility",
        on_delete=models.CASCADE,
        related_name="triage_assessments",
        null=True,
        blank=True,
        help_text="Facility where triage was performed.",
    )
    encounter = models.OneToOneField(
        "encounters.Encounter", on_delete=models.CASCADE, related_name="triage_assessment"
    )

    # Clinical Assessment
    chief_complaint = models.TextField(help_text="Primary reason for visit")
    chief_complaint_category = models.CharField(
        max_length=50, choices=CHIEF_COMPLAINT_CHOICES, help_text="Chief complaint category"
    )
    pain_score = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(10)],
        null=True,
        blank=True,
        help_text="Pain level 0-10",
    )
    mental_status = models.CharField(
        max_length=1, choices=MENTAL_STATUS_CHOICES, help_text="AVPU mental status scale"
    )

    # Glasgow Coma Scale (GCS) - optional detailed neurological assessment
    # Used for trauma, head injury, and altered consciousness cases
    gcs_eye = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(4)],
        null=True,
        blank=True,
        help_text="Eye response: 1=None, 2=To pain, 3=To voice, 4=Spontaneous",
    )
    gcs_verbal = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        null=True,
        blank=True,
        help_text="Verbal response: 1=None, 2=Sounds, 3=Words, 4=Confused, 5=Oriented",
    )
    gcs_motor = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(6)],
        null=True,
        blank=True,
        help_text="Motor response: 1=None, 2=Extension, 3=Flexion, 4=Withdrawal, 5=Localizes, 6=Obeys",
    )

    mobility = models.CharField(
        max_length=20, choices=MOBILITY_CHOICES, help_text="Patient mobility status"
    )
    arrival_mode = models.CharField(
        max_length=20,
        choices=ARRIVAL_MODE_CHOICES,
        default="WALK_IN",
        help_text="How patient arrived",
    )
    referring_facility_name = models.CharField(
        max_length=255,
        blank=True,
        default="",
        help_text="Name of referring facility (required when arrival_mode is REFERRAL)",
    )
    allergies_noted = models.TextField(
        blank=True,
        default="",
        help_text="Allergies noted at triage (snapshot from patient record)",
    )

    # Vital Signs (captured at triage)
    # All vitals are optional (some facilities may not have all equipment)
    spo2 = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text="Oxygen saturation percentage (SpO2)",
    )
    heart_rate = models.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(300)],
        help_text="Heart rate (beats per minute)",
    )
    systolic_bp = models.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(300)],
        help_text="Systolic blood pressure (mmHg)",
    )
    diastolic_bp = models.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(200)],
        help_text="Diastolic blood pressure (mmHg)",
    )
    temperature = models.DecimalField(
        max_digits=4,
        decimal_places=1,
        null=True,
        blank=True,
        validators=[MinValueValidator(30), MaxValueValidator(45)],
        help_text="Body temperature in Celsius (°C)",
    )
    respiratory_rate = models.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(60)],
        help_text="Respiratory rate (breaths per minute)",
    )
    weight = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(500)],
        help_text="Body weight in kilograms (kg)",
    )
    height = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(300)],
        help_text="Body height in centimeters (cm)",
    )

    # =========================================================================
    # ETAT (Emergency Triage Assessment & Treatment) Fields
    # Used for pediatric patients (<5 years). All nullable — not relevant for adults.
    # =========================================================================

    # ETAT Danger Signs (WHO list for children under 5)
    etat_danger_signs = models.JSONField(
        default=list,
        blank=True,
        help_text=(
            "ETAT danger signs present (list of strings). "
            "Valid values: unable_to_drink, convulsions, lethargy, chest_indrawing, "
            "stridor, severe_malnutrition, grunting, cyanosis, severe_pallor, hypothermia"
        ),
    )

    # WHO Dehydration Assessment
    DEHYDRATION_CHOICES = [
        ("NONE", "No dehydration"),
        ("SOME", "Some dehydration"),
        ("SEVERE", "Severe dehydration"),
    ]
    dehydration_level = models.CharField(
        max_length=10,
        choices=DEHYDRATION_CHOICES,
        blank=True,
        default="",
        help_text="WHO dehydration classification (children)",
    )

    # Fontanelle status (relevant for <18 months)
    FONTANELLE_CHOICES = [
        ("NORMAL", "Normal"),
        ("BULGING", "Bulging"),
        ("SUNKEN", "Sunken"),
    ]
    fontanelle_status = models.CharField(
        max_length=10,
        choices=FONTANELLE_CHOICES,
        blank=True,
        default="",
        help_text="Anterior fontanelle status (for infants <18 months)",
    )

    # Breastfeeding ability (relevant for infants)
    BREASTFEEDING_CHOICES = [
        ("NORMAL", "Normal / able to feed"),
        ("REDUCED", "Reduced / poor feeding"),
        ("UNABLE", "Unable to breastfeed / drink"),
    ]
    breastfeeding_ability = models.CharField(
        max_length=10,
        choices=BREASTFEEDING_CHOICES,
        blank=True,
        default="",
        help_text="Breastfeeding / feeding ability (for infants)",
    )

    # Capillary refill time (relevant for children; adults use MAP)
    capillary_refill_seconds = models.IntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(15)],
        help_text="Capillary refill time in seconds (prolonged ≥3s is abnormal)",
    )

    # MUAC for children 6-59 months
    muac_cm = models.DecimalField(
        max_digits=4,
        decimal_places=1,
        null=True,
        blank=True,
        validators=[MinValueValidator(0), MaxValueValidator(30)],
        help_text="Mid-Upper Arm Circumference in cm (SAM <11.5, MAM 11.5-12.4)",
    )

    # Triage Decision
    triage_category = models.CharField(
        max_length=10, choices=TRIAGE_CATEGORY_CHOICES, help_text="Final triage category"
    )
    auto_calculated_category = models.CharField(
        max_length=10,
        choices=TRIAGE_CATEGORY_CHOICES,
        help_text="System-suggested category before nurse override",
    )
    category_override_reason = models.TextField(
        blank=True,
        default="",
        help_text="Required if nurse overrides system suggestion",
    )

    # Routing
    # Option 1: Emergency area (ER zones - no clinic association)
    assigned_area = models.CharField(
        max_length=30,
        choices=ASSIGNED_AREA_CHOICES,
        blank=True,
        default="",
        help_text="Emergency care area assignment (ER zones). Use for emergency cases.",
    )
    # Option 2: Clinic assignment (for OPD/specialty clinics)
    assigned_clinic = models.ForeignKey(
        "clinics.Clinic",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="triage_assignments",
        help_text="Target clinic for routing. Mutually exclusive with assigned_area.",
    )
    assigned_clinician = models.ForeignKey(
        "auth.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="triage_clinician_assignments",
        help_text="Clinician assigned to this patient",
    )

    # Critical Timestamps
    arrival_time = models.DateTimeField(help_text="When patient arrived at facility")
    triage_start_time = models.DateTimeField(help_text="When triage assessment began")
    triage_end_time = models.DateTimeField(null=True, blank=True, help_text="When triage completed")
    seen_by_clinician_time = models.DateTimeField(
        null=True, blank=True, help_text="When patient was seen by clinician"
    )

    # Alerts
    alerts = models.JSONField(
        default=list, help_text="List of critical alerts generated", blank=True
    )

    # Audit
    triaged_by = models.ForeignKey(
        "auth.User",
        on_delete=models.PROTECT,
        related_name="triage_assessments_performed",
        help_text="User who performed triage",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-arrival_time"]
        verbose_name = "Triage Assessment"
        verbose_name_plural = "Triage Assessments"
        permissions = [
            ("perform_triage", "Can perform triage assessments"),
            ("view_triage_queue", "Can view triage queue"),
            ("override_triage_category", "Can override triage category"),
        ]

    def clean(self):
        """
        Validate that either assigned_area OR assigned_clinic is provided, not both.
        Emergency areas (ER zones) use assigned_area.
        OPD/specialty routing uses assigned_clinic.
        """
        from django.core.exceptions import ValidationError

        has_area = bool(self.assigned_area)
        has_clinic = self.assigned_clinic_id is not None

        if not has_area and not has_clinic:
            raise ValidationError(
                "Either 'assigned_area' (for ER zones) or 'assigned_clinic' (for clinics) must be provided."
            )

        if has_area and has_clinic:
            raise ValidationError(
                "Cannot set both 'assigned_area' and 'assigned_clinic'. Choose one routing option."
            )

    def __str__(self) -> str:
        return f"Triage {self.triage_category} - {self.encounter.patient} - {self.arrival_time}"

    def save(self, *args, **kwargs):
        """Auto-resolve tenant (facility/organization) from encounter."""
        if not self.facility_id and self.encounter_id:
            try:
                enc = self.encounter
                if enc.facility_id:
                    self.facility_id = enc.facility_id
            except Exception:
                pass
        if self.facility_id and not self.organization_id:
            try:
                fac = self.facility
                if fac and fac.organization_id:
                    self.organization_id = fac.organization_id
            except Exception:
                pass
        # Last resort: inherit from patient
        if not self.facility_id and self.encounter_id:
            try:
                patient = self.encounter.patient
                if patient.registered_at_facility_id:
                    self.facility_id = patient.registered_at_facility_id
                if patient.organization_id:
                    self.organization_id = patient.organization_id
            except Exception:
                pass
        super().save(*args, **kwargs)

    @property
    def routing_destination(self) -> str:
        """Get human-readable routing destination."""
        if self.assigned_clinic:
            return self.assigned_clinic.name
        if self.assigned_area:
            return dict(self.ASSIGNED_AREA_CHOICES).get(self.assigned_area, self.assigned_area)
        return "Not assigned"

    @property
    def category_priority(self) -> int:
        """Get numeric priority for sorting (lower = higher priority)."""
        return self.CATEGORY_PRIORITY.get(self.triage_category, 99)

    @property
    def gcs_total(self) -> int | None:
        """
        Calculate total Glasgow Coma Scale score (3-15).
        Returns None if any component is missing.
        """
        if all([self.gcs_eye, self.gcs_verbal, self.gcs_motor]):
            return self.gcs_eye + self.gcs_verbal + self.gcs_motor
        return None

    @property
    def gcs_severity(self) -> str | None:
        """
        Get GCS severity classification.
        Returns: 'severe' (3-8), 'moderate' (9-12), 'mild' (13-15), or None.
        """
        total = self.gcs_total
        if total is None:
            return None
        if total <= 8:
            return "severe"
        if total <= 12:
            return "moderate"
        return "mild"

    def calculate_triage_category(self) -> str:
        """
        Calculate triage category based on vitals and symptoms.
        Returns suggested KETA category (RED/ORANGE/YELLOW/GREEN/BLUE).
        """
        vitals = {}

        # Get vitals from encounter
        if hasattr(self.encounter, "spo2") and self.encounter.spo2:
            vitals["spo2"] = self.encounter.spo2
        if hasattr(self.encounter, "pulse") and self.encounter.pulse:
            vitals["heart_rate"] = self.encounter.pulse
        if hasattr(self.encounter, "blood_pressure") and self.encounter.blood_pressure:
            # Parse blood pressure (format: "120/80")
            bp_parts = self.encounter.blood_pressure.split("/")
            if len(bp_parts) == 2:
                try:
                    vitals["systolic_bp"] = int(bp_parts[0])
                    vitals["diastolic_bp"] = int(bp_parts[1])
                except ValueError:
                    pass

        # Check RED criteria (immediate)
        if self.mental_status in ["U", "P"]:
            return "RED"

        if vitals.get("spo2") and vitals["spo2"] < 90:
            return "RED"

        if vitals.get("systolic_bp"):
            if vitals["systolic_bp"] < 90 or vitals["systolic_bp"] > 180:
                return "RED"

        if vitals.get("heart_rate"):
            if vitals["heart_rate"] < 40 or vitals["heart_rate"] > 150:
                return "RED"

        # Check ORANGE criteria (very urgent)
        if self.chief_complaint_category == "CHEST_PAIN" and (
            vitals.get("systolic_bp", 0) > 140 or self.pain_score and self.pain_score >= 7
        ):
            return "ORANGE"

        if (
            self.chief_complaint_category == "DIFFICULTY_BREATHING"
            and vitals.get("spo2")
            and vitals["spo2"] < 95
        ):
            return "ORANGE"

        if self.pain_score and self.pain_score >= 9:
            return "ORANGE"

        # Check YELLOW criteria (urgent)
        if self.pain_score and self.pain_score >= 7:
            return "YELLOW"

        if self.chief_complaint_category == "FEVER" and vitals.get("spo2") and vitals["spo2"] < 95:
            return "YELLOW"

        # GREEN (standard)
        if self.chief_complaint_category in ["FEVER", "HEADACHE", "ABDOMINAL_PAIN"]:
            return "GREEN"

        # BLUE (non-urgent)
        return "BLUE"

    def get_wait_time_minutes(self) -> int:
        """Calculate time in minutes since arrival."""
        now = timezone.now()
        delta = now - self.arrival_time
        return int(delta.total_seconds() / 60)

    def is_wait_time_exceeded(self) -> bool:
        """Check if patient has exceeded target wait time for their category."""
        target = self.TARGET_WAIT_TIMES.get(self.triage_category, 240)
        wait_time = self.get_wait_time_minutes()
        return wait_time > target

    def generate_alerts(self) -> list[str]:
        """Generate alerts based on vitals and symptoms."""
        alerts = []

        # Mental status alerts
        if self.mental_status == "U":
            alerts.append("CRITICAL: Patient unresponsive (AVPU=U)")
        elif self.mental_status == "P":
            alerts.append("CRITICAL: Patient only responds to pain (AVPU=P)")
        elif self.mental_status == "V":
            alerts.append("WARNING: Patient only responds to voice (AVPU=V)")

        # Get vitals from encounter
        if hasattr(self.encounter, "spo2") and self.encounter.spo2:
            if self.encounter.spo2 < 90:
                alerts.append(f"CRITICAL: Severe hypoxemia (SpO2 {self.encounter.spo2}%)")
            elif self.encounter.spo2 < 95:
                alerts.append(f"WARNING: Low oxygen saturation (SpO2 {self.encounter.spo2}%)")

        if hasattr(self.encounter, "pulse") and self.encounter.pulse:
            if self.encounter.pulse < 40:
                alerts.append(f"CRITICAL: Severe bradycardia (HR {self.encounter.pulse} bpm)")
            elif self.encounter.pulse > 150:
                alerts.append(f"CRITICAL: Severe tachycardia (HR {self.encounter.pulse} bpm)")
            elif self.encounter.pulse < 50:
                alerts.append(f"WARNING: Bradycardia (HR {self.encounter.pulse} bpm)")
            elif self.encounter.pulse > 100:
                alerts.append(f"WARNING: Tachycardia (HR {self.encounter.pulse} bpm)")

        if hasattr(self.encounter, "blood_pressure") and self.encounter.blood_pressure:
            bp_parts = self.encounter.blood_pressure.split("/")
            if len(bp_parts) == 2:
                try:
                    systolic = int(bp_parts[0])
                    if systolic < 90:
                        alerts.append(
                            f"CRITICAL: Severe hypotension (BP {self.encounter.blood_pressure})"
                        )
                    elif systolic > 180:
                        alerts.append(
                            f"CRITICAL: Severe hypertension (BP {self.encounter.blood_pressure})"
                        )
                    elif systolic > 140:
                        alerts.append(
                            f"WARNING: Elevated blood pressure (BP {self.encounter.blood_pressure})"
                        )
                except ValueError:
                    pass

        # Pain score alerts
        if self.pain_score:
            if self.pain_score >= 9:
                alerts.append(f"CRITICAL: Severe pain (score {self.pain_score}/10)")
            elif self.pain_score >= 7:
                alerts.append(f"WARNING: Significant pain (score {self.pain_score}/10)")

        # Chief complaint specific alerts
        if self.chief_complaint_category == "CHEST_PAIN":
            alerts.append("ALERT: Chest pain - cardiac evaluation recommended")
        elif self.chief_complaint_category == "DIFFICULTY_BREATHING":
            alerts.append("ALERT: Difficulty breathing - respiratory assessment needed")
        elif self.chief_complaint_category == "ALTERED_CONSCIOUSNESS":
            alerts.append("ALERT: Altered consciousness - neurological assessment needed")

        return alerts

    def route_to_clinic(self, clinic, user, notes: str = "") -> "ClinicVisit":
        """
        Route patient from triage to a specific clinic.

        Creates a ClinicVisit in the target clinic's queue with appropriate
        priority based on triage category.

        Args:
            clinic: Target Clinic instance
            user: User performing the routing
            notes: Optional routing notes

        Returns:
            ClinicVisit: The created clinic visit

        Raises:
            ValueError: If clinic is not active or patient already in queue
        """
        from datetime import date

        from hmis.apps.clinics.models import ClinicSession, ClinicVisit

        # Validate clinic is active
        if clinic.status != "ACTIVE":
            raise ValueError(f"Clinic '{clinic.name}' is not active")

        # Get or create today's session for the clinic
        session, created = ClinicSession.objects.get_or_create(
            clinic=clinic,
            session_date=date.today(),
            defaults={"status": "OPEN"},
        )

        # Check if patient is already in this session's queue (not completed/cancelled)
        existing_visit = ClinicVisit.objects.filter(
            session=session,
            patient=self.encounter.patient,
            status__in=["REGISTERED", "WAITING", "CALLED", "IN_CONSULTATION"],
        ).first()

        if existing_visit:
            raise ValueError(
                f"Patient is already in {clinic.name} queue (Queue #{existing_visit.queue_number})"
            )

        # Create clinic visit
        visit = ClinicVisit.objects.create(
            session=session,
            patient=self.encounter.patient,
            encounter=self.encounter,
            triage_assessment=self,
            visit_type="NEW",
            source="TRIAGE",
            chief_complaint=self.chief_complaint,
            priority=self.triage_category,  # Map triage category to priority
            notes=notes or "",
            registered_by=user,
        )

        visit.ensure_consultation_encounter(existing_encounter=self.encounter)

        return visit


class TriageQueue(models.Model):
    """
    Active triage queue entry for a patient awaiting care.
    Removed when patient is seen by clinician or leaves.
    """

    STATUS_CHOICES = [
        ("WAITING", "Waiting"),
        ("CALLED", "Called"),
        ("WITH_CLINICIAN", "With Clinician"),
        ("COMPLETED", "Completed"),
        ("LEFT_WITHOUT_BEING_SEEN", "Left Without Being Seen (LWBS)"),
    ]

    triage_assessment = models.OneToOneField(
        TriageAssessment, on_delete=models.CASCADE, related_name="queue_entry"
    )
    position = models.IntegerField(help_text="Queue position (auto-calculated by priority)")
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default="WAITING")
    called_at = models.DateTimeField(null=True, blank=True)
    called_by = models.ForeignKey(
        "auth.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="queue_calls",
    )
    notes = models.TextField(blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # Note: Ordering by category needs to be done in Python since we need priority-based sorting
        # Default ordering is by arrival time
        ordering = ["triage_assessment__arrival_time"]
        verbose_name = "Triage Queue Entry"
        verbose_name_plural = "Triage Queue Entries"

    def __str__(self) -> str:
        return f"Queue {self.position} - {self.triage_assessment.triage_category} - {self.status}"

    @classmethod
    def get_active_queue(cls, area: str = None):
        """Get active queue entries, optionally filtered by area.

        Returns queryset sorted by triage priority (RED first) then arrival time (FIFO).
        """
        queryset = cls.objects.exclude(
            status__in=["COMPLETED", "LEFT_WITHOUT_BEING_SEEN"]
        ).select_related("triage_assessment")

        if area:
            queryset = queryset.filter(triage_assessment__assigned_area=area)

        # Convert to list and sort by priority then arrival time
        queue_list = list(queryset)
        queue_list.sort(
            key=lambda x: (x.triage_assessment.category_priority, x.triage_assessment.arrival_time)
        )

        return queue_list

    @classmethod
    def recalculate_positions(cls):
        """Recalculate all queue positions based on priority ordering."""
        active_queue = cls.get_active_queue()
        for index, entry in enumerate(active_queue, start=1):
            entry.position = index
            entry.save(update_fields=["position"])

    def mark_called(self, called_by):
        """Mark patient as called."""
        self.status = "CALLED"
        self.called_at = timezone.now()
        self.called_by = called_by
        self.save(update_fields=["status", "called_at", "called_by"])

    def mark_with_clinician(self):
        """Mark patient as with clinician, update triage timestamps."""
        self.status = "WITH_CLINICIAN"
        self.save(update_fields=["status"])

        # Update assessment timestamp
        self.triage_assessment.seen_by_clinician_time = timezone.now()
        self.triage_assessment.save(update_fields=["seen_by_clinician_time"])

    def mark_completed(self):
        """Mark queue entry as completed."""
        self.status = "COMPLETED"
        self.save(update_fields=["status"])

    def mark_lwbs(self, reason: str = ""):
        """Mark patient as Left Without Being Seen."""
        self.status = "LEFT_WITHOUT_BEING_SEEN"
        if reason:
            self.notes = f"{self.notes}\nLWBS Reason: {reason}".strip()
        self.save(update_fields=["status", "notes"])


class ERBed(models.Model):
    """
    Emergency Room bed/bay.

    Represents a physical bed or bay in the emergency department,
    organized by zone. Separate from the inpatient Bed model because
    ER beds have zone-based organization, shorter stays, and different
    workflow (rapid turnover, cleaning states).

    Phase 3: ER Bed Board
    """

    ZONE_CHOICES = [
        ("ER_RESUS", "ER - Resuscitation"),
        ("ER_ACUTE", "ER - Acute Care"),
        ("ER_FAST_TRACK", "ER - Fast Track"),
        ("OBSERVATION", "Observation Unit"),
        ("TRAUMA", "Trauma Bay"),
        ("PEDIATRIC_ER", "Pediatric ER"),
        ("MATERNITY", "Maternity/Labor"),
    ]

    BED_STATUS_CHOICES = [
        ("AVAILABLE", "Available"),
        ("OCCUPIED", "Occupied"),
        ("CLEANING", "Cleaning"),
        ("OUT_OF_SERVICE", "Out of Service"),
    ]

    zone = models.CharField(
        max_length=20,
        choices=ZONE_CHOICES,
        help_text="ER zone this bed belongs to",
    )
    bed_number = models.CharField(
        max_length=20,
        help_text="Bed/bay identifier within zone (e.g., 'R-01', 'A-05')",
    )
    status = models.CharField(
        max_length=20,
        choices=BED_STATUS_CHOICES,
        default="AVAILABLE",
        help_text="Current bed status",
    )
    current_patient = models.ForeignKey(
        "patients.Patient",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="er_beds",
        help_text="Patient currently occupying this bed",
    )
    current_triage_assessment = models.ForeignKey(
        TriageAssessment,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="er_bed_assignment",
        help_text="Triage assessment for current occupant",
    )
    notes = models.TextField(
        blank=True,
        default="",
        help_text="Additional notes (cleaning reason, out-of-service reason, etc.)",
    )
    status_changed_at = models.DateTimeField(
        auto_now=True,
        help_text="When the bed status last changed",
    )
    status_changed_by = models.ForeignKey(
        "auth.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="er_bed_status_changes",
        help_text="User who last changed the bed status",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ["zone", "bed_number"]
        ordering = ["zone", "bed_number"]
        verbose_name = "ER Bed"
        verbose_name_plural = "ER Beds"

    def __str__(self) -> str:
        zone_display = dict(self.ZONE_CHOICES).get(self.zone, self.zone)
        return f"{zone_display} - {self.bed_number} ({self.get_status_display()})"

    # -------------------------------------------------------------------------
    # State-transition methods
    # -------------------------------------------------------------------------

    def assign_patient(self, patient, triage_assessment=None, user=None):
        """
        Assign a patient to this bed, transitioning to OCCUPIED.

        Args:
            patient: Patient instance to assign
            triage_assessment: Optional TriageAssessment for the patient
            user: User performing the assignment

        Raises:
            ValueError: If bed is not available
        """
        if self.status != "AVAILABLE":
            raise ValueError(
                f"Cannot assign patient to bed {self.bed_number}: "
                f"status is {self.status}, must be AVAILABLE"
            )
        self.status = "OCCUPIED"
        self.current_patient = patient
        self.current_triage_assessment = triage_assessment
        self.status_changed_by = user
        self.save(
            update_fields=[
                "status",
                "current_patient",
                "current_triage_assessment",
                "status_changed_by",
                "status_changed_at",
            ]
        )

    def release(self, user=None, mark_cleaning=True):
        """
        Release a patient from this bed.

        Args:
            user: User performing the release
            mark_cleaning: If True, transition to CLEANING; otherwise AVAILABLE

        Raises:
            ValueError: If bed is not occupied
        """
        if self.status != "OCCUPIED":
            raise ValueError(
                f"Cannot release bed {self.bed_number}: "
                f"status is {self.status}, must be OCCUPIED"
            )
        self.status = "CLEANING" if mark_cleaning else "AVAILABLE"
        self.current_patient = None
        self.current_triage_assessment = None
        self.status_changed_by = user
        self.notes = ""
        self.save(
            update_fields=[
                "status",
                "current_patient",
                "current_triage_assessment",
                "status_changed_by",
                "status_changed_at",
                "notes",
            ]
        )

    def mark_available(self, user=None):
        """
        Mark bed as available (e.g., after cleaning).

        Raises:
            ValueError: If bed is currently occupied
        """
        if self.status == "OCCUPIED":
            raise ValueError(
                f"Cannot mark bed {self.bed_number} as available: "
                "still occupied — release patient first"
            )
        self.status = "AVAILABLE"
        self.current_patient = None
        self.current_triage_assessment = None
        self.status_changed_by = user
        self.notes = ""
        self.save(
            update_fields=[
                "status",
                "current_patient",
                "current_triage_assessment",
                "status_changed_by",
                "status_changed_at",
                "notes",
            ]
        )

    def mark_out_of_service(self, user=None, reason=""):
        """
        Mark bed as out of service.

        Args:
            user: User performing the action
            reason: Reason for taking out of service

        Raises:
            ValueError: If bed is currently occupied
        """
        if self.status == "OCCUPIED":
            raise ValueError(
                f"Cannot take bed {self.bed_number} out of service: "
                "still occupied — release patient first"
            )
        self.status = "OUT_OF_SERVICE"
        self.status_changed_by = user
        self.notes = reason
        self.save(update_fields=["status", "status_changed_by", "status_changed_at", "notes"])

    # -------------------------------------------------------------------------
    # Properties
    # -------------------------------------------------------------------------

    @property
    def is_available(self) -> bool:
        """Whether the bed is available for patient assignment."""
        return self.status == "AVAILABLE"

    @property
    def patient_name(self) -> str:
        """Display name of the current patient, or empty string."""
        if self.current_patient:
            return f"{self.current_patient.first_name} {self.current_patient.last_name}"
        return ""

    @property
    def patient_mrn(self) -> str:
        """MRN of the current patient, or empty string."""
        if self.current_patient:
            return self.current_patient.mrn
        return ""

    @property
    def triage_category(self) -> str:
        """Triage category of the current occupant, or empty string."""
        if self.current_triage_assessment:
            return self.current_triage_assessment.triage_category
        return ""

    @property
    def occupied_duration_minutes(self) -> int | None:
        """Minutes since bed was occupied (None if not occupied)."""
        if self.status != "OCCUPIED":
            return None
        delta = timezone.now() - self.status_changed_at
        return int(delta.total_seconds() / 60)


# =============================================================================
# Triage Room Routing Settings
# =============================================================================


class TriageSettings(models.Model):
    """
    Per-facility triage settings.

    Controls auto-routing of patients to triage rooms when they check in
    to the waiting queue.
    """

    facility = models.OneToOneField(
        "core.Facility",
        on_delete=models.CASCADE,
        related_name="triage_settings",
        help_text="Facility these settings belong to.",
    )
    auto_route_to_room = models.BooleanField(
        default=False,
        help_text=(
            "When enabled, patients checking in are automatically assigned "
            "to a triage room that has capacity and an active (clocked-in) staff member."
        ),
    )
    triage_department = models.ForeignKey(
        "core.Department",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
        help_text=(
            "Department used to identify triage rooms. "
            "Only PLACE resources in this department are considered for auto-routing."
        ),
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Triage Settings"
        verbose_name_plural = "Triage Settings"

    def __str__(self) -> str:
        fac = getattr(self, "facility", None)
        return f"Triage Settings ({fac})" if fac else "Triage Settings"
