# Copyright (c) 2026 Nexora Consulting Ltd. All rights reserved.
# ruff: noqa
"""Inventory models forecasting for Vitora HMIS.

What this file is for:
- Implement models forecasting logic for the inventory domain.

How to use it:
- Import classes and functions from this module in Django app code and tests.

Supported inputs/args:
- Python imports and Django ORM/runtime inputs; no standalone CLI arguments.
"""

from django.conf import settings
from django.db import models

from hmis.apps.core.mixins import FacilityScopedModel
from hmis.apps.core.models import TimeStampedModel

# ---------------------------------------------------------------------------
# Auto-number generators
# ---------------------------------------------------------------------------
from hmis.apps.inventory.models_counts_etims import *  # noqa: F403
from hmis.apps.inventory.models_procurement import *  # noqa: F403
from hmis.apps.inventory.models_stock_flow import *  # noqa: F403


class ForecastMethod(models.TextChoices):
    MOVING_AVERAGE = "MOVING_AVERAGE", "Moving Average"
    EXPONENTIAL_SMOOTHING = "EXPONENTIAL_SMOOTHING", "Exponential Smoothing"
    SEASONAL = "SEASONAL", "Seasonal"


class ReorderUrgency(models.TextChoices):
    CRITICAL = "CRITICAL", "Critical"
    HIGH = "HIGH", "High"
    MEDIUM = "MEDIUM", "Medium"
    LOW = "LOW", "Low"


class ReorderStatus(models.TextChoices):
    PENDING = "PENDING", "Pending"
    CONVERTED_TO_PO = "CONVERTED_TO_PO", "Converted to PO"
    DISMISSED = "DISMISSED", "Dismissed"


class ConsumptionRecord(FacilityScopedModel, TimeStampedModel):
    """
    Aggregated consumption data for a drug over a period.

    Auto-generated from Dispensing and StockAdjustment records by management
    commands or Celery tasks. Used as input for demand forecasting.
    """

    drug = models.ForeignKey(
        "pharmacy.Drug",
        on_delete=models.PROTECT,
        related_name="consumption_records",
    )
    period_start = models.DateField()
    period_end = models.DateField()
    quantity_dispensed = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
        help_text="Total quantity dispensed in the period.",
    )
    quantity_transferred = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
        help_text="Net transfer quantity (out - in) in the period.",
    )
    quantity_adjusted = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0,
        help_text="Net adjustment quantity (damage, loss, expiry) in the period.",
    )

    class Meta:
        ordering = ["-period_end"]
        constraints = [
            models.UniqueConstraint(
                fields=["facility", "drug", "period_start", "period_end"],
                name="unique_consumption_per_drug_period",
            ),
        ]

    def __str__(self):
        return f"{self.drug.generic_name} consumption {self.period_start} – {self.period_end}"

    @property
    def total_consumption(self):
        """Total units consumed in the period (dispensed + outbound adjustments)."""
        return self.quantity_dispensed + self.quantity_adjusted

    @property
    def average_daily_consumption(self):
        """Average daily consumption based on period length."""
        days = (self.period_end - self.period_start).days
        if days <= 0:
            return self.total_consumption
        return self.total_consumption / days


class DemandForecast(FacilityScopedModel, TimeStampedModel):
    """
    Predicted demand for a drug over a future period.

    Generated by the forecasting service using historical ConsumptionRecords.
    """

    drug = models.ForeignKey(
        "pharmacy.Drug",
        on_delete=models.PROTECT,
        related_name="demand_forecasts",
    )
    forecast_date = models.DateField(
        help_text="Date this forecast was generated.",
    )
    period_months = models.PositiveIntegerField(
        default=3,
        help_text="Forecast horizon in months (e.g. 3, 6, 12).",
    )
    predicted_demand = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        help_text="Predicted total demand for the period.",
    )
    confidence_lower = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Lower bound of 95% confidence interval.",
    )
    confidence_upper = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Upper bound of 95% confidence interval.",
    )
    method = models.CharField(
        max_length=25,
        choices=ForecastMethod.choices,
        default=ForecastMethod.MOVING_AVERAGE,
    )
    reorder_point = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Computed: lead_time_demand + safety_stock.",
    )
    suggested_order_quantity = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="demand_forecasts_generated",
        help_text="User who triggered generation, or null for system-generated.",
    )

    class Meta:
        ordering = ["-forecast_date", "-created_at"]

    def __str__(self):
        return f"{self.drug.generic_name} forecast {self.forecast_date} ({self.period_months}m)"


class ReorderSuggestion(FacilityScopedModel, TimeStampedModel):
    """
    Suggested reorder for a drug based on demand forecast vs current stock.

    Can be converted into a PurchaseOrder via the convert_to_po action.
    """

    drug = models.ForeignKey(
        "pharmacy.Drug",
        on_delete=models.PROTECT,
        related_name="reorder_suggestions",
    )
    supplier = models.ForeignKey(
        "inventory.Supplier",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reorder_suggestions",
    )
    current_stock = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        help_text="Stock on hand at time of suggestion.",
    )
    reorder_point = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        help_text="Stock level that triggers a reorder.",
    )
    suggested_quantity = models.DecimalField(
        max_digits=12,
        decimal_places=2,
    )
    urgency = models.CharField(
        max_length=10,
        choices=ReorderUrgency.choices,
        default=ReorderUrgency.MEDIUM,
    )
    status = models.CharField(
        max_length=18,
        choices=ReorderStatus.choices,
        default=ReorderStatus.PENDING,
    )
    purchase_order = models.ForeignKey(
        "inventory.PurchaseOrder",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reorder_suggestions",
        help_text="Set when converted to a PO.",
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return (
            f"{self.drug.generic_name} – {self.get_urgency_display()} "
            f"({self.suggested_quantity} units)"
        )

    def dismiss(self):
        """Mark suggestion as dismissed."""
        self.status = ReorderStatus.DISMISSED
        self.save(update_fields=["status", "updated_at"])

    def mark_converted(self, purchase_order):
        """Link to a PO and mark as converted."""
        self.status = ReorderStatus.CONVERTED_TO_PO
        self.purchase_order = purchase_order
        self.save(update_fields=["status", "purchase_order", "updated_at"])
