import { z } from 'zod';

import { EncounterStatusSchema, GenderSchema } from './patient.schema';

export const EncounterTypeSchema = z.enum([
  'OPD',
  'EMERGENCY',
  'IPD',
  'ANC',
  'PAEDIATRIC',
  'DIALYSIS',
  'ONCOLOGY',
  'SCHEDULED_OPD',
  'FOLLOW_UP',
  'CONSULTANT_REVIEW',
  'CHRONIC_STABLE',
  'SPECIALIST_CLINIC',
  'PROCEDURE',
  'DAY_CASE',
  'WARD_ROUND',
  'DISCHARGE_REVIEW',
]);

export const EncounterSchema = z.object({
  id: z.number(),
  patient: z.number(),
  patient_id: z.number().optional().nullable(),
  patient_name: z.string().optional().nullable(),
  patient_mrn: z.string().optional().nullable(),
  patient_gender: GenderSchema.optional().nullable(),
  patient_date_of_birth: z.string().optional().nullable(),
  patient_age: z.number().optional().nullable(),
  encounter_type: EncounterTypeSchema,
  encounter_type_display: z.string().optional().nullable(),
  encounter_date: z.string(),
  chief_complaint: z.string(),
  status: EncounterStatusSchema,
  arrival_time: z.string().optional().nullable(),
  temperature: z.number().optional().nullable(),
  pulse: z.number().optional().nullable(),
  blood_pressure: z.string().optional().nullable(),
  systolic_bp: z.number().optional().nullable(),
  diastolic_bp: z.number().optional().nullable(),
  respiratory_rate: z.number().optional().nullable(),
  spo2: z.number().optional().nullable(),
  vitals_source: z.string().optional().nullable(),
  vitals_recorded_by: z.number().optional().nullable(),
  vitals_recorded_at: z.string().optional().nullable(),
  weight: z.number().optional().nullable(),
  height: z.number().optional().nullable(),
  bmi: z.number().optional().nullable(),
  bmi_classification: z.string().optional().nullable(),
  vitals_summary: z.string().optional().nullable(),
  has_critical_vitals: z.boolean().optional(),
  alerts: z.string().optional().nullable(),
  allergies: z.string().optional().nullable(),
  chronic_conditions: z.string().optional().nullable(),
  current_medications: z.string().optional().nullable(),
  past_surgeries: z.string().optional().nullable(),
  family_history: z.string().optional().nullable(),
  social_history: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  history_of_present_illness: z.string().optional().nullable(),
  physical_examination: z.string().optional().nullable(),
  assessment: z.string().optional().nullable(),
  clinical_template: z.number().optional().nullable(),
  clinical_template_data: z.record(z.string(), z.unknown()).optional().nullable(),
  disposition: z.string().optional().nullable(),
  disposition_notes: z.string().optional().nullable(),
  cancellation_reason: z.string().optional().nullable(),
  triage_requirement: z.string().optional().nullable(),
  triage_status: z.string().optional().nullable(),
  triage_category: z.string().optional().nullable(),
  triage_completed_at: z.string().optional().nullable(),
  consultation_status: z.string().optional().nullable(),
  linked_encounter: z.number().optional().nullable(),
  visit_reason: z.string().optional().nullable(),
  created_by: z.number().optional().nullable(),
  created_by_name: z.string().optional().nullable(),
  assigned_clinician: z.number().optional().nullable(),
  assigned_clinician_username: z.string().optional().nullable(),
  assigned_clinician_name: z.string().optional().nullable(),
  claimed_at: z.string().optional().nullable(),
  clinic_visit_id: z.number().optional().nullable(),
  clinic_name: z.string().optional().nullable(),
  clinic_type: z.string().optional().nullable(),
  finalized_by: z.number().optional().nullable(),
  finalized_by_username: z.string().optional().nullable(),
  finalized_at: z.string().optional().nullable(),
  created_at: z.string(),
  updated_at: z.string().optional(),
});

export const EncounterTransitionSchema = z.object({
  id: z.number(),
  status: EncounterStatusSchema,
  previous_status: EncounterStatusSchema,
  transitioned_at: z.string(),
  transitioned_by: z.string(),
});

export const ICD10CodeSchema = z.object({
  id: z.number(),
  code: z.string(),
  short_description: z.string().optional().nullable(),
  description: z.string(),
  long_description: z.string().optional().nullable(),
  category: z.string().optional().nullable(),
  chapter: z.string().optional().nullable(),
  is_billable: z.boolean(),
  is_active: z.boolean(),
});

export const PaginatedICD10CodeSchema = z.object({
  count: z.number(),
  next: z.string().nullable(),
  previous: z.string().nullable(),
  results: z.array(ICD10CodeSchema),
});

export const DiagnosisSchema = z.object({
  id: z.number(),
  encounter: z.number(),
  icd10_code: z.number().nullable(),
  icd10_code_display: z.string().optional().nullable(),
  icd10_description: z.string().optional().nullable(),
  icd11_code: z.string().optional().nullable(),
  icd11_display: z.string().optional().nullable(),
  diagnosis_type: z.enum(['PRIMARY', 'SECONDARY', 'DIFFERENTIAL', 'WORKING']),
  free_text_diagnosis: z.string().optional().nullable(),
  notes: z.string(),
  is_confirmed: z.boolean(),
  certainty: z.enum(['suspected', 'probable', 'confirmed', 'ruled_out', 'provisional']),
  diagnosed_by: z.number().optional().nullable(),
  diagnosed_by_name: z.string().optional().nullable(),
  diagnosed_at: z.string().optional().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const PaginatedDiagnosisSchema = z.object({
  count: z.number(),
  next: z.string().nullable(),
  previous: z.string().nullable(),
  results: z.array(DiagnosisSchema),
});

export const MedicationSchema = z.object({
  id: z.number(),
  treatment_plan: z.number(),
  name: z.string(),
  dosage: z.string(),
  frequency: z.string(),
  duration: z.string(),
  route: z.string(),
  quantity: z.string(),
  instructions: z.string(),
  start_date: z.string().optional().nullable(),
  end_date: z.string().optional().nullable(),
  is_active: z.boolean().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const TreatmentPlanSchema = z.object({
  id: z.number(),
  encounter: z.number(),
  template: z.number().optional().nullable(),
  template_name: z.string().optional().nullable(),
  clinical_notes: z.string(),
  medications_json: z.unknown(),
  procedures_json: z.unknown(),
  follow_up_instructions: z.string(),
  follow_up_date: z.string().nullable(),
  diet_recommendations: z.string(),
  activity_restrictions: z.string(),
  referral_needed: z.boolean(),
  referral_specialty: z.string(),
  referral_notes: z.string(),
  status: z.enum(['DRAFT', 'ACTIVE', 'COMPLETED', 'DISCONTINUED']),
  has_follow_up: z.boolean().optional(),
  has_referral: z.boolean().optional(),
  medications: z.array(MedicationSchema),
  created_by: z.number().optional().nullable(),
  created_by_name: z.string().optional().nullable(),
  approved_by: z.number().optional().nullable(),
  approved_by_name: z.string().optional().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const PaginatedEncounterSchema = z.object({
  count: z.number(),
  next: z.string().nullable(),
  previous: z.string().nullable(),
  results: z.array(EncounterSchema),
});