# Generated by Django 5.2.9 on 2026-02-25 21:09

import django.core.validators
import django.db.models.deletion
import hmis.apps.core.history
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0021_change_imaging_order_on_delete"),
        ("clinics", "0009_add_unique_active_patient_per_session"),
        ("encounters", "0023_historicaldiagnosis_historicalencounter"),
        ("patients", "0014_historicalpatient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CounsellingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique counselling type code (e.g., CT-HIV-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Full counselling type name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of counselling service"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HIV", "HIV/AIDS Counselling"),
                            ("MENTAL_HEALTH", "Mental Health Counselling"),
                            ("FAMILY_PLANNING", "Family Planning Counselling"),
                            ("GENERAL", "General Counselling"),
                            ("SUBSTANCE_ABUSE", "Substance Abuse Counselling"),
                            ("GRIEF", "Grief and Bereavement Counselling"),
                            ("TRAUMA", "Trauma Counselling"),
                            ("RELATIONSHIP", "Relationship/Marriage Counselling"),
                            ("ADOLESCENT", "Adolescent Counselling"),
                            ("PRENATAL", "Prenatal/Antenatal Counselling"),
                            ("POSTNATAL", "Postnatal Counselling"),
                            ("NUTRITION", "Nutrition Counselling"),
                            ("CHRONIC_ILLNESS", "Chronic Illness Counselling"),
                            ("PALLIATIVE", "Palliative Care Counselling"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                (
                    "typical_duration_minutes",
                    models.PositiveIntegerField(
                        default=45,
                        help_text="Typical session duration in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "recommended_sessions",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Recommended number of sessions",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "recommended_frequency",
                    models.CharField(
                        default="1x per week",
                        help_text="Recommended session frequency (e.g., '1x per week', 'bi-weekly')",
                        max_length=50,
                    ),
                ),
                (
                    "cost_per_session",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost per session in KES",
                        max_digits=10,
                    ),
                ),
                (
                    "sha_claimable",
                    models.BooleanField(default=True, help_text="Covered by Kenya SHA"),
                ),
                (
                    "sha_intervention_code",
                    models.CharField(
                        blank=True, help_text="SHA intervention code for claims", max_length=50
                    ),
                ),
                (
                    "requires_privacy",
                    models.BooleanField(
                        default=False,
                        help_text="Requires enhanced privacy handling (e.g., HIV, Mental Health)",
                    ),
                ),
                (
                    "requires_referral",
                    models.BooleanField(
                        default=False, help_text="Requires clinical referral before booking"
                    ),
                ),
                (
                    "min_age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum patient age for this counselling type",
                        null=True,
                    ),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum patient age for this counselling type",
                        null=True,
                    ),
                ),
                (
                    "gender_specific",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male only"), ("F", "Female only")],
                        help_text="Gender restriction if applicable",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Counselling Type",
                "verbose_name_plural": "Counselling Types",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="counselling_code_97f636_idx"),
                    models.Index(fields=["category"], name="counselling_categor_7a3c48_idx"),
                    models.Index(fields=["is_active"], name="counselling_is_acti_a52a31_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CounsellingReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("referral_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("HIV_DIAGNOSIS", "New HIV Diagnosis"),
                            ("HIV_ADHERENCE", "HIV Treatment Adherence Support"),
                            ("HIV_PARTNER", "HIV Partner Notification"),
                            ("HIV_PMTCT", "HIV PMTCT Support"),
                            ("DEPRESSION", "Depression"),
                            ("ANXIETY", "Anxiety/Panic Disorder"),
                            ("PTSD", "Post-Traumatic Stress Disorder"),
                            ("SUICIDAL", "Suicidal Ideation/Self-harm"),
                            ("PSYCHOSIS", "Psychosis/Psychiatry Evaluation"),
                            ("SUBSTANCE_ABUSE", "Substance Abuse"),
                            ("FAMILY_PLANNING", "Family Planning Counselling"),
                            ("PREGNANCY", "Pregnancy-related Counselling"),
                            ("GRIEF", "Grief and Bereavement"),
                            ("RELATIONSHIP", "Relationship/Marriage Issues"),
                            ("CHRONIC_ILLNESS", "Chronic Illness Support"),
                            ("ADOLESCENT", "Adolescent Issues"),
                            ("GBV", "Gender-Based Violence"),
                            ("STRESS", "Stress Management"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Primary reason for referral",
                        max_length=30,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent (within 24 hours)"),
                            ("EMERGENCY", "Emergency (immediate - crisis intervention)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "clinical_summary",
                    models.TextField(help_text="Summary of patient's clinical situation"),
                ),
                (
                    "presenting_issues",
                    models.TextField(help_text="Current issues prompting counselling need"),
                ),
                (
                    "goals",
                    models.TextField(blank=True, help_text="Goals for counselling intervention"),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Risk assessment notes (e.g., suicide risk, harm to self/others)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Review"),
                            ("ACCEPTED", "Accepted"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "Patient No Show"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False, help_text="Requires sensitive access permission"
                    ),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Total number of sessions prescribed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "sessions_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of sessions completed"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_notes",
                    models.TextField(blank=True, help_text="Summary notes upon completion"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation if applicable"),
                ),
                (
                    "assigned_counsellor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Counsellor assigned to this referral",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counselling_referrals_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clinic visit for queue management",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counselling_referrals",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counselling_referrals_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source encounter (optional for direct referrals)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counselling_referrals",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counselling_referrals",
                        to="billing.invoice",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counselling_referrals",
                        to="patients.patient",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        help_text="Clinician who made the referral",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counselling_referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counselling_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific counselling type requested",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="counselling.counsellingtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counselling Referral",
                "verbose_name_plural": "Counselling Referrals",
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "view_sensitive_counselling_referral",
                        "Can view sensitive counselling referrals",
                    )
                ],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCounsellingReferral",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("referral_number", models.CharField(db_index=True, editable=False, max_length=30)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("HIV_DIAGNOSIS", "New HIV Diagnosis"),
                            ("HIV_ADHERENCE", "HIV Treatment Adherence Support"),
                            ("HIV_PARTNER", "HIV Partner Notification"),
                            ("HIV_PMTCT", "HIV PMTCT Support"),
                            ("DEPRESSION", "Depression"),
                            ("ANXIETY", "Anxiety/Panic Disorder"),
                            ("PTSD", "Post-Traumatic Stress Disorder"),
                            ("SUICIDAL", "Suicidal Ideation/Self-harm"),
                            ("PSYCHOSIS", "Psychosis/Psychiatry Evaluation"),
                            ("SUBSTANCE_ABUSE", "Substance Abuse"),
                            ("FAMILY_PLANNING", "Family Planning Counselling"),
                            ("PREGNANCY", "Pregnancy-related Counselling"),
                            ("GRIEF", "Grief and Bereavement"),
                            ("RELATIONSHIP", "Relationship/Marriage Issues"),
                            ("CHRONIC_ILLNESS", "Chronic Illness Support"),
                            ("ADOLESCENT", "Adolescent Issues"),
                            ("GBV", "Gender-Based Violence"),
                            ("STRESS", "Stress Management"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Primary reason for referral",
                        max_length=30,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent (within 24 hours)"),
                            ("EMERGENCY", "Emergency (immediate - crisis intervention)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "clinical_summary",
                    models.TextField(help_text="Summary of patient's clinical situation"),
                ),
                (
                    "presenting_issues",
                    models.TextField(help_text="Current issues prompting counselling need"),
                ),
                (
                    "goals",
                    models.TextField(blank=True, help_text="Goals for counselling intervention"),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Risk assessment notes (e.g., suicide risk, harm to self/others)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Review"),
                            ("ACCEPTED", "Accepted"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "Patient No Show"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False, help_text="Requires sensitive access permission"
                    ),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Total number of sessions prescribed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "sessions_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of sessions completed"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_notes",
                    models.TextField(blank=True, help_text="Summary notes upon completion"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation if applicable"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "assigned_counsellor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Counsellor assigned to this referral",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Clinic visit for queue management",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counselling_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Specific counselling type requested",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="counselling.counsellingtype",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Source encounter (optional for direct referrals)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="billing.invoice",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patients.patient",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Clinician who made the referral",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Counselling Referral",
                "verbose_name_plural": "historical Counselling Referrals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCounsellingSession",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("session_number", models.CharField(db_index=True, editable=False, max_length=30)),
                (
                    "session_sequence",
                    models.PositiveIntegerField(
                        default=1, help_text="Session number in the series (1, 2, 3...)"
                    ),
                ),
                ("scheduled_date", models.DateField(help_text="Scheduled date for the session")),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, help_text="Scheduled time for the session", null=True
                    ),
                ),
                (
                    "actual_date",
                    models.DateField(
                        blank=True, help_text="Actual date when session occurred", null=True
                    ),
                ),
                (
                    "actual_start_time",
                    models.TimeField(
                        blank=True, help_text="Actual start time of session", null=True
                    ),
                ),
                (
                    "actual_end_time",
                    models.TimeField(blank=True, help_text="Actual end time of session", null=True),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Actual session duration in minutes",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "Patient No Show"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "pre_session_mood",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Patient's self-reported mood before session (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "pre_session_notes",
                    models.TextField(
                        blank=True, help_text="Notes on patient's presentation before session"
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of session (e.g., 'Individual', 'Group', 'Family')",
                        max_length=50,
                    ),
                ),
                (
                    "topics_discussed",
                    models.TextField(blank=True, help_text="Main topics covered in the session"),
                ),
                (
                    "techniques_used",
                    models.TextField(
                        blank=True, help_text="Therapeutic techniques/interventions used"
                    ),
                ),
                (
                    "client_responses",
                    models.TextField(
                        blank=True, help_text="Patient's responses and reactions during session"
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(
                        blank=True, help_text="Detailed progress notes from the session"
                    ),
                ),
                (
                    "post_session_mood",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Patient's self-reported mood after session (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOOD_PROGRESS", "Good Progress"),
                            ("MODERATE_PROGRESS", "Moderate Progress"),
                            ("LIMITED_PROGRESS", "Limited Progress"),
                            ("NO_PROGRESS", "No Progress"),
                            ("DETERIORATION", "Deterioration"),
                            ("CRISIS_RESOLVED", "Crisis Resolved"),
                            ("CRISIS_ONGOING", "Crisis Ongoing"),
                            ("NEEDS_REFERRAL", "Needs Specialist Referral"),
                            ("PENDING_ASSESSMENT", "Pending Assessment"),
                        ],
                        help_text="Session outcome assessment",
                        max_length=30,
                    ),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Risk assessment notes (suicide, self-harm, harm to others)",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("NONE", "No Risk"),
                            ("LOW", "Low Risk"),
                            ("MODERATE", "Moderate Risk"),
                            ("HIGH", "High Risk"),
                            ("IMMINENT", "Imminent Risk"),
                        ],
                        default="NONE",
                        help_text="Current risk level assessment",
                        max_length=20,
                    ),
                ),
                (
                    "safety_plan",
                    models.TextField(blank=True, help_text="Safety plan if applicable"),
                ),
                (
                    "follow_up_required",
                    models.CharField(
                        choices=[
                            ("CONTINUE", "Continue Sessions as Planned"),
                            ("EXTEND", "Extend Number of Sessions"),
                            ("REDUCE", "Reduce Session Frequency"),
                            ("REFER_PSYCHIATRY", "Refer to Psychiatry"),
                            ("REFER_SOCIAL_WORK", "Refer to Social Work"),
                            ("REFER_PHYSICIAN", "Refer to Physician"),
                            ("DISCHARGE", "Ready for Discharge"),
                            ("CRISIS_PLAN", "Implement Crisis Plan"),
                            ("NONE", "No Follow-up Required"),
                        ],
                        default="CONTINUE",
                        help_text="Recommended follow-up action",
                        max_length=30,
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, help_text="Recommended next session date", null=True
                    ),
                ),
                (
                    "homework",
                    models.TextField(blank=True, help_text="Homework or tasks assigned to patient"),
                ),
                (
                    "goals_for_next_session",
                    models.TextField(blank=True, help_text="Goals to work on in next session"),
                ),
                (
                    "confidentiality_level",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard Confidentiality"),
                            ("RESTRICTED", "Restricted Access"),
                            ("HIGHLY_RESTRICTED", "Highly Restricted (HIV/Mental Health)"),
                        ],
                        default="STANDARD",
                        help_text="Confidentiality level for this session's notes",
                        max_length=20,
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Contains sensitive information requiring restricted access",
                    ),
                ),
                ("is_billed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Associated clinic visit for billing",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "counsellor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Counsellor who conducted the session",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="counselling.counsellingreferral",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Counselling Session",
                "verbose_name_plural": "historical Counselling Sessions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CounsellingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "session_sequence",
                    models.PositiveIntegerField(
                        default=1, help_text="Session number in the series (1, 2, 3...)"
                    ),
                ),
                ("scheduled_date", models.DateField(help_text="Scheduled date for the session")),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, help_text="Scheduled time for the session", null=True
                    ),
                ),
                (
                    "actual_date",
                    models.DateField(
                        blank=True, help_text="Actual date when session occurred", null=True
                    ),
                ),
                (
                    "actual_start_time",
                    models.TimeField(
                        blank=True, help_text="Actual start time of session", null=True
                    ),
                ),
                (
                    "actual_end_time",
                    models.TimeField(blank=True, help_text="Actual end time of session", null=True),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Actual session duration in minutes",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "Patient No Show"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "pre_session_mood",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Patient's self-reported mood before session (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "pre_session_notes",
                    models.TextField(
                        blank=True, help_text="Notes on patient's presentation before session"
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of session (e.g., 'Individual', 'Group', 'Family')",
                        max_length=50,
                    ),
                ),
                (
                    "topics_discussed",
                    models.TextField(blank=True, help_text="Main topics covered in the session"),
                ),
                (
                    "techniques_used",
                    models.TextField(
                        blank=True, help_text="Therapeutic techniques/interventions used"
                    ),
                ),
                (
                    "client_responses",
                    models.TextField(
                        blank=True, help_text="Patient's responses and reactions during session"
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(
                        blank=True, help_text="Detailed progress notes from the session"
                    ),
                ),
                (
                    "post_session_mood",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Patient's self-reported mood after session (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOOD_PROGRESS", "Good Progress"),
                            ("MODERATE_PROGRESS", "Moderate Progress"),
                            ("LIMITED_PROGRESS", "Limited Progress"),
                            ("NO_PROGRESS", "No Progress"),
                            ("DETERIORATION", "Deterioration"),
                            ("CRISIS_RESOLVED", "Crisis Resolved"),
                            ("CRISIS_ONGOING", "Crisis Ongoing"),
                            ("NEEDS_REFERRAL", "Needs Specialist Referral"),
                            ("PENDING_ASSESSMENT", "Pending Assessment"),
                        ],
                        help_text="Session outcome assessment",
                        max_length=30,
                    ),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Risk assessment notes (suicide, self-harm, harm to others)",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("NONE", "No Risk"),
                            ("LOW", "Low Risk"),
                            ("MODERATE", "Moderate Risk"),
                            ("HIGH", "High Risk"),
                            ("IMMINENT", "Imminent Risk"),
                        ],
                        default="NONE",
                        help_text="Current risk level assessment",
                        max_length=20,
                    ),
                ),
                (
                    "safety_plan",
                    models.TextField(blank=True, help_text="Safety plan if applicable"),
                ),
                (
                    "follow_up_required",
                    models.CharField(
                        choices=[
                            ("CONTINUE", "Continue Sessions as Planned"),
                            ("EXTEND", "Extend Number of Sessions"),
                            ("REDUCE", "Reduce Session Frequency"),
                            ("REFER_PSYCHIATRY", "Refer to Psychiatry"),
                            ("REFER_SOCIAL_WORK", "Refer to Social Work"),
                            ("REFER_PHYSICIAN", "Refer to Physician"),
                            ("DISCHARGE", "Ready for Discharge"),
                            ("CRISIS_PLAN", "Implement Crisis Plan"),
                            ("NONE", "No Follow-up Required"),
                        ],
                        default="CONTINUE",
                        help_text="Recommended follow-up action",
                        max_length=30,
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, help_text="Recommended next session date", null=True
                    ),
                ),
                (
                    "homework",
                    models.TextField(blank=True, help_text="Homework or tasks assigned to patient"),
                ),
                (
                    "goals_for_next_session",
                    models.TextField(blank=True, help_text="Goals to work on in next session"),
                ),
                (
                    "confidentiality_level",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard Confidentiality"),
                            ("RESTRICTED", "Restricted Access"),
                            ("HIGHLY_RESTRICTED", "Highly Restricted (HIV/Mental Health)"),
                        ],
                        default="STANDARD",
                        help_text="Confidentiality level for this session's notes",
                        max_length=20,
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Contains sensitive information requiring restricted access",
                    ),
                ),
                ("is_billed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated clinic visit for billing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counselling_sessions",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "counsellor",
                    models.ForeignKey(
                        help_text="Counsellor who conducted the session",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counselling_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="counselling.counsellingreferral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counselling Session",
                "verbose_name_plural": "Counselling Sessions",
                "ordering": ["referral", "session_sequence"],
                "permissions": [
                    (
                        "view_sensitive_counselling_session",
                        "Can view sensitive counselling sessions",
                    )
                ],
                "indexes": [
                    models.Index(fields=["session_number"], name="counselling_session_7fbf5f_idx"),
                    models.Index(
                        fields=["referral", "session_sequence"],
                        name="counselling_referra_a03d1b_idx",
                    ),
                    models.Index(
                        fields=["counsellor", "scheduled_date"],
                        name="counselling_counsel_acb9e1_idx",
                    ),
                    models.Index(fields=["status"], name="counselling_status_6d8a82_idx"),
                    models.Index(fields=["scheduled_date"], name="counselling_schedul_ced61e_idx"),
                    models.Index(fields=["is_sensitive"], name="counselling_is_sens_2a5bce_idx"),
                ],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="counsellingreferral",
            index=models.Index(fields=["referral_number"], name="counselling_referra_e6506e_idx"),
        ),
        migrations.AddIndex(
            model_name="counsellingreferral",
            index=models.Index(fields=["patient", "status"], name="counselling_patient_7003c2_idx"),
        ),
        migrations.AddIndex(
            model_name="counsellingreferral",
            index=models.Index(
                fields=["assigned_counsellor", "status"], name="counselling_assigne_7e08e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="counsellingreferral",
            index=models.Index(fields=["status"], name="counselling_status_5ff919_idx"),
        ),
        migrations.AddIndex(
            model_name="counsellingreferral",
            index=models.Index(fields=["urgency"], name="counselling_urgency_3d69f6_idx"),
        ),
        migrations.AddIndex(
            model_name="counsellingreferral",
            index=models.Index(fields=["created_at"], name="counselling_created_acb7e7_idx"),
        ),
        migrations.AddIndex(
            model_name="counsellingreferral",
            index=models.Index(fields=["is_sensitive"], name="counselling_is_sens_692449_idx"),
        ),
    ]
