# Generated by Django 5.2.9 on 2025-12-29 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("encounter", "Encounter"),
                            ("note", "Clinical Note"),
                            ("assessment", "Assessment"),
                            ("procedure", "Procedure"),
                        ],
                        help_text="Type of clinical template",
                        max_length=20,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Medical specialty (e.g., General Practice, Pediatrics)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Template description"),
                ),
                ("content", models.JSONField(help_text="Template structure as JSON")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="Whether this is a system-provided template"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is currently active"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this template has been used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Template",
                "verbose_name_plural": "Clinical Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Section name", max_length=100)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Whether this section must be completed"
                    ),
                ),
                ("fields", models.JSONField(default=list, help_text="Array of field definitions")),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The template this section belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="clinical_templates.clinicaltemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Section",
                "verbose_name_plural": "Template Sections",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="clinicaltemplate",
            index=models.Index(fields=["template_type"], name="clinical_te_templat_753c79_idx"),
        ),
        migrations.AddIndex(
            model_name="clinicaltemplate",
            index=models.Index(fields=["specialty"], name="clinical_te_special_3d3799_idx"),
        ),
        migrations.AddIndex(
            model_name="clinicaltemplate",
            index=models.Index(fields=["is_system"], name="clinical_te_is_syst_5c36c5_idx"),
        ),
        migrations.AddIndex(
            model_name="clinicaltemplate",
            index=models.Index(fields=["is_active"], name="clinical_te_is_acti_a16eb9_idx"),
        ),
        migrations.AddIndex(
            model_name="clinicaltemplate",
            index=models.Index(fields=["-usage_count"], name="clinical_te_usage_c_f3eec9_idx"),
        ),
    ]
