# Generated by Django 5.2.9 on 2026-01-06 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_templates", "0001_initial"),
        ("encounters", "0013_add_clinical_template_to_encounter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalTemplateSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        help_text="Name of the template at time of snapshot", max_length=200
                    ),
                ),
                (
                    "template_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version of the template at time of snapshot",
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(help_text="The completed template data")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this snapshot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        help_text="The encounter this snapshot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_snapshots",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="The template used (may be null if template was deleted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="clinical_templates.clinicaltemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Template Snapshot",
                "verbose_name_plural": "Clinical Template Snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["encounter"], name="clinical_te_encount_e6ff28_idx"),
                    models.Index(fields=["-created_at"], name="clinical_te_created_0ccb0f_idx"),
                ],
            },
        ),
    ]
