# Generated by Django 5.2.11 on 2026-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HL7Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        help_text="HL7 message type (e.g., 'ADT^A01', 'ORM^O01', 'ORU^R01')",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("OUT", "Outbound"), ("IN", "Inbound")],
                        default="OUT",
                        max_length=3,
                    ),
                ),
                ("raw_message", models.TextField(help_text="Complete HL7 v2 message content")),
                (
                    "message_control_id",
                    models.CharField(
                        db_index=True, help_text="MSH-10 Message Control ID", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("ACK", "Acknowledged"),
                            ("FAILED", "Failed"),
                            ("DEAD", "Dead Letter"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, help_text="Number of send attempts"),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=5, help_text="Maximum retry attempts before dead-letter"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", help_text="Error message from last send attempt"
                    ),
                ),
                (
                    "ack_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ACK code from response (AA, AE, AR)",
                        max_length=5,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Source model type (e.g., 'Patient', 'Admission')",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="Source record ID", null=True
                    ),
                ),
                (
                    "destination_host",
                    models.CharField(
                        blank=True, default="", help_text="Target MLLP host", max_length=255
                    ),
                ),
                (
                    "destination_port",
                    models.PositiveIntegerField(
                        blank=True, help_text="Target MLLP port", null=True
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, help_text="When to attempt next retry", null=True
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When message was successfully sent", null=True
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(blank=True, help_text="When ACK was received", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "HL7 Message",
                "verbose_name_plural": "HL7 Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"], name="hl7_hl7mess_status_c5b42d_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="hl7_hl7mess_resourc_7c1d13_idx",
                    ),
                ],
            },
        ),
    ]
