# Generated by Django 5.2.13 on 2026-05-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_facility_biometrics_agent_national_id"),
        ("hl7", "0003_facility_scoped_model_fix"),
    ]

    operations = [
        migrations.CreateModel(
            name="HL7Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Lancet Lab', 'PathCare')",
                        max_length=150,
                    ),
                ),
                (
                    "endpoint_type",
                    models.CharField(
                        choices=[
                            ("LIS", "Laboratory Information System"),
                            ("RIS", "Radiology Information System"),
                            ("PAS", "Patient Administration System"),
                            ("PHARMACY", "Pharmacy System"),
                            ("OTHER", "Other"),
                        ],
                        default="LIS",
                        max_length=20,
                    ),
                ),
                (
                    "mllp_host",
                    models.CharField(help_text="MLLP hostname or IP address", max_length=255),
                ),
                ("mllp_port", models.PositiveIntegerField(default=2575, help_text="MLLP TCP port")),
                (
                    "receiving_application",
                    models.CharField(
                        default="LAB_LIS",
                        help_text="HL7 MSH-5 Receiving Application",
                        max_length=100,
                    ),
                ),
                (
                    "receiving_facility",
                    models.CharField(
                        default="EXTERNAL_LAB",
                        help_text="HL7 MSH-6 Receiving Facility",
                        max_length=100,
                    ),
                ),
                (
                    "sending_application",
                    models.CharField(
                        default="VITORA_HMIS",
                        help_text="HL7 MSH-3 Sending Application",
                        max_length=100,
                    ),
                ),
                (
                    "sending_facility",
                    models.CharField(
                        blank=True,
                        help_text="HL7 MSH-4 Sending Facility (defaults to facility name)",
                        max_length=100,
                    ),
                ),
                (
                    "lis_code_system",
                    models.CharField(
                        default="LIS_DEFAULT",
                        help_text="External code system for test mapping",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this endpoint is currently active for message routing",
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(default=False, help_text="Use TLS/SSL for MLLP connection"),
                ),
                (
                    "timeout",
                    models.FloatField(default=30.0, help_text="Connection timeout in seconds"),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=5, help_text="Maximum retry attempts for failed messages"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes about this endpoint"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "HL7 Endpoint",
                "verbose_name_plural": "HL7 Endpoints",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="hl7message",
            name="endpoint",
            field=models.ForeignKey(
                blank=True,
                help_text="Resolved HL7 endpoint (facility-scoped)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="hl7.hl7endpoint",
            ),
        ),
        migrations.AddConstraint(
            model_name="hl7endpoint",
            constraint=models.UniqueConstraint(
                fields=("facility", "mllp_host", "mllp_port"), name="unique_facility_endpoint"
            ),
        ),
    ]
