'use client';

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  Loader2,
  BarChart3,
  FileDown,
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { ResponsiveTable } from '@/components/ui/responsive-table';
import { PageHeader } from '@/components/shared/page-header';
import { PullToRefresh } from '@/components/shared/pull-to-refresh';
import { inventoryApi } from '@/lib/api/inventory';
import { getApiErrorMessage } from '@/lib/api/client';
import { useToast } from '@/lib/hooks/use-toast';
import { usePageRefresh } from '@/lib/context/page-refresh-context';
import type { ETIMSDailyReport } from '@/lib/types/inventory';

export default function ETIMSDailyReportsPage() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { refresh, isRefreshing } = usePageRefresh();
  const [generateType, setGenerateType] = useState<'X' | 'Z'>('Z');

  const { data, isLoading } = useQuery({
    queryKey: ['etims-daily-reports'],
    queryFn: () => inventoryApi.listETIMSDailyReports({ page_size: 50 }),
  });

  const generateMutation = useMutation({
    mutationFn: () =>
      inventoryApi.generateETIMSDailyReport({ report_type: generateType }),
    onSuccess: (report) => {
      queryClient.invalidateQueries({ queryKey: ['etims-daily-reports'] });
      toast({
        variant: 'success',
        title: `${report.report_type} Report #${report.report_number} generated`,
      });
    },
    onError: (err) => {
      toast({
        variant: 'destructive',
        title: 'Report generation failed',
        description: getApiErrorMessage(err),
      });
    },
  });

  const reports = data?.results ?? [];

  const columns = [
    {
      key: 'report_type',
      header: 'Type',
      sortable: true,
      cell: (r: ETIMSDailyReport) => (
        <Badge
          variant="outline"
          className={
            r.report_type === 'Z'
              ? 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300'
              : 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300'
          }
        >
          {r.report_type === 'Z' ? 'Z (End of Day)' : 'X (Interim)'}
        </Badge>
      ),
    },
    {
      key: 'report_date',
      header: 'Date',
      sortable: true,
      sortType: 'date' as const,
      cell: (r: ETIMSDailyReport) => new Date(r.report_date).toLocaleDateString(),
    },
    {
      key: 'report_number',
      header: '#',
      sortable: true,
      sortType: 'number' as const,
      cell: (r: ETIMSDailyReport) => r.report_number,
    },
    {
      key: 'total_ns_amount',
      header: 'Sales (NS)',
      sortable: true,
      sortType: 'number' as const,
      cell: (r: ETIMSDailyReport) => (
        <span className="font-mono">
          KES {Number(r.total_ns_amount).toLocaleString()}
        </span>
      ),
    },
    {
      key: 'total_nc_amount',
      header: 'Credits (NC)',
      sortable: true,
      sortType: 'number' as const,
      hideOnMobile: true,
      cell: (r: ETIMSDailyReport) => (
        <span className="font-mono text-destructive">
          {Number(r.total_nc_amount) > 0
            ? `KES -${Number(r.total_nc_amount).toLocaleString()}`
            : '—'}
        </span>
      ),
    },
    {
      key: 'total_ns_count',
      header: 'Receipts',
      sortable: true,
      sortType: 'number' as const,
      hideOnMobile: true,
      cell: (r: ETIMSDailyReport) => `${r.total_ns_count} NS / ${r.total_nc_count} NC`,
    },
    {
      key: 'generated_by_name',
      header: 'Generated By',
      hideOnMobile: true,
      cell: (r: ETIMSDailyReport) => r.generated_by_name || '—',
    },
  ];

  return (
    <PullToRefresh onRefresh={refresh} isRefreshing={isRefreshing}>
      <div className="space-y-4 sm:space-y-6">
        <PageHeader
          title="Daily Reports"
          helpContent="Generate KRA-compliant X (interim) and Z (end-of-day) daily reports. Z reports summarize the full day's transactions. X reports summarize since the last Z report."
          actions={
            <div className="flex items-center gap-2">
              <Select
                value={generateType}
                onValueChange={(v) => setGenerateType(v as 'X' | 'Z')}
              >
                <SelectTrigger className="w-32">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Z">Z Report</SelectItem>
                  <SelectItem value="X">X Report</SelectItem>
                </SelectContent>
              </Select>
              <Button
                size="sm"
                onClick={() => generateMutation.mutate()}
                disabled={generateMutation.isPending}
              >
                {generateMutation.isPending ? (
                  <Loader2 className="mr-1 h-4 w-4 animate-spin" />
                ) : (
                  <FileDown className="mr-1 h-4 w-4" />
                )}
                Generate
              </Button>
            </div>
          }
        />

        {/* Summary Stats */}
        {reports.length > 0 && (
          <div className="grid gap-3 grid-cols-2 sm:grid-cols-4">
            <Card className="relative overflow-hidden">
              <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,0.06),transparent_50%),radial-gradient(circle_at_bottom_right,rgba(59,130,246,0.05),transparent_50%)]" aria-hidden="true" />
              <CardContent className="relative p-3 sm:p-4">
                <p className="text-xs text-muted-foreground">Total Z Reports</p>
                <p className="text-lg font-bold">
                  {reports.filter((r) => r.report_type === 'Z').length}
                </p>
              </CardContent>
            </Card>
            <Card className="relative overflow-hidden">
              <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,0.06),transparent_50%),radial-gradient(circle_at_bottom_right,rgba(59,130,246,0.05),transparent_50%)]" aria-hidden="true" />
              <CardContent className="relative p-3 sm:p-4">
                <p className="text-xs text-muted-foreground">Total X Reports</p>
                <p className="text-lg font-bold">
                  {reports.filter((r) => r.report_type === 'X').length}
                </p>
              </CardContent>
            </Card>
            <Card className="relative overflow-hidden">
              <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,0.06),transparent_50%),radial-gradient(circle_at_bottom_right,rgba(59,130,246,0.05),transparent_50%)]" aria-hidden="true" />
              <CardContent className="relative p-3 sm:p-4">
                <p className="text-xs text-muted-foreground">Latest Sales</p>
                <p className="text-lg font-bold font-mono">
                  {reports[0]
                    ? `KES ${Number(reports[0].total_ns_amount).toLocaleString()}`
                    : '—'}
                </p>
              </CardContent>
            </Card>
            <Card className="relative overflow-hidden">
              <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(34,211,238,0.06),transparent_50%),radial-gradient(circle_at_bottom_right,rgba(59,130,246,0.05),transparent_50%)]" aria-hidden="true" />
              <CardContent className="relative p-3 sm:p-4">
                <p className="text-xs text-muted-foreground">Incomplete</p>
                <p className="text-lg font-bold">
                  {reports[0]?.incomplete_sales_count ?? 0}
                </p>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Reports Table */}
        <ResponsiveTable
          data={reports}
          keyExtractor={(r) => r.id}
          columns={columns}
          isLoading={isLoading}
          emptyMessage="No daily reports generated yet. Use the Generate button above to create your first report."
          defaultSortColumn="report_date"
          defaultSortDirection="desc"
        />
      </div>
    </PullToRefresh>
  );
}
