import { z } from 'zod';

export const FacilityModulesSchema = z.object({
  outpatient: z.boolean(),
  inpatient: z.boolean(),
  emergency: z.boolean(),
  pharmacy: z.boolean(),
  laboratory: z.boolean(),
  imaging: z.boolean(),
  theatre: z.boolean(),
  dialysis: z.boolean(),
  icu: z.boolean(),
  maternity: z.boolean(),
  mortuary: z.boolean(),
  blood_bank: z.boolean(),
  inventory: z.boolean().default(false),
  lis_standalone: z.boolean().default(false),
  pharmacy_standalone: z.boolean().default(false),
  imaging_standalone: z.boolean().default(false),
  triage: z.boolean().default(true),
  scheduling: z.boolean().default(true),
  surveillance: z.boolean().default(false),
  immunizations: z.boolean().default(false),
  allied_health: z.boolean().default(false),
  quality: z.boolean().default(false),
  billing: z.boolean().default(true),
  private_insurance: z.boolean().default(false),
});

export const FacilityListItemSchema = z.object({
  id: z.number(),
  organization: z.number().nullable(),
  organization_name: z.string().nullable(),
  mfl_code: z.string(),
  name: z.string(),
  level: z.string(),
  ownership: z.string(),
  county: z.number(),
  county_name: z.string(),
  sub_county: z.number(),
  sub_county_name: z.string(),
  is_headquarters: z.boolean().default(false),
  branch_code: z.string().default(''),
  sha_contracted: z.boolean(),
  is_active: z.boolean(),
});

export const FacilityDetailSchema = FacilityListItemSchema.extend({
  ward: z.number().nullable().optional(),
  ward_name: z.string().nullable().optional(),
  logo: z.string().nullable().default(null),
  effective_logo_url: z.string().nullable().default(null),
  sha_contract_expiry: z.string().nullable(),
  sha_facility_code: z.string(),
  dhis2_org_unit: z.string().default(''),
  modules: FacilityModulesSchema,
  enabled_module_names: z.array(z.string()),
  has_outpatient: z.boolean(),
  has_inpatient: z.boolean(),
  has_emergency: z.boolean(),
  has_pharmacy: z.boolean(),
  has_laboratory: z.boolean(),
  has_imaging: z.boolean(),
  has_theatre: z.boolean(),
  has_dialysis: z.boolean(),
  has_icu: z.boolean(),
  has_maternity: z.boolean(),
  has_mortuary: z.boolean(),
  has_blood_bank: z.boolean(),
  has_inventory: z.boolean().default(false),
  has_lis_standalone: z.boolean().default(false),
  has_pharmacy_standalone: z.boolean().default(false),
  has_imaging_standalone: z.boolean().default(false),
  has_triage: z.boolean().default(true),
  has_scheduling: z.boolean().default(true),
  has_surveillance: z.boolean().default(false),
  has_immunizations: z.boolean().default(false),
  has_allied_health: z.boolean().default(false),
  has_quality: z.boolean().default(false),
  has_billing: z.boolean().default(true),
  has_private_insurance: z.boolean().default(false),
  // DHA Registry Cache
  dha_registry_synced_at: z.string().nullable().default(null),
  dha_fid_code: z.string().default(''),
  dha_fr_code: z.string().default(''),
  dha_license_status: z.string().default(''),
  dha_license_number: z.string().default(''),
  dha_license_expiry: z.string().default(''),
  dha_operational_status: z.string().default(''),
  dha_sha_contract_status: z.string().default(''),
  dha_sha_contract_start: z.string().default(''),
  dha_sha_contract_end: z.string().default(''),
  dha_total_beds: z.number().default(0),
  dha_icu_beds: z.number().default(0),
  dha_hdu_beds: z.number().default(0),
  dha_facility_type: z.string().default(''),
  dha_keph_level: z.string().default(''),
  dha_ownership: z.string().default(''),
  dha_regulatory_body: z.string().default(''),
  dha_admin_name: z.string().default(''),
  dha_admin_phone: z.string().default(''),
  dha_admin_email: z.string().default(''),
  dha_admin_id: z.string().default(''),
  dha_facility_phone: z.string().default(''),
  dha_facility_email: z.string().default(''),
  dha_registry_data: z.record(z.unknown()).nullable().default(null),
  created_at: z.string(),
  updated_at: z.string(),
});

export const PaginatedFacilityListSchema = z.object({
  count: z.number(),
  next: z.string().nullable(),
  previous: z.string().nullable(),
  results: z.array(FacilityListItemSchema),
});

export type FacilityModulesSchemaType = z.infer<typeof FacilityModulesSchema>;
export type FacilityListItemSchemaType = z.infer<typeof FacilityListItemSchema>;
export type FacilityDetailSchemaType = z.infer<typeof FacilityDetailSchema>;
