# Generated by Django 5.2.11 on 2026-03-07 19:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import hmis.apps.core.history
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0023_historicaldiagnosis_historicalencounter"),
        ("inpatient", "0020_temperaturereading_fluid_intake_ml_and_more"),
        ("mch", "0002_historicalmchregistration_gbv_related_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLabourPartograph",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When labour monitoring started",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("REFERRED", "Referred"),
                        ],
                        default="ACTIVE",
                        help_text="Current labour monitoring status",
                        max_length=20,
                    ),
                ),
                (
                    "parity",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Maternal parity at labour onset", null=True
                    ),
                ),
                (
                    "gestation_weeks",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Gestation in weeks at labour onset",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(45),
                        ],
                    ),
                ),
                (
                    "membrane_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INTACT", "Intact"),
                            ("RUPTURED", "Ruptured"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="",
                        help_text="Whether membranes are intact or ruptured",
                        max_length=20,
                    ),
                ),
                (
                    "liquor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLEAR", "Clear"),
                            ("MECONIUM", "Meconium stained"),
                            ("BLOOD_STAINED", "Blood stained"),
                            ("OFFENSIVE", "Offensive"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="",
                        help_text="Liquor appearance when membranes rupture",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="General labour notes"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the labour partograph was closed", null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked inpatient admission, if mother is admitted",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked clinical encounter, if available",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="MCH registration being monitored in labour",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="mch.mchregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Labour Partograph",
                "verbose_name_plural": "historical Labour Partographs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LabourPartograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When labour monitoring started",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("REFERRED", "Referred"),
                        ],
                        default="ACTIVE",
                        help_text="Current labour monitoring status",
                        max_length=20,
                    ),
                ),
                (
                    "parity",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Maternal parity at labour onset", null=True
                    ),
                ),
                (
                    "gestation_weeks",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Gestation in weeks at labour onset",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(45),
                        ],
                    ),
                ),
                (
                    "membrane_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INTACT", "Intact"),
                            ("RUPTURED", "Ruptured"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="",
                        help_text="Whether membranes are intact or ruptured",
                        max_length=20,
                    ),
                ),
                (
                    "liquor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLEAR", "Clear"),
                            ("MECONIUM", "Meconium stained"),
                            ("BLOOD_STAINED", "Blood stained"),
                            ("OFFENSIVE", "Offensive"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="",
                        help_text="Liquor appearance when membranes rupture",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="General labour notes"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the labour partograph was closed", null=True
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked inpatient admission, if mother is admitted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labour_partographs",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labour_partographs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked clinical encounter, if available",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labour_partographs",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        help_text="MCH registration being monitored in labour",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_partographs",
                        to="mch.mchregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Partograph",
                "verbose_name_plural": "Labour Partographs",
                "ordering": ["-started_at"],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLabourPartographObservation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "observation_time",
                    models.DateTimeField(help_text="Time this observation was taken"),
                ),
                (
                    "fetal_heart_rate",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Fetal heart rate in beats per minute",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(80),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "cervical_dilation_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Cervical dilation in cm",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("10.0")),
                        ],
                    ),
                ),
                (
                    "descent_fifths",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Descent of head in fifths palpable abdominally",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "contractions_per_10_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of contractions in 10 minutes",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "contraction_duration_seconds",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Approximate contraction duration in seconds",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "moulding",
                    models.CharField(
                        blank=True,
                        choices=[("0", "None"), ("+", "+"), ("++", "++"), ("+++", "+++")],
                        default="",
                        help_text="Fetal skull moulding grade",
                        max_length=3,
                    ),
                ),
                (
                    "maternal_pulse",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maternal pulse rate",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "maternal_blood_pressure",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Maternal blood pressure in format 120/80",
                        max_length=10,
                    ),
                ),
                (
                    "maternal_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Maternal temperature in °C",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("30.0")),
                            django.core.validators.MaxValueValidator(Decimal("45.0")),
                        ],
                    ),
                ),
                (
                    "urine_volume_ml",
                    models.PositiveIntegerField(
                        blank=True, help_text="Measured urine volume in mL", null=True
                    ),
                ),
                (
                    "urine_protein",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEGATIVE", "Negative"),
                            ("TRACE", "Trace"),
                            ("1+", "1+"),
                            ("2+", "2+"),
                            ("3+", "3+"),
                            ("4+", "4+"),
                        ],
                        default="",
                        help_text="Urine protein result",
                        max_length=10,
                    ),
                ),
                (
                    "urine_acetone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEGATIVE", "Negative"),
                            ("TRACE", "Trace"),
                            ("1+", "1+"),
                            ("2+", "2+"),
                            ("3+", "3+"),
                            ("4+", "4+"),
                        ],
                        default="",
                        help_text="Urine acetone result",
                        max_length=10,
                    ),
                ),
                (
                    "oxytocin_drops_per_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Oxytocin infusion rate in drops per minute",
                        null=True,
                    ),
                ),
                (
                    "medications",
                    models.TextField(
                        blank=True, default="", help_text="Medications or interventions given"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Additional labour notes"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partograph",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Partograph this observation belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="mch.labourpartograph",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Labour Partograph Observation",
                "verbose_name_plural": "historical Labour Partograph Observations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LabourPartographObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "observation_time",
                    models.DateTimeField(help_text="Time this observation was taken"),
                ),
                (
                    "fetal_heart_rate",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Fetal heart rate in beats per minute",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(80),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "cervical_dilation_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Cervical dilation in cm",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("10.0")),
                        ],
                    ),
                ),
                (
                    "descent_fifths",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Descent of head in fifths palpable abdominally",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "contractions_per_10_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of contractions in 10 minutes",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "contraction_duration_seconds",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Approximate contraction duration in seconds",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "moulding",
                    models.CharField(
                        blank=True,
                        choices=[("0", "None"), ("+", "+"), ("++", "++"), ("+++", "+++")],
                        default="",
                        help_text="Fetal skull moulding grade",
                        max_length=3,
                    ),
                ),
                (
                    "maternal_pulse",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maternal pulse rate",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "maternal_blood_pressure",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Maternal blood pressure in format 120/80",
                        max_length=10,
                    ),
                ),
                (
                    "maternal_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Maternal temperature in °C",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("30.0")),
                            django.core.validators.MaxValueValidator(Decimal("45.0")),
                        ],
                    ),
                ),
                (
                    "urine_volume_ml",
                    models.PositiveIntegerField(
                        blank=True, help_text="Measured urine volume in mL", null=True
                    ),
                ),
                (
                    "urine_protein",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEGATIVE", "Negative"),
                            ("TRACE", "Trace"),
                            ("1+", "1+"),
                            ("2+", "2+"),
                            ("3+", "3+"),
                            ("4+", "4+"),
                        ],
                        default="",
                        help_text="Urine protein result",
                        max_length=10,
                    ),
                ),
                (
                    "urine_acetone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEGATIVE", "Negative"),
                            ("TRACE", "Trace"),
                            ("1+", "1+"),
                            ("2+", "2+"),
                            ("3+", "3+"),
                            ("4+", "4+"),
                        ],
                        default="",
                        help_text="Urine acetone result",
                        max_length=10,
                    ),
                ),
                (
                    "oxytocin_drops_per_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Oxytocin infusion rate in drops per minute",
                        null=True,
                    ),
                ),
                (
                    "medications",
                    models.TextField(
                        blank=True, default="", help_text="Medications or interventions given"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Additional labour notes"),
                ),
                (
                    "partograph",
                    models.ForeignKey(
                        help_text="Partograph this observation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="mch.labourpartograph",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labour_partograph_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Partograph Observation",
                "verbose_name_plural": "Labour Partograph Observations",
                "ordering": ["observation_time"],
                "indexes": [
                    models.Index(
                        fields=["partograph", "observation_time"],
                        name="mch_labourp_partogr_3d8974_idx",
                    )
                ],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
    ]
