# Generated by Django 5.2.11 on 2026-03-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0011_clinicvisit_source_module_and_more"),
        ("mch", "0003_historicallabourpartograph_labourpartograph_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ancvisit",
            name="clinic_visit",
            field=models.OneToOneField(
                blank=True,
                help_text="Canonical clinic visit for this attended ANC consultation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anc_visit",
                to="clinics.clinicvisit",
            ),
        ),
        migrations.AddField(
            model_name="historicalancvisit",
            name="clinic_visit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Canonical clinic visit for this attended ANC consultation",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinicvisit",
            ),
        ),
        migrations.AddField(
            model_name="historicalpncvisit",
            name="clinic_visit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Canonical clinic visit for this attended PNC consultation",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clinics.clinicvisit",
            ),
        ),
        migrations.AddField(
            model_name="pncvisit",
            name="clinic_visit",
            field=models.OneToOneField(
                blank=True,
                help_text="Canonical clinic visit for this attended PNC consultation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pnc_visit",
                to="clinics.clinicvisit",
            ),
        ),
    ]
