# Generated by Django 5.2.11 on 2026-03-13 00:46

import datetime
import django.core.validators
import django.db.models.deletion
import hmis.apps.core.history
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mch", "0006_pncvisit_postpartum_links"),
        ("patients", "0014_historicalpatient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCommunityScreening",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "patient_name_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name captured during the outreach visit when no patient record is linked.",
                        max_length=200,
                    ),
                ),
                (
                    "patient_mrn_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MRN snapshot captured at time of screening.",
                        max_length=50,
                    ),
                ),
                (
                    "screening_type",
                    models.CharField(
                        choices=[
                            ("MALNUTRITION", "Malnutrition Screening"),
                            ("TB_CONTACT", "TB Contact Tracing"),
                            ("MALARIA_RDT", "Malaria RDT"),
                        ],
                        help_text="Type of community screening performed.",
                        max_length=20,
                    ),
                ),
                (
                    "screening_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Date the field screening was conducted.",
                    ),
                ),
                (
                    "chu_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Community Health Unit (CHU) name.",
                        max_length=150,
                    ),
                ),
                (
                    "territory",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Village, cluster, or territory covered during the visit.",
                        max_length=150,
                    ),
                ),
                (
                    "result_summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Compact summary derived from the screening findings.",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text outreach notes or referral details.",
                    ),
                ),
                (
                    "muac_mm",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="MUAC in millimetres for malnutrition screening.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(400),
                        ],
                    ),
                ),
                (
                    "edema_present",
                    models.BooleanField(
                        blank=True, help_text="Whether bilateral oedema was present.", null=True
                    ),
                ),
                (
                    "fever_present",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the client had fever during malaria screening.",
                        null=True,
                    ),
                ),
                (
                    "cough_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days of cough during TB contact tracing.",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(365)],
                    ),
                ),
                (
                    "household_contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Household or index contact associated with TB tracing.",
                        max_length=200,
                    ),
                ),
                (
                    "malaria_rdt_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("invalid", "Invalid"),
                            ("not_done", "Not Done"),
                        ],
                        default="",
                        help_text="Malaria rapid diagnostic test result.",
                        max_length=20,
                    ),
                ),
                (
                    "malaria_treatment_referred",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether treatment or referral was made after malaria screening.",
                        null=True,
                    ),
                ),
                (
                    "tb_referral_made",
                    models.BooleanField(
                        blank=True, help_text="Whether TB referral was made.", null=True
                    ),
                ),
                (
                    "location",
                    models.JSONField(
                        blank=True,
                        help_text="Captured GPS coordinates and accuracy metadata.",
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.TextField(
                        blank=True,
                        help_text="Optional field photo attached to the screening record.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked patient record if the client already exists in HMIS.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Community Screening",
                "verbose_name_plural": "historical Community Screenings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CommunityScreening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient_name_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name captured during the outreach visit when no patient record is linked.",
                        max_length=200,
                    ),
                ),
                (
                    "patient_mrn_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MRN snapshot captured at time of screening.",
                        max_length=50,
                    ),
                ),
                (
                    "screening_type",
                    models.CharField(
                        choices=[
                            ("MALNUTRITION", "Malnutrition Screening"),
                            ("TB_CONTACT", "TB Contact Tracing"),
                            ("MALARIA_RDT", "Malaria RDT"),
                        ],
                        help_text="Type of community screening performed.",
                        max_length=20,
                    ),
                ),
                (
                    "screening_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Date the field screening was conducted.",
                    ),
                ),
                (
                    "chu_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Community Health Unit (CHU) name.",
                        max_length=150,
                    ),
                ),
                (
                    "territory",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Village, cluster, or territory covered during the visit.",
                        max_length=150,
                    ),
                ),
                (
                    "result_summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Compact summary derived from the screening findings.",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text outreach notes or referral details.",
                    ),
                ),
                (
                    "muac_mm",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="MUAC in millimetres for malnutrition screening.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(400),
                        ],
                    ),
                ),
                (
                    "edema_present",
                    models.BooleanField(
                        blank=True, help_text="Whether bilateral oedema was present.", null=True
                    ),
                ),
                (
                    "fever_present",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the client had fever during malaria screening.",
                        null=True,
                    ),
                ),
                (
                    "cough_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days of cough during TB contact tracing.",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(365)],
                    ),
                ),
                (
                    "household_contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Household or index contact associated with TB tracing.",
                        max_length=200,
                    ),
                ),
                (
                    "malaria_rdt_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("invalid", "Invalid"),
                            ("not_done", "Not Done"),
                        ],
                        default="",
                        help_text="Malaria rapid diagnostic test result.",
                        max_length=20,
                    ),
                ),
                (
                    "malaria_treatment_referred",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether treatment or referral was made after malaria screening.",
                        null=True,
                    ),
                ),
                (
                    "tb_referral_made",
                    models.BooleanField(
                        blank=True, help_text="Whether TB referral was made.", null=True
                    ),
                ),
                (
                    "location",
                    models.JSONField(
                        blank=True,
                        help_text="Captured GPS coordinates and accuracy metadata.",
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        help_text="Optional field photo attached to the screening record.",
                        null=True,
                        upload_to="community_screenings/%Y/%m/",
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_screenings_captured",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked patient record if the client already exists in HMIS.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_screenings",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Screening",
                "verbose_name_plural": "Community Screenings",
                "ordering": ["-screening_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["screening_type", "screening_date"],
                        name="mch_communi_screeni_39e8f5_idx",
                    ),
                    models.Index(
                        fields=["patient", "updated_at"], name="mch_communi_patient_f6736f_idx"
                    ),
                ],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
    ]
