# Generated by Django 5.2.11 on 2026-03-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_role_multitenancy_scope"),
        ("mch", "0007_historicalcommunityscreening_communityscreening"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmchregistration",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Facility where registration was created.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="historicalmchregistration",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="mchregistration",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where registration was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mch_registrations",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="mchregistration",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mch_registrations",
                to="core.organization",
            ),
        ),
    ]
