# Generated by Django 5.2.11 on 2026-04-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mch", "0008_historicalmchregistration_facility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabourpartographobservation",
            name="contraction_intensity",
            field=models.CharField(
                blank=True,
                choices=[("MILD", "Mild"), ("MODERATE", "Moderate"), ("STRONG", "Strong")],
                default="",
                help_text="Contraction strength: mild, moderate, or strong",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="labourpartographobservation",
            name="contraction_intensity",
            field=models.CharField(
                blank=True,
                choices=[("MILD", "Mild"), ("MODERATE", "Moderate"), ("STRONG", "Strong")],
                default="",
                help_text="Contraction strength: mild, moderate, or strong",
                max_length=10,
            ),
        ),
    ]
