# Generated by Django 5.2.13 on 2026-04-21 16:34

import hmis.apps.core.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mch', '0010_facility_scoped_model_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityscreening',
            name='photo',
            field=models.FileField(blank=True, help_text='Optional field photo attached to the screening record.', null=True, upload_to='community_screenings/%Y/%m/', validators=[hmis.apps.core.upload_validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='historicalcommunityscreening',
            name='photo',
            field=models.TextField(blank=True, help_text='Optional field photo attached to the screening record.', max_length=100, null=True, validators=[hmis.apps.core.upload_validators.validate_image_upload]),
        ),
    ]
