# Generated by Django 5.2.11 on 2026-03-07 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_chat_session_models"),
        ("encounters", "0023_historicaldiagnosis_historicalencounter"),
        ("inpatient", "0019_observation_charts"),
        ("laboratory", "0017_alter_specimen_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICarePlanResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(help_text="Input payload sent to TibaBot (sanitized)."),
                ),
                (
                    "result_data",
                    models.JSONField(
                        help_text="Full response JSON from TibaBot or fallback engine."
                    ),
                ),
                (
                    "service_mode",
                    models.CharField(
                        default="tibabot", help_text="'tibabot' or 'fallback'.", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("primary_diagnosis", models.CharField(blank=True, default="", max_length=500)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_care_plans",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_care_plans",
                        to="encounters.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Care Plan Result",
                "verbose_name_plural": "AI Care Plan Results",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AICDSResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(help_text="Input payload sent to TibaBot (sanitized)."),
                ),
                (
                    "result_data",
                    models.JSONField(
                        help_text="Full response JSON from TibaBot or fallback engine."
                    ),
                ),
                (
                    "service_mode",
                    models.CharField(
                        default="tibabot", help_text="'tibabot' or 'fallback'.", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rules_fired", models.IntegerField(default=0)),
                ("alert_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_cds_results",
                        to="encounters.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI CDS Result",
                "verbose_name_plural": "AI CDS Results",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AIDischargeResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(help_text="Input payload sent to TibaBot (sanitized)."),
                ),
                (
                    "result_data",
                    models.JSONField(
                        help_text="Full response JSON from TibaBot or fallback engine."
                    ),
                ),
                (
                    "service_mode",
                    models.CharField(
                        default="tibabot", help_text="'tibabot' or 'fallback'.", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("readiness_level", models.CharField(blank=True, default="", max_length=20)),
                ("readiness_score", models.FloatField(blank=True, null=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_discharge_assessments",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Discharge Assessment",
                "verbose_name_plural": "AI Discharge Assessments",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AIICURiskResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(help_text="Input payload sent to TibaBot (sanitized)."),
                ),
                (
                    "result_data",
                    models.JSONField(
                        help_text="Full response JSON from TibaBot or fallback engine."
                    ),
                ),
                (
                    "service_mode",
                    models.CharField(
                        default="tibabot", help_text="'tibabot' or 'fallback'.", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prediction_type",
                    models.CharField(
                        default="predict", help_text="'predict' or 'risk-stratify'.", max_length=20
                    ),
                ),
                ("risk_level", models.CharField(blank=True, default="", max_length=20)),
                ("risk_score", models.FloatField(blank=True, null=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_icu_predictions",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI ICU Risk Result",
                "verbose_name_plural": "AI ICU Risk Results",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AILabInterpretResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(help_text="Input payload sent to TibaBot (sanitized)."),
                ),
                (
                    "result_data",
                    models.JSONField(
                        help_text="Full response JSON from TibaBot or fallback engine."
                    ),
                ),
                (
                    "service_mode",
                    models.CharField(
                        default="tibabot", help_text="'tibabot' or 'fallback'.", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("abnormal_count", models.IntegerField(default=0)),
                ("critical_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_lab_interpretations",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "lab_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interpretations",
                        to="laboratory.labresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Lab Interpretation",
                "verbose_name_plural": "AI Lab Interpretations",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
