# Generated by Django 5.2.13 on 2026-04-21 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_facility_scoped_model_fix'),
        ('core', '0046_alter_facility_logo_alter_organization_logo'),
        ('theatre', '0007_pacurecord_handover_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISurgicalChecklistSessionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_data', models.JSONField(help_text='Input payload sent to TibaBot (sanitized).')),
                ('result_data', models.JSONField(help_text='Full response JSON from TibaBot or fallback engine.')),
                ('service_mode', models.CharField(default='tibabot', help_text="'tibabot' or 'fallback'.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tibabot_session_id', models.CharField(db_index=True, max_length=100)),
                ('current_phase', models.CharField(blank=True, default='', max_length=40)),
                ('percent_complete', models.FloatField(blank=True, null=True)),
                ('phase_complete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_results', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='Facility (branch) where this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.facility')),
                ('organization', models.ForeignKey(blank=True, help_text='Owning organization (tenant).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('surgery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_surgical_checklist_sessions', to='theatre.surgerycase')),
            ],
            options={
                'verbose_name': 'AI Surgical Checklist Session',
                'verbose_name_plural': 'AI Surgical Checklist Sessions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AISurgicalPostOpCarePlanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_data', models.JSONField(help_text='Input payload sent to TibaBot (sanitized).')),
                ('result_data', models.JSONField(help_text='Full response JSON from TibaBot or fallback engine.')),
                ('service_mode', models.CharField(default='tibabot', help_text="'tibabot' or 'fallback'.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procedure_key', models.CharField(blank=True, default='', max_length=100)),
                ('surgical_apgar_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, default='', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_results', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='Facility (branch) where this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.facility')),
                ('organization', models.ForeignKey(blank=True, help_text='Owning organization (tenant).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('surgery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_surgical_post_op_care_plans', to='theatre.surgerycase')),
            ],
            options={
                'verbose_name': 'AI Surgical Post-Op Care Plan',
                'verbose_name_plural': 'AI Surgical Post-Op Care Plans',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AISurgicalPreOpAssessResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_data', models.JSONField(help_text='Input payload sent to TibaBot (sanitized).')),
                ('result_data', models.JSONField(help_text='Full response JSON from TibaBot or fallback engine.')),
                ('service_mode', models.CharField(default='tibabot', help_text="'tibabot' or 'fallback'.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overall_risk_level', models.CharField(blank=True, default='', max_length=20)),
                ('facility_capable', models.BooleanField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_results', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='Facility (branch) where this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.facility')),
                ('organization', models.ForeignKey(blank=True, help_text='Owning organization (tenant).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization')),
                ('surgery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_surgical_pre_op_assessments', to='theatre.surgerycase')),
            ],
            options={
                'verbose_name': 'AI Surgical Pre-Op Assessment',
                'verbose_name_plural': 'AI Surgical Pre-Op Assessments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
