# Generated by Django 5.2.13 on 2026-04-26 19:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_aisurgicalchecklistsessionresult_and_more"),
        ("core", "0050_alter_pushsubscription_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TibaBotFacilityKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="TibaBot API key (tb_...). Shown only once when provisioned.",
                        max_length=255,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="First 16 hex chars of the key hash (returned by TibaBot on provisioning).",
                        max_length=64,
                    ),
                ),
                (
                    "tibabot_facility_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Facility ID registered with TibaBot (e.g. 'knh-001').",
                        max_length=100,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Permitted API scopes (e.g. ["chat", "triage", "icd10", "clinical", "predict"]).',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this key is currently active. Deactivate instead of deleting.",
                    ),
                ),
                (
                    "provisioned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the key was provisioned from TibaBot.",
                    ),
                ),
                (
                    "last_rotated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the key was last rotated.", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Admin notes (rotation reason, etc.)."
                    ),
                ),
                (
                    "facility",
                    models.OneToOneField(
                        help_text="Facility this API key belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tibabot_key",
                        to="core.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "TibaBot Facility Key",
                "verbose_name_plural": "TibaBot Facility Keys",
                "ordering": ["-provisioned_at"],
            },
        ),
    ]
