# Generated by Django 5.2.13 on 2026-04-27 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0007_tibabot_facility_key"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0050_alter_pushsubscription_options"),
        ("imaging", "0005_radiology_reporting"),
        ("laboratory", "0024_add_bill_patient_to_laborder"),
        ("pharmacy", "0023_facility_scoped_model_fix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAdvisoryOrderLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ai_result_id",
                    models.UUIDField(
                        help_text="PK of the AI result row (all AI results use UUID PKs)."
                    ),
                ),
                (
                    "suggestion_category",
                    models.CharField(
                        help_text="Category within result_data, e.g. 'medications', 'pre_op_checklist.investigations', 'complications_to_watch'.",
                        max_length=60,
                    ),
                ),
                (
                    "suggestion_index",
                    models.PositiveIntegerField(
                        help_text="Zero-based index of the suggestion within its category array."
                    ),
                ),
                (
                    "suggestion_text",
                    models.TextField(
                        help_text="Snapshot of the suggestion text at link-creation time."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUGGESTED", "Suggested"),
                            ("ORDERED", "Ordered"),
                            ("DECLINED", "Declined"),
                            ("NOT_APPLICABLE", "Not applicable"),
                        ],
                        default="SUGGESTED",
                        max_length=20,
                    ),
                ),
                ("actioned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actioned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_advisory_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ai_result_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisory_order_links",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "imaging_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_advisory_links",
                        to="imaging.imagingorder",
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_advisory_links",
                        to="laboratory.laborder",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_advisory_links",
                        to="pharmacy.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Advisory Order Link",
                "verbose_name_plural": "AI Advisory Order Links",
                "ordering": ["suggestion_category", "suggestion_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "ai_result_content_type",
                            "ai_result_id",
                            "suggestion_category",
                            "suggestion_index",
                        ),
                        name="unique_advisory_suggestion",
                    )
                ],
            },
        ),
    ]
