# Generated by Django 5.2.13 on 2026-05-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0008_advisory_order_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicareplanresult",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of input/prompt tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aicareplanresult",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of output/completion tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aicareplanresult",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total tokens consumed (input + output).", null=True
            ),
        ),
        migrations.AddField(
            model_name="aicdsresult",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of input/prompt tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aicdsresult",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of output/completion tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aicdsresult",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total tokens consumed (input + output).", null=True
            ),
        ),
        migrations.AddField(
            model_name="aidischargeresult",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of input/prompt tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aidischargeresult",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of output/completion tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aidischargeresult",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total tokens consumed (input + output).", null=True
            ),
        ),
        migrations.AddField(
            model_name="aiicuriskresult",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of input/prompt tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aiicuriskresult",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of output/completion tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aiicuriskresult",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total tokens consumed (input + output).", null=True
            ),
        ),
        migrations.AddField(
            model_name="aiinvestigationsuggestresult",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of input/prompt tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aiinvestigationsuggestresult",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of output/completion tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aiinvestigationsuggestresult",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total tokens consumed (input + output).", null=True
            ),
        ),
        migrations.AddField(
            model_name="ailabinterpretresult",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of input/prompt tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="ailabinterpretresult",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of output/completion tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="ailabinterpretresult",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total tokens consumed (input + output).", null=True
            ),
        ),
        migrations.AddField(
            model_name="aisurgicalchecklistsessionresult",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of input/prompt tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aisurgicalchecklistsessionresult",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of output/completion tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aisurgicalchecklistsessionresult",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total tokens consumed (input + output).", null=True
            ),
        ),
        migrations.AddField(
            model_name="aisurgicalpostopcareplanresult",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of input/prompt tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aisurgicalpostopcareplanresult",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of output/completion tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aisurgicalpostopcareplanresult",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total tokens consumed (input + output).", null=True
            ),
        ),
        migrations.AddField(
            model_name="aisurgicalpreopassessresult",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of input/prompt tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aisurgicalpreopassessresult",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of output/completion tokens consumed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="aisurgicalpreopassessresult",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total tokens consumed (input + output).", null=True
            ),
        ),
    ]
