# Copyright (c) 2026 Nexora Consulting Ltd. All rights reserved.
"""Generate and attach a FINAL_BILL PDF from local invoice/claim data."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from io import BytesIO

from django.core.files.base import ContentFile
from django.db.models import Q

from hmis.apps.billing.models import SHAClaim, SHAClaimAttachment
from hmis.apps.billing.services.document_context import append_standard_header

AUTO_FINAL_BILL_MARKER = "AUTO_FINAL_BILL_FROM_INVOICE"


@dataclass
class FinalBillAttachmentResult:
    attachment_id: int | None
    created: bool
    updated: bool
    skipped_reason: str = ""


class FinalBillAttachmentService:
    """Ensure a local FINAL_BILL-style invoice attachment exists for a claim."""

    @classmethod
    def ensure_for_claim(cls, *, claim: SHAClaim, user) -> FinalBillAttachmentResult:
        uploader = user or getattr(claim, "created_by", None)
        if uploader is None:
            return FinalBillAttachmentResult(
                attachment_id=None,
                created=False,
                updated=False,
                skipped_reason="missing_uploader",
            )

        content = cls._render_final_bill_text(claim)
        if not content:
            return FinalBillAttachmentResult(
                attachment_id=None,
                created=False,
                updated=False,
                skipped_reason="no_invoice_data",
            )

        pdf_bytes = cls._render_pdf_bytes(content)
        filename = f"final_bill_{claim.claim_number}.pdf"
        checksum = hashlib.sha256(pdf_bytes).hexdigest()

        manual_existing = (
            claim.attachments.filter(attachment_type="invoice")
            .filter(Q(name__icontains="final bill") | Q(original_filename__icontains="final_bill"))
            .exclude(description__icontains=AUTO_FINAL_BILL_MARKER)
            .first()
        )
        if manual_existing:
            return FinalBillAttachmentResult(
                attachment_id=manual_existing.id,
                created=False,
                updated=False,
                skipped_reason="manual_final_bill_exists",
            )

        attachment = cls._find_autogenerated_attachment(claim)
        if attachment is None:
            created = SHAClaimAttachment.objects.create(
                claim=claim,
                attachment_type="invoice",
                name=f"Final Bill - {claim.claim_number}",
                description=(
                    "Auto-generated final bill from local invoice and claim line items "
                    f"for claim settlement evidence | System Tag: {AUTO_FINAL_BILL_MARKER}"
                ),
                file=ContentFile(pdf_bytes, name=filename),
                file_size=len(pdf_bytes),
                mime_type="application/pdf",
                checksum=checksum,
                original_filename=filename,
                uploaded_by=uploader,
            )
            return FinalBillAttachmentResult(
                attachment_id=created.id,
                created=True,
                updated=False,
                skipped_reason="",
            )

        attachment.file.save(filename, ContentFile(pdf_bytes), save=False)
        attachment.name = f"Final Bill - {claim.claim_number}"
        attachment.description = (
            "Auto-generated final bill from local invoice and claim line items "
            f"for claim settlement evidence | System Tag: {AUTO_FINAL_BILL_MARKER}"
        )
        attachment.file_size = len(pdf_bytes)
        attachment.mime_type = "application/pdf"
        attachment.checksum = checksum
        attachment.original_filename = filename
        attachment.save(
            update_fields=[
                "file",
                "name",
                "description",
                "file_size",
                "mime_type",
                "checksum",
                "original_filename",
            ]
        )
        return FinalBillAttachmentResult(
            attachment_id=attachment.id,
            created=False,
            updated=True,
            skipped_reason="",
        )

    @classmethod
    def _find_autogenerated_attachment(cls, claim: SHAClaim) -> SHAClaimAttachment | None:
        return (
            claim.attachments.filter(attachment_type="invoice")
            .filter(
                Q(description__icontains=AUTO_FINAL_BILL_MARKER)
                | Q(name__icontains="final bill")
                | Q(original_filename__icontains="final_bill")
            )
            .order_by("-created_at")
            .first()
        )

    @classmethod
    def _render_final_bill_text(cls, claim: SHAClaim) -> str | None:
        invoice = getattr(claim, "invoice", None)
        claim_items = list(claim.items.select_related("tariff").all())

        if not invoice and not claim_items:
            return None

        lines: list[str] = []
        append_standard_header(lines, title="FINAL BILL", claim=claim)
        lines.extend(
            [
                "Billing Context",
                "---------------",
                f"DHA Invoice Number: {getattr(claim, 'dha_invoice_number', '') or 'N/A'}",
                f"Service Date: {getattr(claim, 'service_date', '') or 'N/A'}",
                "",
                "Billed Lines",
                "-----------",
            ]
        )

        total = 0.0
        if invoice:
            lines.append(f"Local Invoice Number: {invoice.invoice_number or 'N/A'}")
            lines.append(f"Invoice Date: {invoice.invoice_date or 'N/A'}")
            lines.append("")
            for item in invoice.items.all():
                qty = item.quantity or 0
                unit = item.unit_price or 0
                line_total = item.line_total or (qty * unit)
                total += float(line_total or 0)
                lines.append(
                    f"- {item.description or 'Service'} | Qty: {qty} | Unit: {unit} | Total: {line_total}"
                )
        else:
            for item in claim_items:
                qty = item.quantity or 0
                unit = item.unit_price or 0
                line_total = item.claimed_amount or (qty * unit)
                total += float(line_total or 0)
                lines.append(
                    f"- {item.description or 'Service'} | Qty: {qty} | Unit: {unit} | Total: {line_total}"
                )

        lines.extend(["", f"Total Amount: {total:.2f}"])
        return "\n".join(lines)

    @staticmethod
    def _render_pdf_bytes(content: str) -> bytes:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas

        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        x = 40
        y = height - 40
        max_width = width - 80
        line_height = 14

        for raw_line in content.splitlines() or [""]:
            line = raw_line or " "
            while line:
                chunk = line
                while pdf.stringWidth(chunk, "Helvetica", 10) > max_width and len(chunk) > 1:
                    chunk = chunk[:-1]
                pdf.setFont("Helvetica", 10)
                pdf.drawString(x, y, chunk)
                y -= line_height
                line = line[len(chunk) :]
                if y < 50:
                    pdf.showPage()
                    y = height - 40

        pdf.save()
        return buffer.getvalue()
