# Generated by Django 5.2.13 on 2026-06-09 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0068_facility_ai_cds_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique hardware/installation identifier generated on first run.",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-friendly name (e.g., 'Reception Desk 1', 'Pharmacy Hub').",
                        max_length=200,
                    ),
                ),
                (
                    "activation_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="One-time activation code issued to the customer.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Activation"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "license_jwt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Current signed license JWT for this installation.",
                    ),
                ),
                (
                    "last_check_in",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this installation checked in for token renewal.",
                        null=True,
                    ),
                ),
                (
                    "check_in_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of last check-in.", null=True
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.TextField(blank=True, default="")),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="App version reported on last check-in.",
                        max_length=50,
                    ),
                ),
                (
                    "os_info",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="OS info reported on last check-in.",
                        max_length=200,
                    ),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who activated this installation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activated_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility this installation is deployed at (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installations",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this installation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
