# Generated by Django 5.2.13 on 2026-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installation",
            name="installation_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique hardware/installation identifier generated on first run.",
                max_length=200,
                unique=True,
            ),
        ),
    ]
