# Generated by Django 5.2.13 on 2026-06-12 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0002_change_installation_id_to_charfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(
                        help_text="Release version string (e.g., '1.4.5').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "manifest_id",
                    models.CharField(
                        help_text="Manifest identifier (e.g., '1.4.5-r3').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "file_hashes",
                    models.JSONField(
                        default=dict, help_text="Map of relative file path → expected SHA-256 hash."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="When this release was published.", null=True
                    ),
                ),
                (
                    "signed_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identity of the release signer (e.g., CI build ID, GPG key fingerprint).",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.AddField(
            model_name="installation",
            name="binary_manifest_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Expected manifest version for integrity checks (e.g., '1.4.5-r3').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="check_in_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of successful check-ins."
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="hardware_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of hardware identifiers (CPU + MB serial + disk UUID).",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="hostname",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hostname reported at last check-in.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="last_reported_hashes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Binary hashes from last check-in {path: sha256}.",
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="revocation_epoch",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Monotonic counter; incremented by cloud to force token refresh.",
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="tamper_flagged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When binary integrity mismatch was first detected.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="tamper_resolved_at",
            field=models.DateTimeField(
                blank=True, help_text="When tamper flag was manually cleared.", null=True
            ),
        ),
        migrations.CreateModel(
            name="CheckInLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("hostname", models.CharField(blank=True, default="", max_length=255)),
                ("app_version", models.CharField(blank=True, default="", max_length=50)),
                ("os_info", models.CharField(blank=True, default="", max_length=200)),
                ("uptime_seconds", models.PositiveIntegerField(default=0)),
                ("user_count_24h", models.PositiveIntegerField(default=0)),
                ("encounter_count_24h", models.PositiveIntegerField(default=0)),
                ("hardware_fingerprint", models.CharField(blank=True, default="", max_length=128)),
                ("binary_hashes", models.JSONField(blank=True, default=dict)),
                (
                    "integrity_match",
                    models.BooleanField(
                        help_text="True if binary hashes matched expected manifest.", null=True
                    ),
                ),
                (
                    "token_issued",
                    models.BooleanField(
                        default=True, help_text="Whether a fresh license JWT was issued."
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_logs",
                        to="licensing.installation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["installation", "-created_at"],
                        name="licensing_c_install_f67bbb_idx",
                    )
                ],
            },
        ),
    ]
