# Generated by Django 5.2.9 on 2026-02-06 18:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("encounters", "0018_encounter_clinic_visit"),
        ("patients", "0010_add_unique_identification_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                ("clinical_indication", models.TextField(help_text="Clinical reason for imaging")),
                (
                    "relevant_clinical_history",
                    models.TextField(
                        blank=True, help_text="Relevant clinical history for radiologist"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ORDERED", "Ordered"),
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed - Pending Report"),
                            ("REPORTED", "Reported"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(auto_now=True)),
                ("scheduled_datetime", models.DateTimeField(blank=True, null=True)),
                ("scheduled_room", models.CharField(blank=True, max_length=50)),
                (
                    "accession_number",
                    models.CharField(blank=True, help_text="PACS accession number", max_length=50),
                ),
                (
                    "study_instance_uid",
                    models.CharField(
                        blank=True, help_text="DICOM Study Instance UID", max_length=128
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imaging_orders",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imaging_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imaging_orders",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imaging Order",
                "verbose_name_plural": "Imaging Orders",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="ImagingProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Unique procedure code", max_length=50, unique=True),
                ),
                ("name", models.CharField(help_text="Full procedure name", max_length=200)),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("XR", "X-Ray"),
                            ("US", "Ultrasound"),
                            ("CT", "Computed Tomography"),
                            ("MRI", "Magnetic Resonance Imaging"),
                            ("NM", "Nuclear Medicine"),
                            ("MG", "Mammography"),
                            ("FL", "Fluoroscopy"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body_region",
                    models.CharField(
                        choices=[
                            ("HEAD", "Head/Brain"),
                            ("NECK", "Neck"),
                            ("CHEST", "Chest"),
                            ("ABDOMEN", "Abdomen"),
                            ("PELVIS", "Pelvis"),
                            ("SPINE", "Spine"),
                            ("UPPER_EXTREMITY", "Upper Extremity"),
                            ("LOWER_EXTREMITY", "Lower Extremity"),
                            ("WHOLE_BODY", "Whole Body"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "radlex_code",
                    models.CharField(blank=True, help_text="RadLex Playbook ID", max_length=50),
                ),
                (
                    "loinc_code",
                    models.CharField(
                        blank=True, help_text="LOINC code for interoperability", max_length=20
                    ),
                ),
                ("requires_contrast", models.BooleanField(default=False)),
                ("requires_sedation", models.BooleanField(default=False)),
                (
                    "special_preparation",
                    models.TextField(blank=True, help_text="Patient preparation instructions"),
                ),
                (
                    "turnaround_hours",
                    models.IntegerField(default=24, help_text="Expected turnaround time in hours"),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "sha_claimable",
                    models.BooleanField(default=True, help_text="Covered by Kenya SHA"),
                ),
                (
                    "sha_intervention_code",
                    models.CharField(
                        blank=True, help_text="SHA intervention code for claims", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("available_in_house", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Imaging Procedure",
                "verbose_name_plural": "Imaging Procedures",
                "ordering": ["modality", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="imaging_ima_code_2e89d1_idx"),
                    models.Index(fields=["modality"], name="imaging_ima_modalit_76eae7_idx"),
                    models.Index(fields=["body_region"], name="imaging_ima_body_re_fc2269_idx"),
                    models.Index(fields=["is_active"], name="imaging_ima_is_acti_5271c7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImagingOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "laterality",
                    models.CharField(
                        choices=[
                            ("NA", "Not Applicable"),
                            ("LEFT", "Left"),
                            ("RIGHT", "Right"),
                            ("BILATERAL", "Bilateral"),
                        ],
                        default="NA",
                        max_length=20,
                    ),
                ),
                (
                    "specific_instructions",
                    models.TextField(
                        blank=True, help_text="Specific instructions for this procedure"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="imaging.imagingorder",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="imaging.imagingprocedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imaging Order Item",
                "verbose_name_plural": "Imaging Order Items",
            },
        ),
        migrations.AddIndex(
            model_name="imagingorder",
            index=models.Index(fields=["order_number"], name="imaging_ima_order_n_64b94d_idx"),
        ),
        migrations.AddIndex(
            model_name="imagingorder",
            index=models.Index(fields=["patient"], name="imaging_ima_patient_9e3d0b_idx"),
        ),
        migrations.AddIndex(
            model_name="imagingorder",
            index=models.Index(fields=["status"], name="imaging_ima_status_14d5d5_idx"),
        ),
        migrations.AddIndex(
            model_name="imagingorder",
            index=models.Index(fields=["ordered_at"], name="imaging_ima_ordered_c273df_idx"),
        ),
        migrations.AddIndex(
            model_name="imagingorder",
            index=models.Index(fields=["priority"], name="imaging_ima_priorit_c8c891_idx"),
        ),
    ]
