# Generated by Django 5.2.9 on 2026-02-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imaging", "0001_initial"),
        ("scheduling", "0003_add_assignment_engine_phase2"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingorder",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked scheduling appointment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imaging_order",
                to="scheduling.appointment",
            ),
        ),
    ]
