# Generated by Django 5.2.9 on 2026-02-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imaging", "0003_dicom_models"),
        ("inpatient", "0015_alter_admission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingorder",
            name="admission",
            field=models.ForeignKey(
                blank=True,
                help_text="IPD admission if imaging ordered during inpatient stay",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imaging_orders",
                to="inpatient.admission",
            ),
        ),
    ]
