# Generated by Django 5.2.9 on 2026-02-14 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imaging", "0004_add_admission_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiologyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "technique",
                    models.TextField(
                        blank=True, default="", help_text="Imaging technique/protocol used"
                    ),
                ),
                (
                    "comparison",
                    models.TextField(
                        blank=True, default="", help_text="Comparison with prior studies (if any)"
                    ),
                ),
                ("findings", models.TextField(help_text="Detailed radiological findings")),
                ("impression", models.TextField(help_text="Summary impression/conclusion")),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Recommended follow-up or additional studies",
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False, help_text="Critical finding requiring urgent communication"
                    ),
                ),
                (
                    "critical_finding_description",
                    models.TextField(
                        blank=True, default="", help_text="Description of the critical finding"
                    ),
                ),
                (
                    "critical_communicated",
                    models.BooleanField(
                        default=False, help_text="Whether critical finding has been communicated"
                    ),
                ),
                (
                    "critical_communicated_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name/identifier of person notified",
                        max_length=200,
                    ),
                ),
                (
                    "critical_communicated_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Communication method (phone, in-person, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "critical_communicated_at",
                    models.DateTimeField(
                        blank=True, help_text="When critical finding was communicated", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PRELIMINARY", "Preliminary"),
                            ("FINAL", "Final"),
                            ("AMENDED", "Amended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was signed/finalized", null=True
                    ),
                ),
                (
                    "amendment_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this report has been amended"
                    ),
                ),
                (
                    "last_amendment_reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for the most recent amendment"
                    ),
                ),
                ("last_amended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "critical_communicated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who communicated the critical finding",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="critical_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imaging_order",
                    models.OneToOneField(
                        help_text="The imaging order this report is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report",
                        to="imaging.imagingorder",
                    ),
                ),
                (
                    "last_amended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amended_radiology_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="Radiologist who created/owns the report",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radiology_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        help_text="The DICOM study linked to this report (if available)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="imaging.dicomstudy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Radiology Report",
                "verbose_name_plural": "Radiology Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amendment_number",
                    models.PositiveIntegerField(
                        help_text="Sequential amendment number for this report"
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for the amendment")),
                (
                    "previous_findings",
                    models.TextField(
                        blank=True, default="", help_text="Findings before this amendment"
                    ),
                ),
                (
                    "previous_impression",
                    models.TextField(
                        blank=True, default="", help_text="Impression before this amendment"
                    ),
                ),
                (
                    "new_findings",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Findings after this amendment (if changed)",
                    ),
                ),
                (
                    "new_impression",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Impression after this amendment (if changed)",
                    ),
                ),
                ("amended_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amended_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="imaging.radiologyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Amendment",
                "verbose_name_plural": "Report Amendments",
                "ordering": ["-amendment_number"],
            },
        ),
        migrations.AddIndex(
            model_name="radiologyreport",
            index=models.Index(fields=["report_number"], name="imaging_rad_report__618433_idx"),
        ),
        migrations.AddIndex(
            model_name="radiologyreport",
            index=models.Index(fields=["imaging_order"], name="imaging_rad_imaging_ef6763_idx"),
        ),
        migrations.AddIndex(
            model_name="radiologyreport",
            index=models.Index(fields=["status"], name="imaging_rad_status_09646a_idx"),
        ),
        migrations.AddIndex(
            model_name="radiologyreport",
            index=models.Index(fields=["is_critical"], name="imaging_rad_is_crit_c7c958_idx"),
        ),
        migrations.AddIndex(
            model_name="radiologyreport",
            index=models.Index(fields=["reported_by"], name="imaging_rad_reporte_363e0d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reportamendment",
            unique_together={("report", "amendment_number")},
        ),
    ]
