# Generated by Django 5.2.13 on 2026-05-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_add_has_private_insurance"),
        ("imaging", "0005_radiology_reporting"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingprocedure",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="imagingprocedure",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="imagingprocedure",
            name="code",
            field=models.CharField(help_text="Procedure code (unique per facility)", max_length=50),
        ),
        migrations.AddIndex(
            model_name="imagingprocedure",
            index=models.Index(fields=["facility"], name="imaging_ima_facilit_9668fd_idx"),
        ),
        migrations.AddConstraint(
            model_name="imagingprocedure",
            constraint=models.UniqueConstraint(
                fields=("facility", "code"), name="unique_procedure_code_per_facility"
            ),
        ),
    ]
