# Generated by Django 5.2.13 on 2026-05-16 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_add_has_private_insurance"),
        ("imaging", "0006_facility_scope_imaging_procedure"),
        ("scheduling", "0019_resource_equipment_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dicomstudy",
            name="calling_ae_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Calling AE title (set for C-STORE arrivals)",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="dicomstudy",
            name="device_serial_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Device serial number from DICOM (0018,1000)",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="dicomstudy",
            name="manufacturer",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Manufacturer from DICOM (0008,0070)",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="dicomstudy",
            name="manufacturer_model_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Manufacturer model name from DICOM (0008,1090)",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="dicomstudy",
            name="source",
            field=models.CharField(
                choices=[
                    ("UPLOAD", "Web Upload"),
                    ("CSTORE", "DICOM C-STORE"),
                    ("EXTERNAL", "External Import"),
                ],
                db_index=True,
                default="UPLOAD",
                help_text="How the study arrived in PACS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dicomstudy",
            name="station_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Station name from DICOM (0008,1010) - typically the modality console hostname",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="dicomstudy",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded/imported this study (null for C-STORE arrivals)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_dicom_studies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ImagingEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Siemens CT Scanner - Room 3')",
                        max_length=200,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("XR", "X-Ray"),
                            ("US", "Ultrasound"),
                            ("CT", "Computed Tomography"),
                            ("MRI", "Magnetic Resonance Imaging"),
                            ("NM", "Nuclear Medicine"),
                            ("MG", "Mammography"),
                            ("FL", "Fluoroscopy"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        help_text="Primary modality",
                        max_length=20,
                    ),
                ),
                (
                    "ae_title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="DICOM AE Title (used for C-STORE/Worklist/MWL)",
                        max_length=16,
                    ),
                ),
                (
                    "station_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="DICOM Station Name (0008,1010)",
                        max_length=128,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, default="", max_length=128)),
                ("model_name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Manufacturer serial number (DICOM 0018,1000)",
                        max_length=128,
                    ),
                ),
                ("software_versions", models.CharField(blank=True, default="", max_length=255)),
                ("room", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("installed_date", models.DateField(blank=True, null=True)),
                ("last_calibration_date", models.DateField(blank=True, null=True)),
                ("next_calibration_due", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "auto_registered",
                    models.BooleanField(
                        default=False,
                        help_text="True if this record was auto-created on first study arrival",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "scheduling_resource",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to scheduling Resource (for QA/maintenance bookings)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imaging_equipment",
                        to="scheduling.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imaging Equipment",
                "verbose_name_plural": "Imaging Equipment",
                "ordering": ["modality", "name"],
            },
        ),
        migrations.AddField(
            model_name="dicomstudy",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="Imaging equipment that produced this study (auto-resolved from DICOM tags)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="studies",
                to="imaging.imagingequipment",
            ),
        ),
        migrations.CreateModel(
            name="StudyShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Random URL-safe token used in the public share URL",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("REFERRAL", "Referral / Second Opinion"),
                            ("PATIENT_COPY", "Patient Copy"),
                            ("RESEARCH", "Research (de-identified)"),
                            ("INSURANCE", "Insurance / SHA Claim"),
                            ("OTHER", "Other"),
                        ],
                        default="REFERRAL",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional human-readable recipient (e.g., 'Dr. J. Mwangi, Aga Khan')",
                        max_length=200,
                    ),
                ),
                ("recipient_email", models.CharField(blank=True, default="", max_length=200)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "pin_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional PIN (hashed with Django's password hasher)",
                        max_length=128,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = unlimited; otherwise number of times the link can be opened",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "allow_download",
                    models.BooleanField(
                        default=False,
                        help_text="If true, recipient may download the original DICOM ZIP",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="imaging.dicomstudy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Share Link",
                "verbose_name_plural": "Study Share Links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="imagingequipment",
            index=models.Index(
                fields=["modality", "is_active"], name="imaging_ima_modalit_cd2aaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingequipment",
            index=models.Index(fields=["ae_title"], name="imaging_ima_ae_titl_72da7b_idx"),
        ),
        migrations.AddIndex(
            model_name="imagingequipment",
            index=models.Index(fields=["serial_number"], name="imaging_ima_serial__1a8cbc_idx"),
        ),
        migrations.AddIndex(
            model_name="studysharelink",
            index=models.Index(fields=["token"], name="imaging_stu_token_9018ca_idx"),
        ),
        migrations.AddIndex(
            model_name="studysharelink",
            index=models.Index(fields=["expires_at"], name="imaging_stu_expires_6afa62_idx"),
        ),
    ]
