# Generated by Django 5.2.13 on 2026-05-25 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_facility_has_imaging_standalone_and_more"),
        ("encounters", "0030_structured_history_models"),
        ("imaging", "0007_dicomstudy_calling_ae_title_and_more"),
        ("patients", "0024_phase_d_drop_pii_plaintext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingorder",
            name="bill_patient",
            field=models.BooleanField(
                default=True,
                help_text="Whether to auto-bill the patient. Defaults to False for standalone orders.",
            ),
        ),
        migrations.AddField(
            model_name="imagingorder",
            name="external_referring_clinician",
            field=models.CharField(
                blank=True,
                help_text="External referring clinician name for walk-in/referral orders",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="imagingorder",
            name="external_referring_facility",
            field=models.CharField(
                blank=True,
                help_text="External referring facility name for walk-in/referral orders",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="imagingorder",
            name="is_walkin",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a standalone/walk-in order without HMIS patient",
            ),
        ),
        migrations.AddField(
            model_name="imagingorder",
            name="walkin_patient_dob",
            field=models.DateField(
                blank=True, help_text="Walk-in patient date of birth", null=True
            ),
        ),
        migrations.AddField(
            model_name="imagingorder",
            name="walkin_patient_gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                help_text="Walk-in patient gender",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="imagingorder",
            name="walkin_patient_id",
            field=models.CharField(
                blank=True,
                help_text="Walk-in patient national ID or other identifier",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="imagingorder",
            name="walkin_patient_name",
            field=models.CharField(
                blank=True, help_text="Walk-in patient full name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="imagingorder",
            name="walkin_patient_phone",
            field=models.CharField(
                blank=True, help_text="Walk-in patient phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="imagingorder",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional - null for standalone walk-in imaging orders",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imaging_orders",
                to="encounters.encounter",
            ),
        ),
        migrations.AlterField(
            model_name="imagingorder",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional - null for standalone walk-in imaging orders",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imaging_orders",
                to="patients.patient",
            ),
        ),
        migrations.CreateModel(
            name="WalkInImagingPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: WLKR-YYYYMMDD-XXXX",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("phone_number_encrypted", models.TextField(blank=True, default="")),
                (
                    "phone_number_hmac",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("email_encrypted", models.TextField(blank=True, default="")),
                ("national_id_encrypted", models.TextField(blank=True, default="")),
                (
                    "national_id_hmac",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NATIONAL_ID", "National ID"),
                            ("PASSPORT", "Passport"),
                            ("BIRTH_CERT", "Birth Certificate"),
                            ("MILITARY_ID", "Military ID"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "referring_facility",
                    models.CharField(
                        blank=True,
                        help_text="External facility that referred this patient",
                        max_length=200,
                    ),
                ),
                (
                    "referring_clinician",
                    models.CharField(
                        blank=True, help_text="Name of referring clinician", max_length=200
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "linked_patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Links to full HMIS patient record if later registered",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imaging_walkin_registrations",
                        to="patients.patient",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Walk-in Imaging Patient",
                "verbose_name_plural": "Walk-in Imaging Patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalImagingOrderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_control_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("sending_application", models.CharField(blank=True, max_length=100)),
                ("sending_facility", models.CharField(max_length=100)),
                ("referring_clinician", models.CharField(blank=True, max_length=200)),
                ("referring_clinician_license", models.CharField(blank=True, max_length=100)),
                ("external_patient_id", models.CharField(blank=True, max_length=100)),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_dob", models.DateField(blank=True, null=True)),
                ("patient_gender", models.CharField(blank=True, max_length=1)),
                ("patient_phone", models.CharField(blank=True, max_length=20)),
                ("patient_id_number", models.CharField(blank=True, max_length=50)),
                (
                    "placer_order_number",
                    models.CharField(
                        db_index=True,
                        help_text="Order/referral number from external system",
                        max_length=100,
                    ),
                ),
                ("priority", models.CharField(default="ROUTINE", max_length=20)),
                ("clinical_indication", models.TextField(blank=True)),
                ("relevant_clinical_history", models.TextField(blank=True)),
                (
                    "requested_procedures",
                    models.JSONField(
                        default=list,
                        help_text="List of requested procedures: [{code, name, laterality, modality}]",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "raw_message",
                    models.TextField(blank=True, help_text="Raw HL7/JSON message content"),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "imaging_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_requests",
                        to="imaging.imagingorder",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "walkin_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_orders",
                        to="imaging.walkinimagingpatient",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Imaging Order Request",
                "verbose_name_plural": "External Imaging Order Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="walkinimagingpatient",
            index=models.Index(
                fields=["registration_number"], name="imaging_wal_registr_93bf2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walkinimagingpatient",
            index=models.Index(fields=["national_id_hmac"], name="imaging_wal_nationa_5ff859_idx"),
        ),
        migrations.AddIndex(
            model_name="walkinimagingpatient",
            index=models.Index(
                fields=["last_name", "first_name"], name="imaging_wal_last_na_23c8b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walkinimagingpatient",
            index=models.Index(fields=["phone_number_hmac"], name="imaging_wal_phone_n_70baf0_idx"),
        ),
        migrations.AddIndex(
            model_name="externalimagingorderrequest",
            index=models.Index(
                fields=["message_control_id"], name="imaging_ext_message_2e820d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalimagingorderrequest",
            index=models.Index(
                fields=["placer_order_number"], name="imaging_ext_placer__6a3ec2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalimagingorderrequest",
            index=models.Index(fields=["status"], name="imaging_ext_status_24023e_idx"),
        ),
    ]
