# Generated by Django 5.2.13 on 2026-07-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imaging", "0011_radiologyreport_supersedes_and_revisions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="radiologyreport",
            new_name="imaging_rad_superse_750b23_idx",
            old_name="imaging_rad_supersede_idx",
        ),
    ]
