# Generated by Django 5.2.13 on 2026-08-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_facility_hdu_nbu_flags"),
        ("imaging", "0013_imagingintegrationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagingintegrationsettings",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AlterField(
            model_name="imagingintegrationsettings",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="imagingintegrationsettings",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="imagingintegrationsettings",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
    ]
