# Generated by Django 5.2.9 on 2026-01-24 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0017_proforma_invoice_support"),
        ("clinical_templates", "0002_add_template_snapshot"),
        ("encounters", "0017_add_admission_integrity_constraints"),
        ("patients", "0010_add_unique_identification_constraint"),
        ("triage", "0005_add_weight_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the clinic (e.g., 'CCC Clinic')", max_length=100
                    ),
                ),
                (
                    "clinic_type",
                    models.CharField(
                        choices=[
                            ("GENERAL_OPD", "General OPD"),
                            ("FILTER_CLINIC", "Filter/Screening Clinic"),
                            ("ANC", "Antenatal Clinic"),
                            ("PNC", "Postnatal Clinic"),
                            ("FP", "Family Planning Clinic"),
                            ("CWC", "Child Welfare Clinic"),
                            ("IMMUNIZATION", "Immunization Clinic"),
                            ("NUTRITION", "Nutrition Clinic"),
                            ("DENTAL", "Dental Clinic"),
                            ("EYE", "Eye/Ophthalmology Clinic"),
                            ("ENT", "ENT Clinic"),
                            ("SURGICAL", "Surgical Outpatient Clinic"),
                            ("ORTHO", "Orthopedic Clinic"),
                            ("PHYSIO", "Physiotherapy Clinic"),
                            ("DERM", "Dermatology Clinic"),
                            ("CCC", "Comprehensive Care Clinic (HIV)"),
                            ("TB", "TB Clinic"),
                            ("DIABETIC", "Diabetic Clinic"),
                            ("HYPERTENSION", "Hypertension Clinic"),
                            ("MENTAL_HEALTH", "Mental Health Clinic"),
                            ("ONCOLOGY", "Oncology Clinic"),
                            ("DIALYSIS", "Dialysis Unit"),
                            ("PROCEDURE", "Procedure Room"),
                            ("DRESSING", "Dressing/Wound Care"),
                            ("INJECTION", "Injection Room"),
                            ("OTHER", "Other Clinic"),
                        ],
                        help_text="Type/category of clinic",
                        max_length=30,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique clinic code (e.g., 'CCC-001', 'DENTAL-001')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Description of services provided"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Physical location (e.g., 'Block A, Room 12')",
                        max_length=100,
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, default="", help_text="Floor/level", max_length=20
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of patients that can be seen simultaneously"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("TEMPORARILY_CLOSED", "Temporarily Closed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "requires_appointment",
                    models.BooleanField(
                        default=False, help_text="Whether patients need prior appointment"
                    ),
                ),
                (
                    "requires_referral",
                    models.BooleanField(
                        default=False,
                        help_text="Whether patients need referral from another clinic",
                    ),
                ),
                (
                    "accepts_walk_ins",
                    models.BooleanField(
                        default=True, help_text="Whether walk-in patients are accepted"
                    ),
                ),
                (
                    "triage_required",
                    models.BooleanField(
                        default=True, help_text="Whether triage is required before this clinic"
                    ),
                ),
                (
                    "eligibility_rules",
                    models.JSONField(
                        blank=True,
                        help_text='\n        Eligibility criteria for this clinic. Example:\n        {\n            "min_age": 0,\n            "max_age": 5,\n            "gender": ["F"],\n            "conditions": ["pregnancy"],\n            "required_enrollments": ["ANC_PROGRAM"]\n        }\n        ',
                        null=True,
                    ),
                ),
                (
                    "default_service_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default consultation fee",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sha_service_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA tariff code for claims",
                        max_length=50,
                    ),
                ),
                (
                    "dhis2_org_unit_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DHIS2 organizational unit ID for reporting",
                        max_length=50,
                    ),
                ),
                (
                    "moh_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MOH service code (for MOH 711/747 reporting)",
                        max_length=20,
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this clinic handles sensitive data (HIV, GBV, Mental Health)",
                    ),
                ),
                (
                    "required_permission",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Permission required to access this clinic's data",
                        max_length=100,
                    ),
                ),
                (
                    "default_clinical_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default clinical template for encounters in this clinic",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_clinics",
                        to="clinical_templates.clinicaltemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic",
                "verbose_name_plural": "Clinics",
                "ordering": ["name"],
                "permissions": [
                    ("view_ccc_clinic", "Can view CCC (HIV) clinic data"),
                    ("view_mental_health_clinic", "Can view Mental Health clinic data"),
                    ("manage_clinic_staff", "Can manage clinic staff assignments"),
                    ("manage_clinic_schedule", "Can manage clinic schedules"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClinicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_date", models.DateField(help_text="Date of this clinic session")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, help_text="When the session was opened", null=True
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the session was closed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Session notes (e.g., issues, supply shortages)",
                    ),
                ),
                ("patients_registered", models.PositiveIntegerField(default=0)),
                ("patients_seen", models.PositiveIntegerField(default=0)),
                ("patients_waiting", models.PositiveIntegerField(default=0)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_clinic_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_clinic_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Session",
                "verbose_name_plural": "Clinic Sessions",
                "ordering": ["-session_date", "clinic"],
                "unique_together": {("clinic", "session_date")},
            },
        ),
        migrations.CreateModel(
            name="ClinicEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Clinic-specific ID (e.g., CCC number, ANC number)",
                        max_length=50,
                    ),
                ),
                ("enrollment_date", models.DateField(help_text="Date of enrollment")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed/Graduated"),
                            ("TRANSFERRED_OUT", "Transferred Out"),
                            ("LOST_TO_FOLLOW_UP", "Lost to Follow-up"),
                            ("DECEASED", "Deceased"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                (
                    "enrollment_data",
                    models.JSONField(
                        blank=True,
                        help_text='\n        Clinic-specific enrollment data. Examples:\n\n        CCC: {\n            "art_start_date": "2024-01-15",\n            "current_regimen": "TDF/3TC/DTG",\n            "who_stage": 2,\n            "cd4_baseline": 350\n        }\n\n        ANC: {\n            "lmp": "2025-09-01",\n            "edd": "2026-06-08",\n            "gravida": 2,\n            "parity": 1\n        }\n\n        Diabetic: {\n            "diagnosis_date": "2020-05-15",\n            "diabetes_type": "Type 2",\n            "current_medications": ["Metformin 500mg BD"]\n        }\n        ',
                        null=True,
                    ),
                ),
                (
                    "next_appointment",
                    models.DateField(blank=True, help_text="Next scheduled visit", null=True),
                ),
                (
                    "appointment_interval_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Default days between appointments"
                    ),
                ),
                (
                    "last_visit_date",
                    models.DateField(blank=True, help_text="Date of last clinic visit", null=True),
                ),
                (
                    "total_visits",
                    models.PositiveIntegerField(
                        default=0, help_text="Total visits since enrollment"
                    ),
                ),
                (
                    "outcome_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of outcome (completion, transfer, etc.)",
                        null=True,
                    ),
                ),
                (
                    "outcome_reason",
                    models.TextField(blank=True, default="", help_text="Reason for outcome"),
                ),
                (
                    "transfer_facility",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Facility transferred to (if applicable)",
                        max_length=200,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinic_enrollments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_enrollments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Enrollment",
                "verbose_name_plural": "Clinic Enrollments",
                "ordering": ["-enrollment_date"],
                "unique_together": {("clinic", "patient", "enrollment_date")},
            },
        ),
        migrations.CreateModel(
            name="ClinicSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of the week (0=Monday, 6=Sunday)",
                    ),
                ),
                ("start_time", models.TimeField(help_text="Opening time")),
                ("end_time", models.TimeField(help_text="Closing time")),
                (
                    "max_patients",
                    models.PositiveIntegerField(
                        default=50, help_text="Maximum patients per session"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="E.g., 'ANC on Mondays only'",
                        max_length=200,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Schedule",
                "verbose_name_plural": "Clinic Schedules",
                "ordering": ["clinic", "day_of_week", "start_time"],
                "unique_together": {("clinic", "day_of_week", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="ClinicStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEAD", "Clinic Lead/In-Charge"),
                            ("DOCTOR", "Doctor/Clinical Officer"),
                            ("NURSE", "Nurse"),
                            ("COUNSELOR", "Counselor"),
                            ("NUTRITIONIST", "Nutritionist"),
                            ("CLERK", "Clerk/Receptionist"),
                            ("OTHER", "Other"),
                        ],
                        default="DOCTOR",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary clinic for this staff member"
                    ),
                ),
                ("start_date", models.DateField(help_text="Assignment start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Assignment end date (null = ongoing)", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Staff Assignment",
                "verbose_name_plural": "Clinic Staff Assignments",
                "ordering": ["clinic", "role", "user__last_name"],
                "unique_together": {("clinic", "user", "role")},
            },
        ),
        migrations.CreateModel(
            name="ClinicVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "queue_number",
                    models.PositiveIntegerField(help_text="Queue number for this session"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered - In queue"),
                            ("WAITING", "Waiting to be called"),
                            ("CALLED", "Called - Patient summoned"),
                            ("IN_CONSULTATION", "In Consultation"),
                            ("COMPLETED", "Completed"),
                            ("REFERRED", "Referred to another clinic"),
                            ("NO_SHOW", "No Show"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REGISTERED",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency (RED)"),
                            ("URGENT", "Urgent (ORANGE)"),
                            ("PRIORITY", "Priority (YELLOW)"),
                            ("STANDARD", "Standard (GREEN)"),
                            ("NON_URGENT", "Non-urgent (BLUE)"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New Patient"),
                            ("RETURN", "Return Visit"),
                            ("FOLLOW_UP", "Follow-up"),
                            ("REFERRAL", "Referral from another clinic"),
                            ("SCHEDULED", "Scheduled Appointment"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("TRIAGE", "From Triage"),
                            ("DIRECT", "Direct to Clinic"),
                            ("REFERRAL", "Referral from Clinic"),
                            ("APPOINTMENT", "Scheduled Appointment"),
                            ("INPATIENT", "From Inpatient Ward"),
                        ],
                        default="TRIAGE",
                        max_length=20,
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When patient was added to clinic queue"
                    ),
                ),
                (
                    "called_at",
                    models.DateTimeField(
                        blank=True, help_text="When patient was called", null=True
                    ),
                ),
                (
                    "consultation_started_at",
                    models.DateTimeField(
                        blank=True, help_text="When consultation started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When visit was completed", null=True
                    ),
                ),
                (
                    "referral_reason",
                    models.TextField(blank=True, default="", help_text="Reason for referral"),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True, default="", help_text="Chief complaint / reason for visit"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", help_text="Additional notes")),
                (
                    "consultation_fee_charged",
                    models.BooleanField(
                        default=False, help_text="Whether consultation fee has been charged"
                    ),
                ),
                (
                    "assigned_clinician",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clinician assigned to see this patient",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_clinic_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "billing_line_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated billing line item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinic_visits",
                        to="billing.invoiceitem",
                    ),
                ),
                (
                    "encounter",
                    models.OneToOneField(
                        blank=True,
                        help_text="Encounter created for this visit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinic_visit",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_visits",
                        to="patients.patient",
                    ),
                ),
                (
                    "referred_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="If referred, the source clinic visit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_out",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "referred_to_clinic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clinic patient was referred to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_referrals",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who registered the visit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_clinic_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="clinics.clinicsession",
                    ),
                ),
                (
                    "triage_assessment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Triage assessment that routed patient here",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinic_visits",
                        to="triage.triageassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Visit",
                "verbose_name_plural": "Clinic Visits",
                "ordering": ["session", "priority", "queue_number"],
                "indexes": [
                    models.Index(
                        fields=["session", "status"], name="clinics_cli_session_161d18_idx"
                    ),
                    models.Index(
                        fields=["patient", "session"], name="clinics_cli_patient_47d7de_idx"
                    ),
                    models.Index(
                        fields=["status", "priority"], name="clinics_cli_status_d75711_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "queue_number"), name="unique_queue_number_per_session"
                    )
                ],
            },
        ),
    ]
