# Generated by Django 5.2.9 on 2026-01-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0001_initial_clinic_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicenrollment",
            name="art_regimen_line",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIRST_LINE", "First Line"),
                    ("SECOND_LINE", "Second Line"),
                    ("THIRD_LINE", "Third Line"),
                ],
                default="",
                help_text="ART regimen line",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="art_start_date",
            field=models.DateField(blank=True, help_text="Date ART was initiated", null=True),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="baseline_cd4_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="CD4 count at enrollment (cells/µL)", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="",
                help_text="Mother's blood group",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="current_art_regimen",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Current ART regimen (e.g., TDF/3TC/DTG)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="diabetes_complications",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Known diabetes complications (retinopathy, nephropathy, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="diabetes_diagnosis_date",
            field=models.DateField(blank=True, help_text="Date diabetes was diagnosed", null=True),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="diabetes_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TYPE_1", "Type 1"),
                    ("TYPE_2", "Type 2"),
                    ("GESTATIONAL", "Gestational"),
                    ("OTHER", "Other"),
                ],
                default="",
                help_text="Type of diabetes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="edd",
            field=models.DateField(
                blank=True, help_text="Expected Date of Delivery (calculated from LMP)", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="gravida",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Number of pregnancies (including current)", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Mother's height in cm (for BMI calculation)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="high_risk_factors",
            field=models.TextField(
                blank=True, default="", help_text="List of high-risk factors if applicable"
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="high_risk_pregnancy",
            field=models.BooleanField(default=False, help_text="Is this a high-risk pregnancy?"),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="hiv_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POSITIVE", "Positive"),
                    ("NEGATIVE", "Negative"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="",
                help_text="HIV status for ANC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="last_reminder_sent",
            field=models.DateTimeField(
                blank=True, help_text="When the last appointment reminder was sent", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="latest_cd4_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Most recent CD4 count (cells/µL)", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="latest_cd4_date",
            field=models.DateField(
                blank=True, help_text="Date of most recent CD4 count", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="latest_fbs",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Latest Fasting Blood Sugar (mmol/L)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="latest_fbs_date",
            field=models.DateField(blank=True, help_text="Date of latest FBS test", null=True),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="latest_hba1c",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Most recent HbA1c (%)",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="latest_hba1c_date",
            field=models.DateField(
                blank=True, help_text="Date of most recent HbA1c test", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="latest_viral_load",
            field=models.PositiveIntegerField(
                blank=True, help_text="Most recent viral load (copies/mL)", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="latest_viral_load_date",
            field=models.DateField(
                blank=True, help_text="Date of most recent viral load test", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="lmp",
            field=models.DateField(blank=True, help_text="Last Menstrual Period date", null=True),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="missed_appointment_alerts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of missed appointment alerts sent"
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="on_insulin",
            field=models.BooleanField(default=False, help_text="Is patient on insulin?"),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="para",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Number of births (live or stillborn >= 28 weeks)", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="partner_hiv_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POSITIVE", "Positive"),
                    ("NEGATIVE", "Negative"),
                    ("UNKNOWN", "Unknown"),
                    ("NOT_TESTED", "Not Tested"),
                ],
                default="",
                help_text="Partner HIV status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="previous_cesarean",
            field=models.BooleanField(
                default=False, help_text="History of previous cesarean section"
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="rhesus_factor",
            field=models.CharField(
                blank=True,
                choices=[("POSITIVE", "Positive"), ("NEGATIVE", "Negative")],
                default="",
                help_text="Rhesus factor",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="viral_load_suppressed",
            field=models.BooleanField(
                blank=True, help_text="Is viral load suppressed (<1000 copies/mL)?", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicenrollment",
            name="who_clinical_stage",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Stage 1"), (2, "Stage 2"), (3, "Stage 3"), (4, "Stage 4")],
                help_text="WHO clinical stage at enrollment",
                null=True,
            ),
        ),
    ]
