# Generated by Django 5.2.9 on 2026-02-08 20:46
"""
Data migration to fix invalid clinic status values.

Some clinics have status='OPEN' which is not a valid choice.
Valid choices are: ACTIVE, INACTIVE, TEMPORARILY_CLOSED.
This migration updates any 'OPEN' status to 'ACTIVE'.
"""

from django.db import migrations


def fix_invalid_clinic_status(apps, schema_editor):
    """Update clinics with invalid 'OPEN' status to 'ACTIVE'."""
    Clinic = apps.get_model("clinics", "Clinic")
    updated_count = Clinic.objects.filter(status="OPEN").update(status="ACTIVE")
    if updated_count:
        print(f"\n  Fixed {updated_count} clinic(s) with invalid status='OPEN' -> 'ACTIVE'")


def reverse_noop(apps, schema_editor):
    """No reverse operation - we don't want to restore invalid data."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0007_seed_specialty_and_procedure_clinics"),
    ]

    operations = [
        migrations.RunPython(fix_invalid_clinic_status, reverse_noop),
    ]
