# Generated by Django 5.2.11 on 2026-03-08 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0010_alter_clinic_clinic_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicvisit",
            name="source_module",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Source module or workflow that created this visit (for traceability)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="clinicvisit",
            name="source_record_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Source record identifier used during live linking and backfill reconciliation",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ClinicProgramAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_date",
                    models.DateField(
                        help_text="Canonical attendance date derived from the linked clinic visit"
                    ),
                ),
                (
                    "source_module",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Clinical module that generated the attendance event",
                        max_length=30,
                    ),
                ),
                (
                    "source_record_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Clinical payload id associated with this attendance event",
                        null=True,
                    ),
                ),
                (
                    "clinic_visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_attendance",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_events",
                        to="clinics.clinicenrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Program Attendance",
                "verbose_name_plural": "Clinic Program Attendance",
                "ordering": ["-attendance_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["enrollment", "attendance_date"],
                        name="clinics_cli_enrollm_728fb9_idx",
                    ),
                    models.Index(
                        fields=["source_module", "source_record_id"],
                        name="clinics_cli_source__5ada57_idx",
                    ),
                ],
            },
        ),
    ]
