# Generated by Django 5.2.11 on 2026-03-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0011_clinicvisit_source_module_and_more"),
        ("core", "0029_multitenancy_clinical_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where this clinic operates.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinics",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinics",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="clinicsession",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where this session runs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_sessions",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="clinicsession",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_sessions",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="clinicvisit",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where this visit occurred.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_visits",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="clinicvisit",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_visits",
                to="core.organization",
            ),
        ),
    ]
