# Generated by Django 5.2.11 on 2026-04-12 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0012_multitenancy_clinical_fks"),
        ("scheduling", "0005_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="scheduling_resource",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked scheduling resource (auto-created for PLACE type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic",
                to="scheduling.resource",
            ),
        ),
    ]
