# Generated by Django 5.2.11 on 2026-04-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0013_add_scheduling_resource"),
        ("scheduling", "0012_add_manage_schedules_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicvisit",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Room assigned to this visit (auto-set from clinician's active shift)",
                limit_choices_to={"resource_type": "PLACE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_visits",
                to="scheduling.resource",
            ),
        ),
        migrations.CreateModel(
            name="ClinicRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is a default room for the clinic"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order for room listing"
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_rooms",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Room (PLACE resource) linked to this clinic",
                        limit_choices_to={"resource_type": "PLACE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_rooms",
                        to="scheduling.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Room",
                "verbose_name_plural": "Clinic Rooms",
                "ordering": ["display_order", "room__name"],
                "constraints": [
                    models.UniqueConstraint(fields=("clinic", "room"), name="unique_clinic_room")
                ],
            },
        ),
    ]
