# Generated by Django 5.2.11 on 2026-04-13 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0014_clinicvisit_room_clinicroom"),
        ("core", "0039_projection_read_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department this clinic belongs to (e.g., Outpatient, MCH)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinics",
                to="core.department",
            ),
        ),
    ]
