# Generated by Django 5.2.13 on 2026-07-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical_templates", "0002_add_template_snapshot"),
        ("clinics", "0018_remove_orphaned_seed_clinics"),
        ("core", "0071_staffprofile_employee_id_unique"),
        ("scheduling", "0022_shift_type_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="code",
            field=models.CharField(
                help_text="Clinic code, unique per facility (e.g., 'CCC-001', 'DENTAL-001')",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="clinic",
            constraint=models.UniqueConstraint(
                fields=("facility", "code"), name="unique_clinic_code_per_facility"
            ),
        ),
    ]
