# Generated by Django 5.2.13 on 2026-07-06 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0019_clinic_code_unique_per_facility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicvisit",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, help_text="When visit was cancelled", null=True),
        ),
        migrations.AddField(
            model_name="clinicvisit",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who cancelled the visit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_clinic_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
