# Generated by Django 5.2.13 on 2026-07-06 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0020_add_cancel_fields_to_clinic_visit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicvisit",
            name="no_show_at",
            field=models.DateTimeField(
                blank=True, help_text="When patient was marked as no-show", null=True
            ),
        ),
        migrations.AddField(
            model_name="clinicvisit",
            name="no_show_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who marked the visit as no-show",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="no_show_clinic_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
