"""
Serializer contract tests for dialysis app.

Auto-generated by scripts/generate_contracts.py — DO NOT edit field sets manually.
Re-run the script to update after serializer changes:
    poetry run python scripts/generate_contracts.py
"""

import pytest  # type: ignore

from hmis.apps.dialysis.serializers import (
    DialysisOrderCreateSerializer,
    DialysisOrderDetailSerializer,
    DialysisOrderListSerializer,
    DialysisSessionCreateSerializer,
    DialysisSessionDetailSerializer,
    DialysisSessionListSerializer,
    VascularAccessCreateSerializer,
    VascularAccessDetailSerializer,
    VascularAccessListSerializer,
)

CONTRACTS: list[tuple[type, frozenset[str]]] = [
    (
        DialysisOrderCreateSerializer,
        frozenset(
            {
                "anticoagulation",
                "blood_flow_rate",
                "clinical_indication",
                "dialysate_composition",
                "dialysate_flow_rate",
                "dialysis_type",
                "dry_weight_kg",
                "end_date",
                "frequency",
                "notes",
                "patient",
                "start_date",
                "target_duration_minutes",
                "target_uf_volume",
                "vascular_access",
            }
        ),
    ),
    (
        DialysisOrderDetailSerializer,
        frozenset(
            {
                "anticoagulation",
                "blood_flow_rate",
                "clinical_indication",
                "created_at",
                "dialysate_composition",
                "dialysate_flow_rate",
                "dialysis_type",
                "dry_weight_kg",
                "end_date",
                "frequency",
                "id",
                "notes",
                "ordered_by",
                "ordered_by_name",
                "patient",
                "patient_mrn",
                "patient_name",
                "start_date",
                "status",
                "target_duration_minutes",
                "target_uf_volume",
                "updated_at",
                "vascular_access",
            }
        ),
    ),
    (
        DialysisOrderListSerializer,
        frozenset(
            {
                "created_at",
                "dialysis_type",
                "end_date",
                "frequency",
                "id",
                "ordered_by_name",
                "patient",
                "patient_mrn",
                "patient_name",
                "start_date",
                "status",
                "target_duration_minutes",
            }
        ),
    ),
    (
        DialysisSessionCreateSerializer,
        frozenset(
            {
                "blood_flow_rate",
                "dialysate_flow_rate",
                "dialysis_type",
                "encounter",
                "machine_number",
                "notes",
                "order",
                "patient",
                "scheduled_date",
                "uf_goal_ml",
                "vascular_access",
            }
        ),
    ),
    (
        DialysisSessionDetailSerializer,
        frozenset(
            {
                "actual_duration_minutes",
                "blood_flow_rate",
                "complications",
                "created_at",
                "dialysate_flow_rate",
                "dialysis_type",
                "encounter",
                "end_time",
                "id",
                "machine_number",
                "notes",
                "order",
                "patient",
                "patient_mrn",
                "patient_name",
                "performed_by",
                "performed_by_name",
                "post_bp",
                "post_pulse",
                "post_weight_kg",
                "pre_bp",
                "pre_pulse",
                "pre_temperature",
                "pre_weight_kg",
                "scheduled_date",
                "session_number",
                "start_time",
                "status",
                "uf_achieved_ml",
                "uf_goal_ml",
                "updated_at",
                "vascular_access",
            }
        ),
    ),
    (
        DialysisSessionListSerializer,
        frozenset(
            {
                "actual_duration_minutes",
                "created_at",
                "dialysis_type",
                "end_time",
                "id",
                "machine_number",
                "patient",
                "patient_mrn",
                "patient_name",
                "scheduled_date",
                "session_number",
                "start_time",
                "status",
            }
        ),
    ),
    (
        VascularAccessCreateSerializer,
        frozenset(
            {
                "access_type",
                "notes",
                "patient",
                "placed_by",
                "placed_date",
                "site",
            }
        ),
    ),
    (
        VascularAccessDetailSerializer,
        frozenset(
            {
                "access_type",
                "created_at",
                "id",
                "last_assessment_date",
                "notes",
                "patient",
                "patient_name",
                "placed_by",
                "placed_date",
                "site",
                "status",
                "updated_at",
            }
        ),
    ),
    (
        VascularAccessListSerializer,
        frozenset(
            {
                "access_type",
                "created_at",
                "id",
                "last_assessment_date",
                "patient",
                "patient_name",
                "placed_date",
                "site",
                "status",
            }
        ),
    ),
]


def _serializer_id(val):
    """Return readable test ID for parametrize."""
    return val.__name__ if isinstance(val, type) else None


@pytest.mark.django_db
class TestContractsDialysis:
    """Contract tests for dialysis serializers."""

    @pytest.mark.parametrize(
        "serializer_class, expected_fields",
        CONTRACTS,
        ids=lambda val: _serializer_id(val),
    )
    def test_serializer_fields_match_contract(self, serializer_class, expected_fields):
        """Serializer field set must match the contract exactly."""
        actual_fields = frozenset(serializer_class().fields.keys())

        added = actual_fields - expected_fields
        removed = expected_fields - actual_fields

        assert not added, (
            f"\n{serializer_class.__name__}: new fields added to serializer.\n"
            f"  Added: {sorted(added)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to include these fields"
        )
        assert not removed, (
            f"\n{serializer_class.__name__}: fields removed from serializer.\n"
            f"  Removed: {sorted(removed)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to remove these fields"
        )
