"""
Serializer contract tests for encounters app.

Auto-generated by scripts/generate_contracts.py — DO NOT edit field sets manually.
Re-run the script to update after serializer changes:
    poetry run python scripts/generate_contracts.py
"""

import pytest  # type: ignore

from hmis.apps.encounters.serializers import (
    DiagnosisNestedSerializer,
    DiagnosisSerializer,
    EncounterListSerializer,
    EncounterSerializer,
    ICD10CodeSerializer,
    InlineCDSAlertSerializer,
    MedicationNestedSerializer,
    MedicationSerializer,
    TreatmentPlanSerializer,
    TreatmentPlanTemplateSerializer,
)

CONTRACTS: list[tuple[type, frozenset[str]]] = [
    (
        DiagnosisNestedSerializer,
        frozenset(
            {
                "certainty",
                "diagnosed_by",
                "diagnosed_by_name",
                "diagnosis_type",
                "free_text_diagnosis",
                "icd10_code",
                "icd10_code_display",
                "icd10_description",
                "icd11_code",
                "icd11_display",
                "id",
                "is_confirmed",
                "snomed_code",
                "snomed_display",
            }
        ),
    ),
    (
        DiagnosisSerializer,
        frozenset(
            {
                "certainty",
                "created_at",
                "diagnosed_at",
                "diagnosed_by",
                "diagnosed_by_name",
                "diagnosis_type",
                "encounter",
                "free_text_diagnosis",
                "icd10_code",
                "icd10_code_display",
                "icd10_description",
                "icd11_code",
                "icd11_display",
                "id",
                "is_confirmed",
                "notes",
                "snomed_code",
                "snomed_display",
                "updated_at",
            }
        ),
    ),
    (
        EncounterListSerializer,
        frozenset(
            {
                "chief_complaint",
                "clinic_name",
                "clinic_type",
                "clinic_visit_id",
                "created_at",
                "disposition",
                "encounter_date",
                "encounter_type",
                "finalized_at",
                "has_critical_vitals",
                "id",
                "patient",
                "patient_mrn",
                "patient_name",
                "status",
                "visit_reason",
            }
        ),
    ),
    (
        EncounterSerializer,
        frozenset(
            {
                "alerts",
                "allergies",
                "arrival_time",
                "assessment",
                "assigned_clinician",
                "assigned_clinician_name",
                "assigned_clinician_username",
                "blood_pressure",
                "bmi",
                "bmi_classification",
                "called_at",
                "can_enter_consultation",
                "cancellation_reason",
                "cds_alerts",
                "chief_complaint",
                "chief_complaint_edit_reason",
                "chief_complaint_edit_reason_other",
                "chief_complaint_edited",
                "chief_complaint_edited_at",
                "chief_complaint_edited_by",
                "chief_complaint_edited_by_username",
                "chief_complaint_original",
                "chronic_conditions",
                "claimed_at",
                "clinic_name",
                "clinic_type",
                "clinic_visit_id",
                "clinical_template",
                "clinical_template_data",
                "consultation_started_at",
                "consultation_status",
                "created_at",
                "created_by",
                "created_by_name",
                "current_medications",
                "diastolic_bp",
                "disposition",
                "disposition_notes",
                "encounter_date",
                "encounter_type",
                "encounter_type_display",
                "facility",
                "facility_name",
                "family_history",
                "finalized_at",
                "finalized_by",
                "finalized_by_username",
                "has_critical_vitals",
                "height",
                "history_of_present_illness",
                "id",
                "linked_encounter",
                "notes",
                "organization",
                "organization_name",
                "past_surgeries",
                "patient",
                "patient_age",
                "patient_date_of_birth",
                "patient_gender",
                "patient_id",
                "patient_mrn",
                "patient_name",
                "physical_examination",
                "pulse",
                "respiratory_rate",
                "social_history",
                "spo2",
                "status",
                "systolic_bp",
                "temperature",
                "triage_bypass_reason",
                "triage_bypassed_at",
                "triage_bypassed_by",
                "triage_bypassed_by_username",
                "triage_category",
                "triage_completed_at",
                "triage_requirement",
                "triage_status",
                "updated_at",
                "visit_reason",
                "vitals_recorded_at",
                "vitals_recorded_by",
                "vitals_source",
                "vitals_summary",
                "wait_time_minutes",
                "weight",
            }
        ),
    ),
    (
        ICD10CodeSerializer,
        frozenset(
            {
                "category",
                "chapter",
                "code",
                "description",
                "id",
                "is_active",
                "is_billable",
                "long_description",
                "short_description",
            }
        ),
    ),
    (
        InlineCDSAlertSerializer,
        frozenset(
            {
                "created_at",
                "id",
                "is_critical",
                "message",
                "priority",
                "rule_code",
                "rule_name",
                "status",
                "suggestion",
            }
        ),
    ),
    (
        MedicationNestedSerializer,
        frozenset(
            {
                "dosage",
                "duration",
                "frequency",
                "id",
                "instructions",
                "is_active",
                "name",
                "quantity",
                "route",
            }
        ),
    ),
    (
        MedicationSerializer,
        frozenset(
            {
                "created_at",
                "dosage",
                "duration",
                "end_date",
                "frequency",
                "id",
                "instructions",
                "is_active",
                "name",
                "quantity",
                "route",
                "start_date",
                "treatment_plan",
                "updated_at",
            }
        ),
    ),
    (
        TreatmentPlanSerializer,
        frozenset(
            {
                "activity_restrictions",
                "approved_by",
                "approved_by_name",
                "clinical_notes",
                "created_at",
                "created_by",
                "created_by_name",
                "diet_recommendations",
                "encounter",
                "follow_up_date",
                "follow_up_instructions",
                "has_follow_up",
                "has_referral",
                "id",
                "medications",
                "medications_json",
                "procedures_json",
                "referral_needed",
                "referral_notes",
                "referral_specialty",
                "status",
                "template",
                "template_name",
                "updated_at",
            }
        ),
    ),
    (
        TreatmentPlanTemplateSerializer,
        frozenset(
            {
                "created_at",
                "created_by",
                "created_by_name",
                "default_instructions",
                "default_medications",
                "default_procedures",
                "department",
                "description",
                "diagnosis_codes",
                "diagnosis_codes_display",
                "follow_up_days",
                "id",
                "is_active",
                "name",
                "updated_at",
            }
        ),
    ),
]


def _serializer_id(val):
    """Return readable test ID for parametrize."""
    return val.__name__ if isinstance(val, type) else None


@pytest.mark.django_db
class TestContractsEncounters:
    """Contract tests for encounters serializers."""

    @pytest.mark.parametrize(
        "serializer_class, expected_fields",
        CONTRACTS,
        ids=lambda val: _serializer_id(val),
    )
    def test_serializer_fields_match_contract(self, serializer_class, expected_fields):
        """Serializer field set must match the contract exactly."""
        actual_fields = frozenset(serializer_class().fields.keys())

        added = actual_fields - expected_fields
        removed = expected_fields - actual_fields

        assert not added, (
            f"\n{serializer_class.__name__}: new fields added to serializer.\n"
            f"  Added: {sorted(added)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to include these fields"
        )
        assert not removed, (
            f"\n{serializer_class.__name__}: fields removed from serializer.\n"
            f"  Removed: {sorted(removed)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to remove these fields"
        )
