"""
Serializer contract tests for laboratory_standalone app.

Auto-generated by scripts/generate_contracts.py — DO NOT edit field sets manually.
Re-run the script to update after serializer changes:
    poetry run python scripts/generate_contracts.py
"""

import pytest  # type: ignore

from hmis.apps.laboratory.standalone.serializers import (
    ExternalOrderAcceptSerializer,
    ExternalOrderRejectSerializer,
    ExternalOrderRequestSerializer,
    ExternalPatientIdentifierCrosswalkSerializer,
    InboundIngestionEventSerializer,
    InboundOrderIngestSerializer,
    LISMessageMappingSerializer,
    LISMessageMappingUpsertSerializer,
    LISMessageMappingValidationSerializer,
    ResultDeliveryLogSerializer,
    ResultDeliveryRequestSerializer,
    StandaloneOrderCreateSerializer,
    StandaloneOrderItemSerializer,
    WalkInPatientCreateSerializer,
    WalkInPatientSerializer,
)

CONTRACTS: list[tuple[type, frozenset[str]]] = [
    (
        ExternalOrderAcceptSerializer,
        frozenset(
            {
                "auto_create_walkin",
                "diagnostic_package",
                "enable_billing",
                "payer_type",
            }
        ),
    ),
    (
        ExternalOrderRejectSerializer,
        frozenset(
            {
                "reason",
            }
        ),
    ),
    (
        ExternalOrderRequestSerializer,
        frozenset(
            {
                "clinical_info",
                "created_at",
                "external_patient_id",
                "id",
                "lab_order",
                "message_control_id",
                "order_priority",
                "patient_dob",
                "patient_gender",
                "patient_id_number",
                "patient_name",
                "placer_order_number",
                "processed_at",
                "processed_by",
                "rejection_reason",
                "requested_tests",
                "sending_application",
                "sending_facility",
                "status",
                "updated_at",
                "walkin_patient",
            }
        ),
    ),
    (
        ExternalPatientIdentifierCrosswalkSerializer,
        frozenset(
            {
                "created_at",
                "external_member_id",
                "external_patient_id",
                "id",
                "patient",
                "patient_name_snapshot",
                "source_system",
                "updated_at",
                "walkin_patient",
            }
        ),
    ),
    (
        InboundIngestionEventSerializer,
        frozenset(
            {
                "channel",
                "created_at",
                "error_message",
                "external_order",
                "id",
                "idempotency_key",
                "last_replayed_at",
                "processed_at",
                "replay_count",
                "source_system",
                "status",
                "trace_id",
                "updated_at",
            }
        ),
    ),
    (
        InboundOrderIngestSerializer,
        frozenset(
            {
                "channel",
                "hl7_message",
                "message_format",
                "payload",
                "source_system",
            }
        ),
    ),
    (
        LISMessageMappingSerializer,
        frozenset(
            {
                "code_system",
                "created_at",
                "external_code",
                "external_display",
                "id",
                "is_active",
                "notes",
                "relationship",
                "test_code",
                "test_id",
                "test_name",
                "updated_at",
            }
        ),
    ),
    (
        LISMessageMappingUpsertSerializer,
        frozenset(
            {
                "code_system",
                "external_code",
                "external_display",
                "is_active",
                "notes",
                "relationship",
                "test_code",
            }
        ),
    ),
    (
        LISMessageMappingValidationSerializer,
        frozenset(
            {
                "hl7_message",
                "message_format",
                "payload",
                "source_system",
            }
        ),
    ),
    (
        ResultDeliveryLogSerializer,
        frozenset(
            {
                "attempt_count",
                "channel",
                "created_at",
                "delivered_at",
                "destination",
                "error_message",
                "external_order",
                "id",
                "lab_order",
                "pdf_filename",
                "requested_by",
                "response_body",
                "response_status_code",
                "status",
                "trace_id",
                "updated_at",
            }
        ),
    ),
    (
        ResultDeliveryRequestSerializer,
        frozenset(
            {
                "channel",
                "destination",
            }
        ),
    ),
    (
        StandaloneOrderCreateSerializer,
        frozenset(
            {
                "clinical_notes",
                "diagnostic_package",
                "enable_billing",
                "items",
                "patient_id",
                "payer_type",
                "priority",
                "referring_clinician",
                "walkin_dob",
                "walkin_gender",
                "walkin_mrn",
                "walkin_name",
                "walkin_national_id",
                "walkin_patient_id",
                "walkin_phone",
            }
        ),
    ),
    (
        StandaloneOrderItemSerializer,
        frozenset(
            {
                "special_instructions",
                "test_code",
            }
        ),
    ),
    (
        WalkInPatientCreateSerializer,
        frozenset(
            {
                "date_of_birth",
                "email",
                "first_name",
                "gender",
                "id_type",
                "last_name",
                "national_id",
                "phone_number",
                "referring_clinician",
                "referring_facility",
            }
        ),
    ),
    (
        WalkInPatientSerializer,
        frozenset(
            {
                "created_at",
                "date_of_birth",
                "email",
                "first_name",
                "full_name",
                "gender",
                "id",
                "id_type",
                "last_name",
                "linked_patient",
                "national_id",
                "phone_number",
                "referring_clinician",
                "referring_facility",
                "registration_number",
                "updated_at",
            }
        ),
    ),
]


def _serializer_id(val):
    """Return readable test ID for parametrize."""
    return val.__name__ if isinstance(val, type) else None


@pytest.mark.django_db
class TestContractsLaboratoryStandalone:
    """Contract tests for laboratory_standalone serializers."""

    @pytest.mark.parametrize(
        "serializer_class, expected_fields",
        CONTRACTS,
        ids=lambda val: _serializer_id(val),
    )
    def test_serializer_fields_match_contract(self, serializer_class, expected_fields):
        """Serializer field set must match the contract exactly."""
        actual_fields = frozenset(serializer_class().fields.keys())

        added = actual_fields - expected_fields
        removed = expected_fields - actual_fields

        assert not added, (
            f"\n{serializer_class.__name__}: new fields added to serializer.\n"
            f"  Added: {sorted(added)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to include these fields"
        )
        assert not removed, (
            f"\n{serializer_class.__name__}: fields removed from serializer.\n"
            f"  Removed: {sorted(removed)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to remove these fields"
        )
