"""
Serializer contract tests for hl7 app.

Auto-generated by scripts/generate_contracts.py — DO NOT edit field sets manually.
Re-run the script to update after serializer changes:
    poetry run python scripts/generate_contracts.py
"""

import pytest  # type: ignore

from hmis.apps.hl7.serializers import (
    HL7EndpointCreateSerializer,
    HL7EndpointListSerializer,
    HL7EndpointSerializer,
    HL7EndpointTestSerializer,
    HL7MessageListSerializer,
    HL7MessageSerializer,
)

CONTRACTS: list[tuple[type, frozenset[str]]] = [
    (
        HL7EndpointCreateSerializer,
        frozenset(
            {
                "endpoint_type",
                "is_active",
                "lis_code_system",
                "max_retries",
                "mllp_host",
                "mllp_port",
                "name",
                "notes",
                "receiving_application",
                "receiving_facility",
                "sending_application",
                "sending_facility",
                "timeout",
                "use_ssl",
            }
        ),
    ),
    (
        HL7EndpointListSerializer,
        frozenset(
            {
                "created_at",
                "endpoint_type",
                "id",
                "is_active",
                "message_count",
                "mllp_host",
                "mllp_port",
                "name",
                "receiving_facility",
            }
        ),
    ),
    (
        HL7EndpointSerializer,
        frozenset(
            {
                "created_at",
                "endpoint_type",
                "id",
                "is_active",
                "lis_code_system",
                "max_retries",
                "message_count",
                "mllp_host",
                "mllp_port",
                "name",
                "notes",
                "receiving_application",
                "receiving_facility",
                "sending_application",
                "sending_facility",
                "timeout",
                "updated_at",
                "use_ssl",
            }
        ),
    ),
    (
        HL7EndpointTestSerializer,
        frozenset(
            {
                "error",
                "latency_ms",
                "success",
            }
        ),
    ),
    (
        HL7MessageListSerializer,
        frozenset(
            {
                "ack_code",
                "acknowledged_at",
                "created_at",
                "direction",
                "id",
                "is_retryable",
                "last_error",
                "message_control_id",
                "message_type",
                "resource_id",
                "resource_type",
                "retry_count",
                "sent_at",
                "status",
            }
        ),
    ),
    (
        HL7MessageSerializer,
        frozenset(
            {
                "ack_code",
                "acknowledged_at",
                "created_at",
                "destination_host",
                "destination_port",
                "direction",
                "id",
                "is_retryable",
                "last_error",
                "max_retries",
                "message_control_id",
                "message_type",
                "next_retry_at",
                "raw_message",
                "resource_id",
                "resource_type",
                "retry_count",
                "sent_at",
                "status",
                "updated_at",
            }
        ),
    ),
]


def _serializer_id(val):
    """Return readable test ID for parametrize."""
    return val.__name__ if isinstance(val, type) else None


@pytest.mark.django_db
class TestContractsHl7:
    """Contract tests for hl7 serializers."""

    @pytest.mark.parametrize(
        "serializer_class, expected_fields",
        CONTRACTS,
        ids=lambda val: _serializer_id(val),
    )
    def test_serializer_fields_match_contract(self, serializer_class, expected_fields):
        """Serializer field set must match the contract exactly."""
        actual_fields = frozenset(serializer_class().fields.keys())

        added = actual_fields - expected_fields
        removed = expected_fields - actual_fields

        assert not added, (
            f"\n{serializer_class.__name__}: new fields added to serializer.\n"
            f"  Added: {sorted(added)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to include these fields"
        )
        assert not removed, (
            f"\n{serializer_class.__name__}: fields removed from serializer.\n"
            f"  Removed: {sorted(removed)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to remove these fields"
        )
