"""
Serializer contract tests for clinical_templates app.

Auto-generated by scripts/generate_contracts.py — DO NOT edit field sets manually.
Re-run the script to update after serializer changes:
    poetry run python scripts/generate_contracts.py
"""
import pytest  # type: ignore

from hmis.apps.clinical_templates.serializers import (
    ClinicalTemplateListSerializer,
    ClinicalTemplateSerializer,
    TemplateSectionSerializer,
)


CONTRACTS: list[tuple[type, frozenset[str]]] = [
    (
        ClinicalTemplateListSerializer,
        frozenset({
            "created_at",
            "created_by",
            "created_by_username",
            "description",
            "id",
            "is_active",
            "is_system",
            "name",
            "specialty",
            "template_type",
            "updated_at",
            "usage_count",
        }),
    ),
    (
        ClinicalTemplateSerializer,
        frozenset({
            "content",
            "created_at",
            "created_by",
            "created_by_username",
            "description",
            "id",
            "is_active",
            "is_system",
            "name",
            "sections",
            "specialty",
            "template_type",
            "updated_at",
            "usage_count",
        }),
    ),
    (
        TemplateSectionSerializer,
        frozenset({
            "fields",
            "id",
            "is_required",
            "name",
            "order",
        }),
    ),
]


def _serializer_id(val):
    """Return readable test ID for parametrize."""
    return val.__name__ if isinstance(val, type) else None


@pytest.mark.django_db
class TestContractsClinicalTemplates:
    """Contract tests for clinical_templates serializers."""

    @pytest.mark.parametrize(
        "serializer_class, expected_fields",
        CONTRACTS,
        ids=lambda val: _serializer_id(val),
    )
    def test_serializer_fields_match_contract(self, serializer_class, expected_fields):
        """Serializer field set must match the contract exactly."""
        actual_fields = frozenset(serializer_class().fields.keys())

        added = actual_fields - expected_fields
        removed = expected_fields - actual_fields

        assert not added, (
            f"\n{serializer_class.__name__}: new fields added to serializer.\n"
            f"  Added: {sorted(added)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to include these fields"
        )
        assert not removed, (
            f"\n{serializer_class.__name__}: fields removed from serializer.\n"
            f"  Removed: {sorted(removed)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to remove these fields"
        )

