"""
Serializer contract tests for moh_reporting app.

Auto-generated by scripts/generate_contracts.py — DO NOT edit field sets manually.
Re-run the script to update after serializer changes:
    poetry run python scripts/generate_contracts.py
"""

import pytest  # type: ignore

from hmis.apps.moh_reporting.serializers import (
    MOH705DiseaseRowSerializer,
    MOH705ReportListSerializer,
    MOH705ReportSerializer,
    MOH711ReportListSerializer,
    MOH711ReportSerializer,
    MOH717ReportListSerializer,
    MOH717ReportSerializer,
    MOHReportApproveSerializer,
    MOHReportGenerateSerializer,
)

CONTRACTS: list[tuple[type, frozenset[str]]] = [
    (
        MOH705DiseaseRowSerializer,
        frozenset(
            {
                "cases_5_and_above",
                "cases_under_5",
                "category_name",
                "icd10_chapter",
                "id",
                "total_cases",
            }
        ),
    ),
    (
        MOH705ReportListSerializer,
        frozenset(
            {
                "created_at",
                "disease_row_count",
                "facility",
                "facility_name",
                "generated_at",
                "id",
                "is_submitted",
                "period_end",
                "period_label",
                "period_start",
                "status",
                "total_5_and_above",
                "total_under_5",
                "total_visits",
            }
        ),
    ),
    (
        MOH705ReportSerializer,
        frozenset(
            {
                "approved_at",
                "approved_by",
                "can_edit",
                "created_at",
                "dhis2_import_summary",
                "dhis2_period",
                "dhis2_submitted_at",
                "disease_rows",
                "facility",
                "facility_name",
                "generated_at",
                "generated_by",
                "id",
                "is_submitted",
                "new_cases",
                "notes",
                "period_end",
                "period_label",
                "period_start",
                "revisits",
                "status",
                "total_5_and_above",
                "total_under_5",
                "total_visits",
                "updated_at",
            }
        ),
    ),
    (
        MOH711ReportListSerializer,
        frozenset(
            {
                "created_at",
                "deliveries_total",
                "facility",
                "facility_name",
                "generated_at",
                "id",
                "is_submitted",
                "malaria_cases_5_and_above",
                "malaria_cases_under_5",
                "period_end",
                "period_label",
                "period_start",
                "status",
            }
        ),
    ),
    (
        MOH711ReportSerializer,
        frozenset(
            {
                "anc_visits",
                "approved_at",
                "approved_by",
                "bcg_given",
                "can_edit",
                "children_stunted",
                "children_underweight",
                "children_wasted",
                "created_at",
                "deliveries_caesarean",
                "deliveries_normal",
                "deliveries_total",
                "dhis2_import_summary",
                "dhis2_period",
                "dhis2_submitted_at",
                "facility",
                "facility_name",
                "fully_immunised",
                "generated_at",
                "generated_by",
                "id",
                "is_submitted",
                "live_births",
                "malaria_cases_5_and_above",
                "malaria_cases_under_5",
                "malaria_in_pregnancy",
                "measles_given",
                "notes",
                "opv_given",
                "penta_given",
                "period_end",
                "period_label",
                "period_start",
                "status",
                "still_births",
                "updated_at",
            }
        ),
    ),
    (
        MOH717ReportListSerializer,
        frozenset(
            {
                "admissions_total",
                "created_at",
                "emergency_visits",
                "facility",
                "facility_name",
                "generated_at",
                "id",
                "is_submitted",
                "opd_total",
                "period_end",
                "period_label",
                "period_start",
                "status",
            }
        ),
    ),
    (
        MOH717ReportSerializer,
        frozenset(
            {
                "admissions_total",
                "approved_at",
                "approved_by",
                "can_edit",
                "created_at",
                "deaths_total",
                "deliveries_caesarean",
                "deliveries_total",
                "dhis2_import_summary",
                "dhis2_period",
                "dhis2_submitted_at",
                "discharges_total",
                "emergency_visits",
                "facility",
                "facility_name",
                "generated_at",
                "generated_by",
                "id",
                "inpatient_days",
                "is_submitted",
                "lab_tests_total",
                "notes",
                "opd_new_visits",
                "opd_revisits",
                "opd_total",
                "period_end",
                "period_label",
                "period_start",
                "referrals_in",
                "referrals_out",
                "status",
                "surgeries_major",
                "surgeries_minor",
                "updated_at",
            }
        ),
    ),
    (
        MOHReportApproveSerializer,
        frozenset(
            {
                "notes",
            }
        ),
    ),
    (
        MOHReportGenerateSerializer,
        frozenset(
            {
                "month",
                "year",
            }
        ),
    ),
]


def _serializer_id(val):
    """Return readable test ID for parametrize."""
    return val.__name__ if isinstance(val, type) else None


@pytest.mark.django_db
class TestContractsMohReporting:
    """Contract tests for moh_reporting serializers."""

    @pytest.mark.parametrize(
        "serializer_class, expected_fields",
        CONTRACTS,
        ids=lambda val: _serializer_id(val),
    )
    def test_serializer_fields_match_contract(self, serializer_class, expected_fields):
        """Serializer field set must match the contract exactly."""
        actual_fields = frozenset(serializer_class().fields.keys())

        added = actual_fields - expected_fields
        removed = expected_fields - actual_fields

        assert not added, (
            f"\n{serializer_class.__name__}: new fields added to serializer.\n"
            f"  Added: {sorted(added)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to include these fields"
        )
        assert not removed, (
            f"\n{serializer_class.__name__}: fields removed from serializer.\n"
            f"  Removed: {sorted(removed)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to remove these fields"
        )
