"""
Serializer contract tests for social_work app.

Auto-generated by scripts/generate_contracts.py — DO NOT edit field sets manually.
Re-run the script to update after serializer changes:
    poetry run python scripts/generate_contracts.py
"""

import pytest  # type: ignore

from hmis.apps.social_work.serializers import (
    CaseNoteCreateSerializer,
    CaseNoteSerializer,
    SocialWorkCaseClosureSerializer,
    SocialWorkCaseCreateSerializer,
    SocialWorkCaseListSerializer,
    SocialWorkCaseSerializer,
    SocialWorkInterventionCompleteSerializer,
    SocialWorkInterventionCreateSerializer,
    SocialWorkInterventionSerializer,
    SocialWorkReferralAssignWorkerSerializer,
    SocialWorkReferralCreateSerializer,
    SocialWorkReferralListSerializer,
    SocialWorkReferralSerializer,
    SocialWorkReferralUpdateStatusSerializer,
)

CONTRACTS: list[tuple[type, frozenset[str]]] = [
    (
        CaseNoteCreateSerializer,
        frozenset(
            {
                "case",
                "contact_date",
                "contact_method",
                "content",
                "duration_minutes",
                "follow_up_actions",
                "follow_up_date",
                "follow_up_required",
                "is_confidential",
                "note_type",
                "participant_names",
                "subject",
            }
        ),
    ),
    (
        CaseNoteSerializer,
        frozenset(
            {
                "author",
                "author_name",
                "case",
                "contact_date",
                "contact_method",
                "contact_method_display",
                "content",
                "created_at",
                "duration_minutes",
                "follow_up_actions",
                "follow_up_date",
                "follow_up_required",
                "id",
                "is_confidential",
                "note_type",
                "note_type_display",
                "participant_names",
                "subject",
                "updated_at",
            }
        ),
    ),
    (
        SocialWorkCaseClosureSerializer,
        frozenset(
            {
                "outcome",
                "outcome_rating",
                "status",
            }
        ),
    ),
    (
        SocialWorkCaseCreateSerializer,
        frozenset(
            {
                "case_type",
                "goals",
                "patient",
                "presenting_problem",
                "priority",
                "referral",
                "risk_level",
                "title",
            }
        ),
    ),
    (
        SocialWorkCaseListSerializer,
        frozenset(
            {
                "assigned_worker",
                "assigned_worker_name",
                "case_number",
                "case_type",
                "case_type_display",
                "id",
                "is_overdue_for_review",
                "is_sensitive",
                "next_review_date",
                "opened_at",
                "patient",
                "patient_mrn",
                "patient_name",
                "risk_level",
                "risk_level_display",
                "status",
                "status_display",
                "title",
            }
        ),
    ),
    (
        SocialWorkCaseSerializer,
        frozenset(
            {
                "assessment",
                "assigned_worker",
                "assigned_worker_name",
                "barriers",
                "case_number",
                "case_type",
                "case_type_display",
                "closed_at",
                "confidentiality_level",
                "days_open",
                "family_composition",
                "follow_up_frequency",
                "goals",
                "id",
                "intervention_plan",
                "interventions_count",
                "is_open",
                "is_overdue_for_review",
                "is_sensitive",
                "next_review_date",
                "notes_count",
                "opened_at",
                "outcome",
                "outcome_rating",
                "patient",
                "patient_mrn",
                "patient_name",
                "presenting_problem",
                "priority",
                "priority_display",
                "psychosocial_history",
                "referral",
                "risk_level",
                "risk_level_display",
                "safety_assessment",
                "secondary_worker",
                "status",
                "status_display",
                "strengths",
                "supervisor",
                "supervisor_name",
                "support_systems",
                "title",
                "updated_at",
            }
        ),
    ),
    (
        SocialWorkInterventionCompleteSerializer,
        frozenset(
            {
                "activities",
                "client_feedback",
                "outcome",
                "outcome_rating",
            }
        ),
    ),
    (
        SocialWorkInterventionCreateSerializer,
        frozenset(
            {
                "case",
                "cost",
                "cost_source",
                "description",
                "external_agency",
                "external_contact",
                "intervention_type",
                "objectives",
                "planned_date",
            }
        ),
    ),
    (
        SocialWorkInterventionSerializer,
        frozenset(
            {
                "activities",
                "case",
                "client_feedback",
                "completion_date",
                "cost",
                "cost_source",
                "created_at",
                "description",
                "external_agency",
                "external_contact",
                "id",
                "intervention_type",
                "intervention_type_display",
                "objectives",
                "outcome",
                "outcome_rating",
                "outcome_rating_display",
                "planned_date",
                "provided_by",
                "provided_by_name",
                "start_date",
                "status",
                "status_display",
                "updated_at",
            }
        ),
    ),
    (
        SocialWorkReferralAssignWorkerSerializer,
        frozenset(
            {
                "assigned_worker",
            }
        ),
    ),
    (
        SocialWorkReferralCreateSerializer,
        frozenset(
            {
                "clinical_summary",
                "confidentiality_notes",
                "encounter",
                "patient",
                "presenting_issues",
                "reason",
                "risk_factors",
                "specific_requests",
                "urgency",
            }
        ),
    ),
    (
        SocialWorkReferralListSerializer,
        frozenset(
            {
                "assigned_worker",
                "assigned_worker_name",
                "created_at",
                "id",
                "is_sensitive",
                "patient",
                "patient_mrn",
                "patient_name",
                "reason",
                "reason_display",
                "referral_number",
                "requires_immediate_attention",
                "status",
                "status_display",
                "urgency",
                "urgency_display",
            }
        ),
    ),
    (
        SocialWorkReferralSerializer,
        frozenset(
            {
                "accepted_at",
                "assigned_worker",
                "assigned_worker_name",
                "clinic_visit",
                "clinical_summary",
                "completed_at",
                "confidentiality_notes",
                "created_at",
                "encounter",
                "external_agency",
                "external_contact",
                "id",
                "is_gbv_case",
                "is_sensitive",
                "patient",
                "patient_mrn",
                "patient_name",
                "presenting_issues",
                "reason",
                "reason_display",
                "referral_number",
                "referred_by",
                "referred_by_name",
                "requires_immediate_attention",
                "risk_factors",
                "specific_requests",
                "status",
                "status_display",
                "updated_at",
                "urgency",
                "urgency_display",
            }
        ),
    ),
    (
        SocialWorkReferralUpdateStatusSerializer,
        frozenset(
            {
                "external_agency",
                "external_contact",
                "notes",
                "status",
            }
        ),
    ),
]


def _serializer_id(val):
    """Return readable test ID for parametrize."""
    return val.__name__ if isinstance(val, type) else None


@pytest.mark.django_db
class TestContractsSocialWork:
    """Contract tests for social_work serializers."""

    @pytest.mark.parametrize(
        "serializer_class, expected_fields",
        CONTRACTS,
        ids=lambda val: _serializer_id(val),
    )
    def test_serializer_fields_match_contract(self, serializer_class, expected_fields):
        """Serializer field set must match the contract exactly."""
        actual_fields = frozenset(serializer_class().fields.keys())

        added = actual_fields - expected_fields
        removed = expected_fields - actual_fields

        assert not added, (
            f"\n{serializer_class.__name__}: new fields added to serializer.\n"
            f"  Added: {sorted(added)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to include these fields"
        )
        assert not removed, (
            f"\n{serializer_class.__name__}: fields removed from serializer.\n"
            f"  Removed: {sorted(removed)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to remove these fields"
        )
