"""
Serializer contract tests for cds app.

Auto-generated by scripts/generate_contracts.py — DO NOT edit field sets manually.
Re-run the script to update after serializer changes:
    poetry run python scripts/generate_contracts.py
"""

import pytest  # type: ignore

from hmis.apps.cds.serializers import (
    CDSAlertListSerializer,
    CDSAlertSerializer,
    CDSDashboardSerializer,
    CDSEvaluateEncounterSerializer,
    CDSOverrideSerializer,
    CDSRuleCreateSerializer,
    CDSRuleListSerializer,
    CDSRuleSerializer,
)

CONTRACTS: list[tuple[type, frozenset[str]]] = [
    (
        CDSAlertListSerializer,
        frozenset(
            {
                "category",
                "created_at",
                "encounter",
                "id",
                "is_critical",
                "is_pending",
                "message",
                "patient",
                "patient_mrn",
                "patient_name",
                "priority",
                "rule",
                "rule_code",
                "rule_name",
                "status",
                "suggested_actions",
                "suggestion",
            }
        ),
    ),
    (
        CDSAlertSerializer,
        frozenset(
            {
                "action_type",
                "age_hours",
                "category",
                "created_at",
                "details",
                "encounter",
                "evidence_level",
                "id",
                "is_critical",
                "is_pending",
                "is_resolved",
                "message",
                "override_reason",
                "patient",
                "patient_mrn",
                "patient_name",
                "priority",
                "resolved_at",
                "resolved_by",
                "resolved_by_name",
                "rule",
                "rule_code",
                "rule_name",
                "status",
                "suggested_actions",
                "suggestion",
                "triggered_by",
                "updated_at",
            }
        ),
    ),
    (
        CDSDashboardSerializer,
        frozenset(
            {
                "active_rules",
                "alerts_by_category",
                "alerts_by_priority",
                "alerts_today",
                "critical_pending",
                "draft_rules",
                "override_rate",
                "pending_alerts",
                "total_alerts",
                "total_rules",
            }
        ),
    ),
    (
        CDSEvaluateEncounterSerializer,
        frozenset(
            {
                "encounter_id",
            }
        ),
    ),
    (
        CDSOverrideSerializer,
        frozenset(
            {
                "reason",
            }
        ),
    ),
    (
        CDSRuleCreateSerializer,
        frozenset(
            {
                "action_message",
                "action_type",
                "category",
                "code",
                "condition",
                "description",
                "evidence_level",
                "metadata",
                "name",
                "priority",
                "references",
                "suggestion",
            }
        ),
    ),
    (
        CDSRuleListSerializer,
        frozenset(
            {
                "action_type",
                "category",
                "code",
                "created_at",
                "evidence_level",
                "id",
                "is_active",
                "name",
                "priority",
                "status",
                "trigger_count",
                "updated_at",
            }
        ),
    ),
    (
        CDSRuleSerializer,
        frozenset(
            {
                "action_message",
                "action_type",
                "approved_at",
                "approved_by",
                "approved_by_name",
                "category",
                "code",
                "condition",
                "created_at",
                "created_by",
                "created_by_name",
                "description",
                "evidence_level",
                "id",
                "is_active",
                "metadata",
                "name",
                "override_rate",
                "priority",
                "references",
                "status",
                "suggestion",
                "trigger_count",
                "updated_at",
            }
        ),
    ),
]


def _serializer_id(val):
    """Return readable test ID for parametrize."""
    return val.__name__ if isinstance(val, type) else None


@pytest.mark.django_db
class TestContractsCds:
    """Contract tests for cds serializers."""

    @pytest.mark.parametrize(
        "serializer_class, expected_fields",
        CONTRACTS,
        ids=lambda val: _serializer_id(val),
    )
    def test_serializer_fields_match_contract(self, serializer_class, expected_fields):
        """Serializer field set must match the contract exactly."""
        actual_fields = frozenset(serializer_class().fields.keys())

        added = actual_fields - expected_fields
        removed = expected_fields - actual_fields

        assert not added, (
            f"\n{serializer_class.__name__}: new fields added to serializer.\n"
            f"  Added: {sorted(added)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to include these fields"
        )
        assert not removed, (
            f"\n{serializer_class.__name__}: fields removed from serializer.\n"
            f"  Removed: {sorted(removed)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to remove these fields"
        )
