"""
Serializer contract tests for allied_health app.

Auto-generated by scripts/generate_contracts.py — DO NOT edit field sets manually.
Re-run the script to update after serializer changes:
    poetry run python scripts/generate_contracts.py
"""
import pytest  # type: ignore

from hmis.apps.allied_health.serializers import (
    AlliedHealthDashboardSerializer,
    AlliedHealthModuleStatsSerializer,
    ClinicQueueStatsSerializer,
    ClinicTypeQueueStatsSerializer,
    CounsellingStatsSerializer,
    NutritionStatsSerializer,
    OccupationalTherapyStatsSerializer,
    PhysiotherapyStatsSerializer,
    SocialWorkStatsSerializer,
    TodaySessionSerializer,
)


CONTRACTS: list[tuple[type, frozenset[str]]] = [
    (
        AlliedHealthDashboardSerializer,
        frozenset({
            "clinic_queue_stats",
            "counselling",
            "nutrition",
            "occupational_therapy",
            "physiotherapy",
            "social_work",
            "todays_sessions",
        }),
    ),
    (
        AlliedHealthModuleStatsSerializer,
        frozenset({
            "completed_today_count",
            "in_progress_count",
            "pending_count",
            "today_sessions_count",
        }),
    ),
    (
        ClinicQueueStatsSerializer,
        frozenset({
            "counselling",
            "mental_health",
            "nutrition",
            "ot",
            "physio",
            "social_work",
            "totals",
        }),
    ),
    (
        ClinicTypeQueueStatsSerializer,
        frozenset({
            "completed_count",
            "in_consultation_count",
            "total_today",
            "waiting_count",
        }),
    ),
    (
        CounsellingStatsSerializer,
        frozenset({
            "completed_today_count",
            "follow_ups_count",
            "in_progress_count",
            "pending_count",
            "today_sessions_count",
        }),
    ),
    (
        NutritionStatsSerializer,
        frozenset({
            "completed_today_count",
            "consultations_count",
            "in_progress_count",
            "pending_count",
            "today_sessions_count",
        }),
    ),
    (
        OccupationalTherapyStatsSerializer,
        frozenset({
            "completed_today_count",
            "in_progress_count",
            "pending_count",
            "today_sessions_count",
        }),
    ),
    (
        PhysiotherapyStatsSerializer,
        frozenset({
            "completed_today_count",
            "in_progress_count",
            "pending_count",
            "today_sessions_count",
        }),
    ),
    (
        SocialWorkStatsSerializer,
        frozenset({
            "open_cases_count",
            "this_week_count",
            "urgent_count",
        }),
    ),
    (
        TodaySessionSerializer,
        frozenset({
            "id",
            "module",
            "patient_mrn",
            "patient_name",
            "scheduled_time",
            "session_number",
            "source",
            "status",
            "treatment_type",
        }),
    ),
]


def _serializer_id(val):
    """Return readable test ID for parametrize."""
    return val.__name__ if isinstance(val, type) else None


@pytest.mark.django_db
class TestContractsAlliedHealth:
    """Contract tests for allied_health serializers."""

    @pytest.mark.parametrize(
        "serializer_class, expected_fields",
        CONTRACTS,
        ids=lambda val: _serializer_id(val),
    )
    def test_serializer_fields_match_contract(self, serializer_class, expected_fields):
        """Serializer field set must match the contract exactly."""
        actual_fields = frozenset(serializer_class().fields.keys())

        added = actual_fields - expected_fields
        removed = expected_fields - actual_fields

        assert not added, (
            f"\n{serializer_class.__name__}: new fields added to serializer.\n"
            f"  Added: {sorted(added)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to include these fields"
        )
        assert not removed, (
            f"\n{serializer_class.__name__}: fields removed from serializer.\n"
            f"  Removed: {sorted(removed)}\n"
            f"  → Re-run: poetry run python scripts/generate_contracts.py\n"
            f"  → Update the frontend Zod schema to remove these fields"
        )

