# Generated by Django 5.2.13 on 2026-05-09 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_add_comment_reaction"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalcomment",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "app_label__in": [
                        "encounters",
                        "laboratory",
                        "pharmacy",
                        "inpatient",
                        "scheduling",
                    ],
                    "model__in": ["encounter", "laborder", "prescription", "admission", "shift"],
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
