# Generated by Django 5.2.10 on 2026-01-07 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_add_payment_receipt_credit_note_models"),
        ("patients", "0007_add_location_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SHAMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sha_number",
                    models.CharField(
                        help_text="SHA member number (format: SHA-XXXXXXXXXX)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        db_index=True, help_text="Kenya National ID linked to SHA", max_length=20
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("principal", "Principal Member"),
                            ("spouse", "Spouse"),
                            ("child", "Child/Dependent"),
                            ("parent", "Parent"),
                            ("other", "Other Dependent"),
                        ],
                        default="principal",
                        max_length=20,
                    ),
                ),
                (
                    "principal_sha_number",
                    models.CharField(
                        blank=True,
                        help_text="Principal member's SHA number (for dependents)",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("pending", "Pending Verification"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_eligibility_check", models.DateTimeField(blank=True, null=True)),
                ("eligibility_valid_until", models.DateField(blank=True, null=True)),
                (
                    "eligibility_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached response from last eligibility check",
                    ),
                ),
                ("coverage_start_date", models.DateField(blank=True, null=True)),
                ("coverage_end_date", models.DateField(blank=True, null=True)),
                (
                    "benefit_package",
                    models.CharField(
                        blank=True, help_text="SHA benefit package code", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sha_members_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sha_member",
                        to="patients.patient",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sha_members_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SHA Member",
                "verbose_name_plural": "SHA Members",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["sha_number"], name="billing_sha_sha_num_ecf0b0_idx"),
                    models.Index(fields=["national_id"], name="billing_sha_nationa_ce31a3_idx"),
                    models.Index(fields=["status"], name="billing_sha_status_c5fe23_idx"),
                ],
            },
        ),
    ]
