# Generated by Django 5.2.10 on 2026-01-07 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_sha_member_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="SHATariff",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="SHA tariff code (e.g., SHA-CONS-001)", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("laboratory", "Laboratory"),
                            ("radiology", "Radiology/Imaging"),
                            ("pharmacy", "Pharmacy/Drugs"),
                            ("procedure", "Procedures"),
                            ("surgery", "Surgery"),
                            ("inpatient", "Inpatient Services"),
                            ("maternity", "Maternity"),
                            ("dental", "Dental"),
                            ("optical", "Optical"),
                            ("physiotherapy", "Physiotherapy"),
                            ("dialysis", "Dialysis"),
                            ("oncology", "Oncology"),
                            ("other", "Other Services"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "facility_level",
                    models.CharField(
                        choices=[
                            ("L1", "Level 1 (Dispensary)"),
                            ("L2", "Level 2 (Health Centre)"),
                            ("L3", "Level 3 (Sub-County Hospital)"),
                            ("L4", "Level 4 (County Hospital)"),
                            ("L5", "Level 5 (National Referral)"),
                            ("L6", "Level 6 (Tertiary/Specialized)"),
                        ],
                        help_text="Applicable facility level",
                        max_length=5,
                    ),
                ),
                (
                    "sha_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="SHA approved reimbursement amount (KES)",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "effective_date",
                    models.DateField(help_text="Date from which this tariff is effective"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when tariff expires (null = no expiry)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applicable_icd10_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ICD-10 codes this tariff applies to",
                    ),
                ),
                (
                    "requires_preauthorization",
                    models.BooleanField(
                        default=False, help_text="Whether pre-authorization is required"
                    ),
                ),
                (
                    "max_quantity_per_claim",
                    models.IntegerField(
                        default=1, help_text="Maximum quantity claimable per encounter"
                    ),
                ),
                (
                    "waiting_period_days",
                    models.IntegerField(
                        default=0, help_text="Waiting period before claimable (days)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "internal_service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked internal service for auto-mapping",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sha_tariffs",
                        to="billing.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "SHA Tariff",
                "verbose_name_plural": "SHA Tariffs",
                "ordering": ["category", "code"],
                "indexes": [
                    models.Index(fields=["code"], name="billing_sha_code_75a5e8_idx"),
                    models.Index(
                        fields=["category", "is_active"], name="billing_sha_categor_864805_idx"
                    ),
                    models.Index(fields=["facility_level"], name="billing_sha_facilit_56be4f_idx"),
                ],
            },
        ),
    ]
