# Generated by Django 5.2.10 on 2026-01-07 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_shaclaim_shaclaimattachment_shaclaimitem_and_more"),
        ("patients", "0007_add_location_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shaclaimattachment",
            options={
                "ordering": ["claim", "attachment_type"],
                "verbose_name": "SHA Claim Attachment",
                "verbose_name_plural": "SHA Claim Attachments",
            },
        ),
        migrations.RenameField(
            model_name="shaclaimattachment",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="shaclaimattachment",
            old_name="file_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="shaclaimattachment",
            name="file_path",
        ),
        migrations.AddField(
            model_name="shaclaimattachment",
            name="checksum",
            field=models.CharField(
                blank=True, help_text="SHA-256 checksum for integrity verification", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="shaclaimattachment",
            name="file",
            field=models.FileField(default=1, max_length=500, upload_to="sha_claims/%Y/%m/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shaclaimattachment",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shaclaimattachment",
            name="page_count",
            field=models.IntegerField(
                blank=True, help_text="Number of pages (for PDFs)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="shaclaimattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("clinical_notes", "Clinical Notes"),
                    ("lab_report", "Laboratory Report"),
                    ("radiology_report", "Radiology Report"),
                    ("prescription", "Prescription"),
                    ("invoice", "Invoice"),
                    ("discharge_summary", "Discharge Summary"),
                    ("operative_notes", "Operative Notes"),
                    ("referral_letter", "Referral Letter"),
                    ("preauth_approval", "Pre-authorization Approval"),
                    ("id_copy", "ID Copy"),
                    ("sha_card", "SHA Card Copy"),
                    ("other", "Other Document"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shaclaimattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sha_attachments_uploaded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SHAEligibilityCheck",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("check_date", models.DateTimeField(auto_now_add=True)),
                (
                    "request_data",
                    models.JSONField(default=dict, help_text="Request payload sent to SHA"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("eligible", "Eligible"),
                            ("ineligible", "Ineligible"),
                            ("pending", "Pending"),
                            ("error", "Error"),
                            ("timeout", "Request Timeout"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(default=dict, help_text="Response from SHA API"),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, help_text="API response time in milliseconds", null=True
                    ),
                ),
                ("is_eligible", models.BooleanField(default=False)),
                ("eligible_until", models.DateField(blank=True, null=True)),
                (
                    "benefit_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Remaining benefit balance",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("ineligibility_reason", models.CharField(blank=True, max_length=255)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sha_eligibility_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sha_eligibility_checks",
                        to="patients.patient",
                    ),
                ),
                (
                    "sha_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_checks",
                        to="billing.shamember",
                    ),
                ),
            ],
            options={
                "verbose_name": "SHA Eligibility Check",
                "verbose_name_plural": "SHA Eligibility Checks",
                "ordering": ["-check_date"],
                "indexes": [
                    models.Index(
                        fields=["sha_member", "check_date"], name="billing_sha_sha_mem_aef28b_idx"
                    ),
                    models.Index(fields=["result"], name="billing_sha_result_f2c893_idx"),
                ],
            },
        ),
    ]
