# Generated by Django 5.2.10 on 2026-01-07 15:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_sha_attachment_eligibility_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shaclaimitem",
            options={
                "ordering": ["claim", "created_at"],
                "verbose_name": "SHA Claim Item",
                "verbose_name_plural": "SHA Claim Items",
            },
        ),
        migrations.AddField(
            model_name="shaclaimitem",
            name="invoice_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sha_claim_items",
                to="billing.invoiceitem",
            ),
        ),
        migrations.AddField(
            model_name="shaclaimitem",
            name="service_date",
            field=models.DateField(
                blank=True, help_text="Date this specific service was provided", null=True
            ),
        ),
        migrations.AddField(
            model_name="shaclaimitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("adjusted", "Adjusted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shaclaimitem",
            name="approved_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="shaclaimitem",
            name="approved_quantity",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="shaclaimitem",
            name="claimed_amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Total claimed (quantity × unit_price)", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="shaclaimitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=10),
        ),
        migrations.AlterField(
            model_name="shaclaimitem",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sha_claim_items",
                to="billing.service",
            ),
        ),
        migrations.AlterField(
            model_name="shaclaimitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, help_text="SHA tariff unit price", max_digits=10
            ),
        ),
    ]
