# Generated by Django 5.2.9 on 2026-01-11 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_alter_shaclaim_status"),
        ("patients", "0008_add_cr_and_identification_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shaclaimitem",
            name="coverage_type",
            field=models.CharField(
                choices=[
                    ("sha", "SHA Coverage"),
                    ("pfms", "PFMS Coverage (Government Subsidy)"),
                    ("both", "Split Between SHA and PFMS"),
                ],
                default="sha",
                help_text="Which coverage pays for this item (SHA, PFMS, or both)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="shamember",
            name="is_pfms_eligible",
            field=models.BooleanField(
                default=False, help_text="Is this member eligible for PFMS (government subsidy)?"
            ),
        ),
        migrations.AddField(
            model_name="shamember",
            name="pfms_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vulnerable", "Vulnerable Population"),
                    ("elderly", "Elderly (65+)"),
                    ("disabled", "Persons with Disability"),
                    ("orphan", "Orphan/Vulnerable Child"),
                    ("indigent", "Indigent"),
                ],
                help_text="PFMS category for government-subsidized coverage",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shamember",
            name="pfms_verified",
            field=models.BooleanField(
                default=False, help_text="Has PFMS eligibility been verified?"
            ),
        ),
        migrations.AddField(
            model_name="shamember",
            name="pfms_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="shamember",
            index=models.Index(fields=["is_pfms_eligible"], name="billing_sha_is_pfms_f627cc_idx"),
        ),
    ]
