# Generated by Django 5.2.9 on 2026-01-11 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0011_add_pfms_coverage_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shamember",
            name="principal",
            field=models.ForeignKey(
                blank=True,
                help_text="Principal member this dependent belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dependents",
                to="billing.shamember",
            ),
        ),
        migrations.AlterField(
            model_name="shamember",
            name="principal_sha_number",
            field=models.CharField(
                blank=True,
                help_text="Principal member's SHA number (for dependents) - external reference",
                max_length=20,
            ),
        ),
    ]
