# Generated by Django 5.2.9 on 2026-01-21 14:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0014_remove_payment_billing_pay_payment_0b3a60_idx_and_more"),
        ("pharmacy", "0010_allow_prescription_without_encounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="stock_allocated",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Quantity allocated from stock batch",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="stock_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Stock batch allocated for pharmacy items",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_items",
                to="pharmacy.stockbatch",
            ),
        ),
    ]
