# Generated by Django 5.2.9 on 2026-01-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0015_invoice_item_stock_allocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
