# Generated by Django 5.2.9 on 2026-02-09 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0020_add_imaging_order_to_invoiceitem"),
        ("imaging", "0003_dicom_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="imaging_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_items",
                to="imaging.imagingorder",
            ),
        ),
    ]
