# Generated by Django 5.2.11 on 2026-03-26 20:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0023_multitenancy_clinical_fks"),
        ("core", "0030_role_multitenancy_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityBillingConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "default_payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("insurance", "Insurance"),
                            ("corporate", "Corporate Account"),
                            ("mixed", "Mixed Payment"),
                        ],
                        default="cash",
                        help_text="Default payment type for new invoices at this facility.",
                        max_length=20,
                    ),
                ),
                (
                    "default_due_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Default number of days until invoice is due."
                    ),
                ),
                (
                    "auto_finalize_on_checkout",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically finalize draft invoices when patient checks out.",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Default tax rate (percentage) applied to invoices. 0 = exempt.",
                        max_digits=5,
                    ),
                ),
                (
                    "sha_accreditation_status",
                    models.CharField(
                        choices=[
                            ("not_applied", "Not Applied"),
                            ("pending", "Application Pending"),
                            ("accredited", "Accredited"),
                            ("conditional", "Conditional Accreditation"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="not_applied",
                        help_text="Current SHA accreditation status for this facility.",
                        max_length=20,
                    ),
                ),
                (
                    "sha_accreditation_date",
                    models.DateField(
                        blank=True, help_text="Date when SHA accreditation was granted.", null=True
                    ),
                ),
                (
                    "sha_accreditation_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Date when current SHA accreditation expires.",
                        null=True,
                    ),
                ),
                (
                    "sha_contract_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA contract reference number.",
                        max_length=50,
                    ),
                ),
                (
                    "sha_contract_start",
                    models.DateField(
                        blank=True,
                        help_text="Date when the SHA contract became effective.",
                        null=True,
                    ),
                ),
                (
                    "sha_contract_end",
                    models.DateField(
                        blank=True, help_text="Date when the SHA contract expires.", null=True
                    ),
                ),
                (
                    "sha_service_level",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA service level agreement tier (e.g., 'Comprehensive', 'Basic').",
                        max_length=50,
                    ),
                ),
                (
                    "sha_max_claim_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum single claim amount allowed under this contract.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "fee_schedule_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the fee schedule applied at this facility.",
                        max_length=100,
                    ),
                ),
                (
                    "fee_schedule_override",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Service code → price overrides. Keys are service codes, values are unit prices.",
                    ),
                ),
                (
                    "mpesa_paybill",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="M-Pesa paybill number for this facility.",
                        max_length=20,
                    ),
                ),
                (
                    "mpesa_account_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default M-Pesa account reference / till number.",
                        max_length=50,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank name for the facility's collection account.",
                        max_length=100,
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank account number for collections.",
                        max_length=50,
                    ),
                ),
                (
                    "bank_branch",
                    models.CharField(
                        blank=True, default="", help_text="Bank branch name.", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.OneToOneField(
                        help_text="The facility this billing config belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_config",
                        to="core.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Billing Config",
                "verbose_name_plural": "Facility Billing Configs",
            },
        ),
    ]
