# Generated by Django 5.2.11 on 2026-04-05 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0025_mpesa_multitenant_credentials"),
        ("immunizations", "0005_aefi_moh_form_expansion"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="immunization_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_items",
                to="immunizations.immunizationrecord",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("service", "Service"),
                    ("pharmacy", "Pharmacy Item"),
                    ("lab", "Lab Test"),
                    ("imaging", "Imaging/Radiology"),
                    ("vaccination", "Vaccination"),
                    ("consumable", "Consumable"),
                    ("other", "Other"),
                ],
                default="service",
                max_length=20,
            ),
        ),
    ]
