# Generated by Django 5.2.13 on 2026-04-16 19:16
# Customised: rename + encrypt existing plaintext M-Pesa credentials with KMS.

from django.db import migrations, models


def encrypt_existing_credentials(apps, schema_editor):
    """Encrypt any existing plaintext M-Pesa credentials in-place."""
    FacilityBillingConfig = apps.get_model("billing", "FacilityBillingConfig")
    rows = FacilityBillingConfig.objects.exclude(
        mpesa_consumer_key_encrypted=""
    ) | FacilityBillingConfig.objects.exclude(
        mpesa_consumer_secret_encrypted=""
    ) | FacilityBillingConfig.objects.exclude(
        mpesa_passkey_encrypted=""
    )
    if not rows.exists():
        return

    from hmis.apps.core.kms import get_kms_provider

    kms = get_kms_provider()
    for cfg in rows:
        changed = False
        for field in (
            "mpesa_consumer_key_encrypted",
            "mpesa_consumer_secret_encrypted",
            "mpesa_passkey_encrypted",
        ):
            val = getattr(cfg, field)
            if val and not val.startswith("gAAAAA"):
                # Plaintext — encrypt it
                setattr(cfg, field, kms.encrypt_string(val))
                changed = True
        if changed:
            cfg.save(
                update_fields=[
                    "mpesa_consumer_key_encrypted",
                    "mpesa_consumer_secret_encrypted",
                    "mpesa_passkey_encrypted",
                ]
            )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0026_add_vaccination_itemtype_and_immunization_fk"),
    ]

    operations = [
        # Step 1: Rename columns (preserves existing data)
        migrations.RenameField(
            model_name="facilitybillingconfig",
            old_name="mpesa_consumer_key",
            new_name="mpesa_consumer_key_encrypted",
        ),
        migrations.RenameField(
            model_name="facilitybillingconfig",
            old_name="mpesa_consumer_secret",
            new_name="mpesa_consumer_secret_encrypted",
        ),
        migrations.RenameField(
            model_name="facilitybillingconfig",
            old_name="mpesa_passkey",
            new_name="mpesa_passkey_encrypted",
        ),
        # Step 2: Change CharField(max_length=200) → TextField
        migrations.AlterField(
            model_name="facilitybillingconfig",
            name="mpesa_consumer_key_encrypted",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Daraja API consumer key (KMS-encrypted).",
            ),
        ),
        migrations.AlterField(
            model_name="facilitybillingconfig",
            name="mpesa_consumer_secret_encrypted",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Daraja API consumer secret (KMS-encrypted).",
            ),
        ),
        migrations.AlterField(
            model_name="facilitybillingconfig",
            name="mpesa_passkey_encrypted",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Lipa Na M-Pesa Online passkey (KMS-encrypted).",
            ),
        ),
        # Step 3: Encrypt any existing plaintext values
        migrations.RunPython(
            encrypt_existing_credentials,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
