# Generated by Django 5.2.13 on 2026-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0031_invoiceitem_theatre_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICD11CodeReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("chapter", models.CharField(blank=True, default="", max_length=50)),
                ("chapter_no", models.CharField(blank=True, default="", max_length=20)),
                ("class_kind", models.CharField(default="category", max_length=20)),
                ("depth_in_kind", models.PositiveIntegerField(default=0)),
                ("entity_id", models.CharField(blank=True, default="", max_length=50)),
                ("foundation_uri", models.CharField(blank=True, default="", max_length=500)),
                ("linearization_uri", models.CharField(blank=True, default="", max_length=500)),
                ("is_leaf", models.BooleanField(default=True)),
                ("is_residual", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ICD-11 Code Reference",
                "verbose_name_plural": "ICD-11 Code References",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="billing_icd_code_f9ee4c_idx"),
                    models.Index(fields=["chapter_no"], name="billing_icd_chapter_de1eaf_idx"),
                    models.Index(fields=["title"], name="billing_icd_title_01579b_idx"),
                ],
            },
        ),
    ]
