# Generated by Django 5.2.13 on 2026-04-29 16:46

from django.db import migrations


def backfill_facility_fk(apps, schema_editor):
    """
    Backfill SHAClaim.facility from facility_code (MFL code) or encounter.facility.

    Strategy:
    1. If claim has an encounter with a facility FK, use that.
    2. Otherwise, match facility_code to Facility.mfl_code.
    """
    SHAClaim = apps.get_model("billing", "SHAClaim")
    Facility = apps.get_model("core", "Facility")

    # Build lookup dict: mfl_code -> facility instance
    mfl_lookup = {}
    for facility in Facility.objects.filter(is_active=True).select_related("organization"):
        if facility.mfl_code:
            mfl_lookup[facility.mfl_code] = facility

    claims_to_update = []
    for claim in SHAClaim.objects.filter(facility__isnull=True).select_related("encounter"):
        facility = None

        # Strategy 1: from encounter
        if claim.encounter_id:
            enc_facility_id = claim.encounter.facility_id if hasattr(claim.encounter, "facility_id") else None
            if enc_facility_id:
                facility = Facility.objects.filter(pk=enc_facility_id).select_related("organization").first()

        # Strategy 2: from facility_code
        if not facility and claim.facility_code:
            facility = mfl_lookup.get(claim.facility_code)

        if facility:
            claim.facility = facility
            claim.organization = facility.organization
            claims_to_update.append(claim)

    if claims_to_update:
        SHAClaim.objects.bulk_update(claims_to_update, ["facility", "organization"], batch_size=500)


def reverse_backfill(apps, schema_editor):
    """Reverse: clear facility FK (non-destructive, facility_code still has the data)."""
    SHAClaim = apps.get_model("billing", "SHAClaim")
    SHAClaim.objects.update(facility=None, organization=None)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0034_add_facility_fk_to_shaclaim"),
    ]

    operations = [
        migrations.RunPython(backfill_facility_fk, reverse_backfill),
    ]
