# Generated by Django 5.2.13 on 2026-04-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0035_backfill_shaclaim_facility_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="shaclaim",
            name="claim_flow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("phc", "Primary Health Care (UHC, Level 2-3)"),
                    ("shif", "SHIF (Level 3+, biometric/OTP consent)"),
                    ("eccif", "Emergency (ECCIF, bundled tariffs)"),
                ],
                help_text="DHA HIE claim flow (PHC/SHIF/ECCIF), set by flow router",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="shaclaim",
            name="is_emergency_claim",
            field=models.BooleanField(
                default=False, help_text="Whether this is an emergency claim (ECCIF flow)"
            ),
        ),
    ]
