# Generated by Django 5.2.13 on 2026-04-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0036_add_claim_flow_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shaclaim",
            name="dha_correlation_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Last X-Correlation-Id used when calling DHA HIE",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="shaclaim",
            name="dha_external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DHA-side claim identifier returned by /api/v1/claims/visit",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="shaclaim",
            name="dha_visit_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When /api/v1/claims/visit succeeded for this claim",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shaclaim",
            name="last_dha_payload_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent successful DHA HIE call",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shaclaim",
            name="last_dha_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Last DHA-side status (VISIT_STARTED, SUBMITTED, CLOSED, ...)",
                max_length=32,
            ),
        ),
    ]
