# Generated by Django 5.2.13 on 2026-04-29 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0037_shaclaim_dha_correlation_id_shaclaim_dha_external_id_and_more"),
        ("core", "0051_dhaoutboundcall"),
        ("patients", "0019_rename_patients_pa_househo_f85c8f_idx_patients_pa_househo_77a2c1_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientContact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("next_of_kin", "Next of Kin"),
                            ("beneficiary", "Beneficiary"),
                            ("other", "Other"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("relationship", models.CharField(blank=True, max_length=64)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("identification_number", models.CharField(blank=True, max_length=64)),
                ("identification_type", models.CharField(blank=True, max_length=32)),
                ("is_otp_recipient", models.BooleanField(default=False)),
                ("dha_contact_id", models.CharField(blank=True, max_length=128)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dha_contacts",
                        to="patients.patient",
                    ),
                ),
                (
                    "sha_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dha_contacts",
                        to="billing.shamember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Contact (DHA)",
                "verbose_name_plural": "Patient Contacts (DHA)",
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "contact_type"], name="billing_pat_patient_d87bb5_idx"
                    ),
                    models.Index(fields=["dha_contact_id"], name="billing_pat_dha_con_2ca715_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SHACoverageSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("eligibility", "Eligibility"),
                            ("benefits", "Benefits"),
                            ("sub_benefits", "Sub-benefits"),
                            ("benefits_interventions", "Benefit Interventions"),
                            ("utilization", "Utilization"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_eligible", models.BooleanField(default=False)),
                ("member_cr_number", models.CharField(blank=True, max_length=64)),
                ("sub_benefit_code", models.CharField(blank=True, max_length=64)),
                ("intervention_code", models.CharField(blank=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("request_params", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(blank=True, max_length=64)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "fetched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dha_coverage_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dha_coverage_snapshots",
                        to="patients.patient",
                    ),
                ),
                (
                    "sha_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dha_coverage_snapshots",
                        to="billing.shamember",
                    ),
                ),
            ],
            options={
                "verbose_name": "SHA Coverage Snapshot",
                "verbose_name_plural": "SHA Coverage Snapshots",
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "snapshot_type", "-fetched_at"],
                        name="billing_sha_patient_1a01a9_idx",
                    ),
                    models.Index(
                        fields=["snapshot_type", "-fetched_at"],
                        name="billing_sha_snapsho_6261ef_idx",
                    ),
                ],
            },
        ),
    ]
