# Generated by Django 5.2.13 on 2026-04-29 20:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0039_shaemergencyclaim_shapreauth"),
        ("core", "0051_dhaoutboundcall"),
        ("patients", "0019_rename_patients_pa_househo_f85c8f_idx_patients_pa_househo_77a2c1_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SHAOtpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("visit", "Visit OTP"), ("discharge", "Discharge OTP")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("verified", "Verified"), ("failed", "Failed")],
                        default="sent",
                        max_length=16,
                    ),
                ),
                ("consent_token", models.CharField(blank=True, default="", max_length=512)),
                ("patient_cr_id", models.CharField(blank=True, default="", max_length=64)),
                ("intervention_codes", models.JSONField(blank=True, default=list)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=128)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="otp_requests",
                        to="billing.shaclaim",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sha_otp_requests",
                        to="patients.patient",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sha_otp_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sha_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="otp_requests",
                        to="billing.shamember",
                    ),
                ),
            ],
            options={
                "verbose_name": "SHA OTP Request",
                "verbose_name_plural": "SHA OTP Requests",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(fields=["kind", "status"], name="billing_sha_kind_94a340_idx"),
                    models.Index(fields=["patient_cr_id"], name="billing_sha_patient_30ff57_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SHAOtpWhitelistRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("beneficiary_cr_id", models.CharField(max_length=64)),
                ("reason_type", models.CharField(blank=True, default="", max_length=64)),
                ("reason", models.TextField(blank=True, default="")),
                ("biometric_attempts", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("dha_guid", models.CharField(blank=True, default="", max_length=128)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=128)),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sha_otp_whitelist_requests",
                        to="patients.patient",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sha_otp_whitelists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SHA OTP Whitelist Request",
                "verbose_name_plural": "SHA OTP Whitelist Requests",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["beneficiary_cr_id"], name="billing_sha_benefic_f16ccf_idx"
                    ),
                    models.Index(fields=["status"], name="billing_sha_status_290011_idx"),
                    models.Index(fields=["dha_guid"], name="billing_sha_dha_gui_60b703_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SHAUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=128)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("dha_file_id", models.CharField(blank=True, default="", max_length=255)),
                ("dha_file_path", models.CharField(blank=True, default="", max_length=512)),
                ("dha_download_url", models.TextField(blank=True, default="")),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=128)),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sha_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SHA Upload",
                "verbose_name_plural": "SHA Uploads",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(fields=["dha_file_id"], name="billing_sha_dha_fil_492306_idx")
                ],
            },
        ),
    ]
