# Generated by Django 5.2.13 on 2026-05-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0041_shadhaprescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="consenttoken",
            name="intervention_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="SHA intervention codes sent with the OTP request",
            ),
        ),
    ]
