# Generated by Django 5.2.13 on 2026-05-01 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0042_consenttoken_intervention_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SHAClaimIntervention",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "intervention_code",
                    models.CharField(
                        help_text="SHA intervention code (e.g., SHA-07-001)", max_length=20
                    ),
                ),
                (
                    "intervention_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable intervention name from HIE response",
                        max_length=255,
                    ),
                ),
                (
                    "benefit_code",
                    models.CharField(
                        blank=True,
                        help_text="Parent benefit package code (e.g., SHA-07)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "required_document_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Required document types from DHA (e.g., ['MEDICAL_REPORT', 'LAB_REPORT'])",
                    ),
                ),
                (
                    "dha_intervention_id",
                    models.CharField(
                        blank=True,
                        help_text="ID returned by HIE for this intervention on the claim",
                        max_length=64,
                    ),
                ),
                (
                    "tariff_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tariff amount for this intervention per HIE response",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_interventions",
                        to="billing.shaclaim",
                    ),
                ),
            ],
            options={
                "verbose_name": "SHA Claim Intervention",
                "verbose_name_plural": "SHA Claim Interventions",
                "ordering": ["claim", "created_at"],
                "indexes": [
                    models.Index(fields=["claim", "status"], name="billing_sha_claim_i_819ef2_idx"),
                    models.Index(
                        fields=["intervention_code"], name="billing_sha_interve_1a4fad_idx"
                    ),
                ],
                "unique_together": {("claim", "intervention_code")},
            },
        ),
    ]
