# Generated by Django 5.2.13 on 2026-05-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0044_add_sha_remittance_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shaclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("validated", "Validated"),
                    ("pending_submission", "Pending Submission (Queued)"),
                    ("submitted", "Submitted"),
                    ("acknowledged", "Acknowledged by SHA"),
                    ("under_review", "Under Review"),
                    ("query", "Query Raised"),
                    ("approved", "Approved"),
                    ("partial", "Partially Approved"),
                    ("rejected", "Rejected"),
                    ("appealed", "Appealed"),
                    ("paid", "Paid"),
                    ("written_off", "Written Off"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
