# Generated by Django 5.2.13 on 2026-05-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0046_consenttoken_auth_guid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shaclaimintervention",
            name="access_point",
            field=models.CharField(
                blank=True,
                choices=[("IP", "Inpatient"), ("OP", "Outpatient"), ("BOTH", "Both")],
                help_text="IP (inpatient), OP (outpatient), or BOTH",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="is_imaging_preauth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="is_oncology_preauth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="is_optical_preauth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="is_renal_preauth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="is_surgical_preauth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="level2_tariff",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="level3_tariff",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="level4_tariff",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="level5_tariff",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="level6_tariff",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="needs_manual_preauth_approval",
            field=models.BooleanField(
                default=False,
                help_text="True if elective preauth (doctor approval required before visit)",
            ),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="needs_preauth",
            field=models.BooleanField(
                default=False, help_text="True if this intervention requires pre-authorization"
            ),
        ),
        migrations.AddField(
            model_name="shaclaimintervention",
            name="payment_mechanism",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PER_DIEM", "Per Diem"),
                    ("FEE_FOR_SERVICE", "Fee for Service"),
                    ("CAPITATION", "Capitation"),
                ],
                help_text="PER_DIEM, FEE_FOR_SERVICE, or CAPITATION — drives billing flow",
                max_length=20,
            ),
        ),
    ]
