# Generated by Django 5.2.13 on 2026-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0047_add_intervention_routing_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitybillingconfig",
            name="sha_agent_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DHA agent identifier (e.g., DHABP05113).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="facilitybillingconfig",
            name="sha_api_environment",
            field=models.CharField(
                choices=[("sandbox", "Sandbox (UAT)"), ("production", "Production")],
                default="sandbox",
                help_text="DHA ILM API environment (sandbox or production).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="facilitybillingconfig",
            name="sha_client_id_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="DHA ILM OAuth client ID (KMS-encrypted)."
            ),
        ),
        migrations.AddField(
            model_name="facilitybillingconfig",
            name="sha_client_secret_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="DHA ILM OAuth client secret (KMS-encrypted)."
            ),
        ),
        migrations.AddField(
            model_name="facilitybillingconfig",
            name="sha_consumer_key_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="DHA ILM API consumer key (KMS-encrypted)."
            ),
        ),
        migrations.AddField(
            model_name="facilitybillingconfig",
            name="sha_encrypted_pin",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Pre-encrypted DHA PIN (stored as-is, already encrypted by DHA).",
            ),
        ),
        migrations.AddField(
            model_name="facilitybillingconfig",
            name="sha_facility_fr_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Facility Registry code for DHA/ILM API calls.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="facilitybillingconfig",
            name="sha_password_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="DHA ILM Basic Auth password (KMS-encrypted)."
            ),
        ),
        migrations.AddField(
            model_name="facilitybillingconfig",
            name="sha_username_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="DHA ILM Basic Auth username (KMS-encrypted)."
            ),
        ),
    ]
