# Generated by Django 5.2.13 on 2026-05-13 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0048_add_sha_ilm_credentials_to_billing_config"),
        ("patients", "0024_phase_d_drop_pii_plaintext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="shamember",
            name="billing_sha_nationa_ce31a3_idx",
        ),
        migrations.RemoveField(
            model_name="shamember",
            name="national_id",
        ),
        migrations.AddField(
            model_name="shamember",
            name="national_id_encrypted",
            field=models.TextField(
                blank=True, default="", help_text="Encrypted Kenya National ID linked to SHA"
            ),
        ),
        migrations.AddField(
            model_name="shamember",
            name="national_id_hmac",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="HMAC blind-index for national ID lookups",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="shamember",
            index=models.Index(fields=["national_id_hmac"], name="billing_sha_nationa_82c940_idx"),
        ),
    ]
