# Generated by Django 5.2.13 on 2026-05-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0051_supplier_bills_accounts_payable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplierbill",
            options={
                "ordering": ["-bill_date", "-created_at"],
                "permissions": [("approve_supplierbill", "Can approve supplier bills for payment")],
                "verbose_name": "Supplier Bill",
                "verbose_name_plural": "Supplier Bills",
            },
        ),
    ]
