# Generated by Django 5.2.13 on 2026-06-02 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0052_add_approve_supplierbill_permission"),
        ("core", "0068_facility_ai_cds_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentpoint",
            name="code",
            field=models.CharField(
                help_text="Short unique code (e.g. CASH-01, MPESA-02)", max_length=50
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentpoint",
            constraint=models.UniqueConstraint(
                fields=("facility", "code"), name="unique_payment_point_code_per_facility"
            ),
        ),
    ]
