# Generated by Django 5.2.13 on 2026-07-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0054_consenttoken_origin_hub_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shaclaimitem",
            name="loinc_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Order-level LOINC code (from TestCatalog) for the test ordered",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shaclaimitem",
            name="result_loinc_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Result-level LOINC code (from LabResult) for the specific observation",
                max_length=20,
            ),
        ),
    ]
