# Generated by Django 5.2.13 on 2026-07-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0055_add_loinc_to_sha_claim_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="consenttoken",
            name="access_point",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IP (inpatient), OP (outpatient) — used for per-access-point consent dedup",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="shaclaim",
            name="previewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the provider preview was last requested (required before submit)",
                null=True,
            ),
        ),
    ]
