# Generated by Django 5.2.13 on 2026-07-09 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0056_uat_compliance_previewed_at_access_point"),
        ("clinics", "0021_add_no_show_fields_to_clinic_visit"),
        ("core", "0074_add_facility_analytics_procedures"),
        ("encounters", "0033_add_cancelled_consultation_status"),
        ("patients", "0024_phase_d_drop_pii_plaintext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("facility", "invoice_number"), name="unique_invoice_number_per_facility"
            ),
        ),
    ]
