# Generated by Django 5.2.13 on 2026-07-09 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0057_invoice_unique_per_facility"),
        ("core", "0075_staffprofile_mfa_disabled"),
        ("encounters", "0033_add_cancelled_consultation_status"),
        ("patients", "0024_phase_d_drop_pii_plaintext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="shaclaim",
            name="claim_number",
            field=models.CharField(
                editable=False,
                help_text="Internal claim reference (format: CLM-YYYYMMDD-XXXX)",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="shaclaim",
            constraint=models.UniqueConstraint(
                fields=("facility", "claim_number"), name="unique_claim_number_per_facility"
            ),
        ),
    ]
