# Generated by Django 5.2.13 on 2026-07-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0058_alter_shaclaim_claim_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shaclaim",
            name="facility_code",
            field=models.CharField(
                help_text="DHA Facility Registry (FR) code — used in FHIR bundles and claim submissions. Resolved from billing_config.sha_facility_fr_code > dha_fr_code > settings fallback.",
                max_length=50,
            ),
        ),
    ]
