# Generated by Django 5.2.13 on 2026-07-14 19:09

import uuid
from django.db import migrations, models


def backfill_invoice_public_ids(apps, schema_editor):
    Invoice = apps.get_model("billing", "Invoice")
    for invoice in Invoice.objects.filter(public_id__isnull=True).iterator(chunk_size=1000):
        invoice.public_id = uuid.uuid4()
        invoice.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0059_alter_shaclaim_facility_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="public_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_invoice_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="invoice",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                unique=True,
            ),
        ),
    ]
