# Generated by Django 5.2.13 on 2026-07-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0066_facilitybillingconfig_hide_capitation_interventions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shaclaimattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("clinical_notes", "Clinical Notes"),
                    ("medical_report", "Medical Report"),
                    ("lab_report", "Laboratory Report"),
                    ("radiology_report", "Radiology Report"),
                    ("prescription", "Prescription"),
                    ("invoice", "Invoice"),
                    ("discharge_summary", "Discharge Summary"),
                    ("operative_notes", "Operative Notes"),
                    ("referral_letter", "Referral Letter"),
                    ("preauth_approval", "Pre-authorization Approval"),
                    ("id_copy", "ID Copy"),
                    ("sha_card", "SHA Card Copy"),
                    ("other", "Other Document"),
                ],
                max_length=30,
            ),
        ),
    ]
