# Generated by Django 5.2.13 on 2026-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0067_alter_shaclaimattachment_attachment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shaclaim",
            name="primary_diagnosis_code",
            field=models.CharField(help_text="Primary ICD-11 diagnosis code", max_length=10),
        ),
        migrations.AlterField(
            model_name="shaclaim",
            name="secondary_diagnosis_codes",
            field=models.JSONField(
                blank=True, default=list, help_text="List of secondary ICD-11 diagnosis codes"
            ),
        ),
    ]
