# Generated by Django 5.2.13 on 2026-08-10 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0071_shaclaimintervention_preview_omission_fields"),
        ("encounters", "0034_encounter_public_id_historicalencounter_public_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingAutomationRule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("encounter_created", "Encounter Created"),
                            ("admission_created", "Admission Created"),
                            ("checkout", "Checkout"),
                            ("daily", "Daily Schedule"),
                        ],
                        default="encounter_created",
                        max_length=30,
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[("once", "One-time"), ("recurring", "Recurring")],
                        default="once",
                        help_text="One-time or recurring charge behavior.",
                        max_length=20,
                    ),
                ),
                (
                    "repeat_every_days",
                    models.PositiveIntegerField(
                        default=1, help_text="For recurring rules, run every N days per context."
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("pharmacy", "Pharmacy Item"),
                            ("lab", "Lab Test"),
                            ("imaging", "Imaging/Radiology"),
                            ("vaccination", "Vaccination"),
                            ("consumable", "Consumable"),
                            ("other", "Other"),
                        ],
                        default="service",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=10),
                ),
                (
                    "unit_price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional fixed price override. If empty, service unit price is used.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("description_template", models.CharField(blank=True, default="", max_length=300)),
                (
                    "encounter_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional encounter type allow-list (e.g. ['OPD', 'EMERGENCY']).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="billing.facilitybillingconfig",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="automation_rules",
                        to="billing.service",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BillingAutomationExecution",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "context_key",
                    models.CharField(
                        help_text="Idempotency context key, e.g. encounter:123", max_length=120
                    ),
                ),
                (
                    "execution_date",
                    models.DateField(help_text="Execution bucket date for recurrence checks."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_automation_executions",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_executions",
                        to="billing.invoiceitem",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="billing.billingautomationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="billingautomationrule",
            index=models.Index(
                fields=["billing_config", "trigger", "is_active"],
                name="billing_bil_billing_7d5ee2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingautomationexecution",
            index=models.Index(
                fields=["rule", "context_key"], name="billing_bil_rule_id_e5fd4c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingautomationexecution",
            constraint=models.UniqueConstraint(
                fields=("rule", "context_key", "execution_date"),
                name="unique_rule_execution_per_context_date",
            ),
        ),
    ]
