# Generated by Django 5.2.13 on 2026-09-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0073_mpesa_facility_verification_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="unit_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
