# Copyright (c) 2026 Nexora Consulting Ltd. All rights reserved.
# Generated by Django 5.2.13 on 2026-09-14 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0074_alter_service_unit_price"),
        ("core", "0093_facility_dha_contract_types_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="service",
            name="billing_ser_code_9a35b9_idx",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="billing_ser_sha_cod_59c3fe_idx",
        ),
        migrations.AddField(
            model_name="service",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="origin_hub_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hub ID where this record was originally created (null = cloud-created).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="origin_local_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Original PK on the source hub (for dedup on cloud receipt).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["facility", "code"], name="billing_ser_facilit_e4d3b2_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["facility", "sha_code"], name="billing_ser_facilit_4a5422_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("facility", "code"), name="unique_service_code_per_facility"
            ),
        ),
    ]
