# Generated by Django 5.2.9 on 2026-02-25 19:04

import django.core.validators
import django.db.models.deletion
import hmis.apps.core.history
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0021_change_imaging_order_on_delete"),
        ("clinics", "0009_add_unique_active_patient_per_session"),
        ("encounters", "0023_historicaldiagnosis_historicalencounter"),
        ("patients", "0014_historicalpatient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysiotherapyTreatmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique treatment type code (e.g., PT-MSK-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Full treatment type name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description of treatment"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MUSCULOSKELETAL", "Musculoskeletal"),
                            ("NEUROLOGICAL", "Neurological"),
                            ("CARDIORESPIRATORY", "Cardiorespiratory"),
                            ("PEDIATRIC", "Pediatric"),
                            ("GERIATRIC", "Geriatric"),
                            ("SPORTS", "Sports Rehabilitation"),
                            ("POST_SURGICAL", "Post-Surgical Rehabilitation"),
                            ("STROKE", "Stroke Rehabilitation"),
                            ("ORTHOPEDIC", "Orthopedic"),
                            ("PAIN_MANAGEMENT", "Pain Management"),
                            ("WOMENS_HEALTH", "Women's Health"),
                            ("OTHER", "Other"),
                        ],
                        default="MUSCULOSKELETAL",
                        max_length=30,
                    ),
                ),
                (
                    "typical_duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Typical session duration in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(240),
                        ],
                    ),
                ),
                (
                    "recommended_sessions",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Recommended number of sessions",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "recommended_frequency",
                    models.CharField(
                        default="2x per week",
                        help_text="Recommended session frequency (e.g., '2x per week', 'daily')",
                        max_length=50,
                    ),
                ),
                (
                    "cost_per_session",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost per session in KES",
                        max_digits=10,
                    ),
                ),
                (
                    "sha_claimable",
                    models.BooleanField(default=True, help_text="Covered by Kenya SHA"),
                ),
                (
                    "sha_intervention_code",
                    models.CharField(
                        blank=True, help_text="SHA intervention code for claims", max_length=50
                    ),
                ),
                ("requires_equipment", models.BooleanField(default=False)),
                (
                    "equipment_needed",
                    models.TextField(blank=True, help_text="Equipment required for treatment"),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, help_text="Treatment contraindications"),
                ),
                ("precautions", models.TextField(blank=True, help_text="Treatment precautions")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Physiotherapy Treatment Type",
                "verbose_name_plural": "Physiotherapy Treatment Types",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="physiothera_code_9b16b6_idx"),
                    models.Index(fields=["category"], name="physiothera_categor_690f1f_idx"),
                    models.Index(fields=["is_active"], name="physiothera_is_acti_23a6e7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PhysiotherapyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "referral_reason",
                    models.CharField(
                        choices=[
                            ("POST_INJURY", "Post-Injury Rehabilitation"),
                            ("POST_SURGERY", "Post-Surgical Rehabilitation"),
                            ("CHRONIC_PAIN", "Chronic Pain Management"),
                            ("MOBILITY", "Mobility Improvement"),
                            ("STRENGTH", "Strength Training"),
                            ("BALANCE", "Balance/Coordination"),
                            ("STROKE_REHAB", "Stroke Rehabilitation"),
                            ("RESPIRATORY", "Respiratory Therapy"),
                            ("PEDIATRIC", "Pediatric Development"),
                            ("SPORTS_INJURY", "Sports Injury"),
                            ("OCCUPATIONAL", "Occupational/Work-related"),
                            ("GERIATRIC", "Geriatric Care"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "clinical_indication",
                    models.TextField(help_text="Clinical reason for physiotherapy referral"),
                ),
                (
                    "relevant_history",
                    models.TextField(
                        blank=True,
                        help_text="Relevant medical/surgical history for physiotherapist",
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, help_text="Working diagnosis")),
                (
                    "precautions",
                    models.TextField(blank=True, help_text="Patient-specific precautions"),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, help_text="Patient-specific contraindications"),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Total number of sessions prescribed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "sessions_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of sessions completed"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        default="2x per week",
                        help_text="Treatment frequency (e.g., '2x per week', 'daily')",
                        max_length=50,
                    ),
                ),
                (
                    "treatment_goals",
                    models.TextField(blank=True, help_text="Goals for physiotherapy treatment"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Treatment start date", null=True),
                ),
                (
                    "expected_end_date",
                    models.DateField(
                        blank=True, help_text="Expected treatment end date", null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_therapist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Physiotherapist assigned to this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physiotherapy_orders_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked clinic visit for queue management",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physiotherapy_orders",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="physiotherapy_orders",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked billing invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physiotherapy_orders",
                        to="billing.invoice",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="physiotherapy_orders_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="physiotherapy_orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physiotherapy_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treatment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="physiotherapy.physiotherapytreatmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Physiotherapy Order",
                "verbose_name_plural": "Physiotherapy Orders",
                "ordering": ["-ordered_at"],
                "permissions": [
                    ("approve_physiotherapy_order", "Can approve physiotherapy orders"),
                    ("assign_physiotherapy_therapist", "Can assign physiotherapist to orders"),
                ],
            },
            bases=(hmis.apps.core.history.HistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPhysiotherapyOrder",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("order_number", models.CharField(db_index=True, editable=False, max_length=30)),
                (
                    "referral_reason",
                    models.CharField(
                        choices=[
                            ("POST_INJURY", "Post-Injury Rehabilitation"),
                            ("POST_SURGERY", "Post-Surgical Rehabilitation"),
                            ("CHRONIC_PAIN", "Chronic Pain Management"),
                            ("MOBILITY", "Mobility Improvement"),
                            ("STRENGTH", "Strength Training"),
                            ("BALANCE", "Balance/Coordination"),
                            ("STROKE_REHAB", "Stroke Rehabilitation"),
                            ("RESPIRATORY", "Respiratory Therapy"),
                            ("PEDIATRIC", "Pediatric Development"),
                            ("SPORTS_INJURY", "Sports Injury"),
                            ("OCCUPATIONAL", "Occupational/Work-related"),
                            ("GERIATRIC", "Geriatric Care"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "clinical_indication",
                    models.TextField(help_text="Clinical reason for physiotherapy referral"),
                ),
                (
                    "relevant_history",
                    models.TextField(
                        blank=True,
                        help_text="Relevant medical/surgical history for physiotherapist",
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, help_text="Working diagnosis")),
                (
                    "precautions",
                    models.TextField(blank=True, help_text="Patient-specific precautions"),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, help_text="Patient-specific contraindications"),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Total number of sessions prescribed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                    ),
                ),
                (
                    "sessions_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of sessions completed"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        default="2x per week",
                        help_text="Treatment frequency (e.g., '2x per week', 'daily')",
                        max_length=50,
                    ),
                ),
                (
                    "treatment_goals",
                    models.TextField(blank=True, help_text="Goals for physiotherapy treatment"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "start_date",
                    models.DateField(blank=True, help_text="Treatment start date", null=True),
                ),
                (
                    "expected_end_date",
                    models.DateField(
                        blank=True, help_text="Expected treatment end date", null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("ordered_at", models.DateTimeField(blank=True, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "assigned_therapist",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Physiotherapist assigned to this order",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked clinic visit for queue management",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked billing invoice",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="billing.invoice",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="patients.patient",
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treatment_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="physiotherapy.physiotherapytreatmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Physiotherapy Order",
                "verbose_name_plural": "historical Physiotherapy Orders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PhysiotherapySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_number",
                    models.PositiveIntegerField(help_text="Session number in treatment course"),
                ),
                ("scheduled_date", models.DateField(help_text="Scheduled date for session")),
                (
                    "scheduled_time",
                    models.TimeField(blank=True, help_text="Scheduled time", null=True),
                ),
                (
                    "actual_date",
                    models.DateField(blank=True, help_text="Actual session date", null=True),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Actual session duration in minutes",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(240),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "pre_pain_score",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (0, "0 - No Pain"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3 - Mild"),
                            (4, "4"),
                            (5, "5 - Moderate"),
                            (6, "6"),
                            (7, "7 - Severe"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10 - Worst Pain"),
                        ],
                        help_text="Pain score before session (0-10)",
                        null=True,
                    ),
                ),
                (
                    "pre_assessment_notes",
                    models.TextField(blank=True, help_text="Pre-session assessment notes"),
                ),
                (
                    "patient_reported_changes",
                    models.TextField(
                        blank=True, help_text="Changes reported by patient since last session"
                    ),
                ),
                (
                    "interventions",
                    models.TextField(blank=True, help_text="Interventions/treatments performed"),
                ),
                (
                    "exercises_performed",
                    models.TextField(blank=True, help_text="Exercises performed during session"),
                ),
                (
                    "modalities_used",
                    models.TextField(
                        blank=True, help_text="Modalities used (e.g., ultrasound, TENS, heat, ice)"
                    ),
                ),
                (
                    "patient_response",
                    models.TextField(blank=True, help_text="Patient's response to treatment"),
                ),
                (
                    "post_pain_score",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (0, "0 - No Pain"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3 - Mild"),
                            (4, "4"),
                            (5, "5 - Moderate"),
                            (6, "6"),
                            (7, "7 - Severe"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10 - Worst Pain"),
                        ],
                        help_text="Pain score after session (0-10)",
                        null=True,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IMPROVED", "Improved"),
                            ("UNCHANGED", "Unchanged"),
                            ("WORSENED", "Worsened"),
                            ("GOALS_MET", "Goals Met"),
                            ("PARTIAL_IMPROVEMENT", "Partial Improvement"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(blank=True, help_text="Session progress notes"),
                ),
                (
                    "home_exercises",
                    models.TextField(blank=True, help_text="Home exercises prescribed"),
                ),
                (
                    "home_exercise_instructions",
                    models.TextField(blank=True, help_text="Instructions for home exercises"),
                ),
                (
                    "precautions_advised",
                    models.TextField(blank=True, help_text="Precautions advised to patient"),
                ),
                (
                    "follow_up_recommendations",
                    models.TextField(blank=True, help_text="Follow-up recommendations"),
                ),
                (
                    "next_session_goals",
                    models.TextField(blank=True, help_text="Goals for next session"),
                ),
                ("is_billed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked clinic visit for queue management",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physiotherapy_sessions",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physiotherapy_sessions",
                        to="billing.invoiceitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="physiotherapy.physiotherapyorder",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="physiotherapy_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Physiotherapy Session",
                "verbose_name_plural": "Physiotherapy Sessions",
                "ordering": ["order", "session_number"],
                "indexes": [
                    models.Index(fields=["order"], name="physiothera_order_i_998a14_idx"),
                    models.Index(fields=["therapist"], name="physiothera_therapi_06df1c_idx"),
                    models.Index(fields=["scheduled_date"], name="physiothera_schedul_fc27b3_idx"),
                    models.Index(fields=["status"], name="physiothera_status_2e93e0_idx"),
                ],
                "unique_together": {("order", "session_number")},
            },
        ),
        migrations.AddIndex(
            model_name="physiotherapyorder",
            index=models.Index(fields=["order_number"], name="physiothera_order_n_03bac6_idx"),
        ),
        migrations.AddIndex(
            model_name="physiotherapyorder",
            index=models.Index(fields=["patient"], name="physiothera_patient_52dbfe_idx"),
        ),
        migrations.AddIndex(
            model_name="physiotherapyorder",
            index=models.Index(fields=["status"], name="physiothera_status_84ee4c_idx"),
        ),
        migrations.AddIndex(
            model_name="physiotherapyorder",
            index=models.Index(fields=["ordered_at"], name="physiothera_ordered_17d949_idx"),
        ),
        migrations.AddIndex(
            model_name="physiotherapyorder",
            index=models.Index(fields=["priority"], name="physiothera_priorit_03e65c_idx"),
        ),
        migrations.AddIndex(
            model_name="physiotherapyorder",
            index=models.Index(
                fields=["assigned_therapist"], name="physiothera_assigne_909473_idx"
            ),
        ),
    ]
