# Generated by Django 5.2.9 on 2025-12-31 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("encounters", "0009_add_encounter_status_workflow"),
        ("patients", "0007_add_location_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LOINCCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
                ),
                ("component", models.CharField(help_text="What is measured", max_length=200)),
                ("property", models.CharField(help_text="Mass, volume, etc.", max_length=50)),
                ("time_aspect", models.CharField(help_text="Point vs duration", max_length=50)),
                ("system", models.CharField(help_text="Specimen type", max_length=100)),
                (
                    "scale_type",
                    models.CharField(help_text="Quantitative, ordinal, etc.", max_length=50),
                ),
                ("method_type", models.CharField(blank=True, max_length=100)),
                ("long_common_name", models.CharField(max_length=300)),
                ("short_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "LOINC Code",
                "verbose_name_plural": "LOINC Codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("IN_HOUSE", "In-House Processing"),
                            ("EXTERNAL", "External Lab Referral"),
                        ],
                        default="IN_HOUSE",
                        max_length=20,
                    ),
                ),
                (
                    "external_lab",
                    models.CharField(
                        blank=True, help_text="External lab name if applicable", max_length=100
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(blank=True, help_text="Clinical context for laboratory"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ORDERED", "Ordered"),
                            ("SPECIMEN_COLLECTED", "Specimen Collected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(auto_now=True)),
                ("specimen_collected", models.BooleanField(default=False)),
                ("specimen_collected_at", models.DateTimeField(blank=True, null=True)),
                ("external_requisition_sent", models.BooleanField(default=False)),
                ("external_requisition_date", models.DateTimeField(blank=True, null=True)),
                ("external_accession_number", models.CharField(blank=True, max_length=50)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_paid", models.BooleanField(default=False)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "specimen_collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specimens_collected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status_changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Order",
                "verbose_name_plural": "Lab Orders",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="LabOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("special_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lab_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="laboratory.laborder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Order Item",
                "verbose_name_plural": "Lab Order Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "numeric_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
                ),
                ("text_value", models.TextField(blank=True)),
                (
                    "option_value",
                    models.CharField(
                        blank=True, help_text="For predefined options", max_length=100
                    ),
                ),
                (
                    "result_flag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NORMAL", "Normal"),
                            ("LOW", "Low"),
                            ("HIGH", "High"),
                            ("CRITICAL_LOW", "Critical Low"),
                            ("CRITICAL_HIGH", "Critical High"),
                            ("ABNORMAL", "Abnormal"),
                            ("POSITIVE", "Positive"),
                            ("NEGATIVE", "Negative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("interpretation", models.TextField(blank=True, help_text="Pathologist notes")),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="UNVERIFIED",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("is_external_result", models.BooleanField(default=False)),
                (
                    "external_result_attachment",
                    models.FileField(blank=True, null=True, upload_to="lab_results/"),
                ),
                ("external_result_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entered_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="laboratory.laborderitem",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Result",
                "verbose_name_plural": "Lab Results",
                "ordering": ["-entered_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Internal test code", max_length=50, unique=True),
                ),
                ("name", models.CharField(help_text="Full test name", max_length=200)),
                ("short_name", models.CharField(help_text="Test abbreviation", max_length=50)),
                (
                    "loinc_code",
                    models.CharField(
                        blank=True,
                        help_text="LOINC code for interoperability",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HEMATOLOGY", "Hematology"),
                            ("CHEMISTRY", "Clinical Chemistry"),
                            ("MICROBIOLOGY", "Microbiology"),
                            ("SEROLOGY", "Serology"),
                            ("PARASITOLOGY", "Parasitology"),
                            ("IMMUNOLOGY", "Immunology"),
                            ("URINALYSIS", "Urinalysis"),
                            ("HISTOPATHOLOGY", "Histopathology"),
                            ("CYTOLOGY", "Cytology"),
                            ("MOLECULAR", "Molecular Diagnostics"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "specimen_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Whole Blood"),
                            ("SERUM", "Serum"),
                            ("PLASMA", "Plasma"),
                            ("URINE", "Urine"),
                            ("STOOL", "Stool"),
                            ("CSF", "Cerebrospinal Fluid"),
                            ("SPUTUM", "Sputum"),
                            ("SWAB", "Swab"),
                            ("TISSUE", "Tissue"),
                            ("ASPIRATE", "Aspirate"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requires_fasting", models.BooleanField(default=False)),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "turnaround_hours",
                    models.IntegerField(default=24, help_text="Expected turnaround time in hours"),
                ),
                ("available_in_house", models.BooleanField(default=True)),
                ("external_lab_partner", models.CharField(blank=True, max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "sha_claimable",
                    models.BooleanField(default=True, help_text="Covered by Kenya SHA"),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("NUMERIC", "Numeric Value"),
                            ("TEXT", "Text Result"),
                            ("OPTIONS", "Predefined Options"),
                            ("PANEL", "Multi-component Panel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "result_unit",
                    models.CharField(
                        blank=True, help_text='e.g., "mg/dL", "mmol/L"', max_length=30
                    ),
                ),
                (
                    "normal_range_male",
                    models.CharField(blank=True, help_text='e.g., "4.5-5.5"', max_length=50),
                ),
                ("normal_range_female", models.CharField(blank=True, max_length=50)),
                ("normal_range_child", models.CharField(blank=True, max_length=50)),
                (
                    "result_options",
                    models.JSONField(
                        blank=True, default=list, help_text="For OPTIONS type results"
                    ),
                ),
                ("is_panel", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "panel_components",
                    models.ManyToManyField(blank=True, to="laboratory.testcatalog"),
                ),
            ],
            options={
                "verbose_name": "Test Catalog",
                "verbose_name_plural": "Test Catalogs",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="laborderitem",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="laboratory.testcatalog"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["order_number"], name="laboratory__order_n_0aa245_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["patient"], name="laboratory__patient_11fe5c_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["status"], name="laboratory__status_a16991_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["ordered_at"], name="laboratory__ordered_0d3d89_idx"),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["verification_status"], name="laboratory__verific_7cf337_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcatalog",
            index=models.Index(fields=["code"], name="laboratory__code_41a2df_idx"),
        ),
        migrations.AddIndex(
            model_name="testcatalog",
            index=models.Index(fields=["loinc_code"], name="laboratory__loinc_c_d6ea20_idx"),
        ),
        migrations.AddIndex(
            model_name="testcatalog",
            index=models.Index(fields=["category"], name="laboratory__categor_50a9ef_idx"),
        ),
    ]
