# Generated by Django 5.2.9 on 2026-01-01 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0002_seed_essential_tests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabQueue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("queue_number", models.CharField(editable=False, max_length=20, unique=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (Emergency)"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "queue_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Collection"),
                            ("COLLECTED", "Sample Collected"),
                            ("PROCESSING", "Processing"),
                            ("REVIEW", "Pending Review"),
                            ("RELEASED", "Results Released"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sample_type", models.CharField(max_length=50)),
                ("sample_id", models.CharField(blank=True, max_length=50)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("processing_completed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("technician_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_lab_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="samples_collected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entry",
                        to="laboratory.laborder",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_results_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Queue",
                "verbose_name_plural": "Lab Queue",
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(fields=["queue_number"], name="laboratory__queue_n_95ff64_idx"),
                    models.Index(
                        fields=["queue_status", "priority"], name="laboratory__queue_s_399b65_idx"
                    ),
                    models.Index(
                        fields=["assigned_technician", "queue_status"],
                        name="laboratory__assigne_51765f_idx",
                    ),
                ],
            },
        ),
    ]
