# Generated by Django 5.2.9 on 2026-01-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0004_alter_labqueue_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabResultTemplate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "test_code",
                    models.CharField(help_text="LOINC or internal test code", max_length=20),
                ),
                ("test_name", models.CharField(max_length=200)),
                (
                    "parameter_code",
                    models.CharField(help_text="LOINC component code", max_length=20),
                ),
                ("parameter_name", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=50)),
                (
                    "reference_ranges",
                    models.JSONField(
                        default=dict,
                        help_text="Reference ranges by demographics: adult_male, adult_female, pediatric, default",
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Critical low threshold",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "critical_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Critical high threshold",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Order in which to display parameter"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Lab Result Template",
                "verbose_name_plural": "Lab Result Templates",
                "ordering": ["test_code", "display_order"],
                "indexes": [
                    models.Index(fields=["test_code"], name="laboratory__test_co_237661_idx"),
                    models.Index(fields=["parameter_code"], name="laboratory__paramet_061b59_idx"),
                ],
                "unique_together": {("test_code", "parameter_code")},
            },
        ),
    ]
