# Generated by Django 5.2.9 on 2026-02-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inpatient", "0015_alter_admission_options"),
        ("laboratory", "0010_add_result_unit_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="laborder",
            name="admission",
            field=models.ForeignKey(
                blank=True,
                help_text="IPD admission if lab ordered during inpatient stay",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_orders",
                to="inpatient.admission",
            ),
        ),
    ]
