# Generated by Django 5.2.9 on 2026-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0012_add_specimen_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="specimen",
            new_name="laboratory__barcode_ba6eff_idx",
            old_name="laboratory__barcode_idx",
        ),
        migrations.RenameIndex(
            model_name="specimen",
            new_name="laboratory__status_4fed28_idx",
            old_name="laboratory__status_idx",
        ),
        migrations.RenameIndex(
            model_name="specimen",
            new_name="laboratory__collect_589af6_idx",
            old_name="laboratory__collected_at_idx",
        ),
        migrations.AlterField(
            model_name="specimen",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
