# Generated by Django 5.2.9 on 2026-02-14 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0014_add_result_validation_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique instrument identifier code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Full instrument name", max_length=200)),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="Equipment manufacturer", max_length=100
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, help_text="Model number/name", max_length=100),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, help_text="Serial number", max_length=100),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Lab department (e.g., Hematology, Chemistry)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether instrument is operational"
                    ),
                ),
                (
                    "interface_type",
                    models.CharField(
                        choices=[
                            ("HL7_MLLP", "HL7 v2 over MLLP"),
                            ("ASTM", "ASTM/LIS2-A2"),
                            ("FHIR", "FHIR R4"),
                            ("MANUAL", "Manual Entry"),
                        ],
                        default="MANUAL",
                        help_text="Communication protocol type",
                        max_length=20,
                    ),
                ),
                (
                    "integration_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Integration settings: host, port, encoding, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Instrument",
                "verbose_name_plural": "Instruments",
                "ordering": ["department", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="laboratory__code_32f5c1_idx"),
                    models.Index(fields=["is_active"], name="laboratory__is_acti_78c335_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnalyzerRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_datetime", models.DateTimeField(help_text="When the analyzer run occurred")),
                (
                    "raw_message",
                    models.TextField(help_text="Raw HL7/ASTM/FHIR message from instrument"),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed message data in structured format",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Message Received"),
                            ("PARSED", "Parsed Successfully"),
                            ("APPLIED", "Results Applied"),
                            ("ERROR", "Parse Error"),
                        ],
                        default="RECEIVED",
                        help_text="Processing status of this run",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error details if parsing failed"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lab technician operating the instrument (null for automated runs)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyzer_runs_operated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        help_text="Specimen this run is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyzer_runs",
                        to="laboratory.specimen",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        help_text="Instrument that produced this run",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyzer_runs",
                        to="laboratory.instrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyzer Run",
                "verbose_name_plural": "Analyzer Runs",
                "ordering": ["-run_datetime"],
                "indexes": [
                    models.Index(fields=["status"], name="laboratory__status_6f3239_idx"),
                    models.Index(fields=["run_datetime"], name="laboratory__run_dat_5f0982_idx"),
                    models.Index(
                        fields=["instrument", "status"], name="laboratory__instrum_fbcc24_idx"
                    ),
                ],
            },
        ),
    ]
