# Generated by Django 5.2.9 on 2026-02-14 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0015_add_instrument_and_analyzer_run_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PRELIMINARY", "Preliminary"),
                            ("FINAL", "Final"),
                            ("AMENDED", "Amended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="Report workflow status",
                        max_length=20,
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was finalized", null=True
                    ),
                ),
                (
                    "conclusion",
                    models.TextField(blank=True, help_text="Summary/conclusion of the report"),
                ),
                (
                    "clinical_info",
                    models.TextField(
                        blank=True, help_text="Clinical information/context provided with order"
                    ),
                ),
                (
                    "amended_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was last amended", null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF report file",
                        null=True,
                        upload_to="lab_reports/%Y/%m/",
                    ),
                ),
                (
                    "fhir_resource_id",
                    models.CharField(
                        blank=True, help_text="FHIR DiagnosticReport resource ID", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amended_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last amended the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amended_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="User who issued the report",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        help_text="Lab order this report is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="laboratory.laborder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnostic Report",
                "verbose_name_plural": "Diagnostic Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["report_number"], name="laboratory__report__d3b4a5_idx"),
                    models.Index(fields=["status"], name="laboratory__status_71be80_idx"),
                    models.Index(fields=["lab_order"], name="laboratory__lab_ord_065e23_idx"),
                    models.Index(fields=["issued_at"], name="laboratory__issued__b50227_idx"),
                ],
            },
        ),
    ]
