# Generated by Django 5.2.9 on 2026-02-18 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0016_add_diagnostic_report_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specimen",
            options={"ordering": ["-created_at"]},
        ),
    ]
