# Generated by Django 5.2.13 on 2026-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0023_alter_labresult_external_result_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='bill_patient',
            field=models.BooleanField(default=True, help_text='Whether to auto-bill the patient. Defaults to False for external lab orders.'),
        ),
    ]
