# Generated by Django 5.2.13 on 2026-05-06 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_facility_biometrics_agent_national_id"),
        ("laboratory", "0027_autoverify_rule_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TATSLATarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("ROUTINE", "Routine"), ("URGENT", "Urgent"), ("STAT", "STAT")],
                        max_length=10,
                    ),
                ),
                (
                    "target_order_to_collect_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Target minutes from order placed to specimen collected",
                        null=True,
                    ),
                ),
                (
                    "target_collect_to_receive_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Target minutes from specimen collected to lab receipt",
                        null=True,
                    ),
                ),
                (
                    "target_receive_to_result_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Target minutes from lab receipt to result entry",
                        null=True,
                    ),
                ),
                (
                    "target_result_to_verify_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Target minutes from result entry to verification",
                        null=True,
                    ),
                ),
                (
                    "target_total_minutes",
                    models.PositiveIntegerField(
                        help_text="Target minutes for total turnaround (order to verification/release)"
                    ),
                ),
                (
                    "breach_escalation_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email to notify on SLA breach (optional)",
                        max_length=254,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_targets",
                        to="laboratory.testcatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "TAT SLA Target",
                "verbose_name_plural": "TAT SLA Targets",
                "ordering": ["test__name", "priority"],
            },
        ),
        migrations.CreateModel(
            name="TATSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("ROUTINE", "Routine"), ("URGENT", "Urgent"), ("STAT", "STAT")],
                        max_length=10,
                    ),
                ),
                ("ordered_at", models.DateTimeField()),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("resulted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tat_order_to_collect",
                    models.FloatField(
                        blank=True, help_text="Minutes from order to collection", null=True
                    ),
                ),
                (
                    "tat_collect_to_receive",
                    models.FloatField(
                        blank=True, help_text="Minutes from collection to receipt", null=True
                    ),
                ),
                (
                    "tat_receive_to_result",
                    models.FloatField(
                        blank=True, help_text="Minutes from receipt to result entry", null=True
                    ),
                ),
                (
                    "tat_result_to_verify",
                    models.FloatField(
                        blank=True, help_text="Minutes from result entry to verification", null=True
                    ),
                ),
                (
                    "tat_total",
                    models.FloatField(
                        blank=True, help_text="Minutes total (order to final)", null=True
                    ),
                ),
                (
                    "is_breach",
                    models.BooleanField(
                        default=False, help_text="True if total TAT exceeded SLA target"
                    ),
                ),
                (
                    "breach_minutes",
                    models.FloatField(
                        blank=True,
                        help_text="Minutes over SLA target (positive = breach)",
                        null=True,
                    ),
                ),
                ("snapshot_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "lab_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tat_snapshot",
                        to="laboratory.laborder",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "resulted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tat_resulted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sla_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="laboratory.tatslatarget",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tat_snapshots",
                        to="laboratory.testcatalog",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tat_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TAT Snapshot",
                "verbose_name_plural": "TAT Snapshots",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkloadSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("tests_entered", models.PositiveIntegerField(default=0)),
                ("tests_verified", models.PositiveIntegerField(default=0)),
                ("specimens_collected", models.PositiveIntegerField(default=0)),
                ("specimens_rejected", models.PositiveIntegerField(default=0)),
                (
                    "avg_entry_time_minutes",
                    models.FloatField(
                        blank=True,
                        help_text="Average time to enter result after receipt",
                        null=True,
                    ),
                ),
                (
                    "avg_verify_time_minutes",
                    models.FloatField(
                        blank=True, help_text="Average time to verify after entry", null=True
                    ),
                ),
                ("critical_results_count", models.PositiveIntegerField(default=0)),
                ("critical_notified_within_30min", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workload Snapshot",
                "verbose_name_plural": "Workload Snapshots",
                "ordering": ["-date", "technician__last_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="tatslatarget",
            constraint=models.UniqueConstraint(
                fields=("facility", "test", "priority"),
                name="unique_sla_target_per_facility_test_priority",
            ),
        ),
        migrations.AddIndex(
            model_name="tatsnapshot",
            index=models.Index(
                fields=["facility", "ordered_at"], name="laboratory__facilit_52a1f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tatsnapshot",
            index=models.Index(fields=["test", "priority"], name="laboratory__test_id_90a4b1_idx"),
        ),
        migrations.AddIndex(
            model_name="tatsnapshot",
            index=models.Index(fields=["is_breach"], name="laboratory__is_brea_77d89a_idx"),
        ),
        migrations.AddIndex(
            model_name="tatsnapshot",
            index=models.Index(fields=["ordered_at"], name="laboratory__ordered_dcaae4_idx"),
        ),
        migrations.AddIndex(
            model_name="workloadsnapshot",
            index=models.Index(fields=["facility", "date"], name="laboratory__facilit_0f7a4d_idx"),
        ),
        migrations.AddIndex(
            model_name="workloadsnapshot",
            index=models.Index(
                fields=["technician", "date"], name="laboratory__technic_5df0b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workloadsnapshot",
            constraint=models.UniqueConstraint(
                fields=("facility", "date", "technician"),
                name="unique_workload_per_facility_date_tech",
            ),
        ),
    ]
