# Generated by Django 5.2.13 on 2026-05-06 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_facility_biometrics_agent_national_id"),
        ("laboratory", "0028_l5_reporting_tat_sla_workload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Antibiotic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="WHONET antibiotic code (e.g. AMP, GEN)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "antibiotic_class",
                    models.CharField(
                        blank=True, help_text="e.g. Penicillins, Aminoglycosides", max_length=100
                    ),
                ),
                (
                    "disk_content",
                    models.CharField(blank=True, help_text="e.g. 10µg, 30µg", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Organism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="WHONET organism code", max_length=30, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("genus", models.CharField(blank=True, max_length=100)),
                ("species", models.CharField(blank=True, max_length=100)),
                (
                    "gram_stain",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Gram Positive"),
                            ("NEGATIVE", "Gram Negative"),
                            ("VARIABLE", "Variable"),
                            ("NA", "Not Applicable"),
                        ],
                        default="NA",
                        max_length=20,
                    ),
                ),
                (
                    "organism_type",
                    models.CharField(
                        choices=[
                            ("BACTERIA", "Bacteria"),
                            ("FUNGUS", "Fungus"),
                            ("PARASITE", "Parasite"),
                            ("VIRUS", "Virus"),
                            ("MYCOBACTERIA", "Mycobacteria"),
                            ("OTHER", "Other"),
                        ],
                        default="BACTERIA",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CultureResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INOCULATED", "Inoculated"),
                            ("INCUBATING", "Incubating"),
                            ("READING", "Reading"),
                            ("PRELIMINARY", "Preliminary"),
                            ("FINAL", "Final"),
                            ("NO_GROWTH", "No Growth"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="INOCULATED",
                        max_length=20,
                    ),
                ),
                (
                    "culture_medium",
                    models.CharField(
                        blank=True, help_text="e.g. Blood Agar, MacConkey", max_length=100
                    ),
                ),
                (
                    "incubation_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, help_text="°C", max_digits=4, null=True
                    ),
                ),
                (
                    "incubation_atmosphere",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AEROBIC", "Aerobic"),
                            ("ANAEROBIC", "Anaerobic"),
                            ("CO2", "CO2 Enriched"),
                            ("MICROAEROPHILIC", "Microaerophilic"),
                        ],
                        default="AEROBIC",
                        max_length=30,
                    ),
                ),
                (
                    "incubation_hours",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total incubation hours", null=True
                    ),
                ),
                ("inoculated_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "colony_count",
                    models.CharField(
                        blank=True,
                        help_text="e.g. >100,000 CFU/ml, Few, Moderate, Heavy",
                        max_length=50,
                    ),
                ),
                (
                    "morphology",
                    models.TextField(blank=True, help_text="Colony morphology description"),
                ),
                (
                    "gram_stain_result",
                    models.TextField(blank=True, help_text="Gram stain findings"),
                ),
                (
                    "microscopy_notes",
                    models.TextField(blank=True, help_text="Direct microscopy findings"),
                ),
                (
                    "identification_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANUAL", "Manual (Biochemical)"),
                            ("VITEK", "VITEK Automated"),
                            ("MALDI_TOF", "MALDI-TOF"),
                            ("MOLECULAR", "Molecular (PCR)"),
                            ("API", "API Strip"),
                            ("OTHER", "Other"),
                        ],
                        default="MANUAL",
                        max_length=50,
                    ),
                ),
                ("preliminary_report", models.TextField(blank=True)),
                ("preliminary_reported_at", models.DateTimeField(blank=True, null=True)),
                ("final_report", models.TextField(blank=True)),
                ("final_reported_at", models.DateTimeField(blank=True, null=True)),
                ("clinical_notes", models.TextField(blank=True, help_text="Notes for clinician")),
                (
                    "is_significant",
                    models.BooleanField(
                        default=True,
                        help_text="Whether growth is clinically significant (vs contaminant)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "inoculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culture_result",
                        to="laboratory.labresult",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="culture_results",
                        to="laboratory.specimen",
                    ),
                ),
                (
                    "organism",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="culture_results",
                        to="laboratory.organism",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AntibioticSensitivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "zone_diameter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Zone diameter in mm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "mic",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Minimum Inhibitory Concentration (µg/ml)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "interpretation",
                    models.CharField(
                        choices=[("S", "Sensitive"), ("I", "Intermediate"), ("R", "Resistant")],
                        max_length=1,
                    ),
                ),
                (
                    "test_method",
                    models.CharField(
                        choices=[
                            ("DISK", "Disk Diffusion (Kirby-Bauer)"),
                            ("MIC_BROTH", "MIC (Broth Dilution)"),
                            ("MIC_ETEST", "MIC (E-test)"),
                            ("VITEK", "VITEK Automated"),
                            ("OTHER", "Other"),
                        ],
                        default="DISK",
                        max_length=20,
                    ),
                ),
                (
                    "breakpoint_standard",
                    models.CharField(
                        blank=True,
                        choices=[("CLSI", "CLSI"), ("EUCAST", "EUCAST"), ("OTHER", "Other")],
                        default="CLSI",
                        max_length=20,
                    ),
                ),
                ("tested_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "antibiotic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sensitivity_results",
                        to="laboratory.antibiotic",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "tested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitivities",
                        to="laboratory.cultureresult",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Antibiotic sensitivities",
                "ordering": ["antibiotic__name"],
                "unique_together": {("culture", "antibiotic")},
            },
        ),
        migrations.CreateModel(
            name="Antibiogram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "total_isolates",
                    models.PositiveIntegerField(default=0, help_text="Number of isolates tested"),
                ),
                ("sensitive_count", models.PositiveIntegerField(default=0)),
                ("intermediate_count", models.PositiveIntegerField(default=0)),
                ("resistant_count", models.PositiveIntegerField(default=0)),
                (
                    "percent_sensitive",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="% susceptible",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "percent_resistant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="% resistant",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "antibiotic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antibiograms",
                        to="laboratory.antibiotic",
                    ),
                ),
                (
                    "organism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antibiograms",
                        to="laboratory.organism",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "organism__name", "antibiotic__name"],
                "unique_together": {("facility", "year", "organism", "antibiotic")},
            },
        ),
    ]
