# Generated by Django 5.2.13 on 2026-05-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_facility_biometrics_agent_national_id"),
        ("laboratory", "0030_l3_analyzer_interfacing"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabBarcodeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        default="SP", help_text="Prefix for generated barcodes", max_length=10
                    ),
                ),
                (
                    "sequence_length",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Number of digits in sequence portion (e.g. 6 → SP-000001)",
                    ),
                ),
                (
                    "include_date",
                    models.BooleanField(
                        default=True, help_text="Include date segment (e.g. SP-20260506-000001)"
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="YYYYMMDD",
                        help_text="Date format in barcode (YYYYMMDD or YYMMDD)",
                        max_length=20,
                    ),
                ),
                (
                    "separator",
                    models.CharField(default="-", help_text="Separator character", max_length=1),
                ),
                (
                    "barcode_format",
                    models.CharField(
                        choices=[("CODE128", "Code 128"), ("CODE39", "Code 39"), ("QR", "QR Code")],
                        default="CODE128",
                        max_length=10,
                    ),
                ),
                (
                    "current_sequence",
                    models.PositiveIntegerField(
                        default=0, help_text="Current sequence counter (auto-incremented)"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Barcode Configuration",
                "verbose_name_plural": "Lab Barcode Configurations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("facility",), name="one_barcode_config_per_facility"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LabWorkflowSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "auto_release_normal_results",
                    models.BooleanField(
                        default=False, help_text="Automatically release results within normal range"
                    ),
                ),
                (
                    "require_double_verification_critical",
                    models.BooleanField(
                        default=True, help_text="Require two verifiers for critical results"
                    ),
                ),
                (
                    "auto_print_on_verify",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically print report when result is verified",
                    ),
                ),
                (
                    "auto_print_labels_on_collect",
                    models.BooleanField(
                        default=True, help_text="Print specimen labels when sample is collected"
                    ),
                ),
                (
                    "notify_clinician_on_critical",
                    models.BooleanField(
                        default=True,
                        help_text="Send alert to ordering clinician for critical results",
                    ),
                ),
                (
                    "notify_clinician_on_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Notify ordering clinician when all results are ready",
                    ),
                ),
                (
                    "require_specimen_receipt",
                    models.BooleanField(
                        default=True,
                        help_text="Require explicit specimen receipt before processing",
                    ),
                ),
                (
                    "specimen_rejection_requires_supervisor",
                    models.BooleanField(
                        default=False, help_text="Require supervisor approval to reject specimens"
                    ),
                ),
                (
                    "tat_warning_threshold_percent",
                    models.PositiveIntegerField(
                        default=75, help_text="Show TAT warning when this % of target elapsed"
                    ),
                ),
                (
                    "allow_duplicate_orders",
                    models.BooleanField(
                        default=False,
                        help_text="Allow duplicate test orders for same patient within 24h",
                    ),
                ),
                (
                    "require_clinical_notes",
                    models.BooleanField(
                        default=False, help_text="Make clinical notes mandatory on lab orders"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Workflow Settings",
                "verbose_name_plural": "Lab Workflow Settings",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("facility",), name="one_workflow_settings_per_facility"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferralLab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "tests_offered",
                    models.TextField(
                        blank=True, help_text="Comma-separated test codes or description"
                    ),
                ),
                (
                    "default_tat_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Expected turnaround time in days"
                    ),
                ),
                (
                    "courier_schedule",
                    models.CharField(
                        blank=True, help_text="e.g. 'Mon/Wed/Fri 8am pickup'", max_length=200
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Lab",
                "verbose_name_plural": "Referral Labs",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("facility", "code"), name="unique_referral_lab_per_facility"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResultCommentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("text", models.TextField(help_text="The comment text to insert into results")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("CRITICAL", "Critical Value"),
                            ("FOLLOW_UP", "Follow-up"),
                            ("METHODOLOGY", "Methodology Note"),
                            ("QUALITY", "Quality Note"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "applicable_tests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit to specific tests; blank = available for all",
                        related_name="comment_templates",
                        to="laboratory.testcatalog",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Comment Template",
                "verbose_name_plural": "Result Comment Templates",
                "ordering": ["category", "display_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("facility", "code"), name="unique_comment_template_per_facility"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SampleLabelTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "label_size",
                    models.CharField(
                        choices=[
                            ("SMALL", "Small (25×10mm)"),
                            ("MEDIUM", "Medium (50×25mm)"),
                            ("LARGE", "Large (75×25mm)"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("include_barcode", models.BooleanField(default=True)),
                ("include_patient_name", models.BooleanField(default=True)),
                ("include_mrn", models.BooleanField(default=True)),
                ("include_dob", models.BooleanField(default=False)),
                ("include_collection_date", models.BooleanField(default=True)),
                ("include_test_name", models.BooleanField(default=True)),
                ("include_specimen_type", models.BooleanField(default=True)),
                ("include_priority", models.BooleanField(default=False)),
                ("copies_per_specimen", models.PositiveIntegerField(default=1)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample Label Template",
                "verbose_name_plural": "Sample Label Templates",
                "ordering": ["-is_default", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("facility",),
                        name="one_default_label_template_per_facility",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SpecimenRejectionReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "requires_recollection",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rejection reason requires a new specimen",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specimen Rejection Reason",
                "verbose_name_plural": "Specimen Rejection Reasons",
                "ordering": ["display_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("facility", "code"), name="unique_rejection_reason_per_facility"
                    )
                ],
            },
        ),
    ]
