# Generated by Django 5.2.13 on 2026-05-07 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_facility_biometrics_agent_national_id"),
        ("encounters", "0030_structured_history_models"),
        ("laboratory", "0032_criticalvaluerange_criticalvaluenotification_and_more"),
        ("patients", "0020_add_principal_national_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="laborder",
            name="is_walkin",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a standalone/walk-in order without HMIS patient",
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="walkin_patient_dob",
            field=models.DateField(
                blank=True, help_text="Walk-in patient date of birth", null=True
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="walkin_patient_gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                help_text="Walk-in patient gender",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="walkin_patient_id",
            field=models.CharField(
                blank=True,
                help_text="Walk-in patient national ID or other identifier",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="walkin_patient_name",
            field=models.CharField(
                blank=True, help_text="Walk-in patient full name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="walkin_patient_phone",
            field=models.CharField(
                blank=True, help_text="Walk-in patient phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="laborder",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                help_text="Clinical encounter (null for standalone lab orders)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_orders",
                to="encounters.encounter",
            ),
        ),
        migrations.AlterField(
            model_name="laborder",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="HMIS patient (null for walk-in/external standalone orders)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_orders",
                to="patients.patient",
            ),
        ),
        migrations.CreateModel(
            name="WalkInPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: WLKN-YYYYMMDD-XXXX",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="National ID, passport, or other identifier",
                        max_length=30,
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NATIONAL_ID", "National ID"),
                            ("PASSPORT", "Passport"),
                            ("BIRTH_CERT", "Birth Certificate"),
                            ("MILITARY_ID", "Military ID"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "referring_facility",
                    models.CharField(
                        blank=True,
                        help_text="External facility that referred this patient",
                        max_length=200,
                    ),
                ),
                (
                    "referring_clinician",
                    models.CharField(
                        blank=True, help_text="Name of referring clinician", max_length=200
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "linked_patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Links to full HMIS patient record if later registered",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="walkin_registrations",
                        to="patients.patient",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Walk-in Patient",
                "verbose_name_plural": "Walk-in Patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalOrderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_control_id", models.CharField(db_index=True, max_length=100)),
                ("sending_application", models.CharField(max_length=100)),
                ("sending_facility", models.CharField(max_length=100)),
                ("external_patient_id", models.CharField(blank=True, max_length=100)),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_dob", models.DateField(blank=True, null=True)),
                ("patient_gender", models.CharField(blank=True, max_length=1)),
                ("patient_id_number", models.CharField(blank=True, max_length=50)),
                (
                    "placer_order_number",
                    models.CharField(
                        db_index=True, help_text="Order number from sending system", max_length=100
                    ),
                ),
                ("order_priority", models.CharField(default="ROUTINE", max_length=20)),
                ("clinical_info", models.TextField(blank=True)),
                (
                    "requested_tests",
                    models.JSONField(default=list, help_text="List of test codes/names requested"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("raw_message", models.TextField(help_text="Raw HL7 message content")),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_requests",
                        to="laboratory.laborder",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "walkin_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_orders",
                        to="laboratory.walkinpatient",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Order Request",
                "verbose_name_plural": "External Order Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="walkinpatient",
            index=models.Index(
                fields=["registration_number"], name="laboratory__registr_415d38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walkinpatient",
            index=models.Index(fields=["national_id"], name="laboratory__nationa_bd5a0f_idx"),
        ),
        migrations.AddIndex(
            model_name="walkinpatient",
            index=models.Index(
                fields=["last_name", "first_name"], name="laboratory__last_na_438681_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walkinpatient",
            index=models.Index(fields=["phone_number"], name="laboratory__phone_n_c72cf3_idx"),
        ),
        migrations.AddIndex(
            model_name="externalorderrequest",
            index=models.Index(
                fields=["message_control_id"], name="laboratory__message_48769f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalorderrequest",
            index=models.Index(
                fields=["placer_order_number"], name="laboratory__placer__a82508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalorderrequest",
            index=models.Index(fields=["status"], name="laboratory__status_16742b_idx"),
        ),
    ]
