# Generated by Django 5.2.13 on 2026-05-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0033_standalone_lis_walkin_external"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SampleLabelTemplate",
        ),
    ]
