# Generated by Django 5.2.13 on 2026-05-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_dhis2_config"),
        ("laboratory", "0034_remove_sample_label_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcatalog",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="testcatalog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="testcatalog",
            name="code",
            field=models.CharField(help_text="Internal test code", max_length=50),
        ),
        migrations.AddConstraint(
            model_name="testcatalog",
            constraint=models.UniqueConstraint(
                fields=("facility", "code"), name="unique_test_code_per_facility"
            ),
        ),
    ]
