# Generated by Django 5.2.13 on 2026-05-13 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_remove_staffinvitation_core_staffi_email_a22f70_idx_and_more"),
        ("laboratory", "0035_scope_testcatalog_to_facility"),
        ("patients", "0024_phase_d_drop_pii_plaintext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="walkinpatient",
            name="laboratory__nationa_bd5a0f_idx",
        ),
        migrations.RemoveIndex(
            model_name="walkinpatient",
            name="laboratory__phone_n_c72cf3_idx",
        ),
        migrations.RemoveField(
            model_name="referrallab",
            name="address",
        ),
        migrations.RemoveField(
            model_name="referrallab",
            name="email",
        ),
        migrations.RemoveField(
            model_name="referrallab",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="walkinpatient",
            name="email",
        ),
        migrations.RemoveField(
            model_name="walkinpatient",
            name="national_id",
        ),
        migrations.RemoveField(
            model_name="walkinpatient",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="referrallab",
            name="address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="referrallab",
            name="email_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="referrallab",
            name="phone_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="email_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="national_id_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="national_id_hmac",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="phone_number_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="walkinpatient",
            name="phone_number_hmac",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="walkinpatient",
            index=models.Index(fields=["national_id_hmac"], name="laboratory__nationa_ef1f3a_idx"),
        ),
        migrations.AddIndex(
            model_name="walkinpatient",
            index=models.Index(fields=["phone_number_hmac"], name="laboratory__phone_n_dea4e6_idx"),
        ),
    ]
