# Generated by Django 5.2.13 on 2026-05-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0036_remove_walkinpatient_laboratory__nationa_bd5a0f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="laborderitem",
            name="panel_parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent panel item if this is an expanded component",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panel_children",
                to="laboratory.laborderitem",
            ),
        ),
    ]
