# Generated by Django 5.2.13 on 2026-07-09 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_staffprofile_mfa_disabled"),
        ("encounters", "0033_add_cancelled_consultation_status"),
        ("inpatient", "0044_alter_admission_admission_number_and_more"),
        ("laboratory", "0042_add_specimen_snomed_code"),
        ("patients", "0024_phase_d_drop_pii_plaintext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="laborder",
            name="order_number",
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AddConstraint(
            model_name="laborder",
            constraint=models.UniqueConstraint(
                fields=("facility", "order_number"), name="unique_order_number_per_facility"
            ),
        ),
    ]
