# Generated by Django 5.2.13 on 2026-07-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0045_diagnosticreport_supersedes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="diagnosticreport",
            new_name="laboratory__superse_0a845b_idx",
            old_name="lab_diag_supersedes_idx",
        ),
    ]
