# Migration purpose: add optional blood-unit linkage on lab orders.
# Run with: poetry run python manage.py migrate laboratory.
# Inputs: none (standard Django migration execution).
# Generated by Django 5.2.13 on 2026-08-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_bank", "0004_blooddonor_origin_hub_id_blooddonor_origin_local_id_and_more"),
        ("laboratory", "0046_rename_lab_diag_supersedes_idx_laboratory__superse_0a845b_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="laborder",
            name="blood_bank_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked blood bank unit for transfusion-related testing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_orders",
                to="blood_bank.bloodunit",
            ),
        ),
    ]
