# Migration purpose: add optional billing_patient linkage for split donor/recipient billing.
# Run with: poetry run python manage.py migrate laboratory.
# Inputs: none (standard Django migration execution).
# Generated by Django 5.2.13 on 2026-08-17 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0047_laborder_blood_bank_unit"),
        ("patients", "0027_alter_historicalpatient_identification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="laborder",
            name="billing_patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Patient to bill for this order (defaults to patient if omitted)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billed_lab_orders",
                to="patients.patient",
            ),
        ),
    ]
