# Copyright (c) 2026 Nexora Consulting Ltd. All rights reserved.
# This migration adds standalone LIS WS3 interoperability models and fields.
# Usage: applied via `python manage.py migrate`.
# Inputs: no direct CLI args beyond Django migration command options.
# Generated by Django 5.2.13 on 2026-09-04 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_facility_lis_onboarding_completed_at"),
        ("laboratory", "0048_laborder_billing_patient"),
        ("patients", "0027_alter_historicalpatient_identification_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalPatientIdentifierCrosswalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                ("source_system", models.CharField(db_index=True, max_length=100)),
                ("external_patient_id", models.CharField(db_index=True, max_length=100)),
                ("external_member_id", models.CharField(blank=True, max_length=100)),
                ("patient_name_snapshot", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "External Patient Identifier Crosswalk",
                "verbose_name_plural": "External Patient Identifier Crosswalks",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InboundIngestionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                (
                    "trace_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "source_system",
                    models.CharField(db_index=True, default="EXTERNAL", max_length=100),
                ),
                ("channel", models.CharField(default="API", max_length=20)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("MAPPED", "Mapped"),
                            ("FAILED", "Failed"),
                            ("REPLAYED", "Replayed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("raw_payload", models.TextField()),
                ("error_message", models.TextField(blank=True)),
                ("replay_count", models.PositiveIntegerField(default=0)),
                ("last_replayed_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Inbound Ingestion Event",
                "verbose_name_plural": "Inbound Ingestion Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResultDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_hub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hub ID where this record was originally created (null = cloud-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "origin_local_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Original PK on the source hub (for dedup on cloud receipt).",
                        null=True,
                    ),
                ),
                (
                    "trace_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("WEBHOOK", "API Callback/Webhook"),
                            ("PDF_PACKAGE", "Downloadable PDF Package"),
                            ("HL7_FHIR", "HL7/FHIR Adapter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=500)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("pdf_filename", models.CharField(blank=True, max_length=255)),
                ("pdf_package", models.BinaryField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Result Delivery Log",
                "verbose_name_plural": "Result Delivery Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="externalorderrequest",
            name="idempotency_key",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="externalorderrequest",
            name="trace_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name="externalorderrequest",
            index=models.Index(fields=["trace_id"], name="laboratory__trace_i_b91116_idx"),
        ),
        migrations.AddIndex(
            model_name="externalorderrequest",
            index=models.Index(fields=["idempotency_key"], name="laboratory__idempot_e5f0d1_idx"),
        ),
        migrations.AddField(
            model_name="externalpatientidentifiercrosswalk",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="externalpatientidentifiercrosswalk",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="externalpatientidentifiercrosswalk",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_identifier_crosswalks",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="externalpatientidentifiercrosswalk",
            name="walkin_patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="identifier_crosswalks",
                to="laboratory.walkinpatient",
            ),
        ),
        migrations.AddField(
            model_name="inboundingestionevent",
            name="external_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingestion_events",
                to="laboratory.externalorderrequest",
            ),
        ),
        migrations.AddField(
            model_name="inboundingestionevent",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="inboundingestionevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="resultdeliverylog",
            name="external_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="result_deliveries",
                to="laboratory.externalorderrequest",
            ),
        ),
        migrations.AddField(
            model_name="resultdeliverylog",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility (branch) where this record was created.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="resultdeliverylog",
            name="lab_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_deliveries",
                to="laboratory.laborder",
            ),
        ),
        migrations.AddField(
            model_name="resultdeliverylog",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (tenant).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="resultdeliverylog",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="externalpatientidentifiercrosswalk",
            index=models.Index(
                fields=["source_system", "external_patient_id"],
                name="laboratory__source__69bebb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalpatientidentifiercrosswalk",
            index=models.Index(
                fields=["external_member_id"], name="laboratory__externa_810ce3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalpatientidentifiercrosswalk",
            constraint=models.UniqueConstraint(
                fields=("facility", "source_system", "external_patient_id"),
                name="uniq_lab_xwalk_facility_source_external_patient",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundingestionevent",
            index=models.Index(
                fields=["status", "created_at"], name="laboratory__status_6df9e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inboundingestionevent",
            index=models.Index(fields=["idempotency_key"], name="laboratory__idempot_58a3a5_idx"),
        ),
        migrations.AddIndex(
            model_name="inboundingestionevent",
            index=models.Index(fields=["source_system"], name="laboratory__source__000d0b_idx"),
        ),
        migrations.AddIndex(
            model_name="inboundingestionevent",
            index=models.Index(fields=["trace_id"], name="laboratory__trace_i_639e8d_idx"),
        ),
        migrations.AddIndex(
            model_name="resultdeliverylog",
            index=models.Index(
                fields=["status", "created_at"], name="laboratory__status_606093_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resultdeliverylog",
            index=models.Index(fields=["channel"], name="laboratory__channel_bc32bd_idx"),
        ),
        migrations.AddIndex(
            model_name="resultdeliverylog",
            index=models.Index(fields=["trace_id"], name="laboratory__trace_i_97569e_idx"),
        ),
    ]
