# Generated by Django 5.2.9 on 2025-12-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="brand_names",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
