# Generated by Django 5.2.9 on 2026-01-10 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0006_add_prescription_number"),
        ("pharmacy", "0006_alertsettings"),
    ]

    operations = []
