# Generated by Django 5.2.9 on 2026-01-10 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0007_merge_0006_add_prescription_number_0006_alertsettings"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="prescription",
            new_name="pharmacy_pr_prescri_2aaaee_idx",
            old_name="pharmacy_pr_prescri_idx",
        ),
        migrations.RenameIndex(
            model_name="prescription",
            new_name="pharmacy_pr_status_3f9cad_idx",
            old_name="pharmacy_pr_status_idx",
        ),
    ]
