# Generated by Django 5.2.9 on 2026-01-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0008_rename_pharmacy_pr_prescri_idx_pharmacy_pr_prescri_2aaaee_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="strength",
            field=models.CharField(max_length=150),
        ),
    ]
