# Generated by Django 5.2.9 on 2026-01-18 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encounters", "0015_remove_plan_field_use_treatment_plan"),
        ("pharmacy", "0009_increase_drug_strength_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional - can be null for walk-in pharmacy prescriptions",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prescriptions",
                to="encounters.encounter",
            ),
        ),
    ]
