# Generated by Django 5.2.9 on 2026-01-29

from django.db import migrations, models


DEFAULT_CATEGORIES = [
    ("ANALGESIC", "Analgesics & Antipyretics"),
    ("ANTIBIOTIC", "Antibiotics"),
    ("ANTIMALARIAL", "Antimalarials"),
    ("ANTIRETROVIRAL", "Antiretrovirals"),
    ("ANTIHYPERTENSIVE", "Antihypertensives"),
    ("ANTIDIABETIC", "Antidiabetics"),
    ("ANTIHISTAMINE", "Antihistamines"),
    ("VITAMIN", "Vitamins & Supplements"),
    ("VACCINE", "Vaccines"),
    ("CONTRACEPTIVE", "Contraceptives"),
    ("PSYCHOTROPIC", "Psychotropic Drugs"),
    ("CONTROLLED", "Controlled Substances"),
    ("OTHER", "Other"),
]


def seed_default_categories(apps, schema_editor):
    DrugCategory = apps.get_model("pharmacy", "DrugCategory")

    for code, name in DEFAULT_CATEGORIES:
        DrugCategory.objects.update_or_create(
            code=code,
            defaults={"name": name, "is_active": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0011_drug_multiple_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="drugcategory",
            index=models.Index(fields=["code"], name="pharmacy_dr_code_08c037_idx"),
        ),
        migrations.AddIndex(
            model_name="drugcategory",
            index=models.Index(fields=["is_active"], name="pharmacy_dr_is_acti_a2a5ae_idx"),
        ),
        migrations.RunPython(seed_default_categories, migrations.RunPython.noop),
    ]
