# Generated by Django 5.2.9 on 2026-02-09 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pharmacy",
            "0013_rename_pharmacy_dr_code_08c037_idx_pharmacy_dr_code_2bc209_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
