# Generated by Django 5.2.11 on 2026-03-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0016_historicalprescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="hpt_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="KNHTS concept ID from DHA HPT Registry (e.g., 10-03913-01)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="hpt_last_synced",
            field=models.DateTimeField(
                blank=True, help_text="When HPT data was last fetched from DHA", null=True
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="hpt_product_id",
            field=models.IntegerField(
                blank=True, db_index=True, help_text="DHA HPT product ID for API lookups", null=True
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="ppb_code",
            field=models.CharField(
                blank=True,
                help_text="Kenya Pharmacy and Poisons Board registration code",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(fields=["hpt_code"], name="pharmacy_dr_hpt_cod_024b45_idx"),
        ),
    ]
