# Generated by Django 5.2.11 on 2026-03-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0017_add_hpt_fields_to_drug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("LOW_STOCK", "Low Stock"),
                    ("OUT_OF_STOCK", "Out of Stock"),
                    ("EXPIRING_SOON", "Expiring Soon"),
                    ("EXPIRED", "Expired"),
                    ("RECALLED", "Product Recalled"),
                    ("RX_EXPIRING", "Prescription Expiring"),
                ],
                max_length=20,
            ),
        ),
    ]
