# Generated by Django 5.2.11 on 2026-03-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0020_dispensing_facility_dispensing_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprescription",
            name="dispensing_type",
            field=models.CharField(
                choices=[
                    ("INTERNAL", "Internal (Hospital Pharmacy)"),
                    ("EXTERNAL", "External (Outside Pharmacy)"),
                ],
                default="INTERNAL",
                help_text="INTERNAL prescriptions are dispensed at the hospital pharmacy; EXTERNAL prescriptions are filled at an outside pharmacy.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="is_discharge_medication",
            field=models.BooleanField(
                default=False,
                help_text="If true, this prescription is intended as a take-home discharge medication.",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="dispensing_type",
            field=models.CharField(
                choices=[
                    ("INTERNAL", "Internal (Hospital Pharmacy)"),
                    ("EXTERNAL", "External (Outside Pharmacy)"),
                ],
                default="INTERNAL",
                help_text="INTERNAL prescriptions are dispensed at the hospital pharmacy; EXTERNAL prescriptions are filled at an outside pharmacy.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="is_discharge_medication",
            field=models.BooleanField(
                default=False,
                help_text="If true, this prescription is intended as a take-home discharge medication.",
            ),
        ),
    ]
