# Generated by Django 5.2.13 on 2026-05-20 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_supplier_address_remove_supplier_email_and_more"),
        ("pharmacy", "0023_facility_scoped_model_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispensing",
            name="store_location",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, auto-deducts from ward stock at this store.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispensings",
                to="inventory.storelocation",
            ),
        ),
    ]
