# Generated by Django 5.2.13 on 2026-05-20 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_supplier_address_remove_supplier_email_and_more"),
        ("pharmacy", "0024_add_store_location_to_dispensing"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockbatch",
            name="store_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Store where this batch is physically stored",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_batches",
                to="inventory.storelocation",
            ),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="location",
            field=models.CharField(
                blank=True, help_text="Shelf/bin within the store (e.g. Shelf A1)", max_length=100
            ),
        ),
    ]
