# Generated by Django 5.2.13 on 2026-05-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_supplier_address_remove_supplier_email_and_more"),
        ("pharmacy", "0025_add_store_location_to_stockbatch"),
    ]

    operations = [
        # Step 1: Rename old CharField columns to legacy
        migrations.RenameField(
            model_name="stockbatch",
            old_name="supplier",
            new_name="supplier_legacy",
        ),
        migrations.RenameField(
            model_name="stockbatch",
            old_name="purchase_order",
            new_name="purchase_order_legacy",
        ),
        # Step 2: Add new FK columns
        migrations.AddField(
            model_name="stockbatch",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_batches",
                to="inventory.supplier",
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_batches",
                to="inventory.purchaseorder",
            ),
        ),
        # Step 3: Remove legacy columns
        migrations.RemoveField(
            model_name="stockbatch",
            name="supplier_legacy",
        ),
        migrations.RemoveField(
            model_name="stockbatch",
            name="purchase_order_legacy",
        ),
    ]
