# Generated by Django 5.2.13 on 2026-05-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0026_link_supplier_po_to_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("MEDICATION", "Medication"),
                    ("CONSUMABLE", "Consumable"),
                    ("REAGENT", "Reagent"),
                ],
                db_index=True,
                default="MEDICATION",
                help_text="MEDICATION for drugs, CONSUMABLE for medical supplies, REAGENT for lab reagents",
                max_length=20,
            ),
        ),
    ]
