# Generated by Django 5.2.13 on 2026-05-25 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_facility_has_imaging_standalone_and_more"),
        ("patients", "0024_phase_d_drop_pii_plaintext"),
        ("pharmacy", "0028_add_consumable_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprescription",
            name="bill_patient",
            field=models.BooleanField(
                default=True,
                help_text="Whether to auto-bill the patient. Defaults to False for standalone orders.",
            ),
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="external_prescription_number",
            field=models.CharField(
                blank=True,
                help_text="Original prescription number from external prescriber",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="is_walkin",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a standalone/walk-in prescription without HMIS patient",
            ),
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="walkin_customer_dob",
            field=models.DateField(
                blank=True, help_text="Walk-in customer date of birth", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="walkin_customer_gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                help_text="Walk-in customer gender",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="walkin_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Walk-in customer national ID or other identifier",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="walkin_customer_name",
            field=models.CharField(
                blank=True, help_text="Walk-in customer full name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="walkin_customer_phone",
            field=models.CharField(
                blank=True, help_text="Walk-in customer phone number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="bill_patient",
            field=models.BooleanField(
                default=True,
                help_text="Whether to auto-bill the patient. Defaults to False for standalone orders.",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="external_prescription_number",
            field=models.CharField(
                blank=True,
                help_text="Original prescription number from external prescriber",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="is_walkin",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a standalone/walk-in prescription without HMIS patient",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="walkin_customer_dob",
            field=models.DateField(
                blank=True, help_text="Walk-in customer date of birth", null=True
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="walkin_customer_gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                help_text="Walk-in customer gender",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="walkin_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Walk-in customer national ID or other identifier",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="walkin_customer_name",
            field=models.CharField(
                blank=True, help_text="Walk-in customer full name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="walkin_customer_phone",
            field=models.CharField(
                blank=True, help_text="Walk-in customer phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="form",
            field=models.CharField(
                choices=[
                    ("TABLET", "Tablet"),
                    ("CAPSULE", "Capsule"),
                    ("SYRUP", "Syrup"),
                    ("INJECTION", "Injection"),
                    ("CREAM", "Cream"),
                    ("OINTMENT", "Ointment"),
                    ("DROPS", "Drops"),
                    ("INHALER", "Inhaler"),
                    ("SUPPOSITORY", "Suppository"),
                    ("POWDER", "Powder"),
                    ("SUSPENSION", "Suspension"),
                    ("SOLUTION", "Solution"),
                    ("GEL", "Gel"),
                    ("PATCH", "Patch"),
                    ("SPRAY", "Spray"),
                    ("UNIT", "Unit/Piece"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalprescription",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Optional - null for standalone walk-in pharmacy prescriptions",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional - null for standalone walk-in pharmacy prescriptions",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prescriptions",
                to="patients.patient",
            ),
        ),
        migrations.CreateModel(
            name="WalkInCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: WLKC-YYYYMMDD-XXXX",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("phone_number_encrypted", models.TextField(blank=True, default="")),
                (
                    "phone_number_hmac",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("email_encrypted", models.TextField(blank=True, default="")),
                ("national_id_encrypted", models.TextField(blank=True, default="")),
                (
                    "national_id_hmac",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NATIONAL_ID", "National ID"),
                            ("PASSPORT", "Passport"),
                            ("BIRTH_CERT", "Birth Certificate"),
                            ("MILITARY_ID", "Military ID"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "referring_facility",
                    models.CharField(
                        blank=True,
                        help_text="External facility that issued the prescription",
                        max_length=200,
                    ),
                ),
                (
                    "referring_clinician",
                    models.CharField(
                        blank=True, help_text="Name of prescribing clinician", max_length=200
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "linked_patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Links to full HMIS patient record if later registered",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_walkin_registrations",
                        to="patients.patient",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Walk-in Pharmacy Customer",
                "verbose_name_plural": "Walk-in Pharmacy Customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalPrescriptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_control_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("sending_application", models.CharField(blank=True, max_length=100)),
                ("sending_facility", models.CharField(max_length=100)),
                ("prescriber_name", models.CharField(blank=True, max_length=200)),
                ("prescriber_license", models.CharField(blank=True, max_length=100)),
                ("external_patient_id", models.CharField(blank=True, max_length=100)),
                ("patient_name", models.CharField(max_length=200)),
                ("patient_dob", models.DateField(blank=True, null=True)),
                ("patient_gender", models.CharField(blank=True, max_length=1)),
                ("patient_phone", models.CharField(blank=True, max_length=20)),
                ("patient_id_number", models.CharField(blank=True, max_length=50)),
                (
                    "external_prescription_number",
                    models.CharField(
                        db_index=True,
                        help_text="Prescription number from external prescriber",
                        max_length=100,
                    ),
                ),
                ("priority", models.CharField(default="ROUTINE", max_length=20)),
                ("clinical_info", models.TextField(blank=True)),
                (
                    "requested_items",
                    models.JSONField(
                        default=list,
                        help_text="List of prescribed items: [{drug_name, drug_code, dose, frequency, duration, quantity}]",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "raw_message",
                    models.TextField(blank=True, help_text="Raw HL7/JSON message content"),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_requests",
                        to="pharmacy.prescription",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "walkin_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_prescriptions",
                        to="pharmacy.walkincustomer",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Prescription Request",
                "verbose_name_plural": "External Prescription Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="walkincustomer",
            index=models.Index(
                fields=["registration_number"], name="pharmacy_wa_registr_622a26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walkincustomer",
            index=models.Index(fields=["national_id_hmac"], name="pharmacy_wa_nationa_75d9a0_idx"),
        ),
        migrations.AddIndex(
            model_name="walkincustomer",
            index=models.Index(
                fields=["last_name", "first_name"], name="pharmacy_wa_last_na_7e50b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walkincustomer",
            index=models.Index(fields=["phone_number_hmac"], name="pharmacy_wa_phone_n_adf390_idx"),
        ),
        migrations.AddIndex(
            model_name="externalprescriptionrequest",
            index=models.Index(
                fields=["message_control_id"], name="pharmacy_ex_message_f51889_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalprescriptionrequest",
            index=models.Index(
                fields=["external_prescription_number"], name="pharmacy_ex_externa_2a376a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalprescriptionrequest",
            index=models.Index(fields=["status"], name="pharmacy_ex_status_1120fd_idx"),
        ),
    ]
