# Generated by Django 5.2.13 on 2026-07-09 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_staffprofile_mfa_disabled"),
        ("encounters", "0033_add_cancelled_consultation_status"),
        ("inpatient", "0044_alter_admission_admission_number_and_more"),
        ("patients", "0024_phase_d_drop_pii_plaintext"),
        ("pharmacy", "0030_dispensing_origin_hub_id_dispensing_origin_local_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprescription",
            name="prescription_number",
            field=models.CharField(
                editable=False,
                help_text="Prescription Number (auto-generated, format: RX-YYYYMMDD-XXXX)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="prescription_number",
            field=models.CharField(
                editable=False,
                help_text="Prescription Number (auto-generated, format: RX-YYYYMMDD-XXXX)",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="prescription",
            constraint=models.UniqueConstraint(
                fields=("facility", "prescription_number"),
                name="unique_prescription_number_per_facility",
            ),
        ),
    ]
