# Generated by Django 5.2.13 on 2026-07-14 19:09

import uuid
from django.db import migrations, models


def backfill_pharmacy_public_ids(apps, schema_editor):
    Dispensing = apps.get_model("pharmacy", "Dispensing")
    HistoricalPrescription = apps.get_model("pharmacy", "HistoricalPrescription")
    Prescription = apps.get_model("pharmacy", "Prescription")

    for dispensing_id in Dispensing.objects.filter(public_id__isnull=True).values_list("id", flat=True).iterator(
        chunk_size=1000
    ):
        Dispensing.objects.filter(id=dispensing_id, public_id__isnull=True).update(public_id=uuid.uuid4())

    for snapshot_id in HistoricalPrescription.objects.filter(public_id__isnull=True).values_list(
        "id", flat=True
    ).iterator(chunk_size=2000):
        HistoricalPrescription.objects.filter(id=snapshot_id, public_id__isnull=True).update(
            public_id=uuid.uuid4()
        )

    for prescription_id in Prescription.objects.filter(public_id__isnull=True).values_list(
        "id", flat=True
    ).iterator(chunk_size=1000):
        Prescription.objects.filter(id=prescription_id, public_id__isnull=True).update(public_id=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0031_alter_historicalprescription_prescription_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispensing",
            name="public_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="public_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="public_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_pharmacy_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="dispensing",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalprescription",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable public UUID for external APIs and links.",
                unique=True,
            ),
        ),
    ]
