#!/usr/bin/env python3
"""
Scrape DHA HIE Integration Scenarios documentation into a single Markdown file.

The site (hie-docs.dha.go.ke) is a Zudoku SPA — content is rendered client-side,
so we use Playwright (headless Chromium) to render JavaScript before extracting.

Targets: https://hie-docs.dha.go.ke/docs/scenarios/overview
         + all scenario sub-pages (1-6)

Outputs: docs/hie-scenarios-reference.md

Usage:
    python scripts/scrape_hie_scenarios.py
    python scripts/scrape_hie_scenarios.py --output /path/to/output.md
    python scripts/scrape_hie_scenarios.py --delay 2.0

Prerequisites:
    pip install playwright beautifulsoup4
    playwright install chromium
"""

import argparse
import re
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import urljoin

try:
    from playwright.sync_api import sync_playwright, Page, Browser
    from bs4 import BeautifulSoup, Tag
except ImportError:
    print("Missing dependencies. Install with:")
    print("  pip install playwright beautifulsoup4")
    print("  playwright install chromium")
    sys.exit(1)


BASE_URL = "https://hie-docs.dha.go.ke"

# Pages to scrape in order
SCENARIO_PAGES = [
    "/docs/scenarios/overview",
    "/docs/scenarios/scenario-1-shif-ip-per-diem",
    "/docs/scenarios/scenario-2-shif-ip-ffs-normal-preauth",
    "/docs/scenarios/scenario-3-shif-ip-ffs-elective-preauth",
    "/docs/scenarios/scenario-4-shif-op-ffs-elective-preauth",
    "/docs/scenarios/scenario-5-shif-op-ffs-normal-preauth",
    "/docs/scenarios/scenario-6-uhc-op-capitation",
]


@dataclass
class ScrapedPage:
    url: str
    title: str
    markdown: str
    mermaid_diagrams: list[str] = field(default_factory=list)


def wait_for_content(page: Page) -> None:
    """Wait for the SPA to finish rendering content."""
    # Wait for the loading spinner to disappear and actual content to appear
    try:
        page.wait_for_selector("article, [class*='prose'], main h1, main h2", timeout=15000)
    except Exception:
        # Fallback: wait for network idle
        pass
    # Additional wait for dynamic content
    page.wait_for_load_state("networkidle")
    # Small extra buffer for late-rendering elements (mermaid, etc.)
    page.wait_for_timeout(1500)


def extract_mermaid_from_page(page: Page) -> list[str]:
    """Extract Mermaid diagram source code from the rendered page."""
    diagrams = []

    # Try to get mermaid source from pre/code elements
    mermaid_sources = page.evaluate("""() => {
        const diagrams = [];

        // Pattern 1: <pre class="mermaid"> or <code class="language-mermaid">
        document.querySelectorAll('pre.mermaid, code.language-mermaid, [class*="mermaid"] code').forEach(el => {
            const text = el.textContent.trim();
            if (text && (text.includes('graph') || text.includes('flowchart') || text.includes('sequenceDiagram'))) {
                diagrams.push(text);
            }
        });

        // Pattern 2: SVG elements generated by mermaid (try to get the original source)
        document.querySelectorAll('svg[id^="mermaid"], svg.mermaid, [class*="mermaid"] svg').forEach(svg => {
            // Some sites store the original source in a data attribute
            const source = svg.getAttribute('data-mermaid') || svg.getAttribute('aria-label') || '';
            if (source) diagrams.push(source);
        });

        // Pattern 3: Look for raw mermaid text in any pre/code blocks
        document.querySelectorAll('pre code').forEach(el => {
            const text = el.textContent.trim();
            if (text.match(/^(graph|flowchart|sequenceDiagram|classDiagram|stateDiagram|gantt|pie)/m)) {
                diagrams.push(text);
            }
        });

        return diagrams;
    }""")

    if mermaid_sources:
        diagrams.extend(mermaid_sources)

    return diagrams


def extract_flowchart_svgs(page: Page) -> list[dict]:
    """Extract flowchart/sequence diagram text from rendered SVGs.

    The DHA site renders Mermaid sequence diagrams as SVGs with actors,
    messages (text elements), and notes. We extract those text elements
    to reconstruct a readable representation of the flow.
    """
    svg_data = page.evaluate("""() => {
        const results = [];
        document.querySelectorAll('svg').forEach(svg => {
            const rect = svg.getBoundingClientRect();
            if (rect.width < 200 || rect.height < 100) return;
            const cls = svg.className && svg.className.baseVal ? svg.className.baseVal : '';
            if (cls.includes('lucide') || cls.includes('icon')) return;

            // Collect all text elements sorted by Y position
            const textEls = [];
            svg.querySelectorAll('text').forEach(el => {
                const t = el.textContent.trim();
                if (t) {
                    const r = el.getBoundingClientRect();
                    const elCls = el.getAttribute('class') || '';
                    textEls.push({text: t, y: r.y, x: r.x, cls: elCls});
                }
            });
            textEls.sort((a, b) => a.y - b.y || a.x - b.x);

            // Categorize by class
            const actors = [];
            const messages = [];
            const notes = [];
            const seqNumbers = [];

            textEls.forEach(item => {
                if (item.cls.includes('actor')) {
                    if (actors.indexOf(item.text) === -1) actors.push(item.text);
                } else if (item.cls.includes('messageText')) {
                    messages.push(item.text);
                } else if (item.cls.includes('noteText')) {
                    notes.push(item.text);
                } else if (item.cls.includes('sequenceNumber')) {
                    seqNumbers.push(item.text);
                }
            });

            // Also collect multi-line note content from tspan
            svg.querySelectorAll('.note tspan').forEach(el => {
                const t = el.textContent.trim();
                if (t && notes.indexOf(t) === -1) notes.push(t);
            });

            const isSeqDiagram = actors.length > 0 || messages.length > 0 || cls.includes('flowchart');
            if (isSeqDiagram && (actors.length > 0 || messages.length > 0)) {
                results.push({
                    actors: actors,
                    messages: messages,
                    notes: notes,
                    width: rect.width,
                    height: rect.height,
                    isSequenceDiagram: true
                });
            }
        });
        return results;
    }""")

    return svg_data or []


def get_page_html(page: Page) -> str:
    """Get the rendered HTML content from the main content area."""
    # Try multiple selectors for the main content
    content_html = page.evaluate("""() => {
        // Try common content selectors for Zudoku docs
        const selectors = [
            'article',
            '[class*="prose"]',
            'main [class*="content"]',
            'main',
        ];

        for (const sel of selectors) {
            const el = document.querySelector(sel);
            if (el && el.innerHTML.trim().length > 100) {
                return el.innerHTML;
            }
        }

        // Fallback: get main's content minus nav/header/footer
        const main = document.querySelector('main');
        if (main) return main.innerHTML;

        return document.body.innerHTML;
    }""")

    return content_html or ""


def get_page_title(page: Page) -> str:
    """Extract the page title from the rendered content."""
    title = page.evaluate("""() => {
        const h1 = document.querySelector('article h1, main h1, [class*="prose"] h1');
        if (h1) return h1.textContent.trim();
        return document.title.split(' - ')[0].trim();
    }""")
    # Clean "Link to ..." anchors
    title = re.sub(r"Link to [\w-]+$", "", title or "").strip()
    return title


def html_to_markdown(html: str, page_url: str) -> str:
    """Convert HTML string to Markdown."""
    soup = BeautifulSoup(html, "html.parser")
    lines: list[str] = []
    _convert_element(soup, lines, page_url)
    text = "\n".join(lines)
    # Clean up excessive blank lines
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    # Remove link anchor suffixes the site adds
    text = re.sub(r"Link to [\w-]+", "", text)
    return text.strip()


def _convert_element(el, lines: list[str], page_url: str) -> None:
    """Recursively convert HTML elements to markdown lines."""
    if isinstance(el, str):
        text = el.strip()
        if text:
            lines.append(text)
        return

    if not isinstance(el, Tag):
        return

    tag = el.name

    # Skip non-content elements
    if tag in ("script", "style", "nav", "button", "noscript", "header", "footer"):
        return

    # Skip elements with certain classes (navigation, breadcrumbs, etc.)
    classes = " ".join(el.get("class", []))
    if any(
        skip in classes
        for skip in ["breadcrumb", "pagination", "sidebar", "toc", "copy-button"]
    ):
        return

    # Headers
    if tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
        level = int(tag[1])
        text = el.get_text(strip=True)
        text = re.sub(r"Link to [\w-]+$", "", text).strip()
        if text:
            lines.append("")
            lines.append(f"{'#' * level} {text}")
            lines.append("")
        return

    # Paragraphs
    if tag == "p":
        text = _inline_text(el, page_url)
        if text.strip():
            lines.append("")
            lines.append(text)
            lines.append("")
        return

    # Code blocks
    if tag == "pre":
        code_el = el.find("code")
        if code_el:
            el_classes = code_el.get("class", [])
            lang = ""
            for cls in el_classes:
                if "language-" in cls:
                    lang = cls.split("language-")[-1]
                    break
            code_text = code_el.get_text()
            lines.append("")
            lines.append(f"```{lang}")
            lines.append(code_text.rstrip())
            lines.append("```")
            lines.append("")
        else:
            code_text = el.get_text()
            lines.append("")
            lines.append("```")
            lines.append(code_text.rstrip())
            lines.append("```")
            lines.append("")
        return

    # Inline code (skip, handled by _inline_text)
    if tag == "code" and el.parent and el.parent.name != "pre":
        return

    # Tables
    if tag == "table":
        _convert_table(el, lines)
        return

    # Lists
    if tag in ("ul", "ol"):
        lines.append("")
        for i, li in enumerate(el.find_all("li", recursive=False)):
            prefix = f"{i + 1}. " if tag == "ol" else "- "
            text = _inline_text(li, page_url)
            lines.append(f"{prefix}{text}")
        lines.append("")
        return

    # Images
    if tag == "img":
        src = el.get("src", "")
        alt = el.get("alt", "Diagram")
        if src and not any(
            skip in src.lower() for skip in ["logo", "icon", "favicon"]
        ):
            full_url = urljoin(page_url, src) if not src.startswith("http") else src
            lines.append("")
            lines.append(f"![{alt}]({full_url})")
            lines.append("")
        return

    # SVG elements (likely diagrams)
    if tag == "svg":
        # Check dimensions/classes to see if it's a diagram
        width = el.get("width", "0")
        classes = " ".join(el.get("class", []))
        if "lucide" in classes or "icon" in classes:
            return  # Skip icons
        title_el = el.find("title")
        if title_el:
            lines.append("")
            lines.append(f"*[Flowchart: {title_el.get_text(strip=True)}]*")
            lines.append("")
        return

    # Blockquote
    if tag == "blockquote":
        lines.append("")
        for child in el.children:
            if isinstance(child, Tag):
                child_text = _inline_text(child, page_url)
                if child_text.strip():
                    for line in child_text.split("\n"):
                        lines.append(f"> {line}")
            elif isinstance(child, str) and child.strip():
                lines.append(f"> {child.strip()}")
        lines.append("")
        return

    # Horizontal rule
    if tag == "hr":
        lines.append("")
        lines.append("---")
        lines.append("")
        return

    # Details/summary
    if tag == "details":
        summary = el.find("summary")
        if summary:
            lines.append("")
            lines.append(
                f"<details><summary>{summary.get_text(strip=True)}</summary>"
            )
            lines.append("")
        for child in el.children:
            if isinstance(child, Tag) and child.name == "summary":
                continue
            _convert_element(child, lines, page_url)
        lines.append("</details>")
        lines.append("")
        return

    # Admonitions / callouts
    if tag == "div" and any(
        kw in classes for kw in ["admonition", "callout", "alert", "warning", "info", "note"]
    ):
        lines.append("")
        # Try to detect type
        if "warning" in classes:
            lines.append("> ⚠️ **Warning**")
        elif "info" in classes:
            lines.append("> ℹ️ **Info**")
        else:
            lines.append("> **Note**")
        text = el.get_text(strip=True)
        for line in text.split("\n"):
            if line.strip():
                lines.append(f"> {line.strip()}")
        lines.append("")
        return

    # Generic: recurse into children
    for child in el.children:
        _convert_element(child, lines, page_url)


def _inline_text(el: Tag, page_url: str) -> str:
    """Convert inline HTML to markdown text."""
    parts: list[str] = []
    for child in el.children:
        if isinstance(child, str):
            parts.append(child)
        elif isinstance(child, Tag):
            if child.name == "code":
                parts.append(f"`{child.get_text()}`")
            elif child.name in ("strong", "b"):
                parts.append(f"**{child.get_text()}**")
            elif child.name in ("em", "i"):
                parts.append(f"*{child.get_text()}*")
            elif child.name == "a":
                href = child.get("href", "")
                text = child.get_text(strip=True)
                if href:
                    if href.startswith("/") or href.startswith("#"):
                        full_url = urljoin(page_url, href)
                    else:
                        full_url = href
                    parts.append(f"[{text}]({full_url})")
                else:
                    parts.append(text)
            elif child.name == "br":
                parts.append("\n")
            elif child.name == "img":
                src = child.get("src", "")
                alt = child.get("alt", "")
                if src and "logo" not in src.lower() and "icon" not in src.lower():
                    full_url = (
                        urljoin(page_url, src)
                        if not src.startswith("http")
                        else src
                    )
                    parts.append(f"![{alt}]({full_url})")
            elif child.name in ("span", "div", "li", "td", "th"):
                parts.append(_inline_text(child, page_url))
            elif child.name in ("script", "style", "button", "svg"):
                pass  # Skip
            else:
                parts.append(child.get_text())
    return "".join(parts).strip()


def _convert_table(table: Tag, lines: list[str]) -> None:
    """Convert an HTML table to markdown table format."""
    rows: list[list[str]] = []

    # Extract header
    thead = table.find("thead")
    headers: list[str] = []
    if thead:
        for th in thead.find_all(["th", "td"]):
            headers.append(th.get_text(strip=True))

    # Extract body rows
    tbody = table.find("tbody") or table
    for tr in tbody.find_all("tr", recursive=False if tbody.name == "tbody" else True):
        cells = [td.get_text(strip=True) for td in tr.find_all(["td", "th"])]
        if cells and any(c.strip() for c in cells):
            rows.append(cells)

    # If thead had no headers, try first row of tbody
    if not headers and rows:
        # Check if first row looks like a header (shorter text, no data)
        headers = rows.pop(0)

    if not headers and not rows:
        return

    # Ensure consistent column count
    max_cols = max(
        len(headers),
        max((len(r) for r in rows), default=0),
    )
    headers = (headers + [""] * max_cols)[:max_cols]

    # Build markdown table
    lines.append("")
    lines.append("| " + " | ".join(h or " " for h in headers) + " |")
    lines.append("| " + " | ".join(["---"] * max_cols) + " |")
    for row in rows:
        padded = (row + [""] * max_cols)[:max_cols]
        # Escape pipe chars in cell content
        escaped = [c.replace("|", "\\|") for c in padded]
        lines.append("| " + " | ".join(escaped) + " |")
    lines.append("")


def _format_sequence_diagram(svg_info: dict) -> str:
    """Format extracted sequence diagram data as readable Markdown.

    Renders actors as participants and messages as numbered flow steps.
    """
    actors = svg_info.get("actors", [])
    messages = svg_info.get("messages", [])
    notes = svg_info.get("notes", [])

    if not messages and not actors:
        return ""

    parts: list[str] = []

    # Show participants
    if actors:
        # Deduplicate (actors often appear twice: top + bottom)
        unique_actors = list(dict.fromkeys(actors))
        parts.append("**Participants:**")
        for actor in unique_actors:
            parts.append(f"- {actor}")
        parts.append("")

    # Show messages as numbered flow
    if messages:
        parts.append("**Flow:**")
        for i, msg in enumerate(messages, 1):
            parts.append(f"{i}. {msg}")
        parts.append("")

    # Show notes if any (additional context)
    if notes:
        unique_notes = list(dict.fromkeys(notes))
        parts.append("**Notes:**")
        for note in unique_notes:
            parts.append(f"- {note}")
        parts.append("")

    return "\n".join(parts)


def scrape_page(page: Page, path: str) -> ScrapedPage | None:
    """Navigate to a page, wait for render, and extract content."""
    url = urljoin(BASE_URL, path)
    print(f"  Navigating: {url}")

    try:
        page.goto(url, wait_until="domcontentloaded", timeout=30000)
        wait_for_content(page)
    except Exception as e:
        print(f"  [ERROR] Failed to load {url}: {e}")
        return None

    # Get title
    title = get_page_title(page)
    if not title:
        title = path.split("/")[-1].replace("-", " ").title()

    # Extract mermaid diagrams
    mermaid_diagrams = extract_mermaid_from_page(page)

    # Extract flowchart SVGs (sequence diagrams)
    svg_data = extract_flowchart_svgs(page)

    # Get rendered HTML content
    content_html = get_page_html(page)

    if not content_html or len(content_html) < 50:
        print(f"  [WARN] Minimal content found for {url}")
        return None

    # Convert to markdown
    markdown = html_to_markdown(content_html, url)

    # Append extracted sequence diagram flows as readable text
    if svg_data:
        for svg_info in svg_data:
            if not svg_info.get("isSequenceDiagram"):
                continue
            diagram_md = _format_sequence_diagram(svg_info)
            if diagram_md:
                # Insert after the "Complete Flow" heading if present
                if "## Complete Flow" in markdown:
                    markdown = markdown.replace(
                        "## Complete Flow",
                        f"## Complete Flow\n\n{diagram_md}",
                        1,  # Only replace first occurrence
                    )
                else:
                    markdown += f"\n\n### Sequence Diagram\n\n{diagram_md}"

    return ScrapedPage(
        url=url,
        title=title,
        markdown=markdown,
        mermaid_diagrams=mermaid_diagrams,
    )


def discover_scenario_links(page: Page) -> list[str]:
    """Discover additional scenario page links from the rendered page."""
    links = page.evaluate("""() => {
        const found = [];
        document.querySelectorAll('a[href*="/docs/scenarios/"]').forEach(a => {
            const href = a.getAttribute('href');
            if (href && !href.includes('#')) {
                // Normalize
                const path = href.startsWith('http')
                    ? new URL(href).pathname
                    : href;
                if (!found.includes(path)) found.push(path);
            }
        });
        return found;
    }""")
    return links or []


def build_document(pages: list[ScrapedPage]) -> str:
    """Build the final unified markdown document."""
    parts: list[str] = []

    # Front matter / header
    parts.append("# DHA HIE Integration Scenarios Reference")
    parts.append("")
    parts.append(
        "> **Source**: [DHA Health Information Exchange Documentation]"
        "(https://hie-docs.dha.go.ke/docs/scenarios/overview)"
    )
    parts.append(
        f"> **Scraped**: {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}"
    )
    parts.append(
        "> **Purpose**: Offline reference for Vitora HMIS SHA integration development"
    )
    parts.append("")
    parts.append("---")
    parts.append("")

    # Table of contents
    parts.append("## Table of Contents")
    parts.append("")
    for i, page in enumerate(pages, 1):
        anchor = re.sub(r"[^a-z0-9\s-]", "", page.title.lower())
        anchor = re.sub(r"\s+", "-", anchor.strip())
        parts.append(f"{i}. [{page.title}](#{anchor})")
    parts.append("")
    parts.append("---")
    parts.append("")

    # Each page as a section
    for page in pages:
        parts.append(f"## {page.title}")
        parts.append("")
        parts.append(f"> Source: [{page.url}]({page.url})")
        parts.append("")

        # Include mermaid diagrams if found
        if page.mermaid_diagrams:
            for diagram in page.mermaid_diagrams:
                parts.append("```mermaid")
                parts.append(diagram)
                parts.append("```")
                parts.append("")

        parts.append(page.markdown)
        parts.append("")
        parts.append("---")
        parts.append("")

    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(
        description="Scrape DHA HIE Scenarios docs to unified Markdown (uses Playwright)"
    )
    parser.add_argument(
        "--output",
        "-o",
        default=None,
        help="Output file path (default: docs/hie-scenarios-reference.md)",
    )
    parser.add_argument(
        "--delay",
        type=float,
        default=2.0,
        help="Delay between page navigations in seconds (default: 2.0)",
    )
    parser.add_argument(
        "--headed",
        action="store_true",
        help="Run browser in headed mode (visible) for debugging",
    )
    args = parser.parse_args()

    # Determine output path
    if args.output:
        output_path = Path(args.output)
    else:
        script_dir = Path(__file__).resolve().parent
        project_root = script_dir.parent
        output_path = project_root / "docs" / "hie-scenarios-reference.md"

    print("DHA HIE Scenarios Scraper (Playwright)")
    print("=" * 40)
    print(f"Output: {output_path}")
    print(f"Delay: {args.delay}s between pages")
    print(f"Mode: {'headed' if args.headed else 'headless'}")
    print()

    with sync_playwright() as pw:
        browser = pw.chromium.launch(headless=not args.headed)
        context = browser.new_context(
            viewport={"width": 1280, "height": 900},
            user_agent=(
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            ),
        )
        page = context.new_page()

        # Step 1: Load overview to discover pages
        print("[1/3] Discovering pages...")
        pages_to_scrape = list(SCENARIO_PAGES)

        try:
            page.goto(
                urljoin(BASE_URL, SCENARIO_PAGES[0]),
                wait_until="domcontentloaded",
                timeout=30000,
            )
            wait_for_content(page)
            additional = discover_scenario_links(page)
            new_pages = [
                p
                for p in additional
                if p not in pages_to_scrape and "/docs/scenarios/" in p
            ]
            if new_pages:
                print(f"  Found {len(new_pages)} additional page(s)")
                for p in new_pages:
                    print(f"    + {p}")
                pages_to_scrape.extend(new_pages)
        except Exception as e:
            print(f"  [WARN] Discovery failed: {e}")

        # Deduplicate while preserving order
        seen = set()
        deduped = []
        for p in pages_to_scrape:
            # Strip fragment anchors
            clean = p.split("#")[0].rstrip("/")
            if clean not in seen:
                seen.add(clean)
                deduped.append(clean)
        pages_to_scrape = deduped

        print(f"  Total pages to scrape: {len(pages_to_scrape)}")
        print()

        # Step 2: Scrape all pages
        print("[2/3] Scraping pages...")
        scraped: list[ScrapedPage] = []

        for i, path in enumerate(pages_to_scrape):
            result = scrape_page(page, path)
            if result:
                scraped.append(result)
                diag_info = (
                    f", {len(result.mermaid_diagrams)} mermaid"
                    if result.mermaid_diagrams
                    else ""
                )
                print(
                    f"  ✓ [{i+1}/{len(pages_to_scrape)}] {result.title} "
                    f"({len(result.markdown):,} chars{diag_info})"
                )
            else:
                print(f"  ✗ [{i+1}/{len(pages_to_scrape)}] Failed: {path}")

            # Polite delay
            if i < len(pages_to_scrape) - 1:
                time.sleep(args.delay)

        print()

        browser.close()

    if not scraped:
        print("[ERROR] No pages were successfully scraped.")
        sys.exit(1)

    # Step 3: Build and write document
    print("[3/3] Building unified document...")
    document = build_document(scraped)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(document, encoding="utf-8")

    print(f"  ✓ Written {len(document):,} characters to {output_path}")
    print(f"  ✓ {len(scraped)} pages included")
    print()
    print("Done!")


if __name__ == "__main__":
    main()
