# Generated by Django 5.2.13 on 2026-04-16 14:37

import django.db.models.deletion
import django.utils.timezone
import hmis.apps.inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_projection_read_models"),
        ("inpatient", "0038_add_scheduling_resource"),
        ("inventory", "0002_storelocation_stocktransfer_transferitem_and_more"),
        ("patients", "0017_death_record"),
        ("pharmacy", "0022_fix_drug_form_mismatches"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "count_number",
                    models.CharField(
                        default=hmis.apps.inventory.models.generate_stock_count_number,
                        editable=False,
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "count_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Count"),
                            ("CYCLE", "Cycle Count"),
                            ("SPOT", "Spot Check"),
                        ],
                        default="CYCLE",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("APPROVED", "Approved"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_counts_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_counts_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = facility main store.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_counts",
                        to="inventory.storelocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WardStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_available", models.PositiveIntegerField(default=0)),
                (
                    "par_level",
                    models.PositiveIntegerField(
                        default=10, help_text="Minimum stock level — triggers replenishment alert."
                    ),
                ),
                (
                    "max_level",
                    models.PositiveIntegerField(
                        default=100, help_text="Maximum stock level for this location."
                    ),
                ),
                ("last_replenished_at", models.DateTimeField(blank=True, null=True)),
                ("last_counted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ward_stocks",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "store_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ward_stocks",
                        to="inventory.storelocation",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to inpatient ward.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ward_stocks",
                        to="inpatient.ward",
                    ),
                ),
            ],
            options={
                "ordering": ["store_location", "drug"],
            },
        ),
        migrations.CreateModel(
            name="WardStockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("REPLENISH", "Replenish"),
                            ("CONSUME", "Consume"),
                            ("RETURN", "Return to Store"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("COUNT_CORRECTION", "Count Correction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(help_text="Positive = in, negative = out.")),
                ("performed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ward_transactions",
                        to="pharmacy.stockbatch",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Patient consuming the item (for CONSUME type).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ward_stock_consumptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ward_stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ward_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.wardstock",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCountItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system_quantity",
                    models.PositiveIntegerField(
                        help_text="System quantity at time of count generation."
                    ),
                ),
                (
                    "counted_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Actual physical count. Null until counted.",
                        null=True,
                    ),
                ),
                (
                    "variance_reason",
                    models.TextField(
                        blank=True, help_text="Required explanation when counted ≠ system."
                    ),
                ),
                ("counted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_count_items",
                        to="pharmacy.stockbatch",
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_items_counted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_count_items",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "stock_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.stockcount",
                    ),
                ),
            ],
            options={
                "ordering": ["drug__generic_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stock_count", "batch"), name="unique_count_item_per_batch"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="wardstock",
            constraint=models.UniqueConstraint(
                fields=("store_location", "drug"), name="unique_ward_stock_per_drug_location"
            ),
        ),
    ]
