# Generated by Django 5.2.13 on 2026-04-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_etimsconfig_options_demandforecast_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etimsconfig",
            options={
                "ordering": ["-created_at"],
                "permissions": [("manage_etims", "Can manage eTIMS configuration")],
                "verbose_name": "eTIMS Configuration",
                "verbose_name_plural": "eTIMS Configurations",
            },
        ),
        migrations.AlterModelOptions(
            name="stockcount",
            options={
                "ordering": ["-created_at"],
                "permissions": [("approve_stock_count", "Can approve stock counts")],
            },
        ),
        migrations.AlterModelOptions(
            name="stocktransfer",
            options={
                "ordering": ["-request_date", "-created_at"],
                "permissions": [("approve_stock_transfer", "Can approve stock transfers")],
            },
        ),
    ]
