# Generated by Django 5.2.13 on 2026-05-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_etimsconfig_options_alter_stockcount_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="address",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="email",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="phone",
        ),
        migrations.AddField(
            model_name="supplier",
            name="address_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="supplier",
            name="email_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
