# Generated by Django 5.2.13 on 2026-05-21 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_add_has_private_insurance"),
        ("inventory", "0008_add_payment_term_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="etimsconfig",
            name="counter_cc",
            field=models.PositiveIntegerField(default=0, help_text="Next CC receipt counter."),
        ),
        migrations.AddField(
            model_name="etimsconfig",
            name="counter_cs",
            field=models.PositiveIntegerField(default=0, help_text="Next CS receipt counter."),
        ),
        migrations.AddField(
            model_name="etimsconfig",
            name="counter_nc",
            field=models.PositiveIntegerField(default=0, help_text="Next NC receipt counter."),
        ),
        migrations.AddField(
            model_name="etimsconfig",
            name="counter_ns",
            field=models.PositiveIntegerField(default=0, help_text="Next NS receipt counter."),
        ),
        migrations.AddField(
            model_name="etimsconfig",
            name="counter_ps",
            field=models.PositiveIntegerField(default=0, help_text="Next PS receipt counter."),
        ),
        migrations.AddField(
            model_name="etimsconfig",
            name="counter_tc",
            field=models.PositiveIntegerField(default=0, help_text="Next TC receipt counter."),
        ),
        migrations.AddField(
            model_name="etimsconfig",
            name="counter_ts",
            field=models.PositiveIntegerField(default=0, help_text="Next TS receipt counter."),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="buyer_pin",
            field=models.CharField(
                blank=True, help_text="Buyer's KRA PIN (optional per §5.1.3).", max_length=15
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="ej_data_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether electronic journal data was sent for this receipt.",
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="original_cu_invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Original CU invoice number for credit note reference.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="original_etims_invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Original invoice for credit notes (NC/CC).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_notes",
                to="inventory.etimsinvoice",
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="qr_code_data",
            field=models.TextField(
                blank=True,
                help_text="QR code string per §6.23.8: date#time#cu_number#cu_receipt_number#internal_data#signature.",
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="receipt_label",
            field=models.CharField(
                choices=[
                    ("NS", "Normal Sale"),
                    ("NC", "Normal Credit Note"),
                    ("CS", "Copy Sale"),
                    ("CC", "Copy Credit Note"),
                    ("TS", "Training Sale"),
                    ("TC", "Training Credit Note"),
                    ("PS", "Proforma Sale"),
                ],
                default="NS",
                help_text="Combined receipt label (NS, NC, CS, CC, TS, TC, PS).",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="receipt_type",
            field=models.CharField(
                choices=[("N", "Normal"), ("C", "Copy"), ("T", "Training"), ("P", "Proforma")],
                default="N",
                help_text="KRA receipt type: N, C, T, P.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="receipt_type_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Sequential counter per receipt type (§6.3)."
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="scu_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Date/time stamped by OSCU/VSCU (§5.3.2).", null=True
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="scu_id",
            field=models.CharField(
                blank=True, help_text="SCU/CU ID from OSCU/VSCU response (§5.3.1).", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="scu_internal_data",
            field=models.CharField(
                blank=True,
                help_text="Internal data string from SCU (§5.3.6 / §6.23.6).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="scu_receipt_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Receipt counter per type from SCU (§5.3.4)."
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="scu_receipt_signature",
            field=models.CharField(
                blank=True,
                help_text="Digital receipt signature from SCU (§5.3.6 / §6.23.7).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="scu_total_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Total receipt counter from SCU (§5.3.5)."
            ),
        ),
        migrations.AddField(
            model_name="etimsinvoice",
            name="transaction_type",
            field=models.CharField(
                choices=[("S", "Sale"), ("NC", "Credit Note")],
                default="S",
                help_text="KRA transaction type: S or NC.",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="ETIMSDailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("X", "X Daily Report (interim)"),
                            ("Z", "Z Daily Report (end of day)"),
                        ],
                        max_length=1,
                    ),
                ),
                ("report_date", models.DateField(help_text="Date the report covers.")),
                (
                    "report_number",
                    models.PositiveIntegerField(help_text="Sequential Z/X report number."),
                ),
                (
                    "total_ns_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total sales amount for all NS receipts, including tax.",
                        max_digits=14,
                    ),
                ),
                (
                    "total_ns_count",
                    models.PositiveIntegerField(default=0, help_text="Number of NS receipts."),
                ),
                (
                    "total_nc_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total credit note amount for all NC receipts (negative).",
                        max_digits=14,
                    ),
                ),
                (
                    "total_nc_count",
                    models.PositiveIntegerField(default=0, help_text="Number of NC receipts."),
                ),
                (
                    "taxable_amount_a",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("tax_amount_a", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "taxable_amount_b",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("tax_amount_b", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "taxable_amount_c",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("tax_amount_c", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "taxable_amount_d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("tax_amount_d", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "taxable_amount_e",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("tax_amount_e", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "opening_deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_items_sold", models.PositiveIntegerField(default=0)),
                (
                    "total_cs_cc_count",
                    models.PositiveIntegerField(default=0, help_text="Copy receipts count."),
                ),
                (
                    "total_cs_cc_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_ts_tc_count",
                    models.PositiveIntegerField(default=0, help_text="Training receipts count."),
                ),
                (
                    "total_ts_tc_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_ps_count",
                    models.PositiveIntegerField(default=0, help_text="Proforma receipts count."),
                ),
                (
                    "total_ps_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("payment_cash", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("payment_mpesa", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "payment_insurance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("payment_other", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "total_discounts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("incomplete_sales_count", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date", "-report_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("facility", "report_type", "report_date", "report_number"),
                        name="unique_etims_daily_report",
                    )
                ],
            },
        ),
    ]
