# Generated by Django 5.2.9 on 2026-02-22 18:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0019_emergency_access"),
        ("encounters", "0022_add_disposition_fields"),
        ("patients", "0010_add_unique_identification_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotifiableDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Disease name (e.g., Cholera, Measles)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "icd10_codes",
                    models.TextField(
                        help_text="Comma-separated ICD-10 codes (e.g., 'A00,A00.0,A00.1,A00.9')"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediate (within 24 hours)"),
                            ("WEEKLY", "Weekly (IDSR)"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="WEEKLY",
                        help_text="MOH notification category",
                        max_length=20,
                    ),
                ),
                (
                    "reporting_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Maximum hours to report to authorities",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(720),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Clinical description and case definition"
                    ),
                ),
                (
                    "case_definition",
                    models.TextField(
                        blank=True, default="", help_text="WHO/MOH case definition criteria"
                    ),
                ),
                (
                    "laboratory_criteria",
                    models.TextField(
                        blank=True, default="", help_text="Laboratory confirmation criteria"
                    ),
                ),
                (
                    "is_ihr_notifiable",
                    models.BooleanField(
                        default=False,
                        help_text="Requires International Health Regulations notification",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether disease is currently on MOH reportable list",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notifiable Disease",
                "verbose_name_plural": "Notifiable Diseases",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["category"], name="surveillanc_categor_dad7fa_idx"),
                    models.Index(fields=["is_active"], name="surveillanc_is_acti_182298_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotifiableCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "onset_date",
                    models.DateField(blank=True, help_text="Date of symptom onset", null=True),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MILD", "Mild"),
                            ("MODERATE", "Moderate"),
                            ("SEVERE", "Severe"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MODERATE",
                        help_text="Clinical severity",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active/Under Treatment"),
                            ("RECOVERED", "Recovered"),
                            ("REFERRED", "Referred to Higher Facility"),
                            ("DECEASED", "Deceased"),
                            ("LOST_TO_FOLLOWUP", "Lost to Follow-up"),
                        ],
                        default="ACTIVE",
                        help_text="Patient outcome",
                        max_length=20,
                    ),
                ),
                (
                    "laboratory_confirmed",
                    models.BooleanField(
                        default=False, help_text="Whether diagnosis is laboratory confirmed"
                    ),
                ),
                (
                    "lab_result_date",
                    models.DateField(
                        blank=True, help_text="Date of confirmatory lab result", null=True
                    ),
                ),
                (
                    "notification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Notification"),
                            ("NOTIFIED", "Notified to County"),
                            ("ACKNOWLEDGED", "Acknowledged by County"),
                            ("INVESTIGATED", "Under Investigation"),
                            ("CLOSED", "Case Closed"),
                        ],
                        default="PENDING",
                        help_text="Notification workflow status",
                        max_length=20,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When case was detected/created",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, help_text="When county health office was notified", null=True
                    ),
                ),
                (
                    "notification_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for notification based on disease category",
                        null=True,
                    ),
                ),
                (
                    "contact_tracing_initiated",
                    models.BooleanField(
                        default=False, help_text="Whether contact tracing has started"
                    ),
                ),
                (
                    "contacts_identified",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of contacts identified"
                    ),
                ),
                (
                    "investigation_notes",
                    models.TextField(
                        blank=True, default="", help_text="Notes from case investigation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        help_text="County health office to notify",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifiable_cases",
                        to="core.county",
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True,
                        help_text="Diagnosis record that triggered case creation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifiable_cases",
                        to="encounters.diagnosis",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        help_text="Encounter where diagnosis was made",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifiable_cases",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "notified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who submitted notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notified_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient with notifiable condition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifiable_cases",
                        to="patients.patient",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="Staff who reported/created the case",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_county",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sub-county for granular reporting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifiable_cases",
                        to="core.subcounty",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        help_text="Notifiable disease type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="surveillance.notifiabledisease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifiable Case",
                "verbose_name_plural": "Notifiable Cases",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="OutbreakThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "case_threshold",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of cases to trigger outbreak alert",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "period_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Period in days for case counting",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether threshold is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        help_text="County for threshold (null = national)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbreak_thresholds",
                        to="core.county",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        help_text="Disease to monitor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="surveillance.notifiabledisease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbreak Threshold",
                "verbose_name_plural": "Outbreak Thresholds",
                "ordering": ["disease__name", "county__name"],
            },
        ),
        migrations.CreateModel(
            name="SurveillanceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("NEW_CASE", "New Case Detected"),
                            ("OVERDUE", "Notification Overdue"),
                            ("OUTBREAK", "Outbreak Threshold Reached"),
                            ("CASE_UPDATE", "Case Updated"),
                        ],
                        default="NEW_CASE",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="Alert message content")),
                (
                    "is_acknowledged",
                    models.BooleanField(
                        default=False, help_text="Whether alert has been acknowledged"
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("sent_via_websocket", models.BooleanField(default=False)),
                ("sent_via_sms", models.BooleanField(default=False)),
                ("sent_via_email", models.BooleanField(default=False)),
                ("sms_recipient", models.CharField(blank=True, default="", max_length=20)),
                ("email_recipient", models.EmailField(blank=True, default="", max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_surveillance_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="Case that triggered this alert",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="surveillance.notifiablecase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surveillance Alert",
                "verbose_name_plural": "Surveillance Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notifiablecase",
            index=models.Index(
                fields=["notification_status"], name="surveillanc_notific_bd0e5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notifiablecase",
            index=models.Index(fields=["detected_at"], name="surveillanc_detecte_059969_idx"),
        ),
        migrations.AddIndex(
            model_name="notifiablecase",
            index=models.Index(
                fields=["disease", "notification_status"], name="surveillanc_disease_dad17d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notifiablecase",
            index=models.Index(
                fields=["county", "notification_status"], name="surveillanc_county__8b8549_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notifiablecase",
            constraint=models.UniqueConstraint(
                fields=("patient", "encounter", "disease"), name="unique_patient_encounter_disease"
            ),
        ),
        migrations.AddConstraint(
            model_name="outbreakthreshold",
            constraint=models.UniqueConstraint(
                fields=("disease", "county"), name="unique_disease_county_threshold"
            ),
        ),
        migrations.AddIndex(
            model_name="surveillancealert",
            index=models.Index(
                fields=["is_acknowledged", "created_at"], name="surveillanc_is_ackn_7b5b6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveillancealert",
            index=models.Index(fields=["alert_type"], name="surveillanc_alert_t_a14bce_idx"),
        ),
    ]
