# Generated by Django 5.2.9 on 2026-02-22 20:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_emergency_access"),
        ("surveillance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IDSRWeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "epi_year",
                    models.PositiveIntegerField(help_text="Epidemiological year (ISO 8601)"),
                ),
                (
                    "epi_week",
                    models.PositiveIntegerField(
                        help_text="Epidemiological week number (1-53)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ],
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(help_text="Monday of the epidemiological week"),
                ),
                ("week_end_date", models.DateField(help_text="Sunday of the epidemiological week")),
                (
                    "facility_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MFL code or facility identifier",
                        max_length=50,
                    ),
                ),
                (
                    "facility_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Facility name at time of report generation",
                        max_length=200,
                    ),
                ),
                (
                    "total_cases",
                    models.PositiveIntegerField(
                        default=0, help_text="Total notifiable cases reported this week"
                    ),
                ),
                (
                    "total_deaths",
                    models.PositiveIntegerField(
                        default=0, help_text="Total deaths from notifiable diseases this week"
                    ),
                ),
                (
                    "immediate_cases",
                    models.PositiveIntegerField(
                        default=0, help_text="Cases of immediate reportable diseases"
                    ),
                ),
                (
                    "lab_confirmed_cases",
                    models.PositiveIntegerField(default=0, help_text="Laboratory confirmed cases"),
                ),
                (
                    "outbreak_declared",
                    models.BooleanField(
                        default=False, help_text="Whether outbreak was declared this week"
                    ),
                ),
                (
                    "outbreak_diseases",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list of outbreak diseases",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("SUBMITTED", "Submitted to DHIS2"),
                            ("FAILED", "Submission Failed"),
                        ],
                        default="DRAFT",
                        help_text="Report workflow status",
                        max_length=20,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When report was auto-generated"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When report was reviewed", null=True
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When report was approved", null=True
                    ),
                ),
                (
                    "dhis2_submitted_at",
                    models.DateTimeField(
                        blank=True, help_text="When submitted to DHIS2", null=True
                    ),
                ),
                (
                    "dhis2_response",
                    models.JSONField(blank=True, help_text="DHIS2 API response", null=True),
                ),
                (
                    "dhis2_import_summary",
                    models.JSONField(
                        blank=True,
                        help_text="DHIS2 import summary (imported, updated, ignored counts)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes or comments"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_idsr_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        help_text="County health office for submission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idsr_weekly_reports",
                        to="core.county",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User or system that generated the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_idsr_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_idsr_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_county",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sub-county for detailed reporting",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idsr_weekly_reports",
                        to="core.subcounty",
                    ),
                ),
            ],
            options={
                "verbose_name": "IDSR Weekly Report",
                "verbose_name_plural": "IDSR Weekly Reports",
                "ordering": ["-epi_year", "-epi_week"],
            },
        ),
        migrations.CreateModel(
            name="IDSRDiseaseSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cases_under_5",
                    models.PositiveIntegerField(
                        default=0, help_text="Cases in children under 5 years"
                    ),
                ),
                (
                    "cases_5_and_above",
                    models.PositiveIntegerField(
                        default=0, help_text="Cases in patients 5 years and above"
                    ),
                ),
                (
                    "total_cases",
                    models.PositiveIntegerField(
                        default=0, help_text="Total cases (auto-calculated)"
                    ),
                ),
                (
                    "deaths_under_5",
                    models.PositiveIntegerField(
                        default=0, help_text="Deaths in children under 5 years"
                    ),
                ),
                (
                    "deaths_5_and_above",
                    models.PositiveIntegerField(
                        default=0, help_text="Deaths in patients 5 years and above"
                    ),
                ),
                (
                    "total_deaths",
                    models.PositiveIntegerField(
                        default=0, help_text="Total deaths (auto-calculated)"
                    ),
                ),
                (
                    "lab_confirmed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of laboratory confirmed cases"
                    ),
                ),
                (
                    "case_fatality_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="CFR percentage (deaths/cases * 100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "is_outbreak",
                    models.BooleanField(
                        default=False, help_text="Whether this disease is in outbreak status"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Disease-specific notes or investigation status",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        help_text="Notifiable disease",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idsr_summaries",
                        to="surveillance.notifiabledisease",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Parent weekly report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_summaries",
                        to="surveillance.idsrweeklyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "IDSR Disease Summary",
                "verbose_name_plural": "IDSR Disease Summaries",
                "ordering": ["disease__name"],
            },
        ),
        migrations.AddIndex(
            model_name="idsrweeklyreport",
            index=models.Index(
                fields=["epi_year", "epi_week"], name="surveillanc_epi_yea_e323d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idsrweeklyreport",
            index=models.Index(fields=["status"], name="surveillanc_status_15a601_idx"),
        ),
        migrations.AddIndex(
            model_name="idsrweeklyreport",
            index=models.Index(fields=["county"], name="surveillanc_county__296530_idx"),
        ),
        migrations.AddConstraint(
            model_name="idsrweeklyreport",
            constraint=models.UniqueConstraint(
                fields=("epi_year", "epi_week", "facility_code"), name="unique_idsr_week_facility"
            ),
        ),
        migrations.AddConstraint(
            model_name="idsrdiseasesummary",
            constraint=models.UniqueConstraint(
                fields=("report", "disease"), name="unique_report_disease_summary"
            ),
        ),
    ]
