# Generated by Django 5.2.11 on 2026-03-02 15:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_mfa_token_failed_attempts"),
        ("patients", "0014_historicalpatient"),
        ("surveillance", "0003_add_dhis2_data_element_mapping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IHRNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_description",
                    models.TextField(help_text="Description of the public health event"),
                ),
                (
                    "event_date",
                    models.DateField(help_text="Date the event was detected/identified"),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Public Health Emergency (PHEIC)"),
                            ("URGENT", "Urgent (within 24 hours)"),
                            ("ROUTINE", "Routine IHR Notification"),
                        ],
                        default="URGENT",
                        help_text="IHR urgency classification",
                        max_length=20,
                    ),
                ),
                (
                    "annex2_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Annex 2 decision instrument responses (JSON)",
                    ),
                ),
                (
                    "is_annex2_positive",
                    models.BooleanField(
                        default=False,
                        help_text="Whether event meets Annex 2 criteria for WHO notification",
                    ),
                ),
                (
                    "cases_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Total cases associated with event"
                    ),
                ),
                (
                    "deaths_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Deaths associated with event"
                    ),
                ),
                (
                    "affected_area",
                    models.TextField(
                        blank=True, default="", help_text="Description of affected geographic area"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("SUBMITTED_COUNTY", "Submitted to County"),
                            ("ESCALATED_NATIONAL", "Escalated to MOH"),
                            ("NOTIFIED_WHO", "Notified to WHO"),
                            ("ACKNOWLEDGED", "Acknowledged by WHO"),
                            ("CLOSED", "Closed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        help_text="Current notification pipeline status",
                        max_length=25,
                    ),
                ),
                (
                    "report_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the notification was first reported",
                    ),
                ),
                (
                    "county_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When County Disease Surveillance Coordinator was notified",
                        null=True,
                    ),
                ),
                (
                    "county_notes",
                    models.TextField(blank=True, default="", help_text="County review notes"),
                ),
                (
                    "national_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When MOH National IHR Focal Point was notified",
                        null=True,
                    ),
                ),
                (
                    "national_notes",
                    models.TextField(blank=True, default="", help_text="MOH review notes"),
                ),
                (
                    "who_notified_at",
                    models.DateTimeField(
                        blank=True, help_text="When WHO IHR Contact Point was notified", null=True
                    ),
                ),
                (
                    "who_reference_number",
                    models.CharField(
                        blank=True, default="", help_text="WHO reference/event ID", max_length=100
                    ),
                ),
                (
                    "who_acknowledged_at",
                    models.DateTimeField(
                        blank=True, help_text="When WHO acknowledged receipt", null=True
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was resolved/closed", null=True
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, default="", help_text="Resolution summary"),
                ),
                (
                    "risk_assessment",
                    models.TextField(
                        blank=True, default="", help_text="Public health risk assessment summary"
                    ),
                ),
                (
                    "response_measures",
                    models.TextField(blank=True, default="", help_text="Response measures taken"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source notifiable case (if triggered by specific case)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ihr_notifications",
                        to="surveillance.notifiablecase",
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        help_text="County where event detected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ihr_notifications",
                        to="core.county",
                    ),
                ),
                (
                    "county_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="County officer who reviewed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ihr_county_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        help_text="IHR-notifiable disease",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ihr_notifications",
                        to="surveillance.notifiabledisease",
                    ),
                ),
                (
                    "national_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="MOH officer who reviewed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ihr_national_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Index patient (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ihr_notifications",
                        to="patients.patient",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="Staff who initiated the IHR notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ihr_notifications_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_county",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sub-county where event detected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ihr_notifications",
                        to="core.subcounty",
                    ),
                ),
            ],
            options={
                "verbose_name": "IHR Notification",
                "verbose_name_plural": "IHR Notifications",
                "ordering": ["-report_date"],
                "permissions": [
                    ("escalate_ihr_to_county", "Can escalate IHR notification to county"),
                    ("escalate_ihr_to_national", "Can escalate IHR notification to MOH"),
                    ("notify_ihr_to_who", "Can notify WHO of IHR event"),
                ],
                "indexes": [
                    models.Index(fields=["status"], name="surveillanc_status_92c054_idx"),
                    models.Index(
                        fields=["urgency", "status"], name="surveillanc_urgency_fff0ec_idx"
                    ),
                    models.Index(
                        fields=["disease", "status"], name="surveillanc_disease_ae31a7_idx"
                    ),
                    models.Index(fields=["report_date"], name="surveillanc_report__dacfc6_idx"),
                ],
            },
        ),
    ]
