# Generated by Django 5.2.11 on 2026-03-26 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_role_multitenancy_scope"),
        ("surveillance", "0004_add_ihr_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="idsrweeklyreport",
            name="facility_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility FK for tenant scoping.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idsr_weekly_reports",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="idsrweeklyreport",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idsr_weekly_reports",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="ihrnotification",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where event was detected.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ihr_notifications",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="ihrnotification",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ihr_notifications",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="notifiablecase",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where case was detected.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifiable_cases",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="notifiablecase",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from facility).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifiable_cases",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="surveillancealert",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="Facility where alert originated.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveillance_alerts",
                to="core.facility",
            ),
        ),
        migrations.AddField(
            model_name="surveillancealert",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning organization (auto-set from case).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveillance_alerts",
                to="core.organization",
            ),
        ),
    ]
