# Generated by Django 5.2.13 on 2026-05-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0006_facility_scoped_model_fix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveillancealert",
            name="email_recipient",
        ),
        migrations.RemoveField(
            model_name="surveillancealert",
            name="sms_recipient",
        ),
        migrations.AddField(
            model_name="surveillancealert",
            name="email_recipient_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="surveillancealert",
            name="sms_recipient_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
