# Generated by Django 5.2.13 on 2026-05-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_facility_dha_registry_cache_and_encrypted_pii"),
        ("surveillance", "0007_remove_surveillancealert_email_recipient_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="outbreakthreshold",
            constraint=models.UniqueConstraint(
                condition=models.Q(("county__isnull", True)),
                fields=("disease",),
                name="unique_disease_national_threshold",
            ),
        ),
    ]
