# Generated by Django 5.2.11 on 2026-04-09 23:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0037_add_facility_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentMonthlySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField(help_text="1-12")),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("OPD", "Outpatient"),
                            ("IPD", "Inpatient"),
                            ("EMERGENCY", "Emergency"),
                            ("PHARMACY", "Pharmacy"),
                            ("LABORATORY", "Laboratory"),
                            ("IMAGING", "Imaging / Radiology"),
                            ("MCH", "Maternal & Child Health"),
                            ("THEATRE", "Theatre / Procedures"),
                        ],
                        max_length=20,
                    ),
                ),
                ("visit_count", models.PositiveIntegerField(default=0)),
                ("unique_patients", models.PositiveIntegerField(default=0)),
                ("revenue", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "top_diagnoses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Top 10 ICD-10 diagnoses, e.g. [{"code":"J06.9","name":"...","count":42}]',
                    ),
                ),
                (
                    "avg_length_of_stay_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Average LOS in days (IPD / inpatient only).",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Monthly Summary",
                "verbose_name_plural": "Department Monthly Summaries",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["facility", "year", "month"], name="analytics_d_facilit_3e2501_idx"
                    )
                ],
                "unique_together": {("facility", "year", "month", "department")},
            },
        ),
        migrations.CreateModel(
            name="DiagnosisTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "icd10_code",
                    models.CharField(help_text="ICD-10 code, e.g. J06.9", max_length=10),
                ),
                ("icd10_name", models.CharField(blank=True, max_length=255)),
                (
                    "granularity",
                    models.CharField(
                        choices=[("WEEKLY", "Weekly"), ("MONTHLY", "Monthly")], max_length=10
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start of the period (Monday for weekly)."),
                ),
                ("period_end", models.DateField(help_text="End of the period (inclusive).")),
                ("case_count", models.PositiveIntegerField(default=0)),
                ("age_band_breakdown", models.JSONField(blank=True, default=dict)),
                ("gender_breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis Trend",
                "verbose_name_plural": "Diagnosis Trends",
                "ordering": ["-period_start", "-case_count"],
                "indexes": [
                    models.Index(
                        fields=["facility", "period_start"], name="analytics_d_facilit_bf62c3_idx"
                    ),
                    models.Index(
                        fields=["icd10_code", "period_start"], name="analytics_d_icd10_c_be30d8_idx"
                    ),
                ],
                "unique_together": {("facility", "icd10_code", "granularity", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="FacilityDailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="Calendar date for this summary.")),
                (
                    "new_patients",
                    models.PositiveIntegerField(
                        default=0, help_text="Patients registered on this date."
                    ),
                ),
                (
                    "total_patients",
                    models.PositiveIntegerField(
                        default=0, help_text="Cumulative patient count as of this date."
                    ),
                ),
                ("encounters_opd", models.PositiveIntegerField(default=0)),
                ("encounters_ipd", models.PositiveIntegerField(default=0)),
                ("encounters_emergency", models.PositiveIntegerField(default=0)),
                (
                    "encounters_other",
                    models.PositiveIntegerField(
                        default=0, help_text="ANC, follow-up, specialist, etc."
                    ),
                ),
                ("encounters_total", models.PositiveIntegerField(default=0)),
                (
                    "revenue_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of completed payments on this date.",
                        max_digits=14,
                    ),
                ),
                ("revenue_cash", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("revenue_mpesa", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "revenue_insurance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("invoices_created", models.PositiveIntegerField(default=0)),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total unpaid balance across all open invoices as of this date.",
                        max_digits=14,
                    ),
                ),
                ("lab_orders_placed", models.PositiveIntegerField(default=0)),
                ("lab_orders_completed", models.PositiveIntegerField(default=0)),
                ("lab_critical_results", models.PositiveIntegerField(default=0)),
                ("prescriptions_dispensed", models.PositiveIntegerField(default=0)),
                ("low_stock_alerts", models.PositiveIntegerField(default=0)),
                ("triage_assessments", models.PositiveIntegerField(default=0)),
                ("triage_emergency_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_wait_time_minutes",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Average triage-to-consultation wait time in minutes.",
                        max_digits=7,
                    ),
                ),
                ("current_admissions", models.PositiveIntegerField(default=0)),
                ("new_admissions", models.PositiveIntegerField(default=0)),
                ("discharges", models.PositiveIntegerField(default=0)),
                (
                    "bed_occupancy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of beds occupied (0–100).",
                        max_digits=5,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Daily Summary",
                "verbose_name_plural": "Facility Daily Summaries",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["facility", "date"], name="analytics_f_facilit_336daf_idx"
                    ),
                    models.Index(fields=["date"], name="analytics_f_date_0c82db_idx"),
                ],
                "unique_together": {("facility", "date")},
            },
        ),
        migrations.CreateModel(
            name="PatientDemographicSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField(default=django.utils.timezone.localdate)),
                ("total_patients", models.PositiveIntegerField(default=0)),
                ("age_distribution", models.JSONField(blank=True, default=dict)),
                ("gender_distribution", models.JSONField(blank=True, default=dict)),
                ("county_distribution", models.JSONField(blank=True, default=list)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Demographic Snapshot",
                "verbose_name_plural": "Patient Demographic Snapshots",
                "ordering": ["-snapshot_date"],
                "unique_together": {("facility", "snapshot_date")},
            },
        ),
    ]
