# Generated by Django 5.2.11 on 2026-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitydailysummary",
            name="clinic_referrals",
            field=models.PositiveIntegerField(
                default=0, help_text="Patients referred from a clinic."
            ),
        ),
        migrations.AddField(
            model_name="facilitydailysummary",
            name="follow_up_encounters",
            field=models.PositiveIntegerField(default=0, help_text="Encounters of type FOLLOW_UP."),
        ),
        migrations.AddField(
            model_name="facilitydailysummary",
            name="referral_ins",
            field=models.PositiveIntegerField(
                default=0, help_text="Patients registered referred from another facility."
            ),
        ),
        migrations.AddField(
            model_name="facilitydailysummary",
            name="return_patients",
            field=models.PositiveIntegerField(
                default=0, help_text="Patients with a prior encounter before this date."
            ),
        ),
        migrations.AddField(
            model_name="facilitydailysummary",
            name="walk_ins",
            field=models.PositiveIntegerField(
                default=0, help_text="Patients registered with referral_source='self'."
            ),
        ),
        migrations.AddField(
            model_name="patientdemographicsnapshot",
            name="insurance_coverage",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="patientdemographicsnapshot",
            name="new_vs_return",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="patientdemographicsnapshot",
            name="referral_source_distribution",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
