# Generated by Django 5.2.11 on 2026-03-29 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0012_multitenancy_clinical_fks"),
        ("core", "0030_role_multitenancy_scope"),
        ("encounters", "0025_multitenancy_clinical_fks"),
        ("inpatient", "0034_multitenancy_clinical_fks"),
        ("patients", "0017_death_record"),
        ("pharmacy", "0022_fix_drug_form_mismatches"),
        ("scheduling", "0003_add_assignment_engine_phase2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Internal procedure code (e.g., PROC-001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Procedure name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Detailed description of the procedure"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor Procedure"),
                            ("DIAGNOSTIC", "Diagnostic Procedure"),
                            ("THERAPEUTIC", "Therapeutic Procedure"),
                            ("PREVENTIVE", "Preventive Procedure"),
                            ("EMERGENCY", "Emergency Procedure"),
                            ("DENTAL", "Dental Procedure"),
                            ("OPHTHALMIC", "Ophthalmic Procedure"),
                            ("ENT", "ENT Procedure"),
                            ("OBSTETRIC", "Obstetric Procedure"),
                            ("WOUND_CARE", "Wound Care"),
                            ("INJECTION", "Injection/Infusion"),
                            ("OTHER", "Other"),
                        ],
                        default="MINOR",
                        max_length=20,
                    ),
                ),
                (
                    "body_system",
                    models.CharField(
                        choices=[
                            ("INTEGUMENTARY", "Integumentary (Skin)"),
                            ("MUSCULOSKELETAL", "Musculoskeletal"),
                            ("RESPIRATORY", "Respiratory"),
                            ("CARDIOVASCULAR", "Cardiovascular"),
                            ("DIGESTIVE", "Digestive"),
                            ("URINARY", "Urinary"),
                            ("REPRODUCTIVE", "Reproductive"),
                            ("NERVOUS", "Nervous"),
                            ("ENDOCRINE", "Endocrine"),
                            ("LYMPHATIC", "Lymphatic"),
                            ("SENSORY", "Sensory (Eye/Ear)"),
                            ("DENTAL", "Dental"),
                            ("GENERAL", "General/Multiple"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "ichi_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ICHI procedure code (WHO standard)",
                        max_length=20,
                    ),
                ),
                (
                    "cpt_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CPT procedure code (if applicable)",
                        max_length=10,
                    ),
                ),
                (
                    "icd10_pcs_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ICD-10-PCS code (if applicable)",
                        max_length=10,
                    ),
                ),
                (
                    "consent_required",
                    models.BooleanField(
                        default=True, help_text="Whether written consent is required"
                    ),
                ),
                (
                    "consent_template",
                    models.TextField(blank=True, default="", help_text="Default consent form text"),
                ),
                (
                    "guardian_consent_required",
                    models.BooleanField(
                        default=False, help_text="Whether guardian consent required for minors"
                    ),
                ),
                (
                    "witness_required",
                    models.BooleanField(
                        default=False, help_text="Whether a witness signature is required"
                    ),
                ),
                (
                    "requires_anesthesia",
                    models.BooleanField(
                        default=False, help_text="Whether anesthesia is typically required"
                    ),
                ),
                (
                    "anesthesia_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of anesthesia (local, general, sedation)",
                        max_length=50,
                    ),
                ),
                (
                    "typical_duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Typical procedure duration in minutes"
                    ),
                ),
                (
                    "requires_fasting",
                    models.BooleanField(
                        default=False, help_text="Whether pre-procedure fasting is required"
                    ),
                ),
                (
                    "pre_procedure_instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Instructions for patient before procedure",
                    ),
                ),
                (
                    "post_procedure_instructions",
                    models.TextField(
                        blank=True, default="", help_text="Instructions for patient after procedure"
                    ),
                ),
                (
                    "required_qualifications",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Staff qualifications required (e.g., 'Surgeon, Nurse')",
                    ),
                ),
                (
                    "minimum_staff_count",
                    models.PositiveIntegerField(default=1, help_text="Minimum staff required"),
                ),
                (
                    "base_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base procedure fee (KES)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "sha_tariff_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA intervention tariff code",
                        max_length=50,
                    ),
                ),
                (
                    "sha_package_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA package code (if bundled)",
                        max_length=50,
                    ),
                ),
                (
                    "requires_follow_up",
                    models.BooleanField(
                        default=False, help_text="Whether follow-up appointment is typically needed"
                    ),
                ),
                (
                    "default_follow_up_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Default days until follow-up"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether procedure is currently offered"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility offering this procedure.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_catalog_entries",
                        to="core.facility",
                    ),
                ),
                (
                    "follow_up_clinic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default clinic for follow-up",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_up_procedures",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (auto-set from facility).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_catalog_entries",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Catalog Entry",
                "verbose_name_plural": "Procedure Catalog",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Kit name (e.g., 'Standard Suturing Kit')", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Default kit for this procedure"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kits",
                        to="procedures.procedurecatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Kit",
                "verbose_name_plural": "Procedure Kits",
                "ordering": ["procedure", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureKitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, help_text="Quantity needed")),
                (
                    "is_optional",
                    models.BooleanField(default=False, help_text="Whether this item is optional"),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                (
                    "drug",
                    models.ForeignKey(
                        help_text="Drug/consumable item from pharmacy catalog",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procedures.procedurekit",
                    ),
                ),
            ],
            options={
                "ordering": ["kit", "-is_optional", "drug__generic_name"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(help_text="Procedure start time")),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, help_text="Procedure end time", null=True),
                ),
                (
                    "actual_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Actual duration in minutes", null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(help_text="Where procedure was performed", max_length=100),
                ),
                ("anesthesia_used", models.BooleanField(default=False)),
                ("anesthesia_type", models.CharField(blank=True, default="", max_length=50)),
                (
                    "anesthesia_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Anesthetic agent used (e.g., Lidocaine 2%)",
                        max_length=100,
                    ),
                ),
                (
                    "anesthesia_dose",
                    models.CharField(
                        blank=True, default="", help_text="Dose administered", max_length=50
                    ),
                ),
                (
                    "pre_procedure_findings",
                    models.TextField(
                        blank=True, default="", help_text="Findings before/during procedure"
                    ),
                ),
                (
                    "technique_description",
                    models.TextField(
                        blank=True, default="", help_text="Description of technique used"
                    ),
                ),
                (
                    "specimens_collected",
                    models.BooleanField(
                        default=False, help_text="Whether specimens were collected"
                    ),
                ),
                (
                    "specimen_details",
                    models.TextField(
                        blank=True, default="", help_text="Details of specimens collected"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed Successfully"),
                            ("PARTIAL", "Partially Completed"),
                            ("ABANDONED", "Abandoned"),
                            ("COMPLICATED", "Completed with Complications"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "immediate_outcome",
                    models.TextField(
                        blank=True, default="", help_text="Immediate post-procedure notes"
                    ),
                ),
                ("complications_occurred", models.BooleanField(default=False)),
                ("complication_details", models.TextField(blank=True, default="")),
                ("post_procedure_instructions_given", models.BooleanField(default=False)),
                (
                    "post_procedure_instructions",
                    models.TextField(
                        blank=True, default="", help_text="Instructions given to patient"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "assistant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assistant (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedures_assisted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_logs",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_logs",
                        to="core.organization",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        help_text="Primary performer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedures_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Log",
                "verbose_name_plural": "Procedure Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureConsumable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(help_text="Quantity used")),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unit cost at time of use",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cost (quantity x unit_cost)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific batch used (for FEFO tracking)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacy.stockbatch",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        help_text="Drug/consumable from pharmacy catalog",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumables",
                        to="procedures.procedurelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Consumable",
                "verbose_name_plural": "Procedure Consumables",
                "ordering": ["log", "drug__generic_name"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated order number (PROC-YYYYMMDD-XXXX)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ORDERED", "Ordered"),
                            ("CONSENT_PENDING", "Consent Pending"),
                            ("SCHEDULED", "Scheduled"),
                            ("READY", "Ready to Perform"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ORDERED",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency — Immediate"),
                            ("URGENT", "Urgent — Within 24 hours"),
                            ("ROUTINE", "Routine — Scheduled"),
                            ("ELECTIVE", "Elective — Non-urgent"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "indication",
                    models.TextField(help_text="Clinical indication / reason for procedure"),
                ),
                (
                    "clinical_notes",
                    models.TextField(blank=True, default="", help_text="Additional clinical notes"),
                ),
                (
                    "body_site",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Specific body site (e.g., 'Right forearm')",
                        max_length=100,
                    ),
                ),
                (
                    "laterality",
                    models.CharField(
                        choices=[
                            ("LEFT", "Left"),
                            ("RIGHT", "Right"),
                            ("BILATERAL", "Bilateral"),
                            ("NA", "Not Applicable"),
                        ],
                        default="NA",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(blank=True, help_text="Scheduled procedure date", null=True),
                ),
                (
                    "scheduled_time",
                    models.TimeField(blank=True, help_text="Scheduled procedure time", null=True),
                ),
                (
                    "scheduled_location",
                    models.CharField(
                        blank=True, default="", help_text="Procedure room/location", max_length=100
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated duration (override from catalog)",
                        null=True,
                    ),
                ),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        help_text="If ordered for inpatient",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedure_orders",
                        to="inpatient.admission",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to scheduling.Appointment for formal booking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedure_orders",
                        to="scheduling.appointment",
                    ),
                ),
                (
                    "assigned_performer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff assigned to perform",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_procedures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_procedure_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clinic visit where procedure was ordered",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedure_orders",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Encounter where procedure was ordered",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedure_orders",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility where procedure was ordered.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_orders",
                        to="core.facility",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        help_text="Clinician who ordered the procedure",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (auto-set from facility).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_orders",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="procedures.procedurecatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Order",
                "verbose_name_plural": "Procedure Orders",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.AddField(
            model_name="procedurelog",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log",
                to="procedures.procedureorder",
            ),
        ),
        migrations.CreateModel(
            name="ProcedureConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending — Not yet signed"),
                            ("SIGNED", "Signed — Consent given"),
                            ("DECLINED", "Declined — Consent refused"),
                            ("WITHDRAWN", "Withdrawn — Consent withdrawn"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("WRITTEN", "Written Consent"),
                            ("VERBAL", "Verbal Consent (documented)"),
                            ("EMERGENCY", "Emergency (implied consent)"),
                        ],
                        default="WRITTEN",
                        max_length=20,
                    ),
                ),
                (
                    "consent_text",
                    models.TextField(help_text="Full consent form text presented to patient"),
                ),
                (
                    "procedure_explained",
                    models.BooleanField(
                        default=False, help_text="Procedure was explained to patient"
                    ),
                ),
                (
                    "risks_explained",
                    models.BooleanField(
                        default=False, help_text="Risks and complications were explained"
                    ),
                ),
                (
                    "alternatives_explained",
                    models.BooleanField(
                        default=False, help_text="Alternative treatments were discussed"
                    ),
                ),
                (
                    "questions_answered",
                    models.BooleanField(
                        default=False, help_text="Patient's questions were answered"
                    ),
                ),
                (
                    "signed_by_patient",
                    models.BooleanField(default=False, help_text="Whether patient signed"),
                ),
                (
                    "patient_signature",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Patient signature (base64 image or typed name)",
                    ),
                ),
                ("patient_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "signed_by_guardian",
                    models.BooleanField(
                        default=False, help_text="Whether guardian signed (for minors)"
                    ),
                ),
                ("guardian_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "guardian_relationship",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Relationship to patient (parent, spouse, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "guardian_id_number",
                    models.CharField(
                        blank=True, default="", help_text="Guardian's ID number", max_length=50
                    ),
                ),
                ("guardian_signature", models.TextField(blank=True, default="")),
                ("guardian_signed_at", models.DateTimeField(blank=True, null=True)),
                ("witness_required", models.BooleanField(default=False)),
                ("witness_name", models.CharField(blank=True, default="", max_length=200)),
                ("witness_signature", models.TextField(blank=True, default="")),
                ("witness_signed_at", models.DateTimeField(blank=True, null=True)),
                ("obtained_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decline_reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for declining/withdrawing consent"
                    ),
                ),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_consents",
                        to="core.facility",
                    ),
                ),
                (
                    "obtained_by",
                    models.ForeignKey(
                        help_text="Staff who obtained consent",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents_obtained",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_consents",
                        to="core.organization",
                    ),
                ),
                (
                    "witnessed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who witnessed the consent",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="witnessed_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent",
                        to="procedures.procedureorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Consent",
                "verbose_name_plural": "Procedure Consents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assessment_date", models.DateField(help_text="Date of outcome assessment")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("SUCCESSFUL", "Successful — Full recovery"),
                            ("PARTIAL_SUCCESS", "Partial Success"),
                            ("HEALING", "Healing as expected"),
                            ("DELAYED_HEALING", "Delayed Healing"),
                            ("INFECTION", "Infection"),
                            ("COMPLICATION", "Post-procedure Complication"),
                            ("RE_PROCEDURE_NEEDED", "Re-procedure Needed"),
                            ("REFERRED", "Referred for Further Care"),
                        ],
                        max_length=30,
                    ),
                ),
                ("findings", models.TextField(help_text="Clinical findings")),
                ("notes", models.TextField(blank=True, default="")),
                ("next_follow_up", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True, default="")),
                (
                    "images",
                    models.JSONField(
                        blank=True, help_text="List of image file references", null=True
                    ),
                ),
                (
                    "assessed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_outcomes_assessed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_outcomes",
                        to="core.facility",
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="procedures.procedurelog",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_outcomes",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure Outcome",
                "verbose_name_plural": "Procedure Outcomes",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="procedurecatalog",
            index=models.Index(fields=["code"], name="procedures__code_0a662c_idx"),
        ),
        migrations.AddIndex(
            model_name="procedurecatalog",
            index=models.Index(fields=["ichi_code"], name="procedures__ichi_co_c7c057_idx"),
        ),
        migrations.AddIndex(
            model_name="procedurecatalog",
            index=models.Index(fields=["category"], name="procedures__categor_bf3d9f_idx"),
        ),
        migrations.AddIndex(
            model_name="procedurecatalog",
            index=models.Index(
                fields=["facility", "is_active"], name="procedures__facilit_a4944f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="procedurekititem",
            unique_together={("kit", "drug")},
        ),
        migrations.AddIndex(
            model_name="procedureorder",
            index=models.Index(fields=["order_number"], name="procedures__order_n_c967a4_idx"),
        ),
        migrations.AddIndex(
            model_name="procedureorder",
            index=models.Index(fields=["patient", "status"], name="procedures__patient_32cc91_idx"),
        ),
        migrations.AddIndex(
            model_name="procedureorder",
            index=models.Index(fields=["scheduled_date"], name="procedures__schedul_cc5a58_idx"),
        ),
        migrations.AddIndex(
            model_name="procedureorder",
            index=models.Index(
                fields=["facility", "status"], name="procedures__facilit_c6cf3b_idx"
            ),
        ),
    ]
