# Generated by Django 5.2.11 on 2026-03-30 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0012_multitenancy_clinical_fks"),
        ("core", "0030_role_multitenancy_scope"),
        ("encounters", "0026_add_scheduled_procedure_visit_reason"),
        ("inpatient", "0034_multitenancy_clinical_fks"),
        ("patients", "0017_death_record"),
        ("procedures", "0002_add_billing_service_fk"),
        ("scheduling", "0003_add_assignment_engine_phase2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurecatalog",
            name="default_clinics",
            field=models.ManyToManyField(
                blank=True,
                help_text="Clinics where this procedure can be performed. When set, scheduling auto-lists available slots from these clinics.",
                related_name="procedure_catalog_entries",
                to="clinics.clinic",
            ),
        ),
        migrations.AddField(
            model_name="procedureorder",
            name="scheduled_clinic",
            field=models.ForeignKey(
                blank=True,
                help_text="Clinic/procedure room where procedure is scheduled",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_procedures",
                to="clinics.clinic",
            ),
        ),
        migrations.AlterField(
            model_name="procedureorder",
            name="scheduled_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-text location (fallback when scheduled_clinic is not set)",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="procedureorder",
            index=models.Index(
                fields=["scheduled_clinic", "scheduled_date", "status"],
                name="procedures__schedul_1723c7_idx",
            ),
        ),
    ]
