# Generated by Django 5.2.13 on 2026-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0005_facility_scoped_model_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurecatalog",
            name="anesthesia_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Anesthesia fee (KES)", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="procedurecatalog",
            name="cleanup_time_minutes",
            field=models.PositiveIntegerField(
                default=15, help_text="Time to clean the theatre after surgery"
            ),
        ),
        migrations.AddField(
            model_name="procedurecatalog",
            name="complexity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MINOR", "Minor"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("MAJOR", "Major"),
                    ("COMPLEX", "Complex"),
                ],
                default="",
                help_text="Surgical complexity (only for SURGICAL category)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="procedurecatalog",
            name="requires_icu_bed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="procedurecatalog",
            name="setup_time_minutes",
            field=models.PositiveIntegerField(
                default=15, help_text="Time to prepare the theatre before surgery"
            ),
        ),
        migrations.AddField(
            model_name="procedurecatalog",
            name="sha_intervention_code",
            field=models.CharField(
                blank=True, default="", help_text="Kenya SHA intervention code", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="procedurecatalog",
            name="special_equipment",
            field=models.TextField(
                blank=True, default="", help_text="Equipment needed beyond standard theatre setup"
            ),
        ),
        migrations.AddField(
            model_name="procedurecatalog",
            name="surgeon_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Surgeon fee (KES)", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="procedurecatalog",
            name="theatre_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Theatre usage fee (KES)", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="procedurecatalog",
            name="typical_blood_requirement",
            field=models.CharField(
                blank=True, default="", help_text='e.g. "2 units PRBC"', max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="procedurecatalog",
            name="category",
            field=models.CharField(
                choices=[
                    ("MINOR", "Minor Procedure"),
                    ("DIAGNOSTIC", "Diagnostic Procedure"),
                    ("THERAPEUTIC", "Therapeutic Procedure"),
                    ("PREVENTIVE", "Preventive Procedure"),
                    ("EMERGENCY", "Emergency Procedure"),
                    ("DENTAL", "Dental Procedure"),
                    ("OPHTHALMIC", "Ophthalmic Procedure"),
                    ("ENT", "ENT Procedure"),
                    ("OBSTETRIC", "Obstetric Procedure"),
                    ("WOUND_CARE", "Wound Care"),
                    ("INJECTION", "Injection/Infusion"),
                    ("SURGICAL", "Surgical Procedure"),
                    ("OTHER", "Other"),
                ],
                default="MINOR",
                max_length=20,
            ),
        ),
    ]
