# Generated by Django 5.2.13 on 2026-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0006_procedurecatalog_anesthesia_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecatalog',
            name='tibabot_procedure_key',
            field=models.CharField(blank=True, default='', help_text='Mapped TibaBot surgical procedure key for AI surgical assistant integration.', max_length=100),
        ),
    ]
