# Generated by Django 5.2.11 on 2026-03-14 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KENHDDDataElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "element_id",
                    models.CharField(
                        help_text="Unique KENHDD element code (e.g. KENHDD-PAT-001)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable element name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Description of the data element"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("PATIENT", "Patient"),
                            ("ENCOUNTER", "Encounter"),
                            ("DIAGNOSIS", "Diagnosis"),
                            ("FACILITY", "Facility"),
                            ("LAB_RESULT", "Lab Result"),
                            ("PRESCRIPTION", "Prescription"),
                            ("MCH_VISIT", "MCH Visit"),
                        ],
                        help_text="Resource type this element applies to",
                        max_length=20,
                    ),
                ),
                (
                    "model_field",
                    models.CharField(
                        help_text="Dot-path to the Django model field (e.g. county.name)",
                        max_length=100,
                    ),
                ),
                (
                    "requirement_level",
                    models.CharField(
                        choices=[
                            ("MANDATORY", "Mandatory"),
                            ("CONDITIONAL", "Conditional"),
                            ("OPTIONAL", "Optional"),
                        ],
                        help_text="Whether this element is mandatory, conditional, or optional",
                        max_length=15,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("DATE", "Date"),
                            ("INTEGER", "Integer"),
                            ("DECIMAL", "Decimal"),
                            ("CODED", "Coded"),
                            ("BOOLEAN", "Boolean"),
                            ("IDENTIFIER", "Identifier"),
                        ],
                        help_text="Expected data type",
                        max_length=15,
                    ),
                ),
                (
                    "coding_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ICD10", "ICD-10"),
                            ("ICD11", "ICD-11"),
                            ("SNOMED_CT", "SNOMED CT"),
                            ("LOINC", "LOINC"),
                            ("MFL", "Master Facility List"),
                            ("CIEL", "CIEL"),
                            ("LOCAL", "Local Code Set"),
                        ],
                        default="",
                        help_text="Coding system (for CODED data type only)",
                        max_length=15,
                    ),
                ),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum length for STRING/IDENTIFIER types",
                        null=True,
                    ),
                ),
                (
                    "format_pattern",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Regex pattern for format validation",
                        max_length=200,
                    ),
                ),
                (
                    "condition_expression",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable condition for CONDITIONAL requirements",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this element is actively validated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KENHDD Data Element",
                "verbose_name_plural": "KENHDD Data Elements",
                "ordering": ["resource_type", "element_id"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "is_active"], name="kenhdd_kenh_resourc_6513a2_idx"
                    ),
                    models.Index(fields=["element_id"], name="kenhdd_kenh_element_34841c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="KENHDDValidationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("PATIENT", "Patient"),
                            ("ENCOUNTER", "Encounter"),
                            ("DIAGNOSIS", "Diagnosis"),
                            ("FACILITY", "Facility"),
                            ("LAB_RESULT", "Lab Result"),
                            ("PRESCRIPTION", "Prescription"),
                            ("MCH_VISIT", "MCH Visit"),
                        ],
                        help_text="Resource type that was validated",
                        max_length=20,
                    ),
                ),
                (
                    "records_checked",
                    models.PositiveIntegerField(
                        help_text="Number of records sampled for validation"
                    ),
                ),
                (
                    "records_compliant",
                    models.PositiveIntegerField(help_text="Number of records fully compliant"),
                ),
                (
                    "compliance_score",
                    models.DecimalField(
                        decimal_places=2, help_text="Compliance percentage (0-100)", max_digits=5
                    ),
                ),
                (
                    "mandatory_pass_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of mandatory elements passing (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "violations",
                    models.JSONField(
                        blank=True, default=dict, help_text="Violation summary keyed by element_id"
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the run",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kenhdd_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KENHDD Validation Run",
                "verbose_name_plural": "KENHDD Validation Runs",
                "ordering": ["-run_at"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "-run_at"], name="kenhdd_kenh_resourc_6f6e24_idx"
                    )
                ],
            },
        ),
    ]
