/**
 * Print Receipt Utility
 *
 * High-level function to print a payment receipt document.
 * Uses the document renderer with the receipt schema and template.
 */

import type { Receipt, ReceiptLineItem } from '@/lib/types/billing';
import type {
  FacilityInfo,
  PatientInfo,
  LayoutType,
  RenderContext,
} from './types';
import { receiptSchema, receiptDefaults } from './schemas/receipt.schema';
import {
  renderDocumentAsync,
  buildPrintDocument,
  openPrintWindow,
  escapeHtml,
  formatDateTime,
} from './renderer';
import { getReceiptQRContent, type QRContent } from '@/lib/utils/qr';

// =============================================================================
// RECEIPT TEMPLATE
// =============================================================================

/**
 * Receipt HTML template
 * Optimized for thermal 80mm printers
 */
const RECEIPT_TEMPLATE = `
<div class="receipt">
  <div class="header">
    <h1>{{facility.name}}</h1>
    <p>{{facility.address}}</p>
    <p>Tel: {{facility.phone}}</p>
    <p class="title">PAYMENT RECEIPT</p>
  </div>

  <div class="divider"></div>

  <div class="meta">
    <div class="row">
      <span>Receipt No:</span>
      <span>{{receipt.number}}</span>
    </div>
    <div class="row">
      <span>Date:</span>
      <span>{{receipt.date}}</span>
    </div>
    <div class="row payment-ref">
      <span>Invoice Ref:</span>
      <span>{{receipt.payment_reference}}</span>
    </div>
    <div class="row">
      <span>Patient:</span>
      <span>{{patient.name}}</span>
    </div>
    <div class="row patient-mrn">
      <span>MRN:</span>
      <span>{{patient.mrn}}</span>
    </div>
    <div class="row">
      <span>Payment Method:</span>
      <span>{{payment.method}}</span>
    </div>
    <div class="row served-by">
      <span>Served By:</span>
      <span>{{staff.served_by}}</span>
    </div>
    <div class="row payment-point">
      <span>Till/Point:</span>
      <span>{{staff.payment_point}}</span>
    </div>
  </div>

  <div class="divider"></div>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{item.description}}</td>
        <td>{{item.amount}}</td>
      </tr>
    </tbody>
  </table>

  <div class="divider"></div>

  <div class="totals">
    <div class="row">
      <span>Total Paid:</span>
      <span>{{payment.amount}}</span>
    </div>
  </div>

  <div class="qr">
    QR / Barcode
  </div>

  <div class="footer">
    <p>
      This receipt acknowledges payment only and does not replace
      a valid invoice or insurance claim document.
    </p>
    <p>Thank you for your visit.</p>
    <p>Generated by {{system.name}}</p>
  </div>
</div>
`;

/**
 * Receipt-specific CSS (extends base)
 */
const RECEIPT_CSS = `
  .receipt {
    max-width: 380px;
    margin: auto;
    background: #ffffff;
    padding: 20px;
    border: 1px solid #ddd;
    box-sizing: border-box;
  }

  .header {
    text-align: center;
    margin-bottom: 16px;
  }

  .header h1 {
    margin: 0;
    font-size: 18px;
    letter-spacing: 1px;
  }

  .header p {
    margin: 4px 0;
    font-size: 12px;
    color: #555;
  }

  .header .title {
    font-weight: bold;
    color: #000;
    margin-top: 8px;
  }

  .divider {
    border-top: 1px dashed #aaa;
    margin: 12px 0;
  }

  .meta,
  .totals {
    font-size: 13px;
  }

  .meta .row,
  .totals .row {
    display: flex;
    justify-content: space-between;
    margin-bottom: 6px;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
    margin-top: 10px;
  }

  table th,
  table td {
    padding: 6px 0;
    text-align: left;
  }

  table th {
    border-bottom: 1px solid #ccc;
  }

  table td:last-child,
  table th:last-child {
    text-align: right;
  }

  .totals {
    margin-top: 10px;
    font-weight: bold;
  }

  .qr {
    margin-top: 14px;
    text-align: center;
    min-height: 100px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .qr img {
    width: 100px;
    height: 100px;
  }

  .footer {
    margin-top: 16px;
    text-align: center;
    font-size: 11px;
    color: #555;
  }

  .footer p {
    margin: 4px 0;
  }

  @media print {
    body {
      background: none;
      padding: 0;
    }

    .receipt {
      border: none;
      box-shadow: none;
    }
  }
`;

// =============================================================================
// PRINT RECEIPT OPTIONS
// =============================================================================

export interface PrintReceiptOptions {
  /** The receipt to print */
  receipt: Receipt;
  /** Patient information (optional, uses receipt.patient_name if not provided) */
  patient?: PatientInfo;
  /** Facility information for header */
  facility?: FacilityInfo;
  /** Layout format (default: thermal-80mm) */
  layout?: LayoutType;
  /** Theme name */
  theme?: string;
}

// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

/**
 * Format currency for display
 */
function formatCurrency(amount: number | string): string {
  const num = typeof amount === 'string' ? parseFloat(amount) : amount;
  return `KES ${num.toLocaleString('en-KE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

/**
 * Format payment method for display
 */
function formatPaymentMethod(method: string): string {
  return method.replace(/_/g, ' ');
}

/**
 * Build line items HTML from receipt
 */
function buildLineItemsHtml(receipt: Receipt): string {
  const amount = parseFloat(receipt.amount);
  const amountPaid = formatCurrency(amount);

  // Use receipt.line_items if available, otherwise create single line item
  if (receipt.line_items && receipt.line_items.length > 0) {
    return receipt.line_items
      .map((item) => {
        const qty = item.quantity > 1 ? ` x${item.quantity}` : '';
        const lineTotal = parseFloat(item.line_total);
        return `<tr>
          <td>${escapeHtml(item.description)}${qty}</td>
          <td>${formatCurrency(lineTotal)}</td>
        </tr>`;
      })
      .join('\n');
  }

  // Fallback: single payment line
  return `<tr><td>Payment</td><td>${amountPaid}</td></tr>`;
}

// =============================================================================
// PRINT RECEIPT
// =============================================================================

/**
 * Print a receipt document
 *
 * @param options - Receipt data and print options
 * @returns Promise that resolves to the print window, or null if failed
 */
export async function printReceipt(options: PrintReceiptOptions): Promise<Window | null> {
  const {
    receipt,
    patient,
    facility,
    layout = 'thermal-80mm',
    theme = 'default',
  } = options;

  // Validate required data
  if (!receipt) {
    console.error('printReceipt: receipt is required');
    return null;
  }

  // Get QR content
  const qrContent = getReceiptQRContent(receipt);

  // Build render context
  const context: RenderContext = {
    // Patient info
    patient: patient || {
      full_name: receipt.patient_name || 'Patient',
      mrn: receipt.patient_mrn || '',
    },

    // Facility info
    facility: facility || {
      name: receipt.facility_name || receiptDefaults.facility.name,
      address: receipt.facility_address || receiptDefaults.facility.address,
      phone: receipt.facility_phone || receiptDefaults.facility.phone,
    },

    // Receipt data
    receipt: {
      receipt_number: receipt.receipt_number,
      receipt_date: formatDateTime(receipt.receipt_date),
      payment_reference: receipt.payment_reference || '',
      amount: formatCurrency(parseFloat(receipt.amount)),
      amount_in_words: receipt.amount_in_words || '',
      payment_method: formatPaymentMethod(receipt.payment_method),
      received_by_username: receipt.received_by_username || receipt.issued_by_username || '',
      payment_point_name: receipt.payment_point_name || receipt.payment_point_code || '',
      line_items: receipt.line_items || [],
    },

    // System name
    system_name: receiptDefaults.system_name,
  };

  // Generate line items HTML
  const lineItemsHtml = buildLineItemsHtml(receipt);

  // Render template
  let bodyHtml = await renderDocumentAsync(
    RECEIPT_TEMPLATE,
    receiptSchema,
    context,
    qrContent
  );

  // Replace line items in table (since repeater may not work for dynamic rows)
  bodyHtml = bodyHtml.replace(
    /<tbody>[\s\S]*?<\/tbody>/,
    `<tbody>\n${lineItemsHtml}\n</tbody>`
  );

  // Hide optional rows if empty
  if (!receipt.payment_reference) {
    bodyHtml = bodyHtml.replace(/<div class="row payment-ref">[\s\S]*?<\/div>/, '');
  }
  if (!receipt.patient_mrn) {
    bodyHtml = bodyHtml.replace(/<div class="row patient-mrn">[\s\S]*?<\/div>/, '');
  }
  if (!receipt.received_by_username && !receipt.issued_by_username) {
    bodyHtml = bodyHtml.replace(/<div class="row served-by">[\s\S]*?<\/div>/, '');
  }
  if (!receipt.payment_point_name && !receipt.payment_point_code) {
    bodyHtml = bodyHtml.replace(/<div class="row payment-point">[\s\S]*?<\/div>/, '');
  }

  // Build complete HTML with CSS
  const title = `Payment Receipt - ${receipt.receipt_number}`;
  const html = buildPrintDocument(bodyHtml, title, layout, theme, RECEIPT_CSS);

  // Open print window
  return openPrintWindow(html);
}

/**
 * Preview a receipt without printing
 * Returns the generated HTML for inspection
 */
export async function previewReceipt(options: PrintReceiptOptions): Promise<string> {
  const {
    receipt,
    patient,
    facility,
    layout = 'thermal-80mm',
    theme = 'default',
  } = options;

  const qrContent = getReceiptQRContent(receipt);

  const context: RenderContext = {
    patient: patient || {
      full_name: receipt.patient_name || 'Patient',
      mrn: receipt.patient_mrn || '',
    },
    facility: facility || {
      name: receipt.facility_name || receiptDefaults.facility.name,
      address: receipt.facility_address || receiptDefaults.facility.address,
      phone: receipt.facility_phone || receiptDefaults.facility.phone,
    },
    receipt: {
      receipt_number: receipt.receipt_number,
      receipt_date: formatDateTime(receipt.receipt_date),
      payment_reference: receipt.payment_reference || '',
      amount: formatCurrency(parseFloat(receipt.amount)),
      amount_in_words: receipt.amount_in_words || '',
      payment_method: formatPaymentMethod(receipt.payment_method),
      received_by_username: receipt.received_by_username || receipt.issued_by_username || '',
      payment_point_name: receipt.payment_point_name || receipt.payment_point_code || '',
      line_items: receipt.line_items || [],
    },
    system_name: receiptDefaults.system_name,
  };

  const lineItemsHtml = buildLineItemsHtml(receipt);

  let bodyHtml = await renderDocumentAsync(
    RECEIPT_TEMPLATE,
    receiptSchema,
    context,
    qrContent
  );

  bodyHtml = bodyHtml.replace(
    /<tbody>[\s\S]*?<\/tbody>/,
    `<tbody>\n${lineItemsHtml}\n</tbody>`
  );

  const title = `Payment Receipt - ${receipt.receipt_number}`;
  return buildPrintDocument(bodyHtml, title, layout, theme, RECEIPT_CSS);
}
