/**
 * Print Referral Letter Utility
 *
 * Generates a printable referral letter document.
 */

import type { ClinicalReferral } from '@/lib/types/referral';
import type { FacilityInfo, ClinicianInfo, PatientInfo, SignatureInfo } from './types';
import { buildPrintDocument, openPrintWindow, escapeHtml, formatDate, renderSignatureColumn } from './renderer';

// =============================================================================
// REFERRAL LETTER TEMPLATE
// =============================================================================

const REFERRAL_TEMPLATE = `
<div class="page">
  <div class="header">
    <div class="clinic-info">
      <strong>{{facility_name}}</strong><br />
      {{facility_address}}<br />
      Tel: {{facility_phone}}<br />
      License No: {{facility_license}}
    </div>
    <div class="doc-type">
      REFERRAL LETTER
    </div>
  </div>

  <div class="ref-bar">
    <div><strong>Referral No:</strong> {{referral_number}}</div>
    <div><strong>Date:</strong> {{referral_date}}</div>
    <div><strong>Priority:</strong> {{priority}}</div>
  </div>

  <div class="addressee">
    <p>To: <strong>{{destination}}</strong></p>
  </div>

  <div class="section">
    <div class="section-title">Patient Information</div>
    <div class="patient-grid">
      <div><strong>Name:</strong> {{patient_name}}</div>
      <div><strong>Patient ID:</strong> {{patient_mrn}}</div>
      <div><strong>Gender:</strong> {{patient_gender}}</div>
      <div><strong>Date of Birth:</strong> {{patient_dob}}</div>
      {{#patient_phone}}
      <div><strong>Phone:</strong> {{patient_phone}}</div>
      {{/patient_phone}}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Reason for Referral</div>
    <div class="content-block">{{reason}}</div>
  </div>

  {{#clinical_notes}}
  <div class="section">
    <div class="section-title">Clinical Notes</div>
    <div class="content-block">{{clinical_notes}}</div>
  </div>
  {{/clinical_notes}}

  {{#hospital_course}}
  <div class="section">
    <div class="section-title">Hospital Course</div>
    <div class="content-block">{{hospital_course}}</div>
  </div>
  {{/hospital_course}}

  {{#has_diagnoses}}
  <div class="section">
    <div class="section-title">Relevant Diagnoses</div>
    <div class="diagnoses-list">{{diagnoses_html}}</div>
  </div>
  {{/has_diagnoses}}

  {{#has_vitals}}
  <div class="section">
    <div class="section-title">Vitals at Time of Referral</div>
    <div class="vitals-grid">{{vitals_html}}</div>
  </div>
  {{/has_vitals}}

  <div class="signature-block">
    <div class="sig">
      Referring Clinician<br />
      {{clinician_name}}<br />
      {{clinician_registration}}
    </div>
    {{signature_column}}
  </div>

  <div class="footer">
    <div>
      This referral letter is electronically generated. Please contact the referring facility for verification.
    </div>
    <div>
      Generated by Vitora HMIS
    </div>
  </div>
</div>
`;

const REFERRAL_CSS = `
  .page { padding: 32px; font-family: 'Times New Roman', serif; }
  .header { display: flex; justify-content: space-between; align-items: flex-start;
    border-bottom: 2px solid #000; padding-bottom: 12px; margin-bottom: 16px; }
  .clinic-info { font-size: 12px; line-height: 1.5; }
  .doc-type { font-size: 20px; font-weight: bold; letter-spacing: 1px; }
  .ref-bar { display: flex; justify-content: space-between; font-size: 13px;
    margin-bottom: 16px; padding: 8px; background: #f5f5f5; border: 1px solid #ddd; }
  .addressee { font-size: 14px; margin-bottom: 16px; }
  .section { margin-bottom: 16px; }
  .section-title { font-weight: bold; font-size: 14px; margin-bottom: 6px;
    border-bottom: 1px solid #ccc; padding-bottom: 2px; }
  .patient-grid { display: grid; grid-template-columns: repeat(2, 1fr);
    gap: 8px 16px; font-size: 13px; }
  .content-block { font-size: 13px; line-height: 1.6; padding: 8px;
    border: 1px solid #eee; background: #fafafa; white-space: pre-wrap; }
  .diagnoses-list { font-size: 13px; }
  .diagnoses-list ul { margin: 0; padding-left: 20px; }
  .diagnoses-list li { margin-bottom: 4px; }
  .vitals-grid { display: grid; grid-template-columns: repeat(2, 1fr);
    gap: 6px 16px; font-size: 13px; }
  .signature-block { margin-top: 48px; display: flex; justify-content: space-between; }
  .sig { width: 45%; border-top: 1px solid #000; padding-top: 6px;
    text-align: center; font-size: 12px; }
  .footer { margin-top: 24px; font-size: 10px; border-top: 1px solid #ccc;
    padding-top: 8px; display: flex; justify-content: space-between; }
  @media print { .page { padding: 0; } }
`;

// =============================================================================
// PRINT FUNCTION
// =============================================================================

export interface PrintReferralOptions {
  referral: ClinicalReferral;
  patient?: PatientInfo;
  facility?: FacilityInfo;
  clinician?: ClinicianInfo;
  /** Digital signature data. When provided, renders signer identity instead of static placeholder. */
  signature?: SignatureInfo;
}

/**
 * Print a referral letter document
 */
export function printReferralLetter(options: PrintReferralOptions): Window | null {
  const { referral, patient, facility, clinician, signature } = options;

  if (!referral) {
    console.error('printReferralLetter: referral is required');
    return null;
  }

  let html = REFERRAL_TEMPLATE;

  // Facility
  html = html.replace(/\{\{facility_name\}\}/g, escapeHtml(facility?.name || ''));
  html = html.replace(/\{\{facility_address\}\}/g, escapeHtml(facility?.address || ''));
  html = html.replace(/\{\{facility_phone\}\}/g, escapeHtml(facility?.phone || ''));
  html = html.replace(/\{\{facility_license\}\}/g, escapeHtml(facility?.license || ''));

  // Referral info
  html = html.replace(/\{\{referral_number\}\}/g, escapeHtml(referral.referral_number));
  html = html.replace(/\{\{referral_date\}\}/g, formatDate(referral.created_at));
  html = html.replace(/\{\{priority\}\}/g, escapeHtml(referral.priority_display));

  // Destination
  const destination = referral.external_facility_name
    || referral.destination_clinic_name
    || referral.target_service_display;
  html = html.replace(/\{\{destination\}\}/g, escapeHtml(destination));

  // Patient
  html = html.replace(/\{\{patient_name\}\}/g, escapeHtml(patient?.full_name || referral.patient_name));
  html = html.replace(/\{\{patient_mrn\}\}/g, escapeHtml(patient?.mrn || referral.patient_mrn));

  // Patient demographics
  const genderMap: Record<string, string> = { M: 'Male', F: 'Female', O: 'Other' };
  const gender = patient?.gender || referral.patient_gender || '';
  html = html.replace(/\{\{patient_gender\}\}/g, escapeHtml(genderMap[gender] || gender));

  const dob = patient?.date_of_birth || referral.patient_date_of_birth || '';
  html = html.replace(/\{\{patient_dob\}\}/g, dob ? formatDate(dob) : 'N/A');

  const phone = patient?.phone || referral.patient_phone || '';
  if (phone) {
    html = html.replace(/\{\{#patient_phone\}\}([\s\S]*?)\{\{\/patient_phone\}\}/g, '$1');
    html = html.replace(/\{\{patient_phone\}\}/g, escapeHtml(phone));
  } else {
    html = html.replace(/\{\{#patient_phone\}\}[\s\S]*?\{\{\/patient_phone\}\}/g, '');
  }

  // Reason
  html = html.replace(/\{\{reason\}\}/g, escapeHtml(referral.reason));

  // Clinical notes
  if (referral.clinical_notes) {
    html = html.replace(/\{\{#clinical_notes\}\}([\s\S]*?)\{\{\/clinical_notes\}\}/g, '$1');
    html = html.replace(/\{\{clinical_notes\}\}/g, escapeHtml(referral.clinical_notes));
  } else {
    html = html.replace(/\{\{#clinical_notes\}\}[\s\S]*?\{\{\/clinical_notes\}\}/g, '');
  }

  // Hospital course
  if (referral.hospital_course) {
    html = html.replace(/\{\{#hospital_course\}\}([\s\S]*?)\{\{\/hospital_course\}\}/g, '$1');
    html = html.replace(/\{\{hospital_course\}\}/g, escapeHtml(referral.hospital_course));
  } else {
    html = html.replace(/\{\{#hospital_course\}\}[\s\S]*?\{\{\/hospital_course\}\}/g, '');
  }

  // Diagnoses
  if (referral.relevant_diagnoses && referral.relevant_diagnoses.length > 0) {
    html = html.replace(/\{\{#has_diagnoses\}\}([\s\S]*?)\{\{\/has_diagnoses\}\}/g, '$1');
    const diagnosesHtml = '<ul>' + referral.relevant_diagnoses.map(
      d => `<li><strong>${escapeHtml(d.code)}</strong> – ${escapeHtml(d.description)}</li>`
    ).join('') + '</ul>';
    html = html.replace(/\{\{diagnoses_html\}\}/g, diagnosesHtml);
  } else {
    html = html.replace(/\{\{#has_diagnoses\}\}[\s\S]*?\{\{\/has_diagnoses\}\}/g, '');
  }

  // Vitals
  const vitals = referral.relevant_vitals;
  if (vitals && Object.values(vitals).some(Boolean)) {
    html = html.replace(/\{\{#has_vitals\}\}([\s\S]*?)\{\{\/has_vitals\}\}/g, '$1');
    const vitalsEntries: string[] = [];
    if (vitals.blood_pressure) vitalsEntries.push(`<div><strong>BP:</strong> ${escapeHtml(vitals.blood_pressure)} mmHg</div>`);
    if (vitals.pulse) vitalsEntries.push(`<div><strong>Pulse:</strong> ${escapeHtml(vitals.pulse)} bpm</div>`);
    if (vitals.temperature) vitalsEntries.push(`<div><strong>Temp:</strong> ${escapeHtml(vitals.temperature)}°C</div>`);
    if (vitals.respiratory_rate) vitalsEntries.push(`<div><strong>RR:</strong> ${escapeHtml(vitals.respiratory_rate)} /min</div>`);
    if (vitals.spo2) vitalsEntries.push(`<div><strong>SpO2:</strong> ${escapeHtml(vitals.spo2)}%</div>`);
    if (vitals.weight) vitalsEntries.push(`<div><strong>Weight:</strong> ${escapeHtml(vitals.weight)} kg</div>`);
    if (vitals.height) vitalsEntries.push(`<div><strong>Height:</strong> ${escapeHtml(vitals.height)} cm</div>`);
    html = html.replace(/\{\{vitals_html\}\}/g, vitalsEntries.join(''));
  } else {
    html = html.replace(/\{\{#has_vitals\}\}[\s\S]*?\{\{\/has_vitals\}\}/g, '');
  }

  // Clinician
  html = html.replace(/\{\{clinician_name\}\}/g, escapeHtml(clinician?.name || referral.referred_by_name));
  html = html.replace(/\{\{clinician_registration\}\}/g, escapeHtml(clinician?.registration_number || ''));

  // Digital signature
  html = html.replace(/\{\{signature_column\}\}/g, renderSignatureColumn(signature));

  const fullHtml = buildPrintDocument(
    html,
    `Referral Letter - ${referral.referral_number}`,
    'a4',
    'default',
    REFERRAL_CSS
  );

  return openPrintWindow(fullHtml);
}
