/**
 * Print Invoice Utility
 *
 * High-level function to print an invoice document.
 * Uses the document renderer with the invoice schema and template.
 */

import type { Invoice, InvoiceItem } from '@/lib/types/billing';
import type {
  FacilityInfo,
  PatientInfo,
  LayoutType,
  RenderContext,
} from './types';
import { invoiceSchema, invoiceDefaults, invoiceStatusColors } from './schemas/invoice.schema';
import {
  renderDocumentAsync,
  buildPrintDocument,
  openPrintWindow,
  escapeHtml,
  formatDate,
} from './renderer';
import { getInvoiceQRContent, type QRContent } from '@/lib/utils/qr';

// =============================================================================
// INVOICE TEMPLATE
// =============================================================================

/**
 * Invoice HTML template
 * A4 format for professional invoicing
 */
const INVOICE_TEMPLATE = `
<div class="invoice">
  <div class="header">
    <div class="facility">
      <h1>{{facility.name}}</h1>
      <p>{{facility.address}}</p>
      <p>Tel: {{facility.phone}}</p>
      <p>License No: {{facility.license}}</p>
    </div>

    <div class="doc-meta">
      <div class="title">INVOICE</div>
      <div>No: {{invoice.number}}</div>
      <div>Issued: {{invoice.date}}</div>
      <div>Due: {{invoice.due_date}}</div>
      <div class="status-badge">{{invoice.status}}</div>
    </div>
  </div>

  <div class="divider"></div>

  <div class="parties">
    <div class="party">
      <h3>Bill To (Patient)</h3>
      <p class="patient-name"><strong>{{patient.name}}</strong></p>
      <p>MRN: {{patient.mrn}}</p>
    </div>

    <div class="party">
      <h3>Payment Summary</h3>
      <p>Total: {{invoice.total}}</p>
      <p>Paid: {{invoice.paid}}</p>
      <p><strong>Balance: {{invoice.balance}}</strong></p>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th>Qty</th>
        <th>Unit Price</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{item.description}}</td>
        <td>{{item.quantity}}</td>
        <td>{{item.unit_price}}</td>
        <td>{{item.total}}</td>
      </tr>
    </tbody>
  </table>

  <div class="summary">
    <div class="totals">
      <div class="row">
        <span>Subtotal</span>
        <span>{{invoice.subtotal}}</span>
      </div>
      <div class="row discount-row">
        <span>Discount</span>
        <span>-{{invoice.discount}}</span>
      </div>
      <div class="row grand">
        <span>Total</span>
        <span>{{invoice.total}}</span>
      </div>
    </div>
  </div>

  <div class="footer">
    <div class="notes">
      <p>
        This invoice constitutes a formal request for payment and may be
        submitted to an insurer for reimbursement or claim processing.
      </p>
      <p>Generated by {{system.name}}</p>
    </div>

    <div class="qr">
      QR / Barcode
    </div>
  </div>
</div>
`;

/**
 * Invoice-specific CSS (extends base)
 */
const INVOICE_CSS = `
  .invoice {
    width: 190mm;
    margin: auto;
    background: #ffffff;
    padding: 20mm;
    box-sizing: border-box;
    font-family: "Inter", Arial, sans-serif;
    color: #111;
  }

  .header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
  }

  .facility h1 {
    margin: 0;
    font-size: 20px;
    font-weight: 700;
    letter-spacing: 0.5px;
  }

  .facility p {
    margin: 4px 0;
    font-size: 13px;
    color: #555;
  }

  .doc-meta {
    text-align: right;
    font-size: 13px;
  }

  .doc-meta .title {
    font-size: 18px;
    font-weight: 700;
    margin-bottom: 8px;
  }

  .status-badge {
    display: inline-block;
    margin-top: 6px;
    padding: 4px 12px;
    font-size: 12px;
    border-radius: 12px;
    font-weight: 600;
  }

  .divider {
    border-top: 1px solid #e5e7eb;
    margin: 24px 0;
  }

  .parties {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 32px;
    font-size: 14px;
  }

  .party h3 {
    margin: 0 0 8px;
    font-size: 13px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: #555;
  }

  .party p {
    margin: 4px 0;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 28px;
    font-size: 14px;
  }

  table thead th {
    text-align: left;
    font-size: 12px;
    text-transform: uppercase;
    color: #555;
    border-bottom: 2px solid #e5e7eb;
    padding-bottom: 10px;
  }

  table tbody td {
    padding: 12px 0;
    border-bottom: 1px solid #f0f0f0;
  }

  table td:last-child,
  table th:last-child {
    text-align: right;
  }

  .summary {
    display: flex;
    justify-content: flex-end;
    margin-top: 24px;
  }

  .totals {
    width: 80mm;
    font-size: 14px;
  }

  .totals .row {
    display: flex;
    justify-content: space-between;
    margin-bottom: 10px;
  }

  .totals .grand {
    font-size: 18px;
    font-weight: 700;
    border-top: 2px solid #111;
    padding-top: 12px;
    margin-top: 12px;
  }

  .footer {
    margin-top: 40px;
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    font-size: 12px;
    color: #555;
  }

  .footer .notes {
    flex: 1;
  }

  .footer .notes p {
    margin: 4px 0;
  }

  .qr {
    width: 100px;
    height: 100px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1px dashed #aaa;
    font-size: 11px;
    color: #666;
  }

  .qr img {
    width: 100%;
    height: 100%;
  }

  @media screen {
    body {
      background: #f4f6f8;
      padding: 32px;
    }
  }

  @media print {
    body {
      background: none;
      padding: 0;
    }

    .invoice {
      box-shadow: none;
    }
  }
`;

// =============================================================================
// PRINT INVOICE OPTIONS
// =============================================================================

export interface PrintInvoiceOptions {
  /** The invoice to print */
  invoice: Invoice;
  /** Patient information (optional, uses invoice fields if not provided) */
  patient?: PatientInfo;
  /** Facility information for header */
  facility?: FacilityInfo;
  /** Layout format (default: a4) */
  layout?: LayoutType;
  /** Theme name */
  theme?: string;
}

// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

/**
 * Format currency for display
 */
function formatCurrency(amount: number | string): string {
  const num = typeof amount === 'string' ? parseFloat(amount) : amount;
  if (isNaN(num)) return 'KES 0.00';
  return `KES ${num.toLocaleString('en-KE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

/**
 * Build line items HTML from invoice
 */
function buildLineItemsHtml(invoice: Invoice): string {
  const items = invoice.items || [];
  
  if (items.length === 0) {
    return '<tr><td colspan="4" style="text-align: center; color: #666;">No line items</td></tr>';
  }

  return items
    .map((item: InvoiceItem) => `
      <tr>
        <td>${escapeHtml(item.description || item.service_name || 'Service')}</td>
        <td>${item.quantity}</td>
        <td>${formatCurrency(item.unit_price)}</td>
        <td>${formatCurrency(parseFloat(item.unit_price) * item.quantity)}</td>
      </tr>
    `)
    .join('\n');
}

/**
 * Get status badge CSS
 */
function getStatusBadgeStyle(status: string): string {
  const colors = invoiceStatusColors[status] || { bg: '#f3f4f6', color: '#6b7280' };
  return `background: ${colors.bg}; color: ${colors.color};`;
}

// =============================================================================
// PRINT INVOICE
// =============================================================================

/**
 * Print an invoice document
 *
 * @param options - Invoice data and print options
 * @returns Promise that resolves to the print window, or null if failed
 */
export async function printInvoice(options: PrintInvoiceOptions): Promise<Window | null> {
  const {
    invoice,
    patient,
    facility,
    layout = 'a4',
    theme = 'default',
  } = options;

  // Validate required data
  if (!invoice) {
    console.error('printInvoice: invoice is required');
    return null;
  }

  // Get QR content
  const qrContent = getInvoiceQRContent(invoice);

  // Calculate amounts
  const subtotal = parseFloat(invoice.subtotal || invoice.total_amount);
  const discount = parseFloat(invoice.discount_amount || '0');
  const total = parseFloat(invoice.total_amount);
  const amountPaid = parseFloat(invoice.amount_paid || '0');
  const balanceDue = invoice.balance_due 
    ? parseFloat(invoice.balance_due) 
    : (total - amountPaid);

  // Build render context
  const context: RenderContext = {
    // Patient info
    patient: patient || {
      full_name: invoice.patient_name || 'N/A',
      mrn: invoice.patient_mrn || 'N/A',
    },

    // Facility info
    facility: facility || invoiceDefaults.facility,

    // Invoice data
    invoice: {
      invoice_number: invoice.invoice_number,
      invoice_date: formatDate(invoice.invoice_date),
      due_date: formatDate(invoice.due_date),
      status: invoice.status,
      subtotal: formatCurrency(subtotal),
      discount_amount: formatCurrency(discount),
      total_amount: formatCurrency(total),
      amount_paid: formatCurrency(amountPaid),
      balance_due: formatCurrency(balanceDue),
      items: invoice.items || [],
    },

    // System name
    system_name: invoiceDefaults.system_name,
  };

  // Generate line items HTML
  const lineItemsHtml = buildLineItemsHtml(invoice);

  // Render template
  let bodyHtml = await renderDocumentAsync(
    INVOICE_TEMPLATE,
    invoiceSchema,
    context,
    qrContent
  );

  // Replace line items in table
  bodyHtml = bodyHtml.replace(
    /<tbody>[\s\S]*?<\/tbody>/,
    `<tbody>\n${lineItemsHtml}\n</tbody>`
  );

  // Style the status badge dynamically
  const statusStyle = getStatusBadgeStyle(invoice.status);
  bodyHtml = bodyHtml.replace(
    /<div class="status-badge">/,
    `<div class="status-badge" style="${statusStyle}">`
  );

  // Hide discount row if zero
  if (discount === 0) {
    bodyHtml = bodyHtml.replace(/<div class="row discount-row">[\s\S]*?<\/div>/, '');
  }

  // Build complete HTML with CSS
  const title = `Invoice - ${invoice.invoice_number}`;
  const html = buildPrintDocument(bodyHtml, title, layout, theme, INVOICE_CSS);

  // Open print window
  return openPrintWindow(html);
}

/**
 * Preview an invoice without printing
 * Returns the generated HTML for inspection
 */
export async function previewInvoice(options: PrintInvoiceOptions): Promise<string> {
  const {
    invoice,
    patient,
    facility,
    layout = 'a4',
    theme = 'default',
  } = options;

  const qrContent = getInvoiceQRContent(invoice);

  const subtotal = parseFloat(invoice.subtotal || invoice.total_amount);
  const discount = parseFloat(invoice.discount_amount || '0');
  const total = parseFloat(invoice.total_amount);
  const amountPaid = parseFloat(invoice.amount_paid || '0');
  const balanceDue = invoice.balance_due 
    ? parseFloat(invoice.balance_due) 
    : (total - amountPaid);

  const context: RenderContext = {
    patient: patient || {
      full_name: invoice.patient_name || 'N/A',
      mrn: invoice.patient_mrn || 'N/A',
    },
    facility: facility || invoiceDefaults.facility,
    invoice: {
      invoice_number: invoice.invoice_number,
      invoice_date: formatDate(invoice.invoice_date),
      due_date: formatDate(invoice.due_date),
      status: invoice.status,
      subtotal: formatCurrency(subtotal),
      discount_amount: formatCurrency(discount),
      total_amount: formatCurrency(total),
      amount_paid: formatCurrency(amountPaid),
      balance_due: formatCurrency(balanceDue),
      items: invoice.items || [],
    },
    system_name: invoiceDefaults.system_name,
  };

  const lineItemsHtml = buildLineItemsHtml(invoice);

  let bodyHtml = await renderDocumentAsync(
    INVOICE_TEMPLATE,
    invoiceSchema,
    context,
    qrContent
  );

  bodyHtml = bodyHtml.replace(
    /<tbody>[\s\S]*?<\/tbody>/,
    `<tbody>\n${lineItemsHtml}\n</tbody>`
  );

  const statusStyle = getStatusBadgeStyle(invoice.status);
  bodyHtml = bodyHtml.replace(
    /<div class="status-badge">/,
    `<div class="status-badge" style="${statusStyle}">`
  );

  if (discount === 0) {
    bodyHtml = bodyHtml.replace(/<div class="row discount-row">[\s\S]*?<\/div>/, '');
  }

  const title = `Invoice - ${invoice.invoice_number}`;
  return buildPrintDocument(bodyHtml, title, layout, theme, INVOICE_CSS);
}
