# Generated by Django 5.2.9 on 2026-02-07 02:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clinics", "0007_seed_specialty_and_procedure_clinics"),
        ("encounters", "0018_encounter_clinic_visit"),
        ("patients", "0010_add_unique_identification_constraint"),
        ("triage", "0005_add_weight_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_type",
                    models.CharField(
                        choices=[("TRIAGE", "Triage Queue"), ("CLINIC", "Direct to Clinic")],
                        default="TRIAGE",
                        help_text="Where patient is routed",
                        max_length=20,
                    ),
                ),
                (
                    "skip_triage",
                    models.BooleanField(default=False, help_text="Whether triage was bypassed"),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New Patient"),
                            ("RETURN", "Returning Patient"),
                            ("FOLLOW_UP", "Follow-up Visit"),
                            ("EMERGENCY", "Emergency"),
                            ("SCHEDULED", "Scheduled Appointment"),
                        ],
                        default="NEW",
                        help_text="Type of visit (auto-detected or specified)",
                        max_length=20,
                    ),
                ),
                (
                    "visit_reason",
                    models.CharField(
                        choices=[
                            ("NEW_COMPLAINT", "New Complaint"),
                            ("FOLLOW_UP", "Follow-up"),
                            ("CHRONIC_CARE", "Chronic Care Review"),
                            ("PROCEDURE_REVIEW", "Post-Procedure Review"),
                            ("REFILL_ONLY", "Medication Refill Only"),
                            ("LAB_REVIEW", "Lab Results Review"),
                            ("REFERRAL_VISIT", "Referral from Another Facility"),
                            ("OTHER", "Other"),
                        ],
                        default="NEW_COMPLAINT",
                        help_text="Reason for visit",
                        max_length=30,
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When patient checked in"
                    ),
                ),
                (
                    "identity_method",
                    models.CharField(
                        choices=[
                            ("MRN", "Medical Record Number"),
                            ("NATIONAL_ID", "National ID"),
                            ("PHONE", "Phone Number"),
                            ("BIOMETRIC", "Biometric Scan"),
                            ("MANUAL", "Manual Verification"),
                        ],
                        default="MRN",
                        help_text="How patient identity was verified",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("IN_TRIAGE", "In Triage"),
                            ("TRIAGED", "Triaged"),
                            ("IN_CONSULTATION", "In Consultation"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="WAITING",
                        help_text="Current check-in status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Additional check-in notes"),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Initial chief complaint captured at check-in",
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who performed the check-in",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic_visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to clinic visit queue entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkin",
                        to="clinics.clinicvisit",
                    ),
                ),
                (
                    "destination_clinic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clinic if routed directly (skip triage)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkins",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Encounter created for this check-in",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkins",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "linked_encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous encounter this visit is following up on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_up_checkins",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient being checked in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="patients.patient",
                    ),
                ),
                (
                    "waiting_queue_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to triage waiting queue entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkin",
                        to="triage.waitingqueue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check-in",
                "verbose_name_plural": "Check-ins",
                "ordering": ["-checked_in_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckInStateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_status", models.CharField(help_text="Previous status", max_length=20)),
                ("to_status", models.CharField(help_text="New status", max_length=20)),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the status changed"),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for status change (optional)"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkin_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_history",
                        to="checkin.checkin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check-in State History",
                "verbose_name_plural": "Check-in State Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(fields=["checked_in_at"], name="checkin_che_checked_f28139_idx"),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["patient", "checked_in_at"], name="checkin_che_patient_0ab405_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(fields=["status"], name="checkin_che_status_2873a9_idx"),
        ),
    ]
