# Generated by Django 5.2.11 on 2026-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("TRIAGE", "Triage Queue"),
                    ("CLINIC", "Direct to Clinic"),
                    ("EMERGENCY", "Emergency Department"),
                ],
                default="TRIAGE",
                help_text="Where patient is routed",
                max_length=20,
            ),
        ),
    ]
