# Generated by Django 5.2.11 on 2026-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0002_add_emergency_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="visit_reason",
            field=models.CharField(
                choices=[
                    ("NEW_COMPLAINT", "New Complaint"),
                    ("FOLLOW_UP", "Follow-up"),
                    ("CHRONIC_CARE", "Chronic Care Review"),
                    ("PROCEDURE_REVIEW", "Post-Procedure Review"),
                    ("REFILL_ONLY", "Medication Refill Only"),
                    ("LAB_REVIEW", "Lab Results Review"),
                    ("REFERRAL_VISIT", "Referral from Another Facility"),
                    ("EMERGENCY", "Emergency"),
                    ("OTHER", "Other"),
                ],
                default="NEW_COMPLAINT",
                help_text="Reason for visit",
                max_length=30,
            ),
        ),
    ]
