# Generated by Django 5.2.11 on 2026-03-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkin", "0005_add_scheduled_procedure_visit_reason"),
        ("procedures", "0002_add_billing_service_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="procedure_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked procedure order for SCHEDULED_PROCEDURE visits",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkins",
                to="procedures.procedureorder",
            ),
        ),
    ]
