# Generated by Django 5.2.13 on 2026-05-04 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0052_facility_biometrics_agent_national_id"),
        ("encounters", "0030_structured_history_models"),
        ("patients", "0020_add_principal_national_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DialysisOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dialysis_type",
                    models.CharField(
                        choices=[
                            ("HEMODIALYSIS", "Hemodialysis"),
                            ("PERITONEAL", "Peritoneal Dialysis"),
                            ("CRRT", "Continuous Renal Replacement Therapy"),
                        ],
                        default="HEMODIALYSIS",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("TWICE_WEEKLY", "Twice Weekly"),
                            ("THRICE_WEEKLY", "Thrice Weekly"),
                            ("DAILY", "Daily"),
                            ("AS_NEEDED", "As Needed"),
                        ],
                        default="THRICE_WEEKLY",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "target_duration_minutes",
                    models.PositiveIntegerField(
                        default=240, help_text="Session duration in minutes"
                    ),
                ),
                ("blood_flow_rate", models.PositiveIntegerField(default=300, help_text="mL/min")),
                (
                    "dialysate_flow_rate",
                    models.PositiveIntegerField(default=500, help_text="mL/min"),
                ),
                (
                    "target_uf_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Target ultrafiltration volume (L)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("dialysate_composition", models.CharField(blank=True, max_length=100)),
                ("anticoagulation", models.CharField(default="Heparin", max_length=100)),
                (
                    "dry_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Target dry weight (kg)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("clinical_indication", models.TextField(help_text="Reason for dialysis")),
                ("notes", models.TextField(blank=True)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dialysis_orders_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dialysis_orders",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VascularAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("AVF", "Arteriovenous Fistula"),
                            ("AVG", "Arteriovenous Graft"),
                            ("CVC_TEMPORARY", "Temporary Central Venous Catheter"),
                            ("CVC_TUNNELED", "Tunneled Central Venous Catheter"),
                            ("PD_CATHETER", "Peritoneal Dialysis Catheter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("MATURING", "Maturing"),
                            ("FAILED", "Failed"),
                            ("REMOVED", "Removed"),
                            ("INFECTED", "Infected"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        help_text="Anatomical site (e.g. Left forearm)", max_length=100
                    ),
                ),
                ("placed_date", models.DateField()),
                ("last_assessment_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vascular_accesses",
                        to="patients.patient",
                    ),
                ),
                (
                    "placed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vascular_accesses_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vascular accesses",
                "ordering": ["-placed_date"],
            },
        ),
        migrations.CreateModel(
            name="DialysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_number", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "dialysis_type",
                    models.CharField(
                        choices=[
                            ("HEMODIALYSIS", "Hemodialysis"),
                            ("PERITONEAL", "Peritoneal Dialysis"),
                            ("CRRT", "Continuous Renal Replacement Therapy"),
                        ],
                        default="HEMODIALYSIS",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ABORTED", "Aborted"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField(default=django.utils.timezone.now)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("actual_duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("blood_flow_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("dialysate_flow_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("uf_goal_ml", models.PositiveIntegerField(blank=True, null=True)),
                ("uf_achieved_ml", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pre_weight_kg",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                ("pre_bp", models.CharField(blank=True, help_text="e.g. 140/90", max_length=10)),
                ("pre_pulse", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pre_temperature",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                (
                    "post_weight_kg",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                ("post_bp", models.CharField(blank=True, max_length=10)),
                ("post_pulse", models.PositiveIntegerField(blank=True, null=True)),
                ("complications", models.TextField(blank=True)),
                ("machine_number", models.CharField(blank=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dialysis_sessions",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility (branch) where this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.facility",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="dialysis.dialysisorder",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning organization (tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dialysis_sessions",
                        to="patients.patient",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dialysis_sessions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vascular_access",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dialysis.vascularaccess",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "-start_time"],
            },
        ),
        migrations.AddField(
            model_name="dialysisorder",
            name="vascular_access",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="dialysis.vascularaccess",
            ),
        ),
    ]
